### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [olikraus/u8g2#1003]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [bf_Close](https://github.com/olikraus/u8g2/blob/ac15bff2ad21fdcb6055c2f0ac968a7b08f5a472/tools/font/bdfconv/bdf_font.c#L79 "bf_Close function")
- [u8x8_bitmap_SetSize](https://github.com/olikraus/u8g2/blob/feaf9c86aea07b4caf15162b0be2a0c9efc45e56/sys/bitmap/common/u8x8_d_bitmap.c#L34 "u8x8_bitmap_SetSize function")

**Comment by olikraus** [comment]
what exactly is the problem here?

**Comment by elfring** [comment]
I am still curious then if another software developer (besides me) can get into the mood to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle") (also with the help of a variant from the following script).

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```

**Comment by olikraus** [comment]
ok, got the point... 
https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first

I wonder whether this is really worth to fix... What is your motivation to request a fix for this issue?

**Comment by elfring** [comment]
I suggest to achieve another small source code reduction.

**Comment by olikraus** [comment]
> I suggest to achieve another small source code reduction.

but the related code is either for the external font converter (which will never go to any embedded system) or is very special and also not part of the embedded u8g2 distribution.

I mean there will be no effect on the code size. U8g2 itself does not use malloc/free.

**Comment by olikraus** [comment]
ok, bf_Close is not part of the embedded code and also u8x8_bitmap_SetSize is not part of the standard u8g2 lib. In fact u8x8_bitmap_SetSize functionality is replaced by writeBitmapXBM function, see #1005 

I will but this on hold...
