### ISSUE TITLE
using arrowkeys

### ISSUE THREAD

**Issue by SFChen-stack** [olikraus/u8g2#1006]
Hey oli,

I got another question again.
I want to try to implement the arrowkeys on a keyboard to move the cursor of the oled screen. But whatever arrow I choose: up, down, left or right it all gives a value of 27 with serial.read how should I go about this to program it?

kind regards,
Leon

**Comment by olikraus** [comment]
Leon.... It is a issue tracker for U8g2, a system to generate graphics on monochrome displays.... It is above my skills to answer questions on serial transmit problems and it is unfortunately not related to this project.
