### ISSUE TITLE
create custom font

### ISSUE THREAD

**Issue by harissutanrafiq** [olikraus/u8g2#1016]
hello @olikraus 
thanks for awesome library, i have problem when creating font
i use this command
bdfconv.exe -v -f 1 -m "560-5205" -n syakir_arabic -o syakir_arabic.c bdf/10x20.bdf

iam download a bdf font from https://www.cl.cam.ac.uk/~mgk25/ucs-fonts.html

and the result is
/*
  Fontname: -Misc-Fixed-Medium-R-Normal--20-200-75-75-C-100-ISO10646-1
  Copyright: Public domain font.  Share and enjoy.
  Glyphs: 1630/5205
  BBX Build Mode: 0
*/

why the result is not from Glyphs: 1630/5205 not 560/5205 ..?
and why its not display anything in my LCD..?

when i use your default font u8g2_font_10x20_t_arabic
/*
  Fontname: -Misc-Fixed-Medium-R-Normal--20-200-75-75-C-100-ISO10646-1
  Copyright: Public domain font.  Share and enjoy.
  Glyphs: 560/5205
  BBX Build Mode: 0
*/

 its working on my LCD

**Comment by olikraus** [comment]
maybe you have to use single quotes for -m
(https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L229)
