### ISSUE TITLE
SSD1306 with ATtiny85 (1)

### ISSUE THREAD

**Issue by SchneHa** [olikraus/u8g2#1021]
In combination of a SSD1306 OLED and an ATtiny85 MC I found out that there is an issue with procedure begin: 
"This function will reset, configure, clear and disable power save mode of the display." 
power save mode isn't switched off and has to be switched off with a second line setPowerSave(0).

**Comment by olikraus** [comment]
What is your exact u8g2 constructor?
What is your code?

**Comment by SchneHa** [comment]
u8g2 constructor and code see #1022
