### ISSUE TITLE
Weird dots ST7920

### ISSUE THREAD

**Issue by leomoty** [olikraus/u8g2#1026]
Using ST7920 with an ESP32, ST7920 is powered by a 5V external power supply. There are some weird dots on two rows of the display and I have no clue why. It doesn't happen if I comment the mfrc522 code.

![20191016_110839](https://user-images.githubusercontent.com/1463740/66928736-446e6180-f008-11e9-9ddf-fec6a2122e2e.jpg)

<details>
<summary>code</summary>
<pre>
#include <Arduino.h>

#include <SPI.h>
#include <Wire.h>

#include <esp_system.h>
#include <time.h>
#include <sys/time.h>

#include <U8g2lib.h>

#include <MFRC522Extended.h>

U8G2_ST7920_128X64_F_HW_SPI u8g2(U8G2_R0, 4, 0);
MFRC522 mfrc522(5, 36);

MFRC522::MIFARE_Key key;
String uid = "";

time_t now;
struct tm timeinfo;
char date_buf[9];
char time_buf[9];

void setup() {
  u8g2.begin();
  u8g2.setBusClock(500000);
  Serial.begin(115200);
  while(!Serial);
  SPI.begin();
  mfrc522.PCD_Init();

  for (byte i = 0; i < 6; i++) {
    key.keyByte[i] = 0xFF;
  }
    Serial.println(F("Setup done"));

}

void loop() {
  time(&now);
  localtime_r(&now, &timeinfo);
  sprintf(date_buf, "%02d/%02d/%02d", timeinfo.tm_mday, timeinfo.tm_mon + 1, timeinfo.tm_year);
  sprintf(time_buf, "%02d:%02d:%02d", timeinfo.tm_hour, timeinfo.tm_min, timeinfo.tm_sec);
  
  u8g2.clearBuffer();

  u8g2.setFont(u8g2_font_ncenB08_tr);
  u8g2.drawStr(2, 9, date_buf);

  u8g2.setFont(u8g2_font_ncenB18_tr);
  u8g2.drawStr(16, 30, time_buf);
  u8g2.drawStr(10, 60, uid.c_str());
  u8g2.sendBuffer();

  if (!mfrc522.PICC_IsNewCardPresent() || !mfrc522.PICC_ReadCardSerial() ) {
    delay(50);
    return;
  }
  uid = "";
  for (byte i = 0; i < mfrc522.uid.size; i++) {
    uid += mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " ";
    uid += String(mfrc522.uid.uidByte[i], HEX);
  }
}
</pre>
</details>

**Comment by olikraus** [comment]
Hmmm.. I have no idea...

**Comment by leomoty** [comment]
Both are tied to ESP32 VSPI, and disabling the RFID SPI module, then the display work as expected. The ESP32 has yet another SPI (HSPI), can I use that instead to try to isolate it?

**Comment by olikraus** [comment]
You can at least use the SW_SPI constructor and name all the pins manually. The SPI subsystem is then bypassed and u8g2 will output the bits manually.

**Comment by tobiea27** [comment]
I'm not familiar with the MFRC522 or the library, but I noticed this:

> MFRC522 mfrc522(5, 36);

In the constructor you used the GPIO 36 for the reset and power-down Pin (NRSTPD).
According to the  [ESP32 datasheet](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf) (PDF page: 49, Note No: 2) GPIO 36 is an input only pin.
Maybe this is causing some troubles. 

Alternatively you could try to use different SPI speeds or change the chip selection Pins.

**Comment by olikraus** [comment]
Closing this, I think I can not support here...
