### ISSUE TITLE
support for uncompressed bitmap font from external SPI flash

### ISSUE THREAD

**Issue by myj-dev** [olikraus/u8g2#1027]
Asian fonts link Chinese/Japanese are of large size, so developer would think about put fonts data to external storage like SPI flash.

**Comment by olikraus** [comment]
This has been discussed before...

https://github.com/olikraus/u8g2/issues/461
https://github.com/olikraus/u8g2/issues/710

A solution (for my sister project) is here:
https://github.com/RobotGB/U8G2_for_Adafruit_GFX_extmem
