### ISSUE TITLE
Please see whats wrong here

### ISSUE THREAD

**Issue by GrahamLambert** [olikraus/u8g2#1030]
![disp](https://user-images.githubusercontent.com/56860988/67261694-0d81cb00-f4a2-11e9-9ce3-fb6774b465b3.jpg)

Hi as you can see I only get 3/4 of the width using your example posted previously

**Comment by olikraus** [comment]
Did you enable 16 bit mode?

https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#16-bit-mode

https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L159

**Comment by GrahamLambert** [comment]
Many thanks!
that did it.  In your section "Controller "il3820", Display 
"296x128"Controller "il3820", Display "296x128"
how do I choose the right one?  I only want to display text on an UNO
I'm currently using this one and it seems ok

U8G2_IL3820_V2_296X128_1_4W_SW_SPI u8g2(U8G2_R0,5, 7, 8, 2, 3);


Regards from Graham Lambert
graham@versatronics.co.za
021 713 1334 / 082 419 1334
www.versatronics.co.za

------------------------ Original Message --------------------

**Comment by GrahamLambert** [comment]
PS
Is there a page somewhere with font examples?
  u8g2.setFont (u8g2_font_ncenB14_tr);


Regards from Graham Lambert
graham@versatronics.co.za
021 713 1334 / 082 419 1334
www.versatronics.co.za

------------------------ Original Message --------------------

**Comment by olikraus** [comment]
> how do I choose the right one? 

Basically its a speed vs RAM trade off... HW SPI would be also better, but I think the overall delay for e-paper is much bigger.

> Is there a page somewhere with font examples?

https://github.com/olikraus/u8g2/wiki/fntlistall

or:

https://github.com/olikraus/u8g2/wiki/fntgrp
