### ISSUE TITLE
Dynamic memory and u8x8 does not name a type

### ISSUE THREAD

**Issue by tomsharpe123** [olikraus/u8g2#1033]
Hi olikraus, 
I am trying to use the libraries to code a speed coach to tell me how fast I am travelling in a boat.
I tried coding it with the U8g2 library but it takes 110% of the
dynamic memory of my Arduino nano so will not upload. When I tried to start changing it
to U8x8 it started to chuck up
U8X8_SSD1309_128X64_NONAME0_F_4W_SW_SPI' does not name a type errors.
Is there any easy way to reduce the dynamic memory of the U8g2 code or to change it to the u8x8? 

Thanks Tom

**Comment by olikraus** [comment]
All your ideas are possible and we can discuss in both directions, but I need little bit more information.

> but it takes 110% of the dynamic memory

Which constructor did you use and what is your Arduino board?

> U8X8_SSD1309_128X64_NONAME0_F_4W_SW_SPI

How does the full line like like?

**Comment by tomsharpe123** [comment]
When I try and upload the U8g2 code it does not upload because it says: 
Sketch uses 18432 bytes (60%) of program storage space. Maximum is 30720 bytes.
Global variables use 2259 bytes (110%) of dynamic memory, leaving -211 bytes for local variables. Maximum is 2048 bytes.
Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.
Error compiling for board Arduino Nano.

This is the code: 
`#include <SPI.h>
#include <SandTimer.h>
#include <millisDelay.h>
#include <Adafruit_GPS.h>   //Libraries
#define GPSSerial Serial
Adafruit_GPS GPS(&GPSSerial);
SandTimer timer1;
#define GPSECHO false
#include <Arduino.h>
#include <U8g2lib.h>
#ifdef U8X8_HAVE_HW_SPI
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif
U8G2_SSD1309_128X64_NONAME0_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);
uint32_t timer = millis();
const int chipSelect = 4;
float ms = 0; //Meters/Second variable
float avems = 0;  //Average M/S variable
float mscounter = 0;  //Speed total (for average)
int integcounter = 0; //Counts half-seconds
float meterstraveled = 0; //Total meters
int splittotal = 0;   //Split total (in seconds)  (Essential to be an integer)
int splitseconds = 0; //Seconds on split display  (Essential to be an integer)
int splitminutes = 0; //Minutes on split display  (Essential to be an integer)
int seconds = 0;
int minutes = 0;
int hours = 0;    //Self-explanatory (for timers)
int splitaveragetotal = 0; //All split seconds added together (for average split)
int splitaverageseconds = 0; //Split average seconds
int splitaverageminutes = 0; //Split average minutes
int splitaverage = 0; //Split average
int splitaveragesecondsdisp = 0; //Display variables, fixes a bug
int splitaverageminutesdisp = 0;
float splitmdisp = 0;
float splitsdisp = 0;  //Display Variables
int tc = 0; //Counter variable
int dp = 0; //Data-point variable
int dpave = 0; //Average of the data-points
int dprec = 0; //Counter variable
float knot = 0;//Speed in knots recorded from GPS
float aveknots = 0;  //Speed in knots averaged over 1/2 second (equal to 1 data point and 5 knot readings)
int knotcounter = 0; //Counter variable
int sensorValue = analogRead(A3); //For the data write switch
float msfm = 0; //M/S for the meters calculation

millisDelay secdelay;   //Timing delay (for timer)



void setup() {
  float voltage = sensorValue * (5.0 / 1023.0);   //Converts A3 reading into a 5v equivalent
  Wire.begin();
  Wire.setClock(400000L);
  Serial.begin(115200);
  GPS.begin(9600);
  GPS.sendCommand(PMTK_SET_NMEA_OUTPUT_RMCGGA);
  GPS.sendCommand(PGCMD_ANTENNA);
  delay(1000);    //GPS initialization
  u8g2.begin();
  GPSSerial.println(PMTK_Q_RELEASE);
  int realhours = GPS.hour - 8;
  if (realhours < 0) {
    realhours = realhours + 24; //For SD timestamp (24 hour format)
  }
}

const char s[] PROGMEM = "Progmem";
const char s1[] PROGMEM  = "ABC" ;
const char s2[] PROGMEM  = "DEF" ;
const char s3[] PROGMEM  = "GHI" ;
const char s4[] PROGMEM  = "SMT" ;

const char *a[] = { s1, s2, s3, s4 };
void loop() {

  sensorValue = analogRead(A3);
  float voltage = sensorValue * (5.0 / 1023.0);

  if (secdelay.justFinished()) {
    seconds++;  //Checks if 1 second has passed, updates seconds variable
    secdelay.repeat();
  }
  if (seconds == 60) {
    seconds = 0;  //Checks if 60 seconds have passed, resets seconds, increases minutes
    minutes++;
  }
  if (minutes == 60) {
    minutes = 0;  //Checks if 60 minutes have passed, resets minutes, increases hours
    hours++;
  }
  char c = GPS.read();
  if (GPSECHO)
    if (c) Serial.print(c);
  if (GPS.newNMEAreceived()) {
    Serial.println(GPS.lastNMEA());
    if (!GPS.parse(GPS.lastNMEA()));  //Serial GPS info for debugging
  }

  if (timer > millis()) timer = millis();   //Restarts main timer


  if (timer1.finished()) {
    knot = knot + GPS.speed; knotcounter++;
    timer1.startOver();
  }

  if (millis() - timer > 500) {   //Runs every half-second (responsible for screen-flicker)
    timer = millis(); // Resets timer
    if (GPS.fix) {

      aveknots = knot / knotcounter;
      Serial.println(aveknots);
      ms = (aveknots * 0.5144444); //Converts knots to meters/second
      Serial.println(ms);
      knot = 0;
      tc = 0;
      knotcounter = 0;
      aveknots = 0;
      if (ms <= 0.75) {
        u8g2.clearBuffer();         // clear the internal memory
        u8g2.setFont(u8g2_font_courR08_tr); 
        u8g2.drawStr(0, 10, "Error: IDLE"); // write something to the internal memory
        u8g2.drawStr(1, 10, "Battery: ");
        u8g2.setFont(u8g2_font_courR08_tr);
        u8g2.setCursor(1, 80);
        u8g2.drawStr(2, 10, "Meters:");
        u8g2.setFont(u8g2_font_courR08_tr);
        u8g2.setCursor(2, 80);
        u8g2.print(meterstraveled);


        u8g2.sendBuffer();          // transfer internal memory to the display






        if (ms > 0.75)
        {

          msfm = ms;
          mscounter = (mscounter + msfm); //Continually adds speed to total (for averages)
          integcounter = (integcounter + 1); //Adds +1 to variable every half second (for averages)
          avems = mscounter / integcounter; //Generates average meters/second (for total)
          meterstraveled = avems * (integcounter / 2); //Calculates total (meters/second divided by seconds)
          meterstraveled = round(meterstraveled);
          splittotal = 500 / (ms); //Generates seconds per 500m
          dp = dp + splittotal;  //Adds data-points for dpave variable
          dprec++;
          if (dprec >= 6) {
            dpave = dp / 6; //Calculates average
            dprec = 0;
            dp = 0; //Resets data-points and counter variable


            splitminutes = dpave / 60; //Generates split minutes from split seconds
            splitseconds = dpave - (splitminutes * 60); //Displays remaining seconds
            splitaveragetotal = splitaveragetotal + splittotal; //All split times (in seconds) added together
            splitaverage = splitaveragetotal / (integcounter); //Averages out split times w/ seconds
            splitaverageminutes = splitaverage / 60; //Calculates split minutes
            splitaverageseconds = splitaverage - splitaverageminutes * 60; //Calculates split seconds
            splitaverageminutesdisp = splitaverageminutes;
            splitaveragesecondsdisp = splitaverageseconds;
            splitmdisp = splitminutes;
            splitsdisp = splitseconds;      //Display variables
            u8g2.clearBuffer();          // clear the internal memory
            u8g2.setFont(u8g2_font_courR08_tr); 
            u8g2.drawStr(0, 10, "M:");
            u8g2.setFont(u8g2_font_courR08_tr);

            u8g2.setCursor(0, 25);
            u8g2.setFont(u8g2_font_courR08_tr);
            u8g2.print(meterstraveled);
            u8g2.drawStr(1, 10, "S:");

            u8g2.setFont(u8g2_font_courR08_tr);
            u8g2.setCursor(1, 25);
            u8g2.print(splitmdisp);
            u8g2.drawStr(1, 50, ":");

            u8g2.setFont(u8g2_font_courR08_tr);
            u8g2.setCursor(1, 75);
            u8g2.print(splitsdisp); //adjust pixels to get a good display
            u8g2.sendBuffer();          // transfer internal memory to the display

          }
        }
      }
    }
  }
}
`
The full line of the error for the U8x8 is:
 exit status 1
'U8X8_SSD1309_128X64_NONAME0_F_4W_SW_SPI' does not name a type
and 

u8x8_code:185:17: error: expected unqualified-id before '.' token

             U8X8.setCursor(1, 75);

**Comment by tomsharpe123** [comment]
For some reason it won't let me add all the code in one section

**Comment by olikraus** [comment]
> U8G2_SSD1309_128X64_NONAME0_F_4W_SW_SPI

The "F" constructor will create a 128x64 pixel buffer (1024 bytes) in your Nano. This is 50% of the overall RAM size. A solution could be to learn how to use the page mode constructors (they have "1" or "2" in their name instead of "F")

> The full line of the error for the U8x8 is:

I mean the source code line instead of the error message. Basically this indicates an error in your constructor call. From where did you copy the constructor?

**Comment by AnHardt** [comment]
To save a lot of memory try to avoid the "\*_F_\*" constructors.
U8G2_SSD1309_128X64_NONAME0_1_4W_HW_SPI will need 128 byte instead of 1024.
But the you have to switch from `u8g2.clearBuffer()/u8g2.sendBuffer()` to `firstPage()/nextPage()`

**Comment by tomsharpe123** [comment]
That's the code with too much dynamic memory the code with U8x8 does not name a type error is: 

`#include <SPI.h>
#include <SandTimer.h>
#include <millisDelay.h>
#include <Adafruit_GPS.h>   //Libraries
#define GPSSerial Serial
Adafruit_GPS GPS(&GPSSerial);
SandTimer timer1;
#define GPSECHO false
#include <Arduino.h>
#include <U8g2lib.h>
#ifdef U8X8_HAVE_HW_SPI
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif
U8X8_SSD1306_128X64_4W_SW_SPI u8x8(/* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);
uint32_t timer = millis();
const int chipSelect = 4;
float ms = 0; //Meters/Second variable
float avems = 0;  //Average M/S variable
float mscounter = 0;  //Speed total (for average)
int integcounter = 0; //Counts half-seconds
float meterstraveled = 0; //Total meters
int splittotal = 0;   //Split total (in seconds)  (Essential to be an integer)
int splitseconds = 0; //Seconds on split display  (Essential to be an integer)
int splitminutes = 0; //Minutes on split display  (Essential to be an integer)
int seconds = 0;
int minutes = 0;
int hours = 0;    //Self-explanatory (for timers)
int splitaveragetotal = 0; //All split seconds added together (for average split)
int splitaverageseconds = 0; //Split average seconds
int splitaverageminutes = 0; //Split average minutes
int splitaverage = 0; //Split average
int splitaveragesecondsdisp = 0; //Display variables, fixes a bug
int splitaverageminutesdisp = 0;
float splitmdisp = 0;
float splitsdisp = 0;  //Display Variables
int tc = 0; //Counter variable
int dp = 0; //Data-point variable
int dpave = 0; //Average of the data-points
int dprec = 0; //Counter variable
float knot = 0;//Speed in knots recorded from GPS
float aveknots = 0;  //Speed in knots averaged over 1/2 second (equal to 1 data point and 5 knot readings)
int knotcounter = 0; //Counter variable
int sensorValue = analogRead(A3); //For the data write switch
float msfm = 0; //M/S for the meters calculation

millisDelay secdelay;   //Timing delay (for timer)



void setup() {
  float voltage = sensorValue * (5.0 / 1023.0);   //Converts A3 reading into a 5v equivalent
  Wire.begin();
  Wire.setClock(400000L);
  Serial.begin(115200);
  GPS.begin(9600);
  GPS.sendCommand(PMTK_SET_NMEA_OUTPUT_RMCGGA);
  GPS.sendCommand(PGCMD_ANTENNA);
  delay(1000);    //GPS initialization
 U8X8.begin();
  GPSSerial.println(PMTK_Q_RELEASE);
  int realhours = GPS.hour - 8;
  if (realhours < 0) {
    realhours = realhours + 24; //For SD timestamp (24 hour format)
  }
}

const char s[] PROGMEM = "Progmem";
const char s1[] PROGMEM  = "ABC" ;
const char s2[] PROGMEM  = "DEF" ;
const char s3[] PROGMEM  = "GHI" ;
const char s4[] PROGMEM  = "SMT" ;

const char *a[] = { s1, s2, s3, s4 };
void loop() {

  sensorValue = analogRead(A3);
  float voltage = sensorValue * (5.0 / 1023.0);

  if (secdelay.justFinished()) {
    seconds++;  //Checks if 1 second has passed, updates seconds variable
    secdelay.repeat();
  }
  if (seconds == 60) {
    seconds = 0;  //Checks if 60 seconds have passed, resets seconds, increases minutes
    minutes++;
  }
  if (minutes == 60) {
    minutes = 0;  //Checks if 60 minutes have passed, resets minutes, increases hours
    hours++;
  }
  char c = GPS.read();
  if (GPSECHO)
    if (c) Serial.print(c);
  if (GPS.newNMEAreceived()) {
    Serial.println(GPS.lastNMEA());
    if (!GPS.parse(GPS.lastNMEA()));  //Serial GPS info for debugging
  }

  if (timer > millis()) timer = millis();   //Restarts main timer


  if (timer1.finished()) {
    knot = knot + GPS.speed; knotcounter++;
    timer1.startOver();
  }

  if (millis() - timer > 500) {   //Runs every half-second (responsible for screen-flicker)
    timer = millis(); // Resets timer
    if (GPS.fix) {

      aveknots = knot / knotcounter;
      Serial.println(aveknots);
      ms = (aveknots * 0.5144444); //Converts knots to meters/second
      Serial.println(ms);
      knot = 0;
      tc = 0;
      knotcounter = 0;
      aveknots = 0;
      if (ms <= 0.75) {
        U8X8.clearBuffer();         // clear the internal memory
        U8X8.setFont(U8X8_font_courR08_tr); // choose a suitable font
        U8X8.drawStr(0, 10, "Error: IDLE"); // write something to the internal memory
        .drawStr(1, 10, "Battery: ");
        U8X8.setFont(U8X8_font_courR08_tr);
        U8X8.setCursor(1, 80);
        U8X8.drawStr(2, 10, "Meters:");
        U8X8.setFont(U8X8_font_courR08_tr);
        U8X8.setCursor(2, 80);
        U8X8.print(meterstraveled);


        U8X8.sendBuffer();          // transfer internal memory to the display






        if (ms > 0.75)
        {

          msfm = ms;
          mscounter = (mscounter + msfm); //Continually adds speed to total (for averages)
          integcounter = (integcounter + 1); //Adds +1 to variable every half second (for averages)
          avems = mscounter / integcounter; //Generates average meters/second (for total)
          meterstraveled = avems * (integcounter / 2); //Calculates total (meters/second divided by seconds)
          meterstraveled = round(meterstraveled);
          splittotal = 500 / (ms); //Generates seconds per 500m
          dp = dp + splittotal;  //Adds data-points for dpave variable
          dprec++;
          if (dprec >= 6) {
            dpave = dp / 6; //Calculates average
            dprec = 0;
            dp = 0; //Resets data-points and counter variable


            splitminutes = dpave / 60; //Generates split minutes from split seconds
            splitseconds = dpave - (splitminutes * 60); //Displays remaining seconds
            splitaveragetotal = splitaveragetotal + splittotal; //All split times (in seconds) added together
            splitaverage = splitaveragetotal / (integcounter); //Averages out split times w/ seconds
            splitaverageminutes = splitaverage / 60; //Calculates split minutes
            splitaverageseconds = splitaverage - splitaverageminutes * 60; //Calculates split seconds
            splitaverageminutesdisp = splitaverageminutes;
            splitaveragesecondsdisp = splitaverageseconds;
            splitmdisp = splitminutes;
            splitsdisp = splitseconds;      //Display variables
            U8X8.clearBuffer();          // clear the internal memory
            U8X8.setFont(U8X8_font_courR08_tr); // choose a suitable font --------------------CHANGE THIS FONT TO SOMETHING LARGER
            U8X8.drawStr(0, 10, "M:");
            U8X8.setFont(U8X8_font_courR08_tr);

            U8X8.setCursor(0, 25);
            U8X8.setFont(U8X8_font_courR08_tr);
            U8X8.print(meterstraveled);
            U8X8.drawStr(1, 10, "S:");

            U8X8.setFont(U8X8_font_courR08_tr);
            U8X8.setCursor(1, 25);
            U8X8.print(splitmdisp);
            U8X8.drawStr(1, 50, ":");

            U8X8.setFont(U8X8_font_courR08_tr);
            U8X8.setCursor(1, 75);
            U8X8.print(splitsdisp); //adjust pixels to get a good display
            U8X8.sendBuffer();          // transfer internal memory to the display

          }
        }
      }
    }
  }
}`

I will have a look into page constructors and see if I can get them to work

**Comment by olikraus** [comment]
type error: You must use "u8x8" instead of "U8X8".

**Comment by tomsharpe123** [comment]
Thanks, I've changed that and still throwing up the same errors. 
The U8g2 version of the code is now down to 72% of the memory by changing the constructor to a page buffer one. Is there anything else that I need to change in the code for it to work?

**Comment by olikraus** [comment]
"1" constructor: you can not use sendBuffer any more. See the u8g2 examples...

**Comment by tomsharpe123** [comment]
I have tried to rewrite it with a page buffer but am still getting loads of errors
 `#include <SPI.h>
#include <SandTimer.h>
#include <millisDelay.h>
#include <Adafruit_GPS.h>   //Libraries
#define GPSSerial Serial
Adafruit_GPS GPS(&GPSSerial);
SandTimer timer1;
#define GPSECHO false
#include <Arduino.h>
#include <U8g2lib.h>
#ifdef U8X8_HAVE_HW_SPI
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif
U8G2_SSD1309_128X64_NONAME2_2_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);
uint32_t timer = millis();
const int chipSelect = 4;
float ms = 0; //Meters/Second variable
float avems = 0;  //Average M/S variable
float mscounter = 0;  //Speed total (for average)
int integcounter = 0; //Counts half-seconds
float meterstraveled = 0; //Total meters
int splittotal = 0;   //Split total (in seconds)  (Essential to be an integer)
int splitseconds = 0; //Seconds on split display  (Essential to be an integer)
int splitminutes = 0; //Minutes on split display  (Essential to be an integer)
int seconds = 0;
int minutes = 0;
int hours = 0;    //Self-explanatory (for timers)
int splitaveragetotal = 0; //All split seconds added together (for average split)
int splitaverageseconds = 0; //Split average seconds
int splitaverageminutes = 0; //Split average minutes
int splitaverage = 0; //Split average
int splitaveragesecondsdisp = 0; //Display variables, fixes a bug
int splitaverageminutesdisp = 0;
float splitmdisp = 0;
float splitsdisp = 0;  //Display Variables
int tc = 0; //Counter variable
int dp = 0; //Data-point variable
int dpave = 0; //Average of the data-points
int dprec = 0; //Counter variable
float knot = 0;//Speed in knots recorded from GPS
float aveknots = 0;  //Speed in knots averaged over 1/2 second (equal to 1 data point and 5 knot readings)
int knotcounter = 0; //Counter variable
int sensorValue = analogRead(A3); //For the data write switch
float msfm = 0; //M/S for the meters calculation

millisDelay secdelay;   //Timing delay (for timer)



void setup(void) {
  float voltage = sensorValue * (5.0 / 1023.0);   //Converts A3 reading into a 5v equivalent
  Wire.begin();
  Wire.setClock(400000L);
  Serial.begin(115200);
  GPS.begin(9600);
  GPS.sendCommand(PMTK_SET_NMEA_OUTPUT_RMCGGA);
  GPS.sendCommand(PGCMD_ANTENNA);
  delay(1000);    //GPS initialization
  u8g2.begin();
  GPSSerial.println(PMTK_Q_RELEASE);
  int realhours = GPS.hour - 8;
  if (realhours < 0) {
    realhours = realhours + 24; //For SD timestamp (24 hour format)
  }
}

const char s[] PROGMEM = "Progmem";
const char s1[] PROGMEM  = "ABC" ;
const char s2[] PROGMEM  = "DEF" ;
const char s3[] PROGMEM  = "GHI" ;
const char s4[] PROGMEM  = "SMT" ;

const char *a[] = { s1, s2, s3, s4 };
void loop(void) {
  u8g2.firstPage();
  do {

  sensorValue = analogRead(A3);
  float voltage = sensorValue * (5.0 / 1023.0);

  if (secdelay.justFinished()) {
    seconds++;  //Checks if 1 second has passed, updates seconds variable
    secdelay.repeat();
  }
  if (seconds == 60) {
    seconds = 0;  //Checks if 60 seconds have passed, resets seconds, increases minutes
    minutes++;
  }
  if (minutes == 60) {
    minutes = 0;  //Checks if 60 minutes have passed, resets minutes, increases hours
    hours++;
  }
  char c = GPS.read();
  if (GPSECHO)
    if (c) Serial.print(c);
  if (GPS.newNMEAreceived()) {
    Serial.println(GPS.lastNMEA());
    if (!GPS.parse(GPS.lastNMEA()));  //Serial GPS info for debugging
  }

  if (timer > millis()) timer = millis();   //Restarts main timer


  if (timer1.finished()) {
    knot = knot + GPS.speed; knotcounter++;
    timer1.startOver();
  }

  if (millis() - timer > 500) {   //Runs every half-second (responsible for screen-flicker)
    timer = millis(); // Resets timer
    if (GPS.fix) {

      aveknots = knot / knotcounter;
      Serial.println(aveknots);
      ms = (aveknots * 0.5144444); //Converts knots to meters/second
      Serial.println(ms);
      knot = 0;
      tc = 0;
      knotcounter = 0;
      aveknots = 0;
      if (ms <= 0.75) {
        u8g2.setFont(u8g2_font_courR08_tr); // choose a suitable font
        u8g2.drawStr(0, 10, "Error: IDLE"); // write something to the internal memory
        u8g2.drawStr(1, 10, "Battery: ");
        u8g2.setFont(u8g2_font_courR08_tr);
        u8g2.setCursor(1, 80);
        u8g2.drawStr(2, 10, "Meters:");
        u8g2.setFont(u8g2_font_courR08_tr);
        u8g2.setCursor(2, 80);
        u8g2.print(meterstraveled);

        if (ms > 0.75)
        {

          msfm = ms;
          mscounter = (mscounter + msfm); //Continually adds speed to total (for averages)
          integcounter = (integcounter + 1); //Adds +1 to variable every half second (for averages)
          avems = mscounter / integcounter; //Generates average meters/second (for total)
          meterstraveled = avems * (integcounter / 2); //Calculates total (meters/second divided by seconds)
          meterstraveled = round(meterstraveled);
          splittotal = 500 / (ms); //Generates seconds per 500m
          dp = dp + splittotal;  //Adds data-points for dpave variable
          dprec++;
          if (dprec >= 6) {
            dpave = dp / 6; //Calculates average
            dprec = 0;
            dp = 0; //Resets data-points and counter variable


            splitminutes = dpave / 60; //Generates split minutes from split seconds
            splitseconds = dpave - (splitminutes * 60); //Displays remaining seconds
            splitaveragetotal = splitaveragetotal + splittotal; //All split times (in seconds) added together
            splitaverage = splitaveragetotal / (integcounter); //Averages out split times w/ seconds
            splitaverageminutes = splitaverage / 60; //Calculates split minutes
            splitaverageseconds = splitaverage - splitaverageminutes * 60; //Calculates split seconds
            splitaverageminutesdisp = splitaverageminutes;
            splitaveragesecondsdisp = splitaverageseconds;
            splitmdisp = splitminutes;
            splitsdisp = splitseconds;      //Display variables
            u8g2.setFont(u8g2_font_courR08_tr); // choose a suitable font --------------------CHANGE THIS FONT TO SOMETHING LARGER
            u8g2.drawStr(0, 10, "M:");
            u8g2.setFont(u8g2_font_courR08_tr);

            u8g2.setCursor(0, 25);
            u8g2.setFont(u8g2_font_courR08_tr);
            u8g2.print(meterstraveled);
            u8g2.drawStr(1, 10, "S:");

            u8g2.setFont(u8g2_font_courR08_tr);
            u8g2.setCursor(1, 25);
            u8g2.print(splitmdisp);
            u8g2.drawStr(1, 50, ":");

            u8g2.setFont(u8g2_font_courR08_tr);
            u8g2.setCursor(1, 75);
            u8g2.print(splitsdisp); //adjust pixels to get a good display
           } while ( u8g2.nextPage() );  
} 
          }
        }
      }
    }
  }
}

`
 errors: 


C:\Users\User\OneDrive\Documents\Arduino\Page_buffer\Page_buffer.ino: In function 'void loop()':

Page_buffer:185:3: error: expected 'while' before '}' token

   }

   ^

Page_buffer:185:3: error: expected '(' before '}' token

Page_buffer:185:3: error: expected primary-expression before '}' token

Page_buffer:185:3: error: expected ')' before '}' token

Page_buffer:185:3: error: expected ';' before '}' token

C:\Users\User\OneDrive\Documents\Arduino\Page_buffer\Page_buffer.ino: At global scope:

Page_buffer:186:1: error: expected declaration before '}' token

 }

 ^

exit status 1
expected 'while' before '}' token

**Comment by olikraus** [comment]
your "if" does not have a closing "}"

**Comment by tomsharpe123** [comment]
Which if statement?

**Comment by olikraus** [comment]
line 153

**Comment by tomsharpe123** [comment]
I've corrected that but it still has the same 6 errors

**Comment by olikraus** [comment]
> I've corrected that but it still has the same 6 errors

Then it is not corrected. What can I say, the "while" does not fit to the corresponding "do"...

**Comment by tomsharpe123** [comment]
Is there an easy way of fixing that?

**Comment by olikraus** [comment]
Sure

**Comment by olikraus** [comment]
Excause the short answer (from my mobile phone). Long version: I really like to answer questions regarding u8g2, but I can not teach or fix C/C++ basics...

**Comment by tomsharpe123** [comment]
I have fixed the basic issues with the code and it is now uploading but I am only seeing the top half of the number

**Comment by tomsharpe123** [comment]
Is there any way to fix this?

**Comment by olikraus** [comment]
Probably the picture loop (first/next page) loop is not executed correctly. 
My suggestion is to put all u8g2 graphics commands into a procedure (e.g. "draw()")
Then put the while loop around this call.

You can see this here: The complexity of the draw commands are hidden inside the function calls. The first/next page loop is clearly visible:

https://github.com/olikraus/u8g2/blob/f0efab642af931ba228e5094e27f8efc0c736ad5/sys/arduino/u8g2_page_buffer/Weather/Weather.ino#L366-L370
