### ISSUE TITLE
Fonts resize

### ISSUE THREAD

**Issue by EliasA97** [olikraus/u8g2#1034]
Hi, this library does a fine job but I have a small problem. 
I must use greek fonts (u8g2_font_10x20_t_greek) but unfortunatelly I didn't found much fonts with different sizes. I mean there are about 5 different fonts with different sizes that include greek characters. I like this specific font but is there any way to make it in other size, like 8x9 or 15x16?

**Comment by olikraus** [comment]
First: There is no resize possible. U8g2 only supports fixed size bitmap fonts. This means we have to rely on font authors to create greek letters.

The good news is: Many fonts have greek letters included, but I did not always render the greek fonts for u8g2. 

Probably all fonts here should include greek letters in the font source, but I did not include them for u8g2: https://github.com/olikraus/u8g2/wiki/fntgrpadobex11

I am very sure that all fonts here also include greek letters: https://github.com/olikraus/u8g2/wiki/fntgrpx11

So for example, if you want greek letters for this font:
![https://raw.githubusercontent.com/wiki/olikraus/u8g2/fntpic/u8g2_font_8x13_tf.png](https://raw.githubusercontent.com/wiki/olikraus/u8g2/fntpic/u8g2_font_8x13_tf.png)

just let me know. Or: You can also render the fonts by your self with the bdfconv tool (https://github.com/olikraus/u8g2/tree/master/tools/font/bdfconv) and the corresponding font source (e.g https://github.com/olikraus/u8g2/blob/master/tools/font/bdf/8x13.bdf)

Another approach is to look around in the u8g2 fonts: For example NBP group contains a lot of fonts with greek gylphs: https://github.com/olikraus/u8g2/wiki/fntgrpnbp

**Comment by EliasA97** [comment]
Hi Oliver, I think it's interesting to make my own fonts but I tried with the bdfconv without success. The program does not even start. I managed to convert a font to bdf with fony but I'm stuck.  Is there any tutorial or video to explain the conversion procedure? Also how can I insert my custom font in the u8g2 library? I'm asking that because I don't want to bother you with my tests!!

**Comment by olikraus** [comment]
> Update: I managed to get a custom font converted by fony and bdfconv but it only shows english glyphs and not the greek characters that I want. Any ideas about that??

You need specify the unicode range for bdfconv with the -m command.
```
bdfconv -f 1 -v -m '32-127,895-1023'
```
where  895-1023 should be the unicode range for the greek letters.

**Comment by EliasA97** [comment]
I don't think thats the problem. When I'm importing a font from windows to fony, the programm only imports characters up to 255, so there is no way to load the greek glyphs which are on 895-1023. Also it exports the bdf only up to 255.

**Comment by olikraus** [comment]
Windows might require " instead of single quotes. See also the u8g2 FAQ

**Comment by EliasA97** [comment]
I did that with ". Also I did exactly what daq says. Do you want to send you my custom font to try it yourself?

**Comment by olikraus** [comment]
If you created the font with fony then indeed the glyphs go until 255 only. But they will appear under the code you have entered them in fony

**Comment by EliasA97** [comment]
So you're saying that I have to import a font in fony, export it as bdf, use the bdfconv, copy the code in my arduino project and then display the greek glyphs?

**Comment by EliasA97** [comment]
Also I have that problem in the picture. The glyphs with ? are greek letters. Do you know why this happens?
![test](https://user-images.githubusercontent.com/56277356/67620803-5ecbea80-f813-11e9-8d9c-60edc980f461.jpg)

**Comment by olikraus** [comment]
> So you're saying that I have to import a font in fony,

Ah, no, you just mentioned fony before, so I thought you might have used it.
Actually it is better not to use fony if you have an existing font with greek letters at the right position, because fony can not work with glyphes above 255.

You could also use -m "32-65535" to convert everything.

**Comment by EliasA97** [comment]
I didn't know that. I have many fonts with greek glyphs but they are .otf and .ttf. How can I convert them to bdf without fony?

**Comment by olikraus** [comment]
I personally use "otf2bdf".

**Comment by EliasA97** [comment]
I just found out that otf2bdf is for linux and I can't access it. Would it be easy for you to convert my font? If you have time for that, please check the link. 

https://we.tl/t-50ZGk1mlMW

**Comment by olikraus** [comment]
Which pt site?

**Comment by EliasA97** [comment]
20

**Comment by olikraus** [comment]
Conversion:

```
	./otf2bdf/otf2bdf -a  -p 20 -o analecta.bdf Analecta.otf
	./bdfconv -v -f 1 -m '32-65535' analecta.bdf -o u8g2_font_analecta.c  -n u8g2_font_analecta -d ../bdf/helvB18.bdf 
```

![analecta](https://user-images.githubusercontent.com/1084992/67624696-3b656780-f834-11e9-9fa4-65bc48a64e08.png)

the zip contains the bdf and the u8g2 font.

[analecta.zip](https://github.com/olikraus/u8g2/files/3775169/analecta.zip)

**Comment by EliasA97** [comment]
wow. Works like a charm. You are the best!!!

I have a last question about doing this on my own. Did you made the font only by these 2 commands? Also how did you made image?

**Comment by olikraus** [comment]
> Did you made the font only by these 2 commands? 

yes

> Also how did you made the image?

The second command will generate a fixed file called bdf.tga (because of the -d option), which was converted with the tool "convert" to png (https://imagemagick.org/script/convert.php).

**Comment by EliasA97** [comment]
Great. Thank's again Oliver. I must tell you that I'll contribute to your library with some greek fonts that I hope to make and send you to add them. For now I'm closing the case.

**Comment by EliasA97** [comment]
Hi again Oliver, I think I'm being very annoying by now but I followed your steps in order to recreate the bdf file but with no result. Is it possible to make a video or something to show me exactly your steps?
![w](https://user-images.githubusercontent.com/56277356/67626824-9b223980-f859-11e9-81bc-504eae4adeda.jpg)

**Comment by EliasA97** [comment]
Actually I made it with this command (otf2bdf -r 72 -p 16 Analecta.otf -o Analecta.bdf) that I fount here:
https://github.com/olikraus/u8g2/wiki/internal#ttf-to-bdf

What are the differences between `otf2bdf` -r 72 -p 16 Analecta.otf -o Analecta.bdf` and `otf2bdf -a  -p 20 -o analecta.bdf Analecta.otf` ??

**Comment by olikraus** [comment]
Looks like you have installed linux :-)

>  Is it possible to make a video or something to show me exactly your steps?

I hope we can manage this without video. 

"-p" sets the desired point size (you had requested 20)
"-r" would set the resolution. Actually I also do not exactly know its effect.
"-a" will force auto hinting. It is a new feature of the freetype lib which I added to otf2bdf by myself (https://github.com/olikraus/u8g2/blob/master/tools/font/otf2bdf/otf2bdf.c#L1300)

To get the "-a" option, you need to download my version of otf2bdf: https://github.com/olikraus/u8g2/tree/master/tools/font/otf2bdf
More specific: You can clone u8g2 repoo (under linux):
`git clone https://github.com/olikraus/u8g2.git`
The goto tools/font/otf2bdf and type make

Regarding otf2bdf: it is more kind of experimenting to figure out which options look best. 

A nice tool is "ftview" (again linux) which allows you to see the effect of each option and size immediately.

**Comment by EliasA97** [comment]
Hi Oliver, I just wanted to tell you that everything works. I made many fonts with your help. Thank's again!!!
