### ISSUE TITLE
Is there any Cyrillic font for U8x8?

### ISSUE THREAD

**Issue by ilgiznurgaliev** [olikraus/u8g2#1035]
Hi,

So the question is in subject? Seems no any Cyrillic font is available for U8x8...

Regards, Casper.

**Comment by olikraus** [comment]
Correct, u8x8 does not support Unicode. However Cyrillic glyphs could be mapped into this region and a new font could be created. Do you have any font in mind for this purpose?

**Comment by ilgiznurgaliev** [comment]
Thanks for your responce.
Lets take u8g2_font_5x8_t_cyrillic as example. Did I understand you correctly, that I can import some glyphs from any cyrillic font? If so I would really appreciate for a small example of how to do this.

**Comment by olikraus** [comment]
The command probably will be something like this:
```
bdfconv -v -f 2 -m "1024-1279>0" -o u8x8_5x8_cyrillic.c -n u8x8_5x8_cyrillic 5x8.bdf
```
The "1024-1279>0" expression will map the cyrillic unicode block into the range from 0 to 255. I am not sure whether this really makes sense, it depends also which you really require.

```
bdfconv -v -f 2 -m "32-127;1024-1151>128;" -o u8x8_5x8_cyrillic.c -n u8x8_5x8_cyrillic 5x8.bdf
```

This should keep the latin chars from ASCII range 32 to 127 and map the lower part of the cyrillic chars to the range from 128 to 255.

Not tested, but it should work like this...

**Comment by ilgiznurgaliev** [comment]
Many thanks. I'll try to install bdfconv and test this.
