### ISSUE TITLE
Can you add support for UC-1602ASYCG01 (US2066)?

### ISSUE THREAD

**Issue by iggymayer** [olikraus/u8g2#1036]
1602 OLED
datasheet:
https://mega.nz/#!hQ1jhaSJ!fAblPo1j9bjlliRZ7KBoUBhqIr-zV03LXSZLiUC_cSY
https://mega.nz/#!tZ8DGSCD!_Pt4eRJAucGrx5ZPbRPAuWHFsNuv9CwMxOR_kKLi46A

**Comment by olikraus** [comment]
this seems to be the US2066 controller: https://www.displayfuture.com/Display/datasheet/controller/US2066.pdf

Implementation can be done (i think), but character ROM can not be supported by u8g2. I can only implement graphics mode (if this is possible with this controller)

**Comment by olikraus** [comment]
I had a closer look to this display: It is a character OLED driver only. Graphics mode is not possible. This means, u8g2 can not support this.

**Comment by iggymayer** [comment]
Thank you
