### ISSUE TITLE
Which font is used for creating U8g2 logo

### ISSUE THREAD

**Issue by e-labInnovations** [olikraus/u8g2#1048]
Hi @olikraus 
Which font is used for creating U8g2 logo?
![u8g2](https://user-images.githubusercontent.com/33958126/69001410-cef5f980-0903-11ea-876c-78fc01fe5b88.png)

**Comment by olikraus** [comment]
Reference:
https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/U8g2Logo/U8g2Logo.ino#L325

Inconsolata Bold: https://github.com/olikraus/u8g2/wiki/fntgrpinconsolata

Which was downloaded from here: https://fontlibrary.org/en/font/inconsolata-lgc#Inconsolata%20LGC-Bold

Any reasion why you need this information?

**Comment by e-labInnovations** [comment]
@olikraus 
Thanks for your information
