### ISSUE TITLE
Stop graphics from looping around when outside of screen boundaries

### ISSUE THREAD

**Issue by ScienceMarc** [olikraus/u8g2#1049]
Is there a way to disable the behavior where something drawn far outside of the display does not seemingly loop back from the other side of the display? I'm using the SSD1327 if that's important.

![gif](https://user-images.githubusercontent.com/24737495/69116914-906f5480-0a53-11ea-9cda-ea734dac434e.gif)

**Comment by olikraus** [comment]
Options: 
 - Enable 16 bit mode: https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L159
 - Check whether the object is outside or not
 - Use https://github.com/olikraus/u8g2/wiki/u8g2reference#setclipwindow

**Comment by ScienceMarc** [comment]
Enabling 16-bit mode resolved the issue. Thanks
