### ISSUE TITLE
Voltage on GPIO D12 when using HW SPI

### ISSUE THREAD

**Issue by aviator93** [olikraus/u8g2#1063]
Hello

I have a rather large sketch running on my Arduino Nano Every to control 3 stepper Motors, an OLED and a rotary Encoder.

On the Every, SW SPI is very slow, so I use HW SPI. This works very fast, but every time I use HW SPI I have a small voltage on GPIO D12. As my stepper Motor is connected to this port, it is always turning slowly. All my digital ports are used, so I can't use a different one but Pin 12. 

Does anybody have an idea how I can prevent this from happening? I would love to use HW SPI...

These are the constructors I use:

U8G2_SSD1327_WS_128X128_1_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ U8X8_PIN_NONE);

U8G2_SSD1327_WS_128X128_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ U8X8_PIN_NONE);

Thanks in advance!
Dominik

**Comment by aviator93** [comment]
Good news!
Problem is not solved but I found a way to use a different gpio instead of 12. The every has even more Digital Pins than the Nano, I didn't know.

**Comment by olikraus** [comment]
I think Arduino SPI will always use D12 (MISO)

**Comment by aviator93** [comment]
thanks Oli for your quick reply! Thats what I thought myself too...
