### ISSUE TITLE
Drawing Logo on Heltec WiFi Lora 32 ESP Module issue

### ISSUE THREAD

**Issue by sanfordjd** [olikraus/u8g2#1064]
I'm seeing a strange issue when trying to *change* the default Logo displayed during startup.  
The example code references an "image.h" file that can be edited.  
When trying to change the image to a custom one, it looks like parts of the image are written "right to left" instead of "left to right".  

I previewed the "Heltec" logo and the logo's bitmap does indeed seem to be written strangely.  
(checked here 'http://javl.github.io/image2cpp/')  The "image.h" file is added as an "include" at the start of the example *.ino files I was reviewing.  This can be reproduced on any of the example files that reference the image.h file ... although I was using the LoRa sender example.  Changing my image.h for the default/ example one is one way to see the issue.

My bmp (which should be an oval with the word "test" behind it):

>

>  #define logo_width 128
>    #define logo_height 53
> 
>     const unsigned char testlogo[] = {
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xfe, 0x04, 0x11, 0x81, 0xc0, 0x82, 0x30, 0x38, 0x10, 0x46, 0x07, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xfd, 0xf7, 0xff, 0xff, 0xbe, 0xff, 0xff, 0xf7, 0xdf, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xfd, 0xf7, 0xff, 0xff, 0xbe, 0xff, 0xff, 0xf7, 0xdf, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xfc, 0x33, 0xff, 0xff, 0x86, 0x7f, 0xff, 0xf0, 0xcf, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xe0, 0x7d, 0xfc, 0xff, 0xff, 0xbf, 0x9f, 0xff, 0xf7, 0xf3, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xf9, 0xfd, 0xfc, 0xff, 0xff, 0xbf, 0xdf, 0xff, 0xf7, 0xfb, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xf9, 0xc1, 0x88, 0x7f, 0xff, 0xbf, 0xdf, 0xf0, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xf9, 0x98, 0x10, 0xff, 0xff, 0x82, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xf9, 0x81, 0x1c, 0xff, 0xff, 0xfc, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0xff, 0xff, 0xff, 0xff, 
>       0xf9, 0x9f, 0x8c, 0xff, 0xff, 0xc0, 0x00, 0x1f, 0xff, 0xff, 0x00, 0x00, 0x7f, 0xff, 0xff, 0xff, 
>       0xf9, 0x9f, 0xcc, 0xff, 0xfe, 0x00, 0x1f, 0xff, 0xff, 0xff, 0xff, 0x00, 0x07, 0xff, 0xff, 0xff, 
>       0xf9, 0xc1, 0x1e, 0x7f, 0xf0, 0x03, 0xff, 0xff, 0xff, 0xff, 0xff, 0xf8, 0x01, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0x80, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x80, 0x3f, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xfe, 0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xf0, 0x0f, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xf8, 0x0f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe, 0x03, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xf0, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x81, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xc0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xe0, 0x7f, 0xff, 
>       0xff, 0xff, 0xff, 0x83, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xf8, 0x3f, 0xff, 
>       0xff, 0xff, 0xff, 0x07, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfc, 0x1f, 0xff, 
>       0xff, 0xff, 0xff, 0x0f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe, 0x1f, 0xff, 
>       0xff, 0xff, 0xfe, 0x1f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0f, 0xff, 
>       0xff, 0xff, 0xfe, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x8f, 0xff, 
>       0xff, 0xff, 0xfc, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc7, 0xff, 
>       0xff, 0xff, 0xfc, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc7, 0xff, 
>       0xff, 0xff, 0xfc, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc7, 0xff, 
>       0xff, 0xff, 0xfc, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc7, 0xff, 
>       0xff, 0xff, 0xfc, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc7, 0xff, 
>       0xff, 0xff, 0xfe, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x8f, 0xff, 
>       0xff, 0xff, 0xfe, 0x1f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x0f, 0xff, 
>       0xff, 0xff, 0xff, 0x0f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe, 0x1f, 0xff, 
>       0xff, 0xff, 0xff, 0x07, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfc, 0x1f, 0xff, 
>       0xff, 0xff, 0xff, 0x83, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xf8, 0x3f, 0xff, 
>       0xff, 0xff, 0xff, 0xc0, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xe0, 0x7f, 0xff, 
>       0xff, 0xff, 0xff, 0xf0, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x81, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xf8, 0x0f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe, 0x03, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xfe, 0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xf8, 0x0f, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0x80, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x80, 0x3f, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xf0, 0x03, 0xff, 0xff, 0xff, 0xff, 0xff, 0xf8, 0x00, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xfc, 0x00, 0x1f, 0xff, 0xff, 0xff, 0xff, 0x00, 0x07, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xc0, 0x00, 0x1f, 0xff, 0xff, 0x80, 0x00, 0x3f, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xf8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xe0, 0x00, 0x00, 0x00, 0x00, 0x7f, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xe0, 0x00, 0x00, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
>       0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
> 
> };

Heltec's logo:

> const unsigned char myBitmap [] PROGMEM = {
> 	// 'undefined, 128x64px
> 	0x00, 0x00, 0x38, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0x70, 0x00, 0xf8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xe0, 0x01, 0xf0, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xc0, 0x07, 0xf0, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xc0, 0x0f, 0xf0, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xc0, 0x1f, 0xf0, 0x1f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xe0, 0x1f, 0xf0, 0x1f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xe0, 0x3f, 0xf8, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xe0, 0x1f, 0xf8, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xe0, 0x1f, 0xf8, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xf0, 0x1f, 0xf8, 0x1f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xf0, 0x1f, 0xfc, 0x1f, 0x80, 0xff, 0x8f, 0x7f, 0xc0, 0xff, 0x7f, 0xc0, 0xff, 0x03, 0xc0, 0x3f, 
> 	0xf0, 0x1f, 0xfc, 0x1f, 0xe0, 0xff, 0x87, 0x3f, 0xc0, 0xff, 0x7f, 0xf0, 0xff, 0x01, 0xf8, 0xff, 
> 	0xf0, 0x0f, 0xfc, 0x1f, 0xe0, 0xff, 0x87, 0x3f, 0xe0, 0xff, 0x7f, 0xf8, 0xff, 0x01, 0xfe, 0xff, 
> 	0xf8, 0x0f, 0xfe, 0x0f, 0xf0, 0xff, 0x87, 0x3f, 0xe0, 0xff, 0x7f, 0xfc, 0xff, 0x01, 0xff, 0xff, 
> 	0xf8, 0xff, 0xff, 0x0f, 0xf0, 0xff, 0xc7, 0x3f, 0xe0, 0xff, 0x3f, 0xfc, 0xff, 0x81, 0xff, 0xff, 
> 	0xf8, 0xff, 0xff, 0x0f, 0xf0, 0xff, 0xc3, 0x1f, 0xe0, 0xff, 0x3f, 0xfc, 0xff, 0xc0, 0xff, 0x7f, 
> 	0xfc, 0xff, 0xff, 0x0f, 0xf8, 0xff, 0xc3, 0x1f, 0xe0, 0xff, 0x3f, 0xfc, 0xff, 0xe0, 0xff, 0x7f, 
> 	0xfc, 0xff, 0xff, 0x07, 0xf8, 0x03, 0xc0, 0x1f, 0x00, 0xfe, 0x01, 0xfe, 0x00, 0xf0, 0x3f, 0x70, 
> 	0xfc, 0xff, 0xff, 0x07, 0xf8, 0x03, 0xe0, 0x0f, 0x00, 0xfe, 0x00, 0xfe, 0x00, 0xf0, 0x1f, 0x60, 
> 	0xfc, 0xff, 0xff, 0x07, 0xf8, 0x03, 0xe0, 0x0f, 0x00, 0xfe, 0x00, 0xfe, 0x00, 0xf0, 0x07, 0x20, 
> 	0xfe, 0xff, 0xff, 0x07, 0xfc, 0xff, 0xe1, 0x0f, 0x00, 0xff, 0x00, 0xff, 0x7f, 0xf8, 0x07, 0x00, 
> 	0xfe, 0x83, 0xff, 0x03, 0xfc, 0xff, 0xf1, 0x0f, 0x00, 0x7f, 0x00, 0xff, 0x7f, 0xf8, 0x03, 0x00, 
> 	0xfe, 0x83, 0xff, 0x03, 0xfc, 0xff, 0xf0, 0x07, 0x00, 0x7f, 0x00, 0xff, 0x7f, 0xfc, 0x03, 0x00, 
> 	0xfe, 0x81, 0xff, 0x03, 0xfc, 0xff, 0xf0, 0x07, 0x00, 0x7f, 0x00, 0xff, 0x3f, 0xfc, 0x03, 0x00, 
> 	0xff, 0xc1, 0xff, 0x01, 0xfe, 0xff, 0xf0, 0x07, 0x80, 0x3f, 0x80, 0xff, 0x3f, 0xfc, 0x03, 0x00, 
> 	0xff, 0xc1, 0xff, 0x01, 0xfe, 0xff, 0xf8, 0x07, 0x80, 0x3f, 0x80, 0xff, 0x3f, 0xfc, 0x03, 0x10, 
> 	0xff, 0xc1, 0xff, 0x01, 0xfe, 0x00, 0xf8, 0x03, 0x80, 0x3f, 0x80, 0x3f, 0x00, 0xfc, 0x03, 0x0c, 
> 	0xff, 0xc0, 0xff, 0x01, 0xff, 0x00, 0xf8, 0x03, 0xc0, 0x3f, 0x80, 0x3f, 0x00, 0xfc, 0x07, 0x0e, 
> 	0xff, 0xe0, 0xff, 0x00, 0x7f, 0x00, 0xf8, 0x03, 0xc0, 0x1f, 0xc0, 0x3f, 0x00, 0xfc, 0xff, 0x0f, 
> 	0xff, 0xe0, 0xff, 0x00, 0xff, 0x7f, 0xfc, 0xff, 0xc1, 0x1f, 0xc0, 0xff, 0x1f, 0xfc, 0xff, 0x0f, 
> 	0x7f, 0xe0, 0xff, 0x00, 0xff, 0x3f, 0xfc, 0xff, 0xc1, 0x1f, 0xc0, 0xff, 0x0f, 0xf8, 0xff, 0x07, 
> 	0x7e, 0xe0, 0xff, 0x80, 0xff, 0x3f, 0xfc, 0xff, 0xe0, 0x1f, 0xc0, 0xff, 0x0f, 0xf8, 0xff, 0x07, 
> 	0x7c, 0xf0, 0x7f, 0x80, 0xff, 0x3f, 0xfe, 0xff, 0xe0, 0x0f, 0xe0, 0xff, 0x0f, 0xf0, 0xff, 0x07, 
> 	0xf8, 0xf0, 0x7f, 0x80, 0xff, 0x1f, 0xfe, 0xff, 0xe0, 0x0f, 0xe0, 0xff, 0x0f, 0xe0, 0xff, 0x07, 
> 	0xe0, 0xf0, 0x7f, 0x80, 0xff, 0x1f, 0xfe, 0xff, 0xe0, 0x0f, 0xe0, 0xff, 0x07, 0x80, 0xff, 0x03, 
> 	0x00, 0xf0, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x00, 
> 	0x00, 0xf8, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0x00, 0xf8, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0x00, 0xf8, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0x00, 0xfc, 0x1f, 0x00, 0x8f, 0xf7, 0xff, 0x7c, 0xbc, 0xc7, 0xf3, 0xff, 0xfc, 0xbc, 0x07, 0x00, 
> 	0x00, 0xfc, 0x1f, 0x00, 0x8f, 0x73, 0xff, 0xfe, 0xbe, 0xc7, 0xfb, 0xff, 0xfe, 0xbd, 0x03, 0x00, 
> 	0x00, 0xfc, 0x1f, 0x80, 0x8f, 0x73, 0xff, 0xef, 0xfe, 0xe7, 0xfb, 0x77, 0xef, 0xfd, 0x03, 0x00, 
> 	0x00, 0xfc, 0x1f, 0x80, 0xdf, 0x7b, 0x9c, 0xe7, 0xfe, 0xf7, 0xe3, 0x71, 0xe7, 0xfd, 0x03, 0x00, 
> 	0x00, 0xfc, 0x0f, 0xc0, 0xdf, 0x79, 0x9e, 0xe3, 0xfe, 0xf3, 0xe3, 0x78, 0xe7, 0xff, 0x03, 0x00, 
> 	0x00, 0xfc, 0x0f, 0xe0, 0xdf, 0x39, 0x8e, 0xf3, 0xff, 0xfb, 0xe7, 0xf8, 0xe7, 0xfe, 0x01, 0x00, 
> 	0x00, 0xfc, 0x0f, 0xe0, 0xdf, 0x3f, 0x8e, 0x7f, 0xff, 0xff, 0xe7, 0x38, 0x7f, 0xee, 0x01, 0x00, 
> 	0x00, 0xf8, 0x0f, 0x70, 0xdc, 0x1f, 0x0e, 0x3f, 0xff, 0x9d, 0xf7, 0x38, 0x3f, 0xef, 0x01, 0x00, 
> 	0x00, 0xf8, 0x0f, 0x00, 0x00, 0x03, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 
> 	0x00, 0xf0, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0x00, 0xe0, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0x00, 0x80, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
> 	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
> };
>

**Comment by olikraus** [comment]
Using gimp with export to xbm usually works for me.

**Comment by sanfordjd** [comment]
I tried that, actually.  
But if you look at the default heltec example in the site linked above, you can see how some groups of columns are inverted ...

**Comment by olikraus** [comment]
Maybe just paste/link the pic.

**Comment by sanfordjd** [comment]
http://javl.github.io/image2cpp/

**Comment by olikraus** [comment]
I think I can close this...
