### ISSUE TITLE
show nothing after Y:23x at SSD1322 256x64

### ISSUE THREAD

**Issue by ttsshadow** [olikraus/u8g2#1065]
I tested two ssd1322 256x64 oled
but always show nothing after Y:23x

test code
```
`for(int counter = 1; counter < 256; counter++) {
      u8g2.clearBuffer();
      u8g2.drawLine(counter, 0, counter, 63);

      u8g2.setCursor(108, 40);
      u8g2.print(counter); 
  
      u8g2.sendBuffer();
      delay(100);
  }`
```
when run to 23x~256 , i can see number only
line is gone

any idea? thx

**Comment by olikraus** [comment]
did you enable 16 bit mode?

https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#16-bit-mode
and
https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L163

**Comment by ttsshadow** [comment]
My bad !!
this issue solved !
