### ISSUE TITLE
Support Drive uc1628, see also issue 1453

### ISSUE THREAD

**Issue by witc** [olikraus/u8g2#1066]
Dear,

Will you plan add support for driver UC1628 please?

Thank you for information.

Best Regards Jan.

**Comment by olikraus** [comment]
Is there any datasheet?

**Comment by witc** [comment]
Hi,

Thank you for response. Datasheet is enclosed.



čt 5. 12. 2019 v 16:47 odesílatel olikraus <notifications@github.com>
napsal:

**Comment by witc** [comment]
Datashett is there: [UC1628c_A1.0.pdf](https://github.com/olikraus/u8g2/files/3928233/UC1628c_A1.0.pdf)

**Comment by olikraus** [comment]
Ah, ok... Is there also a display datasheet which includes the init sequence for your display

**Comment by witc** [comment]
There is Init settings:
![Initial Setting](https://user-images.githubusercontent.com/13749560/70304417-2c45e200-1802-11ea-8414-6602db50d0cc.png)

**Comment by olikraus** [comment]
Are you willing to do some testing here? I mean, I can implement the device, but I can not test it. Usually it requires some bugfixing. Also upload of some pictures of the display output would be required.

**Comment by witc** [comment]
OK, first I buy the display and then I write you here that I can test it :) Thank you very much!!

**Comment by olikraus** [comment]
hmm... what is special about this display? If you anyway have to buy it, did you look at displays with a ST75256 ot ST75320 controller, which are already supported? 
I mean, I will try to add support for this display, but there is always a risk compared to an existing implementaiton.

**Comment by olikraus** [comment]
any update?

**Comment by witc** [comment]
> Hi,


I am waiting for delivery of the display, if there will be problem I will
check  displays with ST75256 as you mentioned. Thank you very much.

**Comment by olikraus** [comment]
no problem, thanks for the feedback.

**Comment by olikraus** [comment]
just open a new issue, if there are some news here...

**Comment by olikraus** [comment]
example code: https://www.topwaydisplay.com/sites/default/files/2020-06/LM160160R.txt
datasheet: https://github.com/olikraus/u8g2/files/3928233/UC1628c_A1.0.pdf
discussion: https://github.com/olikraus/u8g2/discussions/1452

**Comment by olikraus** [comment]
Oh, there is a second issue: https://github.com/olikraus/u8g2/issues/1453

So you solved this already, right?

**Comment by olikraus** [comment]
continued here: https://github.com/olikraus/u8g2/issues/1453
