### ISSUE TITLE
Supported displays not the same as u8g? Add PCD8544 support.

### ISSUE THREAD

**Issue by retrojim** [olikraus/u8g2#107]
I've looked through the list of supported displays, the open and closed issues, and (I think) most of the documentation. Are all the same displays that u8g supported also supported in u8g2? Specifically, I can't find the PCD8544 controller (like the Nokia 5110 displays use). The supported display list looks significantly different between u8g and u8g2. Should I just stick with u8g for my 5110 display?

**Comment by olikraus** [comment]
Yes, the 5110 is still missing. I do the porting step by step and some display types are still missing.

**Comment by olikraus** [comment]
done & tested
