### ISSUE TITLE
u8g2.sendBuffer();  crashes ESP32 with Division by Zero

### ISSUE THREAD

**Issue by smiffycom** [olikraus/u8g2#1073]
I'm struggling with a snippet of code which runs fine in isolation, but when it's transferred to the main target code u8g2.sendBuffer(); crashes the ESP with a Division by Zero error - identical code...

**Comment by olikraus** [comment]
I have no idea how I could help here...

**Comment by smiffycom** [comment]
Sorry, but it was my cock-up. In pasting my code snippet into the main code I had put  u8g2.begin() inside a */ statement... whoops.

But thank you for the great code and replying so rapidly 🙂

Merry Christmas,

smiffy
________________________________
