### ISSUE TITLE
Off-screen drawing?

### ISSUE THREAD

**Issue by Sortland** [olikraus/u8g2#1078]
I'm basically looking for some drawing functions to create an image where no display is involved (the image is intended to be transferred via a webserver running on my board).

So my question: is u8g2 able to use a drawing buffer of a given size without any hardware involved, draw some tings on that buffer and then provide the resulting image data for further processing?

Thanks!

**Comment by olikraus** [comment]
There is a small demo of a virtual screen render function here: https://github.com/olikraus/u8g2/tree/master/sys/bitmap/hello_world

Limitations:
 * Will use malloc() https://github.com/olikraus/u8g2/blob/master/sys/bitmap/common/u8x8_d_bitmap.c#L46
 * Only C interface available
