### ISSUE TITLE
Unicode composite characters / font compression

### ISSUE THREAD

**Issue by JeffCalwood** [olikraus/u8g2#1080]
Here's another request: It would be great to support unicode composite characters, that is, the ability to add accents and other diacitical marks at runtime. For one, it would again improve the ability to support UTF8 encoded strings.
Also, though, I thought this may improve font compression. For come glyphs, the unicode chart includes both a "precomposed version" (example ü) as well as the combined glyphs (u + the double dot diacritical mark). If the lib supported the composite characters, then the font tool could be modified such that it doesn't actually store the precomposed versions anymore, but instead a 'note to self' how to compose the glyph. (this is because we don't know how the UTF-8 encoded string comes in: it could still be using the precomposed version (which it typically does)).
I thought this may actually reduce font size.

Finally, here's a bit of a crazy idea to push this further. Just an idea, and crazy, but it sort of fits here. Once the above would be in place, would it further decrease font size in ROM if one would iteratively/experimentally/randomly attempt to find similarities between other characters ? If you subtract the pixels of an 'o' from the pixels of a 'p', would simply a vertical line remain ? Think about O&Q, P&R, F&E. Would it be shorter to encode the differences in some instances ? Not being able to read Chinese, but to the layman it appears their characters are composed from recurring strokes, no ? Anyhow, if you already had the ability to compose glyphs, maybe there would be a benefit ?

Anyhow, don't let this crazy idea distract from the above: It would be nice to support composite characters, and there maybe a possible font size reduction with little additional effort.

**Comment by olikraus** [comment]
I like your ideas, but u8g2 does not include a full feature freetype-like render engine.

There is no composite glyph support. Mainly because .bdf font format also does not support this and u8g2 font format is very close to .bdf

There are some ideas to build something on top of u8g2 which supports composite glyphs, but it is more a workaround/hack kind of think: Search for drawExtUTF8 /drawExtendedUTF8 here in the closed issue list.
