### ISSUE TITLE
Screen limits ignored in text rendering / no word wrap

### ISSUE THREAD

**Issue by JeffCalwood** [olikraus/u8g2#1081]
At least in the 'u8g2 with Adafruit GFX' repo, the text rendering doesn't seem to clip at the screen boundaries. Is the display driver supposed to perform clipping inside the drawpixel() method ?
No big issues, but related: the text rendering then would draw incomplete (clipped) glyphs and obviously would also not support text wrapping. Which would be nice to have !

**Comment by olikraus** [comment]
> the text rendering doesn't seem to clip at the screen boundaries.

Difficult to say. I think this will depend on the Adafruit libs.
For u8g2 the clipping should be done, although there is a wrapping at the byte or word boundaries (depending on the 16bit #define for u8g2).

> support text wrapping.

Yes, text wrapping is not supported. I think it should be implemented on top of u8g2.
