### ISSUE TITLE
serial port problem

### ISSUE THREAD

**Issue by planer-pro** [olikraus/u8g2#1096]
Hi i use your lib in arduino. Lib is really great! Use userinterface function. In this mode arduino serial port is not working, it will be great suprise for me)) Is it possibility work userinterface function with serial port arduino together?

**Comment by olikraus** [comment]
Which board do you use? Which pins for you use for buttons?

**Comment by planer-pro** [comment]
I use mega2560 r3
As i inspected serial port didn't work because every `inputPass_selection = u8g2.userInterfaceMessage("SYSTEM BLOCKED", "Enter password", "", " ok ");` or `inputPass_selection = u8g2.userInterfaceSelectionList("INPUT PASS", inputPass_selection, number_list);` halting main loop function

**Comment by olikraus** [comment]
> It's a pity, what i must refuse nice library.

It is not the goal of this lib to provide a user interface. Functions like the userInterfaceMessage are only there to demonstrate the graphics capabilities.

Instead you probably may want to use https://github.com/neu-rah/ArduinoMenu which is a menu system based on an existing low level graphics/character output system (such as u8g2).

**Comment by planer-pro** [comment]
Ok, Thanks!
