### ISSUE TITLE
u8g2.print(string); won't work.

### ISSUE THREAD

**Issue by FrostMannen** [olikraus/u8g2#110]
I have tried this code snipp from another issue from aug. Just to try the print statement.

`u8g2.firstPage();`
`do {`
  `//u8g2.setFont(u8g2_font_ncenB14_tr);`
    `    u8g2.setFont(u8g2_font_7x14B_tf);`
    `    u8g2.drawPixel(x,20);`
    `    u8g2.setCursor(10,10);`
    `    u8g2.print(x);`
  `  } while ( u8g2.nextPage() );`
  `  delay(500);`
  `  if(x++>128) x=0;`

The  only thing that is happening to the screen is that it will become blank! But if I comment out the u8g2.print(x); it works again!

version=2.7.5

Using an NONAME 128*64 I2C OLED and an Arduino Uno.

**Comment by FrostMannen** [comment]
My fault, I had old buggy version. Updated to 2.8.5 and NOW it works like a charm :+1:

**Comment by olikraus** [comment]
Great.
