### ISSUE TITLE
Fony is incompatible with cyrillic fonts

### ISSUE THREAD

**Issue by Vadimledyaev** [olikraus/u8g2#1101]
Hi, the current versions of Fony available on their site cannot import cyrillic glyphs into font, tried all the combinations but the program includes other glyphs rather than cyrillic (even with codepage set to windows-1251 which is a cyrillic one)
The problem mentioned on the Fony forums but seems wouldn't be fixed ever. 
The previous version, 1.3.5, works like a charm. I'd recommend you to include it into the repo before it sinks into oblivion.

https://download.cnet.com/Fony/3000-2319_4-10791260.html

**Comment by olikraus** [comment]
Fony 1.3.5 attached.
[Fony_1.3.5.zip](https://github.com/olikraus/u8g2/files/4777129/Fony_1.3.5.zip)
