### ISSUE TITLE
U8g2lib.h: No such file or directory

### ISSUE THREAD

**Issue by dunk8888** [olikraus/u8g2#1106]
Hi ive installed the library but its not right ime sure its the layout inside the folder not sure,any ideas cheers

**Comment by olikraus** [comment]
Which board? Which IDE?

**Comment by dunk8888** [comment]
Board uno ide 1.8.10

**Comment by olikraus** [comment]
Did you follow the install instructions from here: https://github.com/olikraus/u8g2/wiki/u8g2install

**Comment by dunk8888** [comment]
Hi thanks ive sorted it now thanks for your time
