### ISSUE TITLE
Can confirm working with SSD1315

### ISSUE THREAD

**Issue by GarlicToum** [olikraus/u8g2#1107]
Hey olikraus!

I poked around a bit and couldn't find any information (other than a few references in Github issues), but this library does in fact work with the SSD1315 by just using the SSD1306 constructor.

I confirmed it with a Seeed Studio SSD1315 display, and they even reference this library it in their examples: https://github.com/Seeed-Studio/Seeed_Learning_Space/tree/master/Grove%20-%20OLED%20Display%200.96''(SSD1315)V1.0

I figured I'd let you know, or for anyone else trying to use the module.
Thanks for the great work olikraus!

**Comment by olikraus** [comment]
Thanks for letting us know!
