### ISSUE TITLE
SSD1327 i2c

### ISSUE THREAD

**Issue by Mael19** [olikraus/u8g2#1108]
Hello, I have struggle setting up my ssd1327. I successfully managed to use other screens but this one doesn’t seem to work.

I’m starting to think that it’s broken, but when I run an i2c scanner it is recognised...

How can I know whether it’s broken or not supported by this library ?

My model : https://a.aliexpress.com/_Tzjet

**Comment by olikraus** [comment]
I assume there is some wiring problem. Which constructor did you use? Any picture of the setup?

**Comment by Mael19** [comment]
Well I tied with all the constructor that seemed to fit my screen, so the followings :
//U8G2_SSD1327_EA_W128128_1_SW_I2C u8g2(U8G2_R0, 22,21, U8X8_PIN_NONE);
//U8G2_SSD1327_EA_W128128_1_HW_I2C u8g2(U8G2_R0,U8X8_PIN_NONE);
//U8G2_SSD1327_MIDAS_128X128_1_HW_I2C u8g2(U8G2_R0, U8X8_PIN_NONE);

Where 22 and 21 are my hardware i2c pins, it is wired properly and I can make other devices work fine.

Here is also a picture of the setup, as you can see there's nothing very complicated.
![IMG_5068](https://user-images.githubusercontent.com/41644138/74567213-8b983f00-4f75-11ea-8e19-d8593a4fd669.jpg)

**Comment by olikraus** [comment]
Hmmm These Profiboards are not very reliable. Maybe shift everything by one row.

**Comment by Mael19** [comment]
I already tired, and I rewired the setup like 10 times. Somebody on another forum suggested using pull-up resistors, which I tried but nothing seems to change.

**Comment by olikraus** [comment]
Difficult to say what is wrong here. If this would be in my lab, I would start to analyse the I2C traffic on the bus.

**Comment by Mael19** [comment]
Well I don't have anything to analyse the i2c traffic... I notices that when using the following config some lines just blink a few ms when resetting the board. I don't know if that means anything ?

**Comment by olikraus** [comment]
Board reset? Then something else might be wrong.

**Comment by Mael19** [comment]
Yes, either after a board reset (the ESP32) or when the script is done transferring / the board is powered on. Also I can hear a weak buzzing from the screen board

**Comment by olikraus** [comment]
Sounds like a broken display electronics.

**Comment by Mael19** [comment]
Well let's assume it's broken, and I don't have the time or the knowledge to try to prepare it. Thanks for your time !
