### ISSUE TITLE
Questions about sharp Memory LCD LS013B7DH05_144X168.

### ISSUE THREAD

**Issue by iggymayer** [olikraus/u8g2#1112]
Hello, I use ESP32 to connect to this screen. The SW_SPI screen can be displayed normally, but HW_SPI cannot be displayed. How can I solve it?

**Comment by olikraus** [comment]
Hmm... there is a similar issue here:  #1071
Will the solution provided in  #1071 (change mode to 3) also work for you?

**Comment by iggymayer** [comment]
problem solved. Modify it to MODE 1 to display normally, thank you very much!
