### ISSUE TITLE
Strange dots displaying with OLED 128x32

### ISSUE THREAD

**Issue by khoadvfirmware** [olikraus/u8g2#1118]
Hello Olikraus,
Firstly, Thank you very much for a great open source lib!.

I tried to use it with my OLED 128x32 (SSD1305) displaying. 
The displaying in range of 128x32 matrix seems good, but **the problem is some strange pixel at outside of 128x32 matrix is turned ON (as below image).** 
<img width="362" alt="Screen Shot 2020-02-27 at 11 12 41" src="https://user-images.githubusercontent.com/57383867/75411736-d725f200-5952-11ea-9856-cbdce928edcb.png">

Do you have any experiences related to this problem.?
Could you help to give me your opinions?

Thank you very much!
Best regards,

**Comment by olikraus** [comment]
Strange. Can you test a sh1106 128x64 driver. Will the pixel still appear?

**Comment by khoadvfirmware** [comment]
Hi olikraus,

After re-check again for some specification. It seems that some data pin of SSD1305 are not be connected right. I'm confirming it again.
So i will temporary close this topic first!.
If the problem are still occur, i will update further information to you.

Thank you for your reply.!
Best regards,

**Comment by mikepparks** [comment]
I'm seeing this on a 128x32 module as well using "NONAME" HW & SW drivers. Tested using the SH1106 driver as suggested, but the image is now upside-down. Artifacts are still displayed on the physical right side regardless of driver.

![IMG_20200325_095526](https://user-images.githubusercontent.com/1214033/77564143-7ae5bd80-6e7f-11ea-9cf3-9d91faac9f25.jpg)
![IMG_20200325_095623](https://user-images.githubusercontent.com/1214033/77564192-8c2eca00-6e7f-11ea-9424-0d61757ddfa1.jpg)

**Comment by olikraus** [comment]
created a new issue for this
