### ISSUE TITLE
Full Buffer Mode - how to use code inside functions

### ISSUE THREAD

**Issue by bira77** [olikraus/u8g2#1123]
Hi guys,
I have written my code using Full Page Mode and as I use a 128x64 display with I2C Capacitive Touch Controller, the finger touch detection presented a delay. It is due to some board characteristics, like 8MHz clock, some code parts and also the Page Mode time processing.  
My questions are about using Full Buffer Mode.
1) How to use u8g2.clearBuffer, u8g2.sendBuffer (Full Buffer Mode), and all the code between them, inside functions ? When I remove the code from Arduino main loop and put inside a function, the display shows nothing.
2) Is there any instructions about how to mix the Full Buffer Mode code with the rest of the user's code ?
P.S.: I am using the examples of the wiki. Link below.
Thank you very much !

https://github.com/olikraus/u8g2/wiki/setup_tutorial#u8g2-full-buffer--page-buffer-and-u8x8-mode

**Comment by olikraus** [comment]
> When I remove the code from Arduino main loop and put inside a function, the display shows nothing.

It should work, if not, please provide the code (between ```  tags https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)

> Is there any instructions about how to mix the Full Buffer Mode code with the rest of the user's code ?

There is nothing special to consider from my perspective. I mean, u8g2 in full buffer mode almost behaves like any other graphics lib. I probably need more information here.
