### ISSUE TITLE
Some problems occurred when using JLX256160

### ISSUE THREAD

**Issue by vowovrz** [olikraus/u8g2#1126]
Thanks for sharing this library.

![QQ图片20200310223848](https://user-images.githubusercontent.com/8279990/76324303-c7c68180-6320-11ea-9c4d-7788309c48ba.jpg)

**Comment by olikraus** [comment]
Welcome.
What is the problem?

**Comment by vowovrz** [comment]
Background is black.

**Comment by olikraus** [comment]
Maybe change the contrast.

**Comment by vowovrz** [comment]
When choosing anti-comment
U8X8_ST75256_JLX240160_4W_HW_SPI u8x8(/* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);

It looks like this.  Font display is dim.
![QQ图片20200311135319](https://user-images.githubusercontent.com/8279990/76387282-888c4500-63a1-11ea-983f-54634923b034.jpg)

**Comment by vowovrz** [comment]
Thanks , it's works，testContrast (145);

**Comment by vowovrz** [comment]
thanks for the reply!
When the method getWidth () is executed, the returned width is 240, which should actually be 256, and the height is correct.

**Comment by olikraus** [comment]
> When the method getWidth () is executed, the returned width is 240, which should actually be 256, and the height is correct.

You need to enable 16 bit support (see the FAQ).
