### ISSUE TITLE
U8g2 Menu System on STM32

### ISSUE THREAD

**Issue by IWRY1231** [olikraus/u8g2#1135]
Hi,
I just successfully use this library on STM32,and i found some menu functions,but there is too little detail about that.How can i use these functions on STM32 ?

**Comment by olikraus** [comment]
U8g2 is a graphics lib, not a menu system. I added those menu function just to demonstrate how it could be  implemented.

There are some example files for Arduino:
https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/SelectionList/SelectionList.ino

But I personally suggest to use a more complete menu system like https://github.com/neu-rah/ArduinoMenu which supports u8g2.
