### ISSUE TITLE
I'm seeing this on a 128x32 module as well using "NONAME" HW & SW drivers. Tested using the SH1106 driver as suggested, but the image is now upside-down. Artifacts are still displayed on the physical right side regardless of driver.

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#1136]
I'm seeing this on a 128x32 module as well using "NONAME" HW & SW drivers. Tested using the SH1106 driver as suggested, but the image is now upside-down. Artifacts are still displayed on the physical right side regardless of driver.

![IMG_20200325_095526](https://user-images.githubusercontent.com/1214033/77564143-7ae5bd80-6e7f-11ea-9cf3-9d91faac9f25.jpg)
![IMG_20200325_095623](https://user-images.githubusercontent.com/1214033/77564192-8c2eca00-6e7f-11ea-9424-0d61757ddfa1.jpg)

_Originally posted by @mikepparks in https://github.com/olikraus/u8g2/issues/1118#issuecomment-603962671_

**Comment by olikraus** [comment]
Can you provide the datasheet for this display?

**Comment by mikepparks** [comment]
https://www.waveshare.com/wiki/1.3inch_OLED_HAT

**Comment by olikraus** [comment]
So you are say neither SSD1305 128X32_NONAME (https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#ssd1305-128x32_noname) nor SSD1305 128X32_ADAFRUIT (https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#ssd1305-128x32_adafruit) will work?

**Comment by mikepparks** [comment]
It appears that this display will work as expected via the ADAFRUIT driver. The pixels on the edge are not visible, and the alignment appears to be correct. Using the NONAME driver, the width of the pixels displaying on the edge appear to be directly related to the number of pixels that the coordinates are being shifted to the left in normal orientation.

**Comment by olikraus** [comment]
ok, then this sounds the problem is solved, right?

**Comment by mikepparks** [comment]
If I use the other driver, yes. Thanks.
