### ISSUE TITLE
First line empty / last line white dots 

### ISSUE THREAD

**Issue by lltodoll** [olikraus/u8g2#1137]
Hello,

I have a question:

My display shows on the left side (first column) nothing and on the right side (last column) white dots. What I am doing wrong? Or is it a bug? 

Here my Code:
```
#include <Arduino.h>
#include <U8x8lib.h>

#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif

U8X8_SSD1306_128X64_NONAME_HW_I2C u8x8(U8X8_PIN_NONE); 

void setup(void)
{
  u8x8.begin();
}


void loop(void)
{
  u8x8.setFont(u8x8_font_amstrad_cpc_extended_r);
  u8x8.drawString(0, 0, "ABCDEFGHIJKLMNOP");
  u8x8.drawString(0, 1, "BCDEFGHIJKLMNOPQ");
  u8x8.drawString(0, 2, "CDEFGHIJKLMNOPQR");
  delay(100000);
  u8x8.clearDisplay();
}
```

...and this is the result:
![IMG_20200329_105219](https://user-images.githubusercontent.com/12458872/77845190-11322000-71ad-11ea-9b9d-8db9013f57f9.jpg)

Thanks for reply ...

**Comment by olikraus** [comment]
It could be a SH1106 display controller instead of the SSD1306.

**Comment by lltodoll** [comment]
Yes that was it. Thanks a lot :)

**Comment by v1993** [comment]
@lltodoll By the way

```
#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif
```

most likely can be omitted.

**Comment by olikraus** [comment]
Yes... I think it was once required in an older version of the Arduino IDE.

**Comment by lltodoll** [comment]
ah ok thx
