### ISSUE TITLE
Round displays

### ISSUE THREAD

**Issue by stephenrjohnson** [olikraus/u8g2#1139]
Sorry to ask this question here, but I'm looking for a round display to fit in a 52mm car gauge, I've looked at the readme but I can't see to find anything that's supported. If someone could point me at something that's supported that would be amazing.

**Comment by olikraus** [comment]
52 mm is a bug number. There are round monochrome OLEDs from EA with 37 mm: https://www.lcd-module.com/fileadmin/eng/pdf/grafik/W128128-XR.pdf

**Comment by stephenrjohnson** [comment]
Thanks I did find these but unsure on their support and the ribbon cable looks fiddly to connect to things.
