### ISSUE TITLE
Q: will u8g2 work with I2C SH1106 display controlled by atmega8 via non standard I2C pins  (SCL/SDA)?

### ISSUE THREAD

**Issue by Rolandas3** [olikraus/u8g2#1148]
Hi,

i am building my project of amplifier which is controlled by atmega8. The plan is to use some graphics (VU meter, display volume/tone levels, etc) and SH1106 1.3inch  OLED display.  I cannot reuse standard I2C pins though. Can your library be used for such a task?

Kind regards, Rolandas

**Comment by olikraus** [comment]
U8g2 emulates I2C for none-HW-I2C pins on any Arduino Environment, so the answer is "yes".
