### ISSUE TITLE
How can get the pixel value

### ISSUE THREAD

**Issue by AlirezaAbdiyan** [olikraus/u8g2#1158]
Hi,
How can get the pixel value?

Thanks

**Comment by olikraus** [comment]
Unfortunately there is not getPixel value function. In fact there is not always a full memory buffer available, so such a function can not be implemented.
If you really want a pixel value, you can use the direct buffer API: https://github.com/olikraus/u8g2/wiki/u8g2reference#direct-access-buffer-api

**Comment by AlirezaAbdiyan** [comment]
ok
Thanks for your replay.
