### ISSUE TITLE
how to change little codes for ssd1322_256_64 to supporting font grayscale

### ISSUE THREAD

**Issue by DennisLeng** [olikraus/u8g2#1161]
![image](https://user-images.githubusercontent.com/63696747/79300252-c805fe00-7f18-11ea-8be7-aa2977845253.png)

Perhaps change little codes in u8x8_d_ssd1322.c，set font grayscale at one page，for 4spi stm32 ，This has troubled me for a long time，please help me？

**Comment by olikraus** [comment]
What exactly is the problem?

**Comment by olikraus** [comment]
Any feedback?
