### ISSUE TITLE
u8g2 wiki fonts page

### ISSUE THREAD

**Issue by dingo27mobile** [olikraus/u8g2#1168]
Hello,

this is not primarily issue with library but with Github - I use u8g2 wiki often to search for fonts, and recently there are so many fonts that Github puts a "You have triggered an abuse detection mechanism." This is for page https://github.com/olikraus/u8g2/wiki/fntlistall. Also, images for bigger fonts do not load correctly.
Fonts do not have preview from line fntpic/u8g2_font_t0_12b_tf_short.png u8g2_font_t0_12b_tf UW ttyp0, i am not sure if it is only me or other people as well. I am sure before it worked ok.

After the mechanism enables, there is no way to look for any page on github.

I know this is a lot of work but would be helpful to split page in more articles. Thanks in advance.

BTW you lib is awesome.

**Comment by olikraus** [comment]
For me it works (again?)

Maybe it is related to this: 
![https://heise.cloudimg.io/width/1920/q85.png-lossy-85.webp-lossy-85.foil1/_www-heise-de_/imgs/18/2/8/8/4/5/0/6/Cloud_is_no_magic_2020-04-24_090759-b585a73cab58878f.png](https://heise.cloudimg.io/width/1920/q85.png-lossy-85.webp-lossy-85.foil1/_www-heise-de_/imgs/18/2/8/8/4/5/0/6/Cloud_is_no_magic_2020-04-24_090759-b585a73cab58878f.png)

**Comment by dingo27mobile** [comment]
Actually this is happening for me for few weeks... 

![aa](https://user-images.githubusercontent.com/64262983/80259928-fc9b5780-8686-11ea-8e51-d6dffd911b6b.png)

But if it works on your side there must be mistake on my side.

**Comment by olikraus** [comment]
Hmmm....
