### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by aktoey** [olikraus/u8g2#1173]
Can this library be ported to the ARM platform

**Comment by olikraus** [comment]
Done already.

**Comment by JamesGKent** [comment]
@aktoey saying can it be ported to arm is a big vague, but I have this library running on and ARM7 device, a cortex M3, a cortex M4.

but for the platform you are working on **you** need to tell it how to push data to the display. this is well documented and even some examples/contributed code:
[Porting to new platform](https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform)
