### ISSUE TITLE
doesnt support chip select on ERM19264-3 display

### ISSUE THREAD

**Issue by abusakib** [olikraus/u8g2#1174]
here i added the data sheet
https://www.buydisplay.com/download/manual/ERM19264-3_Series_Datasheet.pdf

**Comment by olikraus** [comment]
It might still work if you do not connect cs0.

**Comment by abusakib** [comment]
i connect cso and cs1

**Comment by abusakib** [comment]
still facing the same problem

**Comment by abusakib** [comment]
![FL-28-04-2020-02-00-43](https://user-images.githubusercontent.com/21017059/80521355-b6a70200-89ac-11ea-9438-b925c699a70a.jpg)
see the status

**Comment by olikraus** [comment]
You may try different combinations.
How does your constructor look like?

**Comment by m3mory** [comment]
for the ERM19264-3 Displays the CS Lines need to be changed, as there are only two CS lines available.
This worked for me:
if ( v.x < 8 )
      {
	u8x8->cad_cb(u8x8, U8X8_MSG_CAD_START_TRANSFER, 4, NULL);  //6 -->4
	u8x8_ks0108_out(u8x8, &v, arg_ptr);
	u8x8->cad_cb(u8x8, U8X8_MSG_CAD_END_TRANSFER, 7, NULL);
      }
      if ( v.x < 16 )
      {
	u8x8->cad_cb(u8x8, U8X8_MSG_CAD_START_TRANSFER, 6, NULL); //5 --> 6
	u8x8_ks0108_out(u8x8, &v, arg_ptr);
	u8x8->cad_cb(u8x8, U8X8_MSG_CAD_END_TRANSFER, 7, NULL);
      }
      if ( v.x < 24 )
      {
	u8x8->cad_cb(u8x8, U8X8_MSG_CAD_START_TRANSFER, 5, NULL); //  3 -->5
	u8x8_ks0108_out(u8x8, &v, arg_ptr);
	u8x8->cad_cb(u8x8, U8X8_MSG_CAD_END_TRANSFER, 7, NULL);
      }

**Comment by olikraus** [comment]
Thanks for the update :-)
