### ISSUE TITLE
ld7032 60x32 constructors

### ISSUE THREAD

**Issue by bturner1273** [olikraus/u8g2#1177]
Okay so your hardware spi for ld7032 definitely works, I just got it going but I was having trouble with every other constructor for the ld7032. Also I was wondering what 2ND means in a constructor. 

This is the working Pin Mapping/Code:
```cpp
#include <Arduino.h>
#include <U8g2lib.h>
#include <U8x8lib.h> 

#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif

//Pin Mapping
//Arduino Micro       ->      LCD
//-------------------------------
//SCK                 ->      Clock
//MOSI                ->      Data In
//SS                  ->      Chip Select
//D2                  ->      A0 (Register Select)
//D3                  ->      Reset
//GND                 ->      GND,GND
//3.3V                ->      3.3V
U8G2_LD7032_60X32_F_4W_HW_SPI u8g2(U8G2_R0, SS, 2, 3);
//U8G2_LD7032_60X32_F_2ND_4W_HW_SPI u8g2(U8G2_R0, SS, 2, 3); does not work with this mapping
 void setup(void) {
   u8g2.begin();
 }

 void loop(void) {
   u8g2.clearBuffer();
   u8g2.setFont(u8g2_font_logisoso16_tf);	
   u8g2.drawStr(5,16,"Hello");	
   u8g2.sendBuffer();					
   delay(10000);
 }
```

I am using an arduino micro with the seed studio ocell .5 inch oled. And followed some of this tutorial (till it specified pins that implied using the software spi constructor that didn't work for me)
[https://www.seeedstudio.com/document/pdf/OCELL_use_guide2.pdf](url)

I didn't take much time to look into the code but I did see there was that issue (#865) you had previously with Majestix1970 and I couldn't get the sw spi or hardware or software i2c working. Could it be related?

**Comment by bturner1273** [comment]
nevermind I am stupid

**Comment by olikraus** [comment]
2nd refers to a second hardware which is there on some boards.
