### ISSUE TITLE
Question: Non Arduino Dependant Library

### ISSUE THREAD

**Issue by 32teeth** [olikraus/u8g2#1179]
Is there available a version that has no dependencies on Arduino?

What significance do  the below libraries play?
```
#include <Arduino.h>
#include <Print.h>
```

Please feel free to take this conversation outside of git issue

### Get In Touch

| [<img src="https://raw.githubusercontent.com/wiki/32teeth/GabozePocaio-Round1/images/icons/github.png" width="40px">](https://github.com/32teeth)[<img src="https://raw.githubusercontent.com/wiki/32teeth/GabozePocaio-Round1/images/icons/instagram.png" width="40px">](https://www.instagram.com/thirtytwoteeth/)[<img src="https://raw.githubusercontent.com/wiki/32teeth/GabozePocaio-Round1/images/icons/messenger.png" width="40px">](https://www.facebook.com/messages/t/32teeth)[<img src="https://raw.githubusercontent.com/wiki/32teeth/GabozePocaio-Round1/images/icons/twitter.png" width="40px">](https://twitter.com/eugeneyevhen)[<img src="https://raw.githubusercontent.com/wiki/32teeth/GabozePocaio-Round1/images/icons/youtube.png" width="40px">](https://www.youtube.com/user/32teeth/)[<img src="https://raw.githubusercontent.com/wiki/32teeth/GabozePocaio-Round1/images/icons/linkedin.png" width="40px">](https://ca.linkedin.com/in/32teeth) |
| ------------------------------------------------------------ |
| Find me on the internet and lets chat                        |

**Comment by olikraus** [comment]
The core part of U8g2/u8x8 is written in C and does not depend on Arduino.
The source is here: 
https://github.com/olikraus/u8g2/tree/master/csrc

There are also several examples on how to use this lib on none-Arduino environments:
https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform
