### ISSUE TITLE
ADC buttons values list in menu or simulate LOW

### ISSUE THREAD

**Issue by vslinuxdotnet** [olikraus/u8g2#1181]
Hello, I have limited GPIO available so is possible to use ADC interval to simulate the keys ?
I try to do this to simulate a key press:
```
digitalWrite(6, LOW);
delay( 100 );
digitalWrite(6, HIGH);
```
Don't work.
I try the simulate the event menu, the selection works... but them freezes in u8g2.userInterfaceMessage.
I try to send the event as U8X8_MSG_GPIO_MENU_HOME
 and comment the:
`u8g2.getMenuEvent()`
but also don't work.
Any idea ?

Thank you

**Comment by olikraus** [comment]
Well... as mentioned... maybe better use a full featured menu system like Arduino Menu (see my other answer)
