### ISSUE TITLE
About sharp memory lcd LS027B7DH01A

### ISSUE THREAD

**Issue by iggymayer** [olikraus/u8g2#1182]
Hello
How to switch this screen to white background and black text?

Datasheet
https://mega.nz/file/RBE3nKTT#P17BGD8qlaG2vuQt2MqGKnK7QoHCrR8N0nRl3u2fdnE

**Comment by olikraus** [comment]
This is not possible, but you could draw a black box with drawBox and use white text.

**Comment by iggymayer** [comment]
Thank you！
