### ISSUE TITLE
invalid start of buffer (garbage pixel on LCD) ST7565

### ISSUE THREAD

**Issue by selevo** [olikraus/u8g2#1187]
LCD:  fpc-12864b-v11 (on transistor tester LCR-T4  LCR-T3)
It is not erased.
I think the beginning of the start adrtess LCD RAM is set incorrectly and therefore the cleaning function does not affect this part of the screen.
And u8x8.drawString(0,0,"Hello World!"); not  in zero position.
In which file can I fix this?
(I'm not an experienced programmer)
![ScreenShot001980](https://user-images.githubusercontent.com/13694921/81501169-dfea5b00-92e7-11ea-96c2-1e9c5da22b37.jpg)

```

/*

  HelloWorld.ino
  
  "Hello World" version for U8x8 API

  Universal 8bit Graphics Library (https://github.com/olikraus/u8g2/)

  Copyright (c) 2016, olikraus@gmail.com
  All rights reserved.

  

*/

#include <Arduino.h>
#include <U8x8lib.h>

#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif

  U8X8_ST7565_ZOLEN_128X64_4W_SW_SPI u8x8(/* clock=*/ 2, /* data=*/ 1, /* cs=*/ U8X8_PIN_NONE, /* dc=*/ 3, /* reset=*/ 4);
// End of constructor list



void setup(void)
{
    pinMode(6, OUTPUT);
  digitalWrite(6, HIGH);
   
  u8x8.begin();
  u8x8.setFlipMode(1);
  u8x8.setPowerSave(0);
  u8x8.setContrast(40);
  
  
}

void loop(void)
{
 
  u8x8.setFont(u8x8_font_chroma48medium8_r);
 u8x8.drawString(0,0,"Hello World!");
  delay(1000);
  u8x8.drawString(0,0,"TEST2");
  delay(1000);
}

```

**Comment by olikraus** [comment]
Maybe another ST7565 constructor works better. They do indeed differ in the left position. Please test some of the other constructors. Adjust the contrast if required.

**Comment by selevo** [comment]
I checked others, but there the image of the letters is mirrored.
But there is no chaos of pixels.
![ScreenShot001981](https://user-images.githubusercontent.com/13694921/81506023-b2f87100-9304-11ea-970a-4211a70dfbea.jpg)

U8X8_ST7565_LX12864_4W_SW_SPI

**Comment by olikraus** [comment]
There are many more to try. Please test the following devices also:

https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#st7565-64128n
and
https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#st7565-nhd_c12864

**Comment by selevo** [comment]
But  this graphical...

**Comment by olikraus** [comment]
Yes sure, u8x8 will also exist

**Comment by selevo** [comment]
I looked, there is nothing suitable.

**Comment by olikraus** [comment]
I would expect that the constructor 
U8X8_ST7565_NHD_C12864_4W_SW_SPI
will work. How will it look like? Can you send a picture?
You may need to adjust the contrast by setContrast.

**Comment by selevo** [comment]
clear screen  with any setContrast

**Comment by olikraus** [comment]
Well, ok, then use "U8X8_ST7565_ZOLEN_128X64_4W_SW_SPI"
Locate u8x8_d_st7565.c on your local disk. change the following value from 4 to 0:
https://github.com/olikraus/u8g2/blob/9ecb87c4b62e91302006d278fc3498263a6c567d/csrc/u8x8_d_st7565.c#L110

Will this help?
