### ISSUE TITLE
Grove 128x64 SSD1308Z

### ISSUE THREAD

**Issue by ForbiddenEra** [olikraus/u8g2#1191]
https://wiki.seeedstudio.com/Grove-OLED_Display_0.96inch/

Not listed, but test is working for me with this constructor:
U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);

Seems rotated from what the Seeed library outputs, I'm sure that's easy enough to fix, just thought I'd let you know since I didn't initially see the 1308 listed. 

Funny this one says 
//U8G2_SSD1306_128X64_ALT0_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);   // same as the NONAME variant, but may solve the "every 2nd line skipped" problem

but actually causes that problem with this one..!

Happy though, display would've been pretty useless with the Seed library in my application, font too small!

Thanks for the lib.

Edit: no actual issue here.

**Comment by olikraus** [comment]
Thanks for the informant!
:-)
