### ISSUE TITLE
interruption in the serial port caused by the page update on the display lcd

### ISSUE THREAD

**Issue by gregoriomagno** [olikraus/u8g2#1193]
every time this piece of code is executed it generates a communication failure would be:

u8g2.firstPage ();
   do {
     drawMenu ();
   } while (u8g2.nextPage ());

I would like to know how to solve this problem

**Comment by olikraus** [comment]
Too less information to say something, but I remember that something similar was reported for ESP systems. Maybe search here in the issues.
