### ISSUE TITLE
Serial.print causes problem with u8x8 and ST7565

### ISSUE THREAD

**Issue by michalmalekci** [olikraus/u8g2#1195]
Hi
Every time when I try to write something on the debug console using Serial.println(), a display (ST7565) stops working - nothing is displayed but a program works. I use ESP32.
Is there anyone who can help me with this problem?

**Comment by olikraus** [comment]
Not sure how I can help here.. did you solve the problem?

**Comment by olikraus** [comment]
hmm... I have no idea...
