### ISSUE TITLE
u8g2 examples

### ISSUE THREAD

**Issue by jbltimberrock** [olikraus/u8g2#1207]
I just installed the u8g2 library and was trying to load and run Examples. None of the examples will compile without this error: 'u8g2' was not declared in this scope. Not even Hello World.  I'm using a UNO R3. Shouldn't examples run as-is without any other effort? Any suggestions?

**Comment by jbltimberrock** [comment]
Further, there appears to be at least two sketches in the Examples therein that DO NOT conform to Arduino naming protocol as messages appear when starting Arduino about sketches beginning with numbers. I believe Library Mgr said Version 2.27.2

**Comment by jbltimberrock** [comment]
Better off to use Adafruit_SSD1306 and Adafruit_GFX. They are foolproof.

**Comment by olikraus** [comment]
> I just installed the u8g2 library and was trying to load and run Examples. None of the examples will compile without this error: 'u8g2' was not declared in this scope. 

You need to uncomment the display as adviced in the comments of the examples.

**Comment by jbltimberrock** [comment]
that's OK, I'll use Adafruit libraries and have no issues...I've already
deleted u8g2
