### ISSUE TITLE
Issue in RA8835 320x240 initialization

### ISSUE THREAD

**Issue by dyezepchik** [olikraus/u8g2#1212]
Found this library so cool! Thanks! Got my winstar 320x240 screen working in minutes with a generic stm32f103rb board and arduino IDE.
But then noticed that I can draw only in a 240x240 rectangle. After 240 pixels by X axis all the graphics overflows to the beginning of the screen i.e. 0px by X. I'm using U8G2_RA8835_320X240_1_6800 constructor. 
 @olikraus , could you please point me what to look at?

**Comment by dyezepchik** [comment]
sorry, it was 16 bit mode

**Comment by olikraus** [comment]
:-)

Hmmm... maybe I should activate 16 bit once u8g2 compiles for __ARM__

**Comment by dyezepchik** [comment]
Well, actually it depends not on ARM, but on what we need to address in the screen. If the screen by at least one axis is more than 256, probably it's needed? I don't remember how exactly my screen memory is addressed, was connecting it long time ago...

**Comment by olikraus** [comment]
true, but I can not change the code at runtime from 8 to 16 bit. I could just enable 16 for all displays on those platforms which used to have more flash and RAM.

Let's see. I am happy that your problem was solved.
