### ISSUE TITLE
Missing method to set OLED brightness with U8x8Log

### ISSUE THREAD

**Issue by XFer012** [olikraus/u8g2#1215]
Hello,
I'm using U8x8Log with an SSD1306 OLED, very nice, thanks for this excellent library!
I would like to raise the brightness because I need to work outside and the tiny screen is hardly readable; but I did not find a method to to that, at least on the reference page:
https://github.com/olikraus/u8g2/wiki/u8logreference

Is there a way?

(I'm using: 
U8X8_SSD1306_128X64_NONAME_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);
....
U8X8LOG g_u8x8log;
)

Thanks

**Comment by XFer012** [comment]
Ok, I've found that I have to set contrast with the u8x8 object, not with the u8x8log object, so it's 

u8x8.setContrast(255)

Unfortunately it's still very dim (maybe because I only have Vcc=3.3v available, not 5v), but it's not a library shortcoming

**Comment by olikraus** [comment]
Maybe also your power supply is also not able to deliver more current. 
An additional cap between gnd and power supply may also help.

**Comment by XFer012** [comment]
No, it works fine with high brightness if I use the regular U8g2 (not the U8x8log).
I ended up using the regular U8g2, it was unreadable otherwise.

**Comment by olikraus** [comment]
ok... strange...
