### ISSUE TITLE
setContrast not working on Nokia 5110 display

### ISSUE THREAD

**Issue by ChrisXenon** [olikraus/u8g2#1216]
Oli, I am in awe of the contributions you have made - thank you.
I am driving a Nokia 5110 from a Wemos D1 mini. Everything works fine except that setContrast() has no effect, and whilst I have found a couple of other people saying similar none relate to this situation, so I hope you can help.

The code snippet is:

 if   (rightButtonPressed)
       {displayContrast = displayContrast + 25;
        if (displayContrast > 255) displayContrast = 0;
        u8g2.setContrast(displayContrast);
        rightButtonPressed = false;
        return;
       };

Do I need to do something else for the contrast change to take effect? A sendBuffer() is done subsequent to this elsewhere, but it doesn't help.
In case it's relevant, the constructor is:
U8G2_PCD8544_84X48_F_4W_HW_SPI u8g2(U8G2_R0, U8X8_PIN_NONE, DC_PIN, U8X8_PIN_NONE);     // Nokia 5110 Display

- and I am connecting RST of diaply & Wemod together and I am tying display CE to GND.

All other functions seem to be working fine.

Also, I know there is a Bias command for the display but I don't see a h8g2 command to use it. Is there one?

Many thanks
Chris

**Comment by olikraus** [comment]
Actually set contrast will execute the following code:
https://github.com/olikraus/u8g2/blob/99b63a38a3fde09a453fe0143c567bfa242d1c09/csrc/u8x8_d_pcd8544_84x48.c#L124-L128

It should actually work.

**Comment by ChrisXenon** [comment]
Thank you for your reply Oli. Well, it doesn't work. Perhaps I have a faulty unit. I ordered 3 more and they arrived but none work. It seems the zebra strip and netallic frame mechanism for connecting the PCB to the display is very unreliable. Will your library work on the HX1230 display? This unit bonds the display to the PCB and has better resolution.

Thanks again.
Chris

**Comment by olikraus** [comment]
HX1230 support is there: https://github.com/olikraus/u8g2/issues?q=is%3Aissue+hx1230

**Comment by ChrisXenon** [comment]
Apologies - I'm wasting your time.

Thanks again
Chris

**Comment by olikraus** [comment]
Not a problem. Other topics require much more effort ;)
