### ISSUE TITLE
u8g2 stops the Arduino Nano Every with I2C and DOGXL240

### ISSUE THREAD

**Issue by Algorab** [olikraus/u8g2#1218]
Hello Olikraus,
after several seconds or some minutes the Arduino is stopping or maybe internally crashing.
Have an Arduino NANO Every with a DOG XL 240 Display connected with I2c. When I run
a little counter example for reproduce after a several seconds or minutes the Arduino is
stop working. Then I have to reset then it is start again and stops again after a while.
This happens in frame also in the page mode. In the page mode the stops happen later
as in the frame mode what I could observe.

Arduino IDE: 1.8.12
Board: Arduino Nano Every
MCU: ATmega4809
avrdude: Version 6.3-20190619
Programmer : jtag2updi

I attached a sketch for reproduce.
[DisplayRun.ino.txt](https://github.com/olikraus/u8g2/files/4758749/DisplayRun.ino.txt)

**Comment by olikraus** [comment]
What will happen if you remove the serial output? Will it work?

**Comment by Algorab** [comment]
I tried it without the serial output, additionally change the display orientation and with different I2C clock speed settings again, the Arduino stops as described in the first comment.

**Comment by Algorab** [comment]
I test it with an arduino mkr1010 wifi and the display, the behavior still exists. This board is debuggable with openocd, but I didn't get it working.

**Comment by olikraus** [comment]
Can you use this constructor:
`U8G2_UC1611_EA_DOGXL240_F_HW_I2C u8g2(U8G2_R3, 3); `

What will happen with software emulated I2C?

`U8G2_UC1611_EA_DOGXL240_F_SW_I2C u8g2(U8G2_R3,SCL, SDA, 3); `

**Comment by Algorab** [comment]
U8G2_UC1611_EA_DOGXL240_F_HW_I2C u8g2(U8G2_R3, 3); ->
With this constructor it is stopping / crashing.

U8G2_UC1611_EA_DOGXL240_F_SW_I2C u8g2(U8G2_R3,SCL, SDA, 3); ->
With this it was running nearly 24h nonstop. It is much slower than the HW variant, this not really impact my project. I tried then this constructor with my second I2C device (RTC), the display then was blank.

**Comment by olikraus** [comment]
ok, understand. But it looks like an issue with the Arduino I2C low level software. At the moment I do not exactly know how to debug or fix this, any idea?

**Comment by Algorab** [comment]
I switched from I2C for the display to 3W SPI and it works like a charm. No crashes/stops of the arduino, fast and precise on display changes. Due I haven't a jlink jtag/swd hardware debugger I can't dig more in. I don't know whether then I see what I expect to see (a crash dump or stacktrace). Maybe somebody can confirm that. Then I would invest in such a debugger and in time. 
The RTC is still connected via I2C.
This is my first arduino project so I am not so experienced and my learning curve is high. At this point I don't have any clue how I can help further.

**Comment by olikraus** [comment]
Sounds like a good workaround. I will close this issue. Feel free to reopen...
