### ISSUE TITLE
LoadFromSD.ino is not working as expected

### ISSUE THREAD

**Issue by e-labInnovations** [olikraus/u8g2#1223]
Code: [LoadFromSD.ino](https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/LoadFromSD/LoadFromSD.ino)
Board: Arduino UNO
OLED: `U8G2_SSD1306_64X32_NONAME_1_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);`
SD Card Module: [HW-125](https://file.vishnumaiea.in/hardware/micro-sd/Catalex-Micro-SD-Card-Module_3_LS.jpg)
Output Serial Monitor:
![image](https://user-images.githubusercontent.com/33958126/84570156-321c1180-ada9-11ea-9f8e-2e38a400016e.png)
Outupt OLED:
![image](https://user-images.githubusercontent.com/33958126/84570315-647a3e80-adaa-11ea-944e-82fa292cdb42.png)

**Comment by olikraus** [comment]
Which display did you connect? Is this really a 64x32 display?

**Comment by e-labInnovations** [comment]
128x64

**Comment by olikraus** [comment]
Nice.

> Can I use .xbm file instead of .bin file?

Yes, but you need to write a .xbm format reader instead of the current drawFile() procedure.
https://github.com/olikraus/u8g2/blob/99b63a38a3fde09a453fe0143c567bfa242d1c09/sys/arduino/u8g2_page_buffer/LoadFromSD/LoadFromSD.ino#L377

I decided to use a special binary format to speed up the reading process. .xbm will slowdown loading and increase code in your uC.

**Comment by e-labInnovations** [comment]
**Thank you so much**

How can I convert my `.xbm` image file to `.bin` file?
I think png2bin tool can create a `.bin` file from a `.png` file. Can you give example command of png2bin tool?

**Comment by olikraus** [comment]
> How can I convert my .xbm image file to .bin file?

The code is included in the .ino file. On the other side you could use "gimp" to convert xbm to png.

The command will be:
```
png2bin picture.png picture.bin
```
This will generate picture.bin out of picture.png.

**Comment by e-labInnovations** [comment]
# Thank You
