### ISSUE TITLE
SSD1322 in 8080 Only works when reset is hold

### ISSUE THREAD

**Issue by DuminduRan** [olikraus/u8g2#1225]
I have made a custom board for ssd1322 following the attached schematic. I have uploaded the code with following constructor

U8G2_SSD1322_NHD_256X64_F_8080 u8g2(U8G2_R0,8,9, 10, 11, 4, 5, 6, 7,  /*enable=*/ 22, /*cs=*/ 23, /*dc=*/ 24, /*reset=*/ 25);

But it works only when I press and hold the reset button on arduino mega. Once I released it will clear the screen. By the way I am using hello World example. Sometimes there is a small square in a corner as well as some flickering can be seen. appreciate any help
Thanks
![Capture](https://user-images.githubusercontent.com/66998925/84760020-1dc45880-afe5-11ea-9af2-cb7009b6a6d0.JPG)

**Comment by olikraus** [comment]
ok... so you solved your problem?
