### ISSUE TITLE
SPI conflict with U8G2_SH1107 and Adafruit_BMP3XX

### ISSUE THREAD

**Issue by alnitac** [olikraus/u8g2#1231]
Hello,
I'm struggling since several days with this problem.
I have a Pimoroni Oled 1"12 display and one BMP388 connected to an Arduino Iot33.
Separately both are working fine, but together there is no way.
Both are on hardware SPI, CS 9 and 10.
With bmp.begin() first, the display works fine, but no pressure measurement.
With u8g2.begin() first, pressure measurement works fine, but no display.
Someone an idea how i can resolve this ?
Thanks.

**Comment by olikraus** [comment]
You probably need to reduce the spi clock speed. See the notes in the u8g2 reference manual for setBusClock.

**Comment by alnitac** [comment]
Clock speed is 66 kHz when display works, and 1 Mhz when BMP works.
Setting clock speed in u8g2 doesn't change anything.
I need to investigate the BMP library to find a solution.
Thanks for the guidance.

**Comment by alnitac** [comment]
I've tried to change the SPI clock speed in both librairies with no better result. 
I continue to investigate, found in BMP3XX library that SPI_MODE0 is not defined in SPI.beginTransaction, don't know if this is important.

**Comment by olikraus** [comment]
> I continue to investigate, found in BMP3XX library that SPI_MODE0 is not defined in SPI.beginTransaction, don't know if this is important.

The default should be spi mode 0 and also the SH1107 driver will use mode 0, so this should not be a problem.

https://github.com/olikraus/u8g2/blob/0966f30f7daeb9249f1a4d2042460932a0b2ac48/csrc/u8x8_d_sh1107.c#L368

BTW: Which constructor did you use? You must use the HW_SPI constructor.

**Comment by alnitac** [comment]
Ouch, i used SW_SPI constructor, because it worked on it's own.
With the  HW_SPI it displays only a little stroke of pixels.
The joined image is created with SW_SPI. Then i upload the same sketch with HW_SPI and only in the middle there is a stroke of pixels moving around. I blurred lower part of the image.
![Oled](https://user-images.githubusercontent.com/48484712/86018211-50c70d00-ba25-11ea-94d7-bd0cfaa215b5.jpg)

**Comment by olikraus** [comment]
Maybe you can now apply the setBusClock command again. Will it help? Maybe start with 100000 (100kHz) and increase that value.

**Comment by alnitac** [comment]
I tried several values without any change.
Software SPI works, Hardware SPI displays nothing more than a stroke of pixels, but only if something was displayed before.
I understand that even clearBuffer() does nothing with hardware SPI.

**Comment by olikraus** [comment]
Maybe you should get Hardware SPI to work reliable first. If you use one of the existing U8g2 examples, will HW SPI work?

**Comment by alnitac** [comment]
This sketch works perfectly with SW SPI. 
It does not work with HW SPI : nothing on the display.
![OledSW](https://user-images.githubusercontent.com/48484712/86333734-944f9000-bc4c-11ea-9558-13e297c5648a.jpg)


[TestOled.txt](https://github.com/olikraus/u8g2/files/4862779/TestOled.txt)

**Comment by olikraus** [comment]
Summary:
 * Both devices (OLED and BMP) are connected to the same SPI bus, so the SPI pins are shared. 
 * There are two different CS lines, one for OLED and one for BMP
 * SW SPI works for the OLED
 * HW SPI does NOT workf for the OLED
 * BMP Lib will use HW SPI 

The point is: Both libs MUST use HW SPI. otherweise they will conflict with each other. If you use SW SPI with the oled, then the pins are reprogrammed to work as normal GPIO pins and the SPI hardware is deactivated. As a consequence the BMP will not work. On the other side, BMP will activate HW SPI subsystem, then u8g2 SW SPI will not work, be cause it assumes the SPI pins to be normal GPIO pins.

As a consequence: Both libs MUST use HW SPI. 

> It does not work with HW SPI : nothing on the display.

This needs to be solved. Once this is solved, the both libs will work together.

**Comment by alnitac** [comment]
I tried every constructor 128X128 pixels using HW SPI : no pixel appears on display.
Sorry, my skills are insufficient to dive into the library, otherwise i am ready to help.

**Comment by olikraus** [comment]
In order to help, we need more information.
Which u8g2 HW SPI constructor did you use (including args)?
Which Arduino Board do you use?
How are pins connected between Board and Display?

**Comment by alnitac** [comment]
Working constructor is : 
U8G2_SH1107_PIMORONI_128X128_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 12, /* reset=*/ 8);
NOT working constructor is : 
U8G2_SH1107_PIMORONI_128X128_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=/ 10, / dc=/ 12, / reset=*/ 8);

I tried on two different boards with same results : Arduino Nano 33 IoT and Arduino Nano 33 BLE

Pin connections : 

![image](https://user-images.githubusercontent.com/48484712/86516722-4e005980-be23-11ea-8fd8-d4e81c0d22ca.png)

**Comment by olikraus** [comment]
Connection seems to be correct. It might still be a speed problem. You need to place the bus speed command before u8g2.begin.

**Comment by alnitac** [comment]
I tried a lot of values, still nothing on display. :(

**Comment by olikraus** [comment]
Hmm.. I also do not know, what is wrong here... To solve your initial problem, you could connect your display to complete different GPIO pins. I mean: Do not use D11 and D13 but something else with `U8G2_SH1107_PIMORONI_128X128_F_4W_SW_SPI`.

**Comment by alnitac** [comment]
Indeed it works with software SPI, but sendBuffer() takes more than 250 ms to complete, that's too slow as i need to mesure pression at least every 100 ms.

**Comment by olikraus** [comment]
not sure, what else I could suggest here...
