### ISSUE TITLE
Tabs and spaces

### ISSUE THREAD

**Issue by ArminJo** [olikraus/u8g2#1235]
Hi Oli,
thanks for this amazing library! 🥇 

Browsing through your code would be a bit easier, if you could convert all tabs to spaces.
(and remove trailing spaces).
This would be wonderful.
Thanks in advance.

Armin from Cologne

**Comment by olikraus** [comment]
Does the tab size break the format somehow? Tab size should be 8 spaces.

**Comment by ArminJo** [comment]
My tabs are Eclipse wide set to 4 spaces and yes, it breaks the format of your code.
You use tabs and spaces randomly, so it would be nice to be consistent.
BTW. In our software development department, tabs are banned.

**Comment by olikraus** [comment]
As I said, the tab size is 8 blanks. This should be consistent (although I can not ensure this for any pull requests).
 
> You use tabs and spaces randomly, so it would be nice to be consistent.

Any specific example would be great.

**Comment by ArminJo** [comment]
line 81 ff. in U8x8lib.cpp
![2020-07-12 12_00_35-WORKSPACE_ARDUINO - LCD_src_lib_U8g2_U8x8lib cpp - E__WORKSPACE_ARDUINO - Eclips](https://user-images.githubusercontent.com/3881884/87243604-96c59d00-c437-11ea-884b-ef7cb4dea6bb.png)

**Comment by olikraus** [comment]
Hmm... as mentioned, you should use 8 spaces per tab and not 4. So I would say your editior setting needs to be changed. Moreover this should be consistent throughout all files. Any example which demonstrates any inconsistency?

**Comment by ArminJo** [comment]
> you should use 8 spaces per tab and not 4

Thank you for the valuable advice.

But tell me. why do you sometimes use spaces and sometimes tabs for indentation?

**Comment by olikraus** [comment]
I do not use tabs for indentation. Instead a tab is used to replace 8 spaces. 
Indentation is 2 spaces in my code, so at indent level 4 my code editor will insert once tab.

Oli (Exil-Franke)

**Comment by ArminJo** [comment]
Ok, now I understand.
This saves a few bytes on the disc, but gives strange results on editors not following the tab is 8 spaces rule. 😟

**Comment by olikraus** [comment]
Actually, I assume my editor just moves to the next tab stop.

**Comment by ArminJo** [comment]
So I dare there will be no solution, but it is your code, and others have to adjust.

**Comment by olikraus** [comment]
Well... Probability yes
