### ISSUE TITLE
u8g2 and RTC not working together

### ISSUE THREAD

**Issue by Asolex63** [olikraus/u8g2#1239]
When I use the program as below, the RTC time value gets messed up. If I don't print anything to the display the time keeps corrrect. If I use the firstpage-nextpage method the result is the same. Setting the I2C adress has no effect either. When I use the adafruit library the RTC does not get messed up but then the display format is not correct. It is not an adafruit display so that makes sense. What am I missing?

![image](https://user-images.githubusercontent.com/68269887/87397673-fdbc9080-c5b4-11ea-89b8-ffd0fdc0c5fc.png)

![image](https://user-images.githubusercontent.com/68269887/87398036-9bb05b00-c5b5-11ea-9b5e-f172450a3181.png)

**Comment by JamesGKent** [comment]
that RTC supports only 100KHz I2C clock, but i think your display supports 400KHz, U8G2 will set the bus speed to its requirements, so you might need to either set the bus speed back to 100KHz after writing to the display, or tell u8g2 to use 100KHz to the display.

**Comment by Asolex63** [comment]
Thanks for helping me out, that is exactly what I missed, 
Added the statement   Wire.setClock(100000);   and it works like a charm.

**Comment by olikraus** [comment]
:-)
