### ISSUE TITLE
Text appearing on a MAX7219 is reversed

### ISSUE THREAD

**Issue by imekon** [olikraus/u8g2#1240]
I used the following to display text on a KWMobile board (4 x 8 x 8 LED display) - see below. The problem is the text is appearing reversed (instead of 'text' it appears as 'txet'). I've tried U8G2_MIRROR which flips each character but it still remains as 'txet'. I think it's wired as 8 x 8 blocks in reverse - so fonts that aren't 8x8 don't look right! Is there any way to get u8g2 to display in reverse across 4 8 x 8 displays?

`#include <U8g2lib.h>`

`U8G2_MAX7219_32X8_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 11, /* data=*/ 12, /* cs=*/ 10, /* dc=*/ U8X8_PIN_NONE, /* reset=*/ U8X8_PIN_NONE);`

`void u8g2_prepare(void)`
`{`
`  u8g2.setFont(u8g2_font_amstrad_cpc_extended_8f);`
`  u8g2.setFontRefHeightExtendedText();`
`  u8g2.setContrast(40);`
`  //u8g2.setFlipMode(true);`
`  u8g2.setDrawColor(1);`
`  u8g2.setFontPosTop();`
`  u8g2.setFontDirection(0);`
`}`

`void display_text(const char *text)`
`{`
`  u8g2.clearBuffer();`
`  u8g2_prepare();`
`  u8g2.drawStr(0, 0, text);`
`  u8g2.sendBuffer();`
`}`

`void setup() `
`{`
`  u8g2.begin();`
`}`

`void loop() `
`{`
`  display_text("text");`
`}`

**Comment by olikraus** [comment]
Difficult, I guess some low level code needs to be modified
