### ISSUE TITLE
'u8g2' was not declared in this scope

### ISSUE THREAD

**Issue by wudyg** [olikraus/u8g2#1241]
HelloWorld:308:3: error: 'u8g2' was not declared in this scope

   u8g2.firstPage();

   ^

exit status 1
'u8g2' was not declared in this scope

**Comment by olikraus** [comment]
You need to uncomment a suitable constructor first.

**Comment by alaintanguy** [comment]
"You need to uncomment a suitable constructor first."
Need more explanation or link Please

**Comment by olikraus** [comment]
The referenced file contains a list of constructors. Exactly one of them needs to be uncommented.
