### ISSUE TITLE
LCD Dot Matrix Screen Refreshes every loop Iternation

### ISSUE THREAD

**Issue by slickmezzie** [olikraus/u8g2#1242]
Hi Oliver,

Great library - thanks for sharing!

I am having a few issues displaying my ECG graph on my dot matrix (128x64) screen. The screen seems to refresh every loop iteration rather than after 127 loops (i.e. full screen)...

All I get is a line segments moving across the screen (the screen does clear every 127th iteration as the title text flickers)... Obviously I would like all the line segments to remain on the screen until I refresh the screen after it is full.

My very basic code is below (I am no coder by any stretch of the imagination!), please be gentle:

It is my code but I can't see why it is not working...

Code...

``` C++
void loop(void) {
  u8g2.firstPage();
   do {
    if(x>127)  
  {
    // Clear Display
    u8g2.clear(); // Works
    x=0;
    lastx=x;
  }
    // u8g2.firstPage();
    // Display Heading text
    u8g2.setFont(u8g2_font_ncenB08_tr);
    u8g2.drawStr(35,10,"ECG Display");
    int sensorValue = analogRead(A0);
    // print out the sensorValue to serial port:
    Serial.println(sensorValue);
    // delay(1);        // delay in between reads for stability
    // Display scaled ECG data
    // Draw line segment
    y=(63-(sensorValue/16));
    u8g2.drawLine(lastx, lasty, x, y);
    // delay(10); test
    lastx=x;
    lasty=y;
    // Increment x 
    x++;
  }
  while (u8g2.nextPage());
}
```
Thanks in advance.

Regards,
Dave.

**Comment by olikraus** [comment]
Did you use the `_F_` constructor?

**Comment by slickmezzie** [comment]
No I didn’t, I will look into it (I do remember seeing it when I was investigating why it wasn’t working - I should have investigated it further...).

Apologies and thanks for getting back to me.

Regards,
Dave
Sent from my iPhone

On 26 Jul 2020, at 5:08 pm, olikraus <notifications@github.com> wrote:

Did you use the _F_ constructor?
