### ISSUE TITLE
KS0108 192x64 display with 2 CS lines and BCD select

### ISSUE THREAD

**Issue by wa2mze** [olikraus/u8g2#1244]
How do I set up a KS0108 based 192x64 display that has only 2 CS lines?  Instead of one CS pin for each controller, this one uses an encoded select for CS0 and CS1 with 0,0 0,1 and 1,0 selecting the controllers, 1,1 for NONE.  I've been searching in the code for the logic that sets the CS pins, but I can't find the callback function define and implementation.

**Comment by olikraus** [comment]
I assume you need to update this procedure:
https://github.com/olikraus/u8g2/blob/0966f30f7daeb9249f1a4d2042460932a0b2ac48/csrc/u8x8_byte.c#L331-L338

"arg" will get values  0, 1, 2 and 4 which needs to be translated to your needs.
