### ISSUE TITLE
Issue with Serial1 with u8g2 Teensy 3.2

### ISSUE THREAD

**Issue by Renaudp** [olikraus/u8g2#1245]
Hello,
Have you experienced issue while recieving data on Serial1 with Teensy 3.2?
if I comment u8g2.sendBuffer() in my code, datas are correctly recieved.
Thank you in advance,

**Comment by olikraus** [comment]
sendBuffer() will take some milliseconds. Maybe the delay is too long. 
Solution could be a bigger receive buffer with Serial1 (not sure whether this is possible) or increased speed with sendBuffer(). Did you use hardware SPI/I2C for u8g2?

**Comment by Renaudp** [comment]
I am using I2C. I've found what was wrong... Serial overflow!
Thanks again for your great job! u8g2 is cool!
