### ISSUE TITLE
[new functionality] The multiplier for the UserInterfaceInputValue function

### ISSUE THREAD

**Issue by greenmagics** [olikraus/u8g2#1252]
Hello!
I needed to change the value with the function "userInterfaceInputValue", but not linearly (1, 2, 3, 4, 5 etc), but in steps (5, 10, 15 etc), so I added an extra value (uint8_t multiplier) sent to the variable. You can use 1 to keep the previous mode of operation or, for example, 5 as in my case. In the archive I am sending 3 files in which I added this change.

Regards Szymon from Poland ;)

[u8g2_input_value.zip](https://github.com/olikraus/u8g2/files/5037794/u8g2_input_value.zip)

**Comment by olikraus** [comment]
I think the best would be to just to takeover the code of that function into your project. Then adapt the code to your needs.

https://github.com/olikraus/u8g2/blob/0966f30f7daeb9249f1a4d2042460932a0b2ac48/csrc/u8g2_input_value.c#L44

The other option probably would be to use a full featured user interface like Arduino-Menu.
