### ISSUE TITLE
Set SSD1322 oscillator frequency

### ISSUE THREAD

**Issue by nikeee** [olikraus/u8g2#1257]
I'm trying to set the oscillator frequency of the SSD1322:
https://www.newhavendisplay.com/app_notes/SSD1322.pdf

I think this is the relevant part of the initialization:
https://github.com/olikraus/u8g2/blob/2ab787cc546dbce67d37727289a918e875328f3a/csrc/u8x8_d_ssd1322.c#L275

Assuming we cant override the init sequence, is there an API to send the command?

**Comment by olikraus** [comment]
Will this work?
https://github.com/olikraus/u8g2/wiki/u8g2reference#sendf

**Comment by nikeee** [comment]
It works, thanks!
