### ISSUE TITLE
Can Not Add u8g2.zip or u8glib-master.zip to Libarey in Arduino

### ISSUE THREAD

**Issue by StevenArkon** [olikraus/u8g2#1260]
Using Windows 10 with Arduino installed from the Windows App Store Version 1.8.13 (Windows Store 1.8.42.0) I downloaded u8glib.zip from Github and tried to install it with the following error, "Specified folder/zip file does not contain a valid library". I then downloaded u8g2.zip and tried to install it, With the same results. Of course when I try to compile my Marlin 3D Printer Firmware Configuration.h and, adv.h files I get a lot of errors that point back to the missing Liberals.  Can anyone help me get this issue resolved?

**Comment by olikraus** [comment]
no further feedback... closing...
