### ISSUE TITLE
using u8g2 library for 3.37'' OLED 240x128, display partially distorted 

### ISSUE THREAD

**Issue by AfrasiabSaleem** [olikraus/u8g2#1261]
Hi Oliver...!
I m trying to use u8g2 library to display on my 3.37'' OLED 240x128 with SSD1322 driver, firstly I couldn't find the exact matching constructor in the constructor list so I used
U8G2_SSD1322_NHD_256X64_1_4W_SW_SPI constructor which is built for 256x64 pixels OLED but with same driver SSD1322.
I used the "Hello World by page buffer" example. It is partially working, which means it shows the display but the issue is that 16 columns from the left are not used by the program and show junk display. i have tried to figure out using drawPixel(x,y) command to see the location of each pixel but the actual (17,0) pixel is addressed at (0,0) by the program. This lead me to the conclusion that it is because of the mismatch in pixel in constructor and actual LCD.
Is there any way to change the pixel height and width in the library or any other method to solve this problem.

i have a attached a picture which shows the unused 16 columns as i started writing numbers from (0,60)

PS: I m using U8G2_MIRROR in the constructor and FlipMode(1) to straighten my text. Also i m using Arduino pro mini 3.3V.

![OLED 3 37'' 240x128](https://user-images.githubusercontent.com/70088898/90973317-6266f580-e53a-11ea-9d6a-81d0fbded279.png)

**Comment by olikraus** [comment]
On your local copy of u8g2 you probably need to change the x offset which seems to be different in your display:

https://github.com/olikraus/u8g2/blob/0966f30f7daeb9249f1a4d2042460932a0b2ac48/csrc/u8x8_d_ssd1322.c#L260

Instead of 0x01c try some bigger value like 0x020

**Comment by AfrasiabSaleem** [comment]
I changed both the offsets default_x_offset and flipmode_x_offset to 0x020 and the issue **RESOLVED**...!!! ... Thank You Soo much for your quick response and help... This library is a great work from you I must say ...

**Comment by olikraus** [comment]
:)
