### ISSUE TITLE
u8g2 library with FT232H

### ISSUE THREAD

**Issue by jbodart** [olikraus/u8g2#1262]
Hi, I just bought an SH1122 oled driver I want to use though FT232H instead of Arduino.
Is there anyway to use the u8g2 library for that?
Thanks

**Comment by olikraus** [comment]
It would require custom low level driver for u8g2. This is basically described here:
https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform

Your problem might be also related to this pull request: #1203, see here: https://github.com/olikraus/u8g2/tree/master/sys/linux-i2c
