### ISSUE TITLE
System5x7 font

### ISSUE THREAD

**Issue by crd5014** [olikraus/u8g2#1266]
I am trying to find a U8G2 font that matches the old GLCD System5x7 font.  Is there one available?  Thanks.

**Comment by olikraus** [comment]
Maybe this?
https://github.com/olikraus/u8g2/wiki/fntgrpx11#5x7

**Comment by crd5014** [comment]
OK, thanks. In looking into this further, it looks like the System5x7 font may be better defined as a 6x8 font, mono-
spaced including one pixel trailing space and a line space. Attached is a screenshot of the GLCD version.
![IMG_8389](https://user-images.githubusercontent.com/56406837/91665107-1bcc4a80-eaa8-11ea-966b-70f100e920b5.jpg)

**Comment by olikraus** [comment]
Maybe the 6x12 is more close:
https://github.com/olikraus/u8g2/wiki/fntgrpx11#6x12

But I do not think you will find something identical.

**Comment by crd5014** [comment]
OK, thanks
