### ISSUE TITLE
u8g2.print and Arduino Mega

### ISSUE THREAD

**Issue by BertJager** [olikraus/u8g2#1269]
Tried to use the u8g2.print command with Arduino Nano --> no problem.
Tried to use the u8g2.print command with Arduino Uno--> no problem.
Tried to use the u8g2.print command with Arduino Mega --> problem...!!!

[u8g2_mega.txt](https://github.com/olikraus/u8g2/files/5155852/u8g2_mega.txt)

Does Arduino Mega support this command, and if yes, what am I doeing wrong.

**Comment by olikraus** [comment]
There is no sendbuffer
