### ISSUE TITLE
Fet EPD support

### ISSUE THREAD

**Issue by sbsohrabi** [olikraus/u8g2#1279]
I successfully tested your library with several displays. You did a great job. thanks
I've just bought EPDs from this company(Fet).
Does your u8g2 support these two EPDs?
[达远-E0213A26-A2_2.pdf](https://github.com/olikraus/u8g2/files/5194049/-E0213A26-A2_2.pdf)
[达远-E029A37-A1 -2.9inch-Three color.pdf](https://github.com/olikraus/u8g2/files/5194059/-E029A37-A1.-2.9inch-Three.color.pdf)

**Comment by olikraus** [comment]
I tried to support EPDs, but finally I decided, that U8g2 does not really fit to provide proper support for EPDs, so I stopped supporting EPDs with U8g2.
