### ISSUE TITLE
Help, I want to use the U8G2 library on stm32 but I am not sure which files to move over

### ISSUE THREAD

**Issue by mohdezzi7** [olikraus/u8g2#1280]
Hi, 

Could I am having issues with using the U8G2 library on stm32. 

It does not seem to work when I include the entire folder path. The compiler returns an error in the tool folder saying that items.h and png.h do not exist in pathway. 

Is there a fix around this?

**Comment by olikraus** [comment]
U8g2 doesn't require those files, so I'm sure it isn't a u8g2 problem.

**Comment by mohdezzi7** [comment]
Oh! okay are there some files that I do need?

I am trying to program a 128x64 LCD screen with the ST9720 controller.

Kind regards,
Mohdezzi7
________________________________

**Comment by olikraus** [comment]
You basically need all files of the arc for of this project.
