### ISSUE TITLE
Which constructor for SH1107 128x64 ?

### ISSUE THREAD

**Issue by tavdog** [olikraus/u8g2#1281]
I only see a constructor for SH1107_64x128. Will that work for the 128x64 as well ? This is for the new 128x64 oled featherwing from Adafruit : https://www.adafruit.com/product/4650

**Comment by olikraus** [comment]
Did you check the constructor list in the u8g2 wiki? At the end you need to test which constructor works best.

**Comment by olikraus** [comment]
Yes, the mentioned constructor seems the only one which fits to your display dimensions: https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#sh1107-64x128

If the rotation doesn't fit, use R1 as first argument.

**Comment by tavdog** [comment]
Ok, thank you for the clarification.
