### ISSUE TITLE
Any support for TM9665ACC?

### ISSUE THREAD

**Issue by spase74** [olikraus/u8g2#1283]
Does u8g2 support TM9665ACC (https://aliexpress.ru/item/32683763108.html) ? It claims it uses ST7565 but LCD matrix is 96x65, rather than 128x64. Tried all ST7565, ST7567 types and PCF8812 96X65 without success.

**Comment by olikraus** [comment]
At least something should be visible.
Anyhow, because this is very old, can I close this topic?

**Comment by spase74** [comment]
Ok, let's close it.
Nothing is visible. At all.
Anyway I've got some examples from csdn and is close to make a patch to support this display. When (and if) it is ready, I'll go with a PR then.
