### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by Charley175** [olikraus/u8g2#1287]
HI！My LCD screen does not have a DC pin, what should I do?  

uint8_t Data = 0xFA;
uint8_t Cmd = 0xF8;
uint8_t Clean = 0x01;
 case U8X8_MSG_GPIO_DC:
        if (arg_int){
             HAL_SPI_Transmit(&Spi2, (uint8_t *) &Data, 1, 10000);
        }else{ 
             HAL_SPI_Transmit(&Spi2, (uint8_t *) &Cmd, 1, 10000);}
 break;

Then I wanted to use the above command to tell my LCD12864, whether I want to write data or commands, but my LCD display is messed up, please help me，thanks.

**Comment by olikraus** [comment]
Without the datasheet of your display it is impossible to help.
