### ISSUE TITLE
UpdateDisplayArea character shift

### ISSUE THREAD

**Issue by periperiperiperi** [olikraus/u8g2#1288]
Hi, im new to this so apologies in advance. I seem to be having a similar issue to another user (#1277 ) where, sendbuffer and update display work perfectly, however when i use updatedisplayarea it appears as garbage. after investigating, it is actually shifting parts of the character along in proportion with the specificed tile width and height. If i specify the max height and only half the width, then only every second line of the word prints.  I am using atmega328P and st7920 128x64 blue/white lcd. this means that the max tile size is 16x8. examples shown below.
max height, arbitrary width gives garbage
![image](https://user-images.githubusercontent.com/71540759/93659949-91b34880-fa8d-11ea-8a5c-766e9548724d.png)
![IMG_7414](https://user-images.githubusercontent.com/71540759/93660033-59f8d080-fa8e-11ea-9a9e-a8232b5a3467.jpg)

max height, exactly half width gives every 2nd line (kind of).
![image](https://user-images.githubusercontent.com/71540759/93659973-d3dc8a00-fa8d-11ea-9fb7-25c0b3e702dc.png)
![IMG_7415](https://user-images.githubusercontent.com/71540759/93660038-6715bf80-fa8e-11ea-8982-6cf02258f577.jpg)

max height max width gives expected output
![image](https://user-images.githubusercontent.com/71540759/93659983-e6ef5a00-fa8d-11ea-9c49-300fb9d6d2d0.png)
![IMG_7416](https://user-images.githubusercontent.com/71540759/93660043-6c730a00-fa8e-11ea-8ae3-8960a99163c0.jpg)
Thanks so much

**Comment by olikraus** [comment]
The quick answer is: UpdateDisplayArea is not supported for the following display controllers: SH1122, LD7032, ST7920, ST7986, LC7981, T6963, SED1330, RA8835, MAX7219, LS0xx
But it should mention this in the description.

**Comment by periperiperiperi** [comment]
ah okay sorry about that, thanks anyway!
a quick workaround i managed to come up with was to update a slice of the screen. that is, update the full width and only a portion of the height. this allowed much higher refresh speeds

**Comment by olikraus** [comment]
I have updated the menual.

https://github.com/olikraus/u8g2/wiki/u8g2reference#updatedisplayarea
