### ISSUE TITLE
Support for NHD-2.23-12832UCW3 SSD 1305 ?

### ISSUE THREAD

**Issue by nordseele** [olikraus/u8g2#1294]
Hi, 
Thanks for making this library.
Would it be possible to add support for the [NHD-2.23-12832UCW3](https://www.mouser.fr/datasheet/2/291/NHD_2_23_12832UCW3-1222125.pdf) OLED display please ? It's a 128x32 SSD1305 display.

It's not part of the list of supported devices already but I'm testing the wiring with the constructor of another device U8G2_SSD1305_128X32_ADAFRUIT_1_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8); and the "page buffer, graphics test" example provided. (on a Teensy 3.6) Of course, since it's not made for this specific device the bottom of some pages is cropped and the " bitmap overlay" is a bit flickering (unless this is normal, I don't know) but beside that it seems to work. I'd be happy to provide more details and to do some tests if support for the NHD-2.23-12832UCW3 is added. 

Or perhaps should I use one of the existing constructor and try to adjust the offset or something ? Please let me know.

Thanks.

![IMG_0190](https://user-images.githubusercontent.com/47527859/94364266-4e2d8f80-00c8-11eb-8fbd-e283e5e5a020.JPG)

**Comment by olikraus** [comment]
Can you run the page mode "FlipMode" example? If the frame at the display borders stays constant and never changes, then everything is fine.

**Comment by nordseele** [comment]
Yes, sure.
The frame remains constant indeed (photo A). Some "ghost" pixels briefly appear/flash on each rotation (photo B).
I'm not sure wether it's the normal behavior since I'm not familiar with the library yet but I will do more tests now.
Thanks.

##### Photo A
<img width="536" alt="Capture d’écran 2020-10-03 à 17 37 13" src="https://user-images.githubusercontent.com/47527859/94995515-26926780-059f-11eb-828a-20c741049799.png">

##### Photo B
<img width="736" alt="Capture d’écran 2020-10-03 à 17 46 51" src="https://user-images.githubusercontent.com/47527859/94995713-745b9f80-05a0-11eb-955a-4db858b7e655.png">

**Comment by nordseele** [comment]
Just did a few more tests, trying various constructors (Full screen, Page buffer and HW and SW), nothing super intensive yet but I think everything's fine with this display. That's good news :)

Thank you very much!

**Comment by olikraus** [comment]
Not sure from where those pixel came from, but I also assume, that everything looks good. Thanks for all the pictures.
