### ISSUE TITLE
can constructor name be a variable?

### ISSUE THREAD

**Issue by Kmanggaard** [olikraus/u8g2#1295]
My terminology is probably way off, but I'm trying to do something like this:

U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI disp0(U8G2_R0, /* cs=*/ 2, /* dc=*/ 10, /* reset=*/ 9);
myVar = disp0;
myVar.sendBuffer();

Hope that makes sense.
If it's possible, what kind of variable should I use?

**Comment by olikraus** [comment]
It would be a waste of memory, but should work.
I acctually woruld prefer pointers instead.
``` C++
U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI *myVar
U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI disp0(U8G2_R0, /* cs=/ 2, / dc=/ 10, / reset=*/ 9);
myVar = &disp0;
myVar->sendBuffer();
```
But all in all it is more a C++ question...

**Comment by Kmanggaard** [comment]
Memory I have plenty of, so I'll give it a go. Thanks for an incredible
library and great support.

**Comment by olikraus** [comment]
> Memory I have plenty of, so I'll give it a go. 

Pointer are also faster. ;)
