### ISSUE TITLE
Proteus simulation issues

### ISSUE THREAD

**Issue by valfa14** [olikraus/u8g2#1297]
https://github.com/olikraus/u8glib/issues/513
I'm facing also same issues with u8g2 lib :/

**Comment by olikraus** [comment]
I think I can not help here. I do not know anything about "proteus simulator". 
U8g2 works in Arduino IDE as expected. If it doesn't work in "proteus simulator" then I would suggest to contact "proteus simulator" people.

**Comment by SWIPHER** [comment]
Hi,I had the same problem with you but I solved just now.I found it only works with SPI mode in Proteus, the code is like this
`U8G2_SSD1306_128X64_NONAME_F_4W_SW_SPI u8g2(U8G2_R0,24,25,26,23,27);`
It works on the Arduino mega2560 moudle in proteus. And the Circuit diagram is like this:
![proteus](https://user-images.githubusercontent.com/37608954/127543584-aec6e7ac-9ef2-48a4-8910-1e9ab3d93c46.jpg)

**Comment by 223222981** [comment]
> 
![display](https://user-images.githubusercontent.com/39449246/168409121-e25a9271-5acd-4606-ac8a-d468a921c6d9.png)

Thank you I succeeded too
