### ISSUE TITLE
St7571 Display 

### ISSUE THREAD

**Issue by s54b32julian** [olikraus/u8g2#1298]
Hello Oli,

I don’t see 128x128 ST7571 in constructor. Is it available via other constructor or not supported at the moment?

Best regards,

**Comment by olikraus** [comment]
If it is not in this list: https://github.com/olikraus/u8g2/wiki/u8g2setupcpp
then it is not supported. :-(

**Comment by s54b32julian** [comment]
Would it be possible for you to add this with this datasheet https://www.crystalfontz.com/controllers/Sitronix/ST7571/305/ or if I send you one display? There are sadly no other displays in 128x128pixel with ~45x45mm display area.

**Comment by s54b32julian** [comment]
No chance? The display is not that expensive, but of course would come free to you ;) maybe it‘s not much work, as they are very similar to UC1611. And maybe to the others from ST-Drivers.

**Comment by olikraus** [comment]
The problem is mainly my available time on working on this. Unfortunately, the ST7571 differs a lot from UC1611. 
It would be easier to have a specific init sequence for your display. Is there any datasheet for your display (you have provided the datasheet of the controller)?

**Comment by olikraus** [comment]
I have ordered this display: https://aliexpress.com/item/32608068279.html
Will arrive in 4 weeks.

**Comment by s54b32julian** [comment]
Oli you are the real MVP. Is there a way to spend you a coffee or beer? Some people here on Github have a paypal-link for that, you too?

**Comment by olikraus** [comment]
No donation required, if any, I would take the beer :-D 
Let's wait until I receive this display. My e-mail (see any source code) is connected to paypal.

**Comment by olikraus** [comment]
Added support for this display.

![https://raw.githubusercontent.com/wiki/olikraus/u8g2/img/st7571.jpg](https://raw.githubusercontent.com/wiki/olikraus/u8g2/img/st7571.jpg)
