### ISSUE TITLE
Mutiple displays issue with framebuffer conflict

### ISSUE THREAD

**Issue by DatanoiseTV** [olikraus/u8g2#1300]
I'm using 3 displays for testing in my appliatication:
U8G2_SSD1322_NHD_256X64_F_4W_HW_SPI display0(U8G2_R0, /* cs=*/ 5, /* dc=*/ 13, /* reset=*/ 12);  // Enable U8G2_16BIT in u8g2.h
U8G2_SSD1306_128X64_NONAME_1_HW_I2C display2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE, /* clock=*/ 22, /* data=*/ 21);
U8G2_SSD1322_NHD_128X64_F_4W_HW_SPI display1(U8G2_R0, /* cs=*/ 32, /* dc=*/ 13, /* reset=*/ 33);  // Enable U8G2_16BIT in u8g2.h

For all display I do <display>.begin(); <display>.clearBuffer();, drawing, and <display>sendBuffer();

Now the weird part, and I can confirm it's not a coding mistake here:
display1 and display2 display the same content..

**Comment by olikraus** [comment]
> I can confirm it's not a coding mistake here

It might not be a mistake, but it is still caused by your code. So... please share the code.
It is also strange that you have 2 full buffer constructors and one page buffer constructor.
