### ISSUE TITLE
Bug with print and uint32_t

### ISSUE THREAD

**Issue by 762SPR** [olikraus/u8g2#1306]
I just finished tracking down a bug I am having with trying to print a uint32_t to the screen. It was giving me fits because it wasn't throwing an error or anything, but once the code uploaded, the application was just bricked and nothing would display on the screen. I couldn't even recompile and directly upload the code again, I had to initiate the upload and hit the reset button. This line of code wasn't even being executed, as it was inside an if statement that wasn't running, but just having it in the code at all bricked the whole thing.

If I cast to uint16_t, everything works fine. If I use drawStr with the uint32_t, it works fine. But print will not work with just a straight uint32_t

Is it better to use drawStr vs print? I like that drawStr eliminates the need to have a separate call to setCursor, but it also makes it so I can't call it in sequence to print a label and then value ex: 

```
u8g2.print("label: ");
u8g2.print(someInt);
```

Regardless, I have a workaround for now, but it would be nice to either be able to print uint32_t directly, OR at least have it throw an error or warning so idiots like me don't spend an hour trying to figure out why their board just bricks itself on code that isn't even being executed... If it helps, I am using a 32u4, and a generic 128x64 oled with this constructor:

`U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ 3, /* data=*/ 2, /* reset=*/ U8X8_PIN_NONE);`

**Comment by olikraus** [comment]
The print function comes from the Arduino lib. It is actually not part of u8g2. The same issue should be there with serial.print.
