### ISSUE TITLE
Trying to port the library to STM32, no go

### ISSUE THREAD

**Issue by spi5498** [olikraus/u8g2#1307]
So after days of puzzling bits of information together, i came up with this:
[https://pastebin.com/L75pGi92](url)

I have checked that i have "traffic" on my scope. Its only two channels, so i have checked it a bit rough. Ie CS low when data is transferred and so. However nothing comes up on the LCD. The wiring is checked 10 times, atleast.

Does anyone see anything obvious? Otherwise i need to dig out my logic analyzer, however it does not have SPI decoding.

**Comment by spi5498** [comment]
Did notice that i had "disable" in the MSG_BYTE_INIT, changed that to enable instead ofcourse. Same problem though..

**Comment by spi5498** [comment]
So, after more or less two days wasted, still cant get any life out of this with the STM. I have no idea why it is so hard.
Attaching a snippet from the scope. this is from the init routine.
Yellow: RST
Red: CLK
Blue: CS
Green: Data

![lcdscope](https://user-images.githubusercontent.com/60155713/95659289-505c0900-0b20-11eb-8c80-9b5e85496deb.jpg)

**Comment by spi5498** [comment]
I did try out the SPI decoding on my PicoScope, and with just the code for Init and powersave i get this over the SPI:

0 02 32 50 C1 6C 00 87 00

Does that make any sense?

**Comment by spi5498** [comment]
Nope, data is totally wrong.

**Comment by spi5498** [comment]
I see that there is 30 commands sent in the init sequence and thats corresponds to whats in the sourcefile for my controller. 
Atleast thats something.
However, it is completely the wrong data.

**Comment by olikraus** [comment]
According to your code https://pastebin.com/L75pGi92 , i see the following issues:
1) the gpio&delay procedure should implement all the delay messages.
2) I wonder that there is no RS/A0/DC handling

**Comment by spi5498** [comment]
Thanks for your response, as i said, this code that is posted here will not be used anymore. I will do a complete makeover.
the reset procedure in the code for my display controller is commented out. Is that not used?

**Comment by olikraus** [comment]
> the reset procedure in the code for my display controller is commented out. Is that not used?

Do you have link to the code?

**Comment by olikraus** [comment]
oh, same question in new post. I will answer there.
