### ISSUE TITLE
in program screen rotation

### ISSUE THREAD

**Issue by soheils2** [olikraus/u8g2#131]
hey there 
first i wanna thank u for this awesome library.

in u8glib (v1) we can change screen rotation in  the code for even each draw with this codes:

u8g.setRot0();
u8g.setRot90();
u8g.setRot180();
u8g.setRot270();

but in this version you can just set the rotation on  the begining and there is no way to rotate it in the program ,
OR i couldnt find the void that do this. 

please let me now if there is a way to change the rotation in program. tnx

**Comment by olikraus** [comment]
There is no function as such. Maybe I add this..

  u8g2->cb = rotation;
  u8g2->cb->update(u8g2);

**Comment by olikraus** [comment]
oh, it is already there:
```
   void setDisplayRotation(const u8g2_cb_t *u8g2_cb) {
      u8g2_SetDisplayRotation(&u8g2, u8g2_cb); }
```
But indeed the documentation is missing.

**Comment by olikraus** [comment]
documentation done
