### ISSUE TITLE
[Question] Code size U8g2 vs. U8x8...

### ISSUE THREAD

**Issue by dl9sec** [olikraus/u8g2#1310]
Hi,

I have currently code using the U8g2 library running on a Arduino Pro Micro (ATmega 32U) with a 128x64 SSD1306 . The program memory is nearly full (676 bytes free), but I want to put some more code in.

I assumed using the U8x8 library will save some codespace, but I was totally wrong. The code size increases by about 4kBytes!

Is it a misunderstanding of mine, that the U8x8 is a smaller and more compact library? Or has it to do with used OLED hardware?

Any ideas welcome.

Thank you in advance.

Regards, Thorsten

**Comment by olikraus** [comment]
Maybe you have used too big or too many fonts. Posting your code might also help.
