### ISSUE TITLE
esp32 with 19264 ks0108 lcd miss the pixels position with every redraw

### ISSUE THREAD

**Issue by GoDotMad** [olikraus/u8g2#1312]
this is the hello world example 

I tried it in page buffer (1 & 2 page) and in full buffer 
as well as in u8x8 mode
it seems that when a redraw of the buffer occurs some pixels shift or something

**Comment by GoDotMad** [comment]
![Uploading IMG_20201015_223122.jpg…]()

**Comment by GoDotMad** [comment]
[Uploading VID-20201016-WA0001.mp4…]()

**Comment by GoDotMad** [comment]
![Uploading ezgif-3-8385f3dcc95e.gif…]()

**Comment by GoDotMad** [comment]
https://gifyu.com/image/8w6i

**Comment by GoDotMad** [comment]
forgot to mention that it works without any problems using arduino uno 

so is it possible that it is caused by the difference in processor architecture 


also I'm using platformio on vscode not arduino ide

**Comment by GoDotMad** [comment]
terns out that my lcd needs a little bit more time after the enable signal 

I tried to adjust the times in the screen info struct
but it was already near maximum with 250 ns
so I adjusted the u8x8_byte_ks0108 function by coping the call to the delay function once more

I think that the reason it worked on the uno is because it is slower than the esp32 

and by the way 
this is a super cool library 
every thing is organized and modular 
and all you need to modify it is some time and understanding of the lcd controller

so thanks for this great library

**Comment by olikraus** [comment]
Excause my delay in looking into issues. Just read your posts.
I am happy you solved this issue. Good work.

**Comment by AhmadSarifudin** [comment]
@GoDotMad Hi 

> terns out that my lcd needs a little bit more time after the enable signal
> 
> I tried to adjust the times in the screen info struct but it was already near maximum with 250 ns so I adjusted the u8x8_byte_ks0108 function by coping the call to the delay function once more
> 
> I think that the reason it worked on the uno is because it is slower than the esp32
> 
> and by the way this is a super cool library every thing is organized and modular and all you need to modify it is some time and understanding of the lcd controller
> 
> so thanks for this great library

Hi @GoDotMad  , I have same problem , Can you explain  where part do you change about times in the screen info , in the library? , Thanks

**Comment by GoDotMad** [comment]
Hi @AhmadSarifudin ,

are you usind a screen with the same controller as the one I mentioned?

**Comment by flewis88** [comment]
@GoDotMad I'd be interested to know your workaround too. I'm getting broken graphics

**Comment by GoDotMad** [comment]
Hi there, 
what lcd and what controller are you using? 

I hope I'm not too late to reply.

**Comment by flewis88** [comment]
ESP32 is generic, similar to this: https://joy-it.net/en/products/SBC-NodeMCU-ESP32
And the KS0108 is model ABG128064A50-DIW-R

Appreciate you replying!
