### ISSUE TITLE
again UC1698 

### ISSUE THREAD

**Issue by mcarosh** [olikraus/u8g2#1313]
Dear olikraus
sorry for asking again and with a large break for help in this case :/ I´m still working on it 
Meanwhile I know why it is "half"working with the uc1610 library. There you upscale the Byte to 16bit. But with the UC1698 I need to expand the Byte to 32bit or more specifically I need to send one Bit four times (for example if one Byte is 01010101 I just need to send 0000 1111 0000 1111 0000 1111 0000 1111). But in your code are to many variables and ties to other files I do not know :( i´ve already tried some modifications but always failed. Maybe You have some patience left for me and you can give me a little help/hint? I think/hope it shouldn´t be too complicated to expand the Byte in this way?!
So far say thank you in advance 
Greez
mcarosh

**Comment by olikraus** [comment]
Well, I do not know how the byte needs to be expanded.
Maybe take a sheet of paper and try to make a picture on how to map 8 bits to 32 bit. Maybe give chars from a to h for the 8 bits. then place the chars into the 32 bit word. I mean, before programming there should be a clear picture on how it should look like.

**Comment by mcarosh** [comment]
First a really big thanks for your patience with me
Here are the examples of expansions:

the letter:
a (UTF-8=0061) 01100001 -> 00001111 11110000 00000000 00001111
b (UTF-8=0062) 01100010 -> 00001111 11110000 00000000 11110000
c (UTF-8=0063) 01100011 -> 00001111 11110000 00000000 11111111
d (UTF-8=0064) 01100100 -> 00001111 11110000 00001111 00000000
e (UTF-8=0065) 01100101 -> 00001111 11110000 00001111 00001111
f (UTF-8=0066) 01100110 -> 00001111 11110000 00001111 11110000
g (UTF-8= 0067) 01100111 -> 00001111 11110000 00001111 11111111
h (UTF-8=0068) 01101000 -> 00001111 11110000 11110000 00000000


As I already wrote we only need to send each Bit four times. I do not know if there is a possibility to do this.
If not, here is a code to transform the byte to four bytes:

// transform data to Display-data:
 
void Data_processing(uchar temp)  // turns 1byte B/W data to 4k-color data(RRRR-GGGG-BBBB)   
{unsigned char temp1,temp2,temp3,temp4,temp5,temp6,temp7,temp8;
unsigned char h11,h12,h13,h14,h15,h16,h17,h18,d1,d2,d3,d4;

                        temp1=temp&0x80;
                        temp2=(temp&0x40)>>3;
                        temp3=(temp&0x20)<<2;
                        temp4=(temp&0x10)>>1;
                        temp5=(temp&0x08)<<4;
                        temp6=(temp&0x04)<<1;
                        temp7=(temp&0x02)<<6;
                        temp8=(temp&0x01)<<3;
                        h11=temp1|temp1>>1|temp1>>2|temp1>>3;
                        h12=temp2|temp2>>1|temp2>>2|temp2>>3;
                        h13=temp3|temp3>>1|temp3>>2|temp3>>3;
                        h14=temp4|temp4>>1|temp4>>2|temp4>>3;
                        h15=temp5|temp5>>1|temp5>>2|temp5>>3;
                        h16=temp6|temp6>>1|temp6>>2|temp6>>3;
                        h17=temp7|temp7>>1|temp7>>2|temp7>>3;
                        h18=temp8|temp8>>1|temp8>>2|temp8>>3;
                        d1=h11|h12;
                        d2=h13|h14;
                        d3=h15|h16;
                        d4=h17|h18;

                        write_data(d1);
                        write_data(d2);
                        write_data(d3);
                        write_data(d4);
}

Furthermore i want to mention that I´ve also found the "upscale-process" for the UC1610 in the u8x8_8x8.c file but always failed with modification :(

So far I say big thanks again and hope that i was able to clear some uncertainties.
Wish a nice evening
mcarosh

**Comment by mcarosh** [comment]
Hi again :)
Just for update, I´m pretty sure I solved it in theory. But my bad skills in coding is the reason why I still need your help  :/ 
In short:

In UC1610 you expand the byte to 16bit by interleaving Bits. We only need to do this to 32Bits. Should be only one more step/line

As I wrote

a (UTF-8=0061) 01100001 -> 00001111 11110000 00000000 00001111

would be the solution,but 

a (UTF-8=0061) 01100001 -> 00000001 00010000 00000000 00000001

should also be working.

This might be  the reason why it is half working.
Tomorrow I will try some modification but there I think I will need your help.
But really, in theory this is the solution ;)
So far greez again
mcarosh

**Comment by AnHardt** [comment]
```cpp
uint32_t a(uint8_t b){
  uint32_t r = 0;
  for (uint8_t m = 1<<7; m; m >>= 1) {
    r <<= 4;
    if (m & b) r |= 0x0f;
  }
  return r;
}

uint32_t b(uint8_t i) {
  uint32_t r = 0;
  if (i & 0b10000000) r |= 0xf0000000;
  if (i & 0b01000000) r |= 0x0f000000;
  if (i & 0b00100000) r |= 0x00f00000;
  if (i & 0b00010000) r |= 0x000f0000;
  if (i & 0b00001000) r |= 0x0000f000;
  if (i & 0b00000100) r |= 0x00000f00;
  if (i & 0b00000010) r |= 0x000000f0;
  if (i & 0b00000001) r |= 0x0000000f;
  return r;
}
```

**Comment by AnHardt** [comment]
Or a mixture from a() and c()? 
'''cpp
void d(uint8_t i) {
  uint8_t m = 1<<7;
  do {
    uint8_t r = 0;
    if (m & i) r |= 0xf0;
    m >>= 1;
    if (m & i) r |= 0x0f;
    m >>= 1;
    Serial.print(r,DEC);
    Serial.print(",");
  } while(m);
}
```

**Comment by mcarosh** [comment]
thx for reply AnHardt
My problem is that I do not know the structure of U8g2. As I am modifying the UC1610 file I need to modify all files which are involved by the upscale process. I´ve already found parts in the u8x8_8x8.c file and u8x8.h file and tried to modify them. But it does not work :( 
I think the Interleaving-process is correct?!
Made changes from:

uint16_t u8x8_upscale_byte(uint8_t x) 
{
	uint16_t y = x;
	y |= (y << 4);		// x = (x | (x << S[2])) & B[2];
	y &= 0x0f0f;
	y |= (y << 2);		// x = (x | (x << S[1])) & B[1];
	y &= 0x3333;
	y |= (y << 1);		// x = (x | (x << S[0])) & B[0];
	y &= 0x5555;
  
	y |= (y << 1);		// z = x | (y << 1);
	return y;
}


to


uint32_t u8x8_upscale_byte(uint8_t x) 
{
	uint32_t y = x;
	y |= (y << 8);		// x = (x | (x << S[3])) & B[3];
	y &= 0x00ff00ff;
	y |= (y << 4);		// x = (x | (x << S[2])) & B[2];
	y &= 0x0f0f0f0f;
	y |= (y << 2);		// x = (x | (x << S[1])) & B[1];
	y &= 0x33333333;
	y |= (y << 1);		// x = (x | (x << S[0])) & B[0];
	y &= 0x55555555;
  
	y |= (y << 1);		// z = x | (y << 1);
	return y;
}

But this is not enough
I guess there also need to be some modification at the  u8x8_d_uc1610.c file itself
Maybe at this part:

static uint8_t *u8x8_convert_tile_for_uc1610(uint8_t *t)
{
  uint8_t i;
  uint16_t r;
  static uint8_t buf[16];
  uint8_t *pbuf = buf;

  for( i = 0; i < 8; i++ )
  {
    r = u8x8_upscale_byte(*t++);
    *pbuf++ = r & 255;
    r >>= 0;
    *pbuf++ = r;
  }
  return buf;
}

But everything I tried was without success

Maybe there is a documentation somewhere with further explanation of the u8g2 structure and their variables. Until now I´m a little bit stuck

**Comment by AnHardt** [comment]
I'd try:
```cpp
static uint8_t *u8x8_convert_tile_for_uc1610(uint8_t *t)
{
  uint8_t i;
  uint32_t r; // 32 bit type
  static uint8_t buf[32]; // double the buffer
  uint8_t *pbuf = buf;

  for( i = 0; i < 8; i++ )
  {
    r = u8x8_upscale_byte(*t++);
    // copy two more bytes
    *pbuf++ = r & 255;
    r >>= 8;
    *pbuf++ = r & 255;
    r >>= 8;
    //
    *pbuf++ = r & 255;
    r >>= 8;
    *pbuf++ = r;
  }
  return buf;
}
```
and In [case U8X8_MSG_DISPLAY_DRAW_TILE](https://github.com/olikraus/u8g2/blob/b4e5ca4dd7aa16f9d1faec45b92157a03de3e74d/csrc/u8x8_d_uc1610.c#L278)
```diff
- u8x8_cad_SendData(u8x8, 16, u8x8_convert_tile_for_uc1610(ptr));
+ u8x8_cad_SendData(u8x8, 32, u8x8_convert_tile_for_uc1610(ptr));
```
likely it needs more changes in `case U8X8_MSG_DISPLAY_DRAW_TILE:` to write the data to the correct address in the display.

**Comment by mcarosh** [comment]
Hi AnHardt
First thx for your support
Tried your suggestion but sadly this also does not work :(
Greez

**Comment by AnHardt** [comment]
What does 'does not work' mean? Symptoms?

**Comment by mcarosh** [comment]
Sorry :)
Okay first two pics are without any modification and the other two with modification, each in landscape and portrait:
![DSC_20200312_195300_820](https://user-images.githubusercontent.com/26525104/96749774-88d6cf00-13cb-11eb-9feb-0c410e045d8f.JPG)
![DSC_20200305_181700_657](https://user-images.githubusercontent.com/26525104/96749804-8ffddd00-13cb-11eb-99dc-1f53f82e2302.JPG)
![DSC_20201021_150953_536](https://user-images.githubusercontent.com/26525104/96749824-9724eb00-13cb-11eb-9a3a-ec6afc82affe.JPG)
![DSC_20201021_182147_134](https://user-images.githubusercontent.com/26525104/96749881-a9068e00-13cb-11eb-8664-67bbc71e8c12.JPG)

So I think the way is correct but I m pretty sure there is some modification missing because now in landscape "Hello World" is readable but in portrait not and offset is not working anymore???

**Comment by mcarosh** [comment]
Has anybody some hints left? After modifying hours of hours nearly every file without success I am really at the end :/

**Comment by olikraus** [comment]
Today I have implemented support for ST7528 controller. I think the situation is comparable: There is nobody whom you can ask, there is noone who could help. The only source is a datasheet which is soooo bad, that it is misleading at the best.
So at the end it did cost me 4 to 5 hours to understand the internal memory architecture of the ST7528: It is different to anything else what I saw so far with u8g2. I had to go down to the very beginning and write simple individual values into the controller RAM to see what effects those values have. Step by step I had to understand how bits are collected to form a brightness value for a pixel.

I am afraid there is noone who could help. Maybe only the developer of the controller would have an idea. :-(

Not sure if this helps: It took me several attempts over more than 1 year to add support for the ST75256.

And the UC1698... I have a display at my lab. But I never saw anyhing on it. Maybe its software, but I think I still have a wiring bug, It is indeed the only display, which is in my lab, which refused to work until now.  
Excause... probably not much of help from my end.

**Comment by olikraus** [comment]
One more thing: If I remember correctly, we would need to transfer 8 bits (or 16? or 24?) for one pixel, right? So the resulting speed would also be very bad.

**Comment by mcarosh** [comment]
Hi Olikraus
First thx for your reply

The UC1698 need 4bpp and the perfomance should be well enough. This I was told by the person who gave me the formula to expand the 8 Bits to 32 Bits. He uses a PIC-controller in SPI-mode and he said/wrote he has no performance issues. If you see my pictures I think the solution by interleaving bits will work. My actual problem is that it only works in x-direction. In y-direction it always double the size of the tile. Maybe you can give me a detailed documentation for your library. Because I really do not know which variable stands for :/
In theory the solution is really simple as I wrote 11 days ago. And now I only need the right "addressings" for the pixels.
Thx again for your support 
Regards
mcarosh

**Comment by mcarosh** [comment]
Still fighting to implement uc1698 :/ Is there any description how to implement new driver to U8G2-library. I would be very happy to get some help with this because in the end it should not be too difficult to add this display driver as it need just a 4bpp-command like any other 4 bit grey-scale display (such as the ssd1327). So if anybody has some hints let me know :) Meanwhile I will stay with the "try-and-error-method" :)
regards
mcarosh

**Comment by olikraus** [comment]
Each u8g2 driver is located in its own u8x8_d file (actually the driver is for u8x8, u8g2 is build on top of u8x8).
Let's use the ssd1329 as a reference:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_ssd1329.c

The implementation is done by providing a callback functions. this is here:
https://github.com/olikraus/u8g2/blob/1b656cbd5d61d5a907a0f9f32e3b48fd5e2fc3cf/csrc/u8x8_d_ssd1329.c#L288

Your new driver has to react to several messages, which are passed via the msg arguments.
Sometimes the msg contain extra data, which are passed as arg_int and/or arg_ptr.

One of the first messages is "U8X8_MSG_DISPLAY_SETUP_MEMORY". If this is received, then your driver has to do its memory setup. This is done here:
https://github.com/olikraus/u8g2/blob/1b656cbd5d61d5a907a0f9f32e3b48fd5e2fc3cf/csrc/u8x8_d_ssd1329.c#L290-L294

The setup is simplified and only requires a certain fixed data, which needs to provided by you. This data is here:
https://github.com/olikraus/u8g2/blob/1b656cbd5d61d5a907a0f9f32e3b48fd5e2fc3cf/csrc/u8x8_d_ssd1329.c#L264

In other words you can takeover the code for "U8X8_MSG_DISPLAY_SETUP_MEMORY" but you certainly need a different "display info" data.

If the user calls the .begin() statement, then your display should receive the init code. This happens here:
https://github.com/olikraus/u8g2/blob/1b656cbd5d61d5a907a0f9f32e3b48fd5e2fc3cf/csrc/u8x8_d_ssd1329.c#L173-L176

The third most important function is the drawing itself:
https://github.com/olikraus/u8g2/blob/1b656cbd5d61d5a907a0f9f32e3b48fd5e2fc3cf/csrc/u8x8_d_ssd1329.c#L203

"arg_int" is a repeat counter. This means, you need to repeat the pixel drawing that many times.
The draw/bitmap information is provided via "arg_ptr", which points to a u8x8_tile_t, a structure, which contains the details of the draw command.

The tile struct is defined here:
https://github.com/olikraus/u8g2/blob/1b656cbd5d61d5a907a0f9f32e3b48fd5e2fc3cf/csrc/u8x8.h#L212-L218

In total the draw command means: At tile position x,y draw the bitmap provided in "tile_ptr". The bitmap has a height of 8 pixel and a width of "cnt"*8 pixel.
There are actually two different bitmap formats, but the most common format is described here:
https://github.com/olikraus/u8g2/wiki/u8g2reference#memory-structure-for-controller-with-u8x8-support
So, "tile_ptr" will point to such a memory structure.

Everything in u8g2 will finally go via this function. All the magic and translation to your display has to happen here.

Once your u8x8_d...c function is finished you need to register your function here:
https://github.com/olikraus/u8g2/blob/master/tools/codebuild/codebuild.c

This step will define the memory architecture (one of two), define the name and connect your display to the communication interfaces. Recompilation and execution will then generate the constructors for u8g2 and u8x8.
I certainly can do this for you once your u8x8_d file is ready.

**Comment by mcarosh** [comment]
holy :) ...
Thanks for your fast response. Now i will try but I am pretty sure this will take some time until I get the whole thing into my head :) But really thanks again for your effort and i will (hopefully) report to you when it´s done
best regards

**Comment by olikraus** [comment]
closing this for now, feel free to reopen...

**Comment by olikraus** [comment]
Indeed I have one LCD with uc1698 in my lab... 
#2139

**Comment by mcarosh** [comment]
So this is still alive :) :) :)
Maybe this could be useful

https://github.com/henningmz/uc1698

In the end we will get it done ;)
best regards

**Comment by olikraus** [comment]
wow, nice. Could be a good template code for u8g2.
