### ISSUE TITLE
Navigate Menu with 4x4 Keypad

### ISSUE THREAD

**Issue by EmriBG13** [olikraus/u8g2#1316]
Hi, Wondered how can I control my U8g2 menu with a 4x4 keypad, couldn't figure out how to use with buttons, but since I already use a keypad in my project I thought it might be a good idea to use the keypad instead. (BTW I'm new here, but if you need any information let me know.)
U8G2_ST7920_128X64_1_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* CS=*/ 10, /* reset=*/ 8);

**Comment by olikraus** [comment]
U8g2 is not a user interface lib. I added button just because of some demo applications. Better use Arduino Menu (https://github.com/neu-rah/ArduinoMenu) or something similar.
