### ISSUE TITLE
SSD1306 128x64 X axis offset issue

### ISSUE THREAD

**Issue by rowellx68** [olikraus/u8g2#132]
Running the "HelloWorld" example results in the image below. Both OLED screens I have tried has this issue and this issue also occurs with u8glib.

Also, I'm using this constructor `U8G2_SSD1306_128X64_NONAME_1_SW_I2C u8g2(U8G2_R0, SCL, SDA, U8X8_PIN_NONE);`

![fullsizerender 5](https://cloud.githubusercontent.com/assets/10155704/21549766/6ada4fe6-cdec-11e6-9860-f2d3e4099571.jpg)

**Comment by olikraus** [comment]
This is a SH1106 device, i guess. Try the SH1106 constructor instead.

**Comment by rowellx68** [comment]
using the SH1106 constructor fixed the issue. Thank you!
