### ISSUE TITLE
ST7586s/ST7587 driver 160x120 resolution

### ISSUE THREAD

**Issue by mahmeh** [olikraus/u8g2#1337]
Hi, i have been looking at these displays, but was hesitant to buy before i know if they would be supported by u8g2

https://www.aliexpress.com/item/1867792466.html?spm=a2g0o.cart.0.0.9bbf3c00Lx7odF&mp=1
https://www.aliexpress.com/item/32622806995.html?spm=a2g0o.cart.0.0.9bbf3c00Lx7odF&mp=1

**Comment by olikraus** [comment]
Difficult, none of the displays is supported directly. The controller ST7586 is supported, so it may work with a little bit of code update.

**Comment by olikraus** [comment]
closing this for now...
