### ISSUE TITLE
Nodemcu and ST7920

### ISSUE THREAD

**Issue by marcoayamada** [olikraus/u8g2#1343]
Hi everyone!

I'm struggling with Nodemcu (esp8266) and ST7920 display. A simple clock test program doesn't works fine.

Some pixels in display are mess or/and weird characters are show:

![image](https://user-images.githubusercontent.com/21116298/99914301-37c43e80-2cdb-11eb-9883-f991d29ecac1.png)

My code:

```
#include <Arduino.h>
#include <U8g2lib.h>

U8G2_ST7920_128X64_F_SW_SPI u8g2(U8G2_R2, 14, 13, 15); 

void setup(void) {
  
  u8g2.begin(); 
}

uint8_t m = 24;

void loop(void) {
  char m_str[3];
  strcpy(m_str, u8x8_u8toa(m, 2));    /* convert m to a string with two digits */
  u8g2.firstPage();
  do {
    u8g2.setFont(u8g2_font_logisoso62_tn);
    u8g2.drawStr(0,63,"9");
    u8g2.drawStr(33,63,":");
    u8g2.drawStr(50,63,m_str);
  } while ( u8g2.nextPage() );
  delay(2000);
  m++;
  if ( m == 60 )
    m = 0;
}
```
My breadboard:

![image](https://user-images.githubusercontent.com/21116298/99914360-a6a19780-2cdb-11eb-9e66-c05143f317ba.png)

Could anyone help me with this?

**Comment by olikraus** [comment]
Looks like a timing or signal quality issue. In fact the ST7920 is the most sensitive display regarding this. You may also shorten your wires and/or use different holes in your protoboard.
You can also try to reduce the bus transfer speed with the SetBusClock command.

**Comment by olikraus** [comment]
any success?

**Comment by marcoayamada** [comment]
I didn't test modifying the circuit yet. But I set clock to a slow speed and the result was better. I think if I add a capacitor in a circuit this issue will be solved. I will try this week.

**Comment by Bruno999B** [comment]
I have the same problem with :
U8G2_ST7920_128X64_F_HW_SPI u8g2(U8G2_R2, D8);

but work perfectly with :
U8G2_ST7920_128X64_F_SW_SPI u8g2(U8G2_R2, 14, 13, 15, U8X8_PIN_NONE);

**Comment by Bruno999B** [comment]
Apparently the addition of a Sanyo 3300uf 6.3v capacitor on the esp8266's VIN solved the problem, works well in hardware SPI at 1mhz.

**Comment by olikraus** [comment]
hmmm, I guess it's time to close this issue...
