### ISSUE TITLE
SSD1322 256x64 : only 16 lines appear

### ISSUE THREAD

**Issue by beber00** [olikraus/u8g2#1348]
Hello,

Thanks a lot for your lib ! (already used on other screens).

I tried to used it on a new chinese OLED 256x64 SSD1322 but It's impossible to see more than 16 lines

I put it on a 4wire SPI 
I enable the 16 BIT mode (by uncomment the _#define U8G2_16BIT_ line)

I've done lots of tests 
- modifying display start line
- modifying  multiplex ratio

but always 16 lines ! :-(

Have you got an idea where I can check ? I'm lost :-(

**Comment by olikraus** [comment]
maybe you have used the wrong constructor or didn't use the page loop for the _1_ or _2_ constructor.
