### ISSUE TITLE
SH1106 display area is 2 pixels off the actual screen area

### ISSUE THREAD

**Issue by ValChinnici** [olikraus/u8g2#1349]
I have a 1.3" Oled display, and I am trying to test it with an Arduino Uno.

The library works, as I am able to display the examples included in it... I have selected the line below (SPI) 

`U8G2_SH1106_128X64_NONAME_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);`

However I realised the display area has shifted 2 pixels on the left. It happens to be a very common issue people have been experiencing with this screen, but I haven't find a solution for it yet. I have tried many examples and looked for solutions online, nothing seems to work. Below a picture of the oled screen with the highlighted area that has shifted. 

![photo_2020-12-01_14-23-25](https://user-images.githubusercontent.com/7326814/100746282-cd995100-33e0-11eb-9129-204689bd5439.jpg)

**Comment by olikraus** [comment]
Will the ssd1306 driver work?

**Comment by VKin-Arduino** [comment]
> Will the ssd1306 driver work?

I tried, if I use that driver the oled doesn't light up :(

**Comment by olikraus** [comment]
hmm, the ssd1306 should work.

You could try to set the x offset to 0:
https://github.com/olikraus/u8g2/blob/1b656cbd5d61d5a907a0f9f32e3b48fd5e2fc3cf/csrc/u8x8_d_ssd1306_128x64_noname.c#L394-L395
However, this is the main difference between sh1106 and ssd1306
