### ISSUE TITLE
Epson E-1330BA LCD Screen

### ISSUE THREAD

**Issue by amd989** [olikraus/u8g2#1350]
Hi, 

I came across this large LCD board with ID PJUP397ZB, it's being driven by an Epson E-1330BA, I can only assume this chip is analog to a SED1330FBA or similar, as the pins connected to the main connector follow the same pattern as the [SED1330F datasheet](https://www.lcd-module.de/eng/pdf/zubehoer/sed1330.pdf) pinout. There is almost no information I could find about this LCD online. It came from an old [KX-WL50 ](http://salestores.com/panasonickxw.html) word processor. And is apparently 80 chars by 14 lines if that ad is to be believed. The LCD works fine inside of this machine.

Anyways, I'm having trouble getting it to work, after finding all it's relevant pins, it seems to show some signs of life, but I can't get anything to show up other than some intermittent lines. 

The board seems to be hardwired for 6800. as SEL1 and SEL2 are connected to VCC and GND respectively matching this table:
![image](https://user-images.githubusercontent.com/1676879/100769237-c1ee6000-33c9-11eb-896b-23f514f5cef0.png)

Here's what I did, voltages were taken while the LCD before pulled out of the machine.

| Arduino | Connection  | Voltages in Machine| Voltages in Arduino |
|---------|-------------|------------|-----------------------|
| 0-7     | d0-d7       |  1-3v       | 0-0.3v |
| 8       | Enable      | 0v    | 0-0.5v (oscillating) |
| 9       | Chip Select | 4v | 0-4v  (oscillating) |
| 10      | A0 / DC       | 2.5 v |  0.2v  |
| 11      | Reset       | 5v |  4.2v
| GND     | R/W         | 5v * | ?? |

*While the docs say this pin is supposed to be GND, I find it to be `5v` while the LCD is operational inside the machine.

Having flashed the HelloWorld example. After connecting power I see some lines in the screen (some lines may be faulty), then it gets cleared (by the reset sequence, I suppose) then nothing.

I have used the following constructors
`U8G2_SED1330_240X128_2_6800`
`U8G2_RA8835_320X240_1_6800`
`U8G2_RA8835_NHD_240X128_1_6800`

I have turned on/off 16 bit mode but seemingly makes no difference.

At this point, I'm not entirely sure if this is a new type of display. Or I'm wiring it wrong. 

There is only one extra pin in the connector that's left. But is not connected to the 1330BA but is rather connected to the "**DF**" pin in all the "80-DOT LCD segment drivers" MSM5298A and MSM5299A in the board.

Which is described as

> **DF**
> Synchronous signal input pin for alternate signal for LCD driving.
> 

And follows this table according to the datasheet
![image](https://user-images.githubusercontent.com/1676879/100770885-c287f600-33cb-11eb-92a6-99d7c3cb9ea5.png)

Connecting this Pin to GND or otherwise touching it, makes some faint but visible lines to appear in the screen. 

I'm using Arduino UNO.

~~The contrast potentiometer is weird as in it seems to have its own ground (separate from GND everywhere else). Measuring pins 1 and 3 labeled "volume" below will give you `5v` but measuring pin 3 and GND will give you `-15v`. the word processor voltage is `12v`. ( I'm thinking I might need a negative voltage source for the contrast)~~ I applied -12v and got a better view at the pixels in the screen. I will have to work on a negative voltage circuit for this.

Any help would be appreciated.
Thanks!

![image](https://user-images.githubusercontent.com/1676879/100786637-6c717d80-33e0-11eb-9709-a7754a696d9d.jpeg)
![image](https://user-images.githubusercontent.com/1676879/100786646-70050480-33e0-11eb-81da-305fb086f042.jpeg)

**Comment by amd989** [comment]
If I leave it on for a while it eventually flashes into this

![image](https://user-images.githubusercontent.com/1676879/100796499-c11bf500-33ee-11eb-9f04-d8a4c5975f25.jpeg)

**Comment by olikraus** [comment]
I think you already tested the correct constructors. I can not say much about wiring. 
One more thing to consider is the LCD voltage: It is either a negative or positive voltage maybe of -15 or 15V. If this voltage is not generated internally, then it needs to be provided via one of the pins. Did you measure this voltage somewhere? If this voltage is not available, then nothing will be visible.
