### ISSUE TITLE
Support for SSD1805

### ISSUE THREAD

**Issue by mohammad0663** [olikraus/u8g2#1352]
Hello .
Please add ssd1805 driver to library if possible.
I have a spi 128 64 display and I need support in your library.

**Comment by olikraus** [comment]
From a quick look into the datasheet it looks like that the SSD1805 is compatible with the ST7565 or the UC1701. Can you test those constructors with your display?

**Comment by mohammad0663** [comment]
hi olikraus.
I used ST7565_EA_DOGM128.
I had problems with the show. I activated the screen by rotating the screen and making simple changes.
Thankful .

**Comment by olikraus** [comment]
Is this problem solved, then?

**Comment by mohammad0663** [comment]
YES .

**Comment by olikraus** [comment]
Great 😃

Todo @olikraus : add the ssd1805 to the command list.
