### ISSUE TITLE
Ability to automatically format long text to multiple lines

### ISSUE THREAD

**Issue by 343434** [olikraus/u8g2#1355]
Hi,

I am using SH1106 i2c display `U8G2_SH1106_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);`. I have a variable length message coming in from MQTT. Is it possible to automatically format and display the text broken down into multiple lines and filling up the screen? Right now it is overlapping itself on line 1.

Do I have to manually implement this? When I try to get character width using `u8g2.getMaxCharWidth();`, it tells me that my constructor doesnt have this method... How would I go about doing this?

Thanks

**Comment by olikraus** [comment]
`u8g2.getMaxCharWidth()` is implemented here:
https://raw.githubusercontent.com/olikraus/u8g2/master/cppsrc/U8g2lib.h

> Do I have to manually implement this?

Basically yes, but maybe u8log will fit: https://github.com/olikraus/u8g2/wiki/u8logreference
