### ISSUE TITLE
Change I²C Address of 1.3 inch 128x64 OLED

### ISSUE THREAD

**Issue by e-labInnovations** [olikraus/u8g2#1359]
I have a [128×64 1.3 inch I²C OLED display](https://m.alibaba.com/product/60501952008/module-128x64-1-3inch-oled-lcd.html). I want change the I²C address of the corresponding display. Please help me.
Last week a changed SSD1306 128×64 0.96 inch I²C display I²C address by changing the piston of the resistor. 

Back side of the 1.3 inch display
![](https://i.imgur.com/lNxEC8U.jpg)

**Comment by olikraus** [comment]
Difficult if such change is not foreseen by the PCB itself. I will close this issue, I doubt that this can be answered here.
