### ISSUE TITLE
Display with SED1520 is not working

### ISSUE THREAD

**Issue by JeanNorsk** [olikraus/u8g2#1365]
Hi

I'm using the Arduino uno with the IDE version 1.8.42.0. I have a Display called "jd12232A3" with a SED1520 as LCD Controller. The GLCD is from a disassambeled product. I want to use this GLCD for a Project and for this I want to write a simple test code.
`#include <U8g2lib.h>
#include <U8x8lib.h>
#include <SPI.h>

U8G2_SED1520_122X32_2 u8g2(U8G2_R0,12,13,2,3,4,5,6,7,11,10,9,8);

void setup() 
{
  u8g2.begin();
}

void loop(void) 
{
  u8g2.setFont(u8g2_font_ncenB14_tr);
  u8g2.drawStr(0,20,"Hello World!");
  
  delay(1000);
}`
But after programming, the Display displays absolutely nothing. 

![IMG_20201223_185826](https://user-images.githubusercontent.com/76532518/103024885-fd0b2b80-4550-11eb-8cee-fdf2ac173cd3.jpg)

I made the connection like it's written in the setup for the display together with the "datasheet" i found.
Does anyone have a idea what the problem could be?

**Comment by olikraus** [comment]
At least the send buffer command is missing. Better use one of the existing examples.
