### ISSUE TITLE
Three screens with the same address using TCA9548 multiplexer

### ISSUE THREAD

**Issue by panakos** [olikraus/u8g2#1370]
Hi, I am trying to use 3 oled screens in my project all with address 0x3c 

I am running two 0.91" 128x32  using :

U8G2_SSD1306_128X32_UNIVISION_F_HW_I2C display1(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);  // Adafruit ESP8266/32u4/ARM Boards + FeatherWing OLED

I use one instance for both screens and I switch between them using the TCA9548, no problem with them 

My 3rd screen is an 1.3" 128x64 using  :

U8G2_SSD1306_128X64_NONAME_F_SW_I2C display2(U8G2_R0, /* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE);   // All Boards without Reset of the Display

as soon as I begin display2 , none of the screens are working. 

any Idea?

`
#include <Arduino.h>
#include <U8g2lib.h>
#define TCAADDR 0x70
#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif

U8G2_SSD1306_128X32_UNIVISION_F_HW_I2C display1(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);  // Adafruit ESP8266/32u4/ARM Boards + FeatherWing OLED
U8G2_SSD1306_128X64_NONAME_F_SW_I2C display2(U8G2_R0, /* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE);   // All Boards without Reset of the Display
// End of constructor list

void setup(void) {
   tcaselect(2);
   delay(100);  
  display1.begin();
  
   tcaselect(6);
   delay(100);  
 display2.begin();
}

void loop(void) {
   tcaselect(2);
  display1.clearBuffer();          // clear the internal memory
  display1.setFont(u8g2_font_ncenB18_tr); // choose a suitable font
 display1.drawStr(90,30,"Hello"); // write something to the internal memory
  display1.setCursor(10,30);
  display1.setFont(u8g2_font_fub25_tn); // choose a suitable font
  display1.print(345);
  display1.sendBuffer();
  delay(1000);  
 tcaselect(6);
  display2.clearBuffer();					// clear the internal memory
  display2.setFont(u8g2_font_ncenB18_tr);	// choose a suitable font
  display2.drawStr(0,30,"Hello");	// write something to the internal memory
  display2.setCursor(0,60);
  display2.print("Bandit");
  display2.sendBuffer();					// transfer internal memory to the display
  delay(1000);  
}
  void tcaselect(uint8_t port) {
  if (port > 7) return;
  Wire.beginTransmission(TCAADDR);
  Wire.write(1 << port);
  Wire.endTransmission();  
}
`

**Comment by olikraus** [comment]
You can not mix HW and SW I2C on the same pins.
