### ISSUE TITLE
SSD1315 Support request

### ISSUE THREAD

**Issue by Directlaww** [olikraus/u8g2#1376]
Hello! 

Is there any chance to get a support of the 128x64 display working with driver "SSD1315" (https://de.aliexpress.com/item/32639731302.html) 

kind regards from Germany

**Comment by olikraus** [comment]
Not confirmed, but what I heard is this: The SSD1315 is compatible with the SSD1306, so the SSD1306 driver should work.

**Comment by Directlaww** [comment]
My display was simply broken at the lower part of the glass. So I ordered a real SSD1306 display and it worked perfectly. 

Nevertheless, thanks for your quick answer!
