### ISSUE TITLE
ESP-IDF with Arduino as Core not building in Platform IO because of missing Macro

### ISSUE THREAD

**Issue by DanteNahuel** [olikraus/u8g2#1385]
Hi all,
I was trying to use this library in an esp-idf framework based project with Arduino as Core using Platformio IDE.
I found that I couldn't make it work because the Constructor Class definitions weren't defined.
I asked in PlatformIO about it and I got some help ([Link](https://community.platformio.org/t/add-arduino-library-to-esp-idf-with-arduino-core-as-component/18562))
As you can see there, it seems the Classes are not getting defined unless U8X8_USE_PINS is defined in a macro
and U8X8_USE_PINS is only defined if there's a macro defining ARDUINO.

My main question with this is why having an empty Macro definition for U8X8_USE_PINS is required for defining all the u8g2 Classes?
I can bypass this by using build flags in PlatformIO, but I want to understand what's going on under the hood

**Comment by olikraus** [comment]
U8g2 / U8x8 classes are wrapper around a pure c library. 
This pure c library is almost hardware independent, except the pin mapping for the Arduino environment. 
So I added U8X8_USE_PINS in cases where the pure c library is compiled in Arduino environment to tell the underling C lib, that there should be an array for the pin mapping.
