### ISSUE TITLE
scrolling the display_OLED ssd1322

### ISSUE THREAD

**Issue by Milad-cyber** [olikraus/u8g2#1389]
Hello olikraus,
First of all thank you for the drivers. 
I didn't find the display scroll function, can you help me how can I add scroll functions?
Best regards 
Milad,

**Comment by olikraus** [comment]
What kind of scrolling do you mean? Display Hardware scrolling or software scrolling?

Software Scrolling:
This is done by redrawing all or parts of the screen at a different x,y position.
Vertical scrolling is demonstrated in the Shen Nong example by using a pixel delta which is constantly increased:
https://github.com/olikraus/u8g2/blob/3c6460a73f7f310c665cef0af1d2bac49bf6c655/sys/arduino/u8g2_page_buffer/Shennong/Shennong.ino#L504

Hardware Scrolling:
This is very display specific and is not supported as such, however you can send the corresponding commands to the display with the sendF command. Here is an example for the SSD1306:
https://github.com/olikraus/u8g2/blob/3c6460a73f7f310c665cef0af1d2bac49bf6c655/sys/arduino/u8g2_page_buffer/HardwareScroll/HardwareScroll.ino#L341
Obviously you have to study the display datasheet to figure out the specific command sequence for your display.
