### ISSUE TITLE
Variable font size with one font.

### ISSUE THREAD

**Issue by skaman82** [olikraus/u8g2#1397]
Hi, and thanks for your hard work on this. I am wondering is it possible to add a function to enlarge fonts like in the adafruit GFX library? I know it is possible in u8x8 already (at least to display double the size) but it is not possible in the main library as far I am seeing it. It would save a some space to be able to use just one font in different sizes. Also small fonts have, if there are enlarged, a classy vintage look as well. :)

**Comment by olikraus** [comment]
Very difficult, because the glyphs are compressed and do not contain a fixed line wrap marker to repeat the same line multiple times. Double width chars might be possible.

But effort might be use and the extra code required might be more than a bigger font would require.
