### ISSUE TITLE
add st7628  or any colored nokia lcd support?

### ISSUE THREAD

**Issue by soheils2** [olikraus/u8g2#140]
hey 
i just working with my new project and i want to know if u can add this lcd to your library?

**Comment by soheils2** [comment]
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwijtvzRsKbRAhVIKywKHdEABgoQFggZMAA&url=https%3A%2F%2Fgithub.com%2Fkr4fty%2FST7628-Nokia-1600-LCD-Library&usg=AFQjCNHFi6qBK2pXeVUMIhh1MH-3gLs3kg&sig2=rGqEtjWhmr9TFZQIlDhPMA&bvm=bv.142059868,d.bGg

**Comment by olikraus** [comment]
u8g2 is a library for monochrome displays.

**Comment by soheils2** [comment]
okay but why? in last version there is some color lcds in supported devices

https://www.youtube.com/watch?v=PyO0zI5jXAc

![image](https://cloud.githubusercontent.com/assets/22795891/21620679/bf549cd0-d20a-11e6-8ac8-be36a8bfe0d1.png)

this is what i writing with your library and some other libs ; for now i used monochrome  lcd that will be awesome if u can add colored lcds to the lib again...

**Comment by olikraus** [comment]
Nice work.

For color lcds/oleds: i have split the code into ucglib (color) and u8g2 (monochrome).
However: I can not add a new device without having it physically on my desk.

**Comment by Blue-Marlin** [comment]
There is a fundamental difference between:
* Colour displays - where you can set any pixels colour at your will
* Coloured displays - like in the picture above - where some pixels (upper quarter?) have an other colour than the others.
