### ISSUE TITLE
Other atmega MCU

### ISSUE THREAD

**Issue by Abu100135** [olikraus/u8g2#1407]
Hello
I want to thank you for all your effort and libraries. I have tried your example code in avr https://github.com/olikraus/u8g2/blob/master/sys/avr/avr-libc/atmega328p-hw-i2c/main.c
it works fine with atmega 328. But if i want to use other MCU like Atmega128 how can i use different defines for pins from your defines in https://github.com/olikraus/u8g2/blob/master/csrc/u8x8.h.
Second Parts how to change all pins such as 
#define U8X8_PIN_D0 0      to  #define U8X8_PIN_D0 PINA0
for Parallel devices.
Thanks .

**Comment by olikraus** [comment]
The mentioned code had been contributed and I can not say anything on this code.

I personally had created the instructions from here:
https://github.com/olikraus/u8g2/wiki/u8g2as7
Within that page there is a reference to an example code, which could be modified to you needs:
https://github.com/olikraus/u8g2/blob/master/sys/avr/as7/main.c

The u8x8 definitions starting from here:
https://github.com/olikraus/u8g2/blob/3c6460a73f7f310c665cef0af1d2bac49bf6c655/csrc/u8x8.h#L288
must not be changed.
