### ISSUE TITLE
add thickness to drawline

### ISSUE THREAD

**Issue by soheils2** [olikraus/u8g2#141]
in feature versions u can add thickness to the lines  
OR 
add angle into the darwbox(); void  

for now i draw thicker lines by drawing lots of lines together and change the xy , it can be a built-in "void" for thicker lines

PS; sorry about my bad english  grammer :("

**Comment by olikraus** [comment]
Either adding thickness or adding angle into drawbox() will make the library very large. Also algorithms are very complicated.
I suggest to use drawTriangle() 
At least adding two triangles would make up one "Quadrilateral" 
You could also do the required math for the "rotated box" by yourself and use drawTriangle.

Conclusion: 
1. Lines with thickness and rotated boxes is very complicated. At least i will not add this, but i would be happy to accept any pull requests.
2. I think the problem can be solved by using drawTriangle with some additional math operations.

**Comment by drfailov** [comment]
To achieve thickness effect I made this calculations to triangulate desired form by 2 triangles. My tests showed than there's no gap between triangles.
Hust replace `lcd()->` by your u8g2 call.


```
void drawThickLine(float centerX, float centerY, float toX, float toY, float thickness){ 
  float dx = toX-centerX;
  float dy = toY-centerY;
  float d = sqrt(dx*dx+dy*dy);
  float ux = dx/d;
  float uy = dy/d;
  float mux = ux*thickness;
  float muy = uy*thickness;
  float rx1 = muy;   //https://limnu.com/sketch-easy-90-degree-rotate-vectors/
  float ry1 = -mux;
  float rx2 = -muy;
  float ry2 = mux;

  float x0 = centerX+rx1;
  float y0 = centerY+ry1;
  float x1 = centerX+rx2;
  float y1 = centerY+ry2;
  float x2 = toX+rx1;
  float y2 = toY+ry1;
  float x3 = toX+rx2;
  float y3 = toY+ry2;
  lcd()->drawTriangle(/*x0*/x0, /*y0*/y0, /*x1*/x1, /*y1*/y1, /*x2*/x2, /*y2*/y2);
  lcd()->drawTriangle(/*x0*/x1, /*y0*/y1, /*x1*/x3, /*y1*/y3, /*x2*/x2, /*y2*/y2);
}
```

**Comment by JanHBade** [comment]
Draw Line with Thickness can made with: https://de.wikipedia.org/wiki/Bresenham-Algorithmus
(KI made that for me)

```
#define _swap_int(a, b) \
    {                   \
        int32_t t = a;      \
        a = b;          \
        b = t;          \
    }

void drawLineWidth(int32_t x0, int32_t y0, int32_t x1, int32_t y1, int32_t width)
{
    int32_t steep = abs(y1 - y0) > abs(x1 - x0);
    if (steep)
    {
        _swap_int(x0, y0);
        _swap_int(x1, y1);
    }

    if (x0 > x1)
    {
        _swap_int(x0, x1);
        _swap_int(y0, y1);
    }

    int32_t dx, dy;
    dx = x1 - x0;
    dy = abs(y1 - y0);

    int32_t err = dx / 2;
    int32_t ystep;

    if (y0 < y1)
    {
        ystep = 1;
    }
    else
    {
        ystep = -1;
    }

    for (; x0 <= x1; x0++)
    {
        for (int32_t w = -width / 2; w <= width / 2; w++)
        {
            if (steep)
            {
                u8g2.drawPixel(y0 + w, x0);
            }
            else
            {
                u8g2.drawPixel(x0, y0 + w);
            }
        }
        err -= dy;
        if (err < 0)
        {
            y0 += ystep;
            err += dx;
        }
    }
}
```

**Comment by olikraus** [comment]
thanks for sharing
