### ISSUE TITLE
U8g2 raspberry pi, files to compile

### ISSUE THREAD

**Issue by spi5498** [olikraus/u8g2#1423]
Hello,

I have successfully compiled and run the C-version of the library on my Raspberry PI.
Works great, i am using it without Wiring PI.

However, I compile it with gcc *.c and that results in over 20mb of binary.

Currently not using any IDE.

My experience with compiling with this kind of library as you understand is very limited.

Is there like a flowchart of what files to compile / link or any other trick? I have seen another project like this with a build script, that is also producing very large binarys so that does not seem to work either.

My guess is now that i compile support for every LCD, every font etc.

If it helps, i am using the ST756s ERC240160

Any pointers here would be greatly appreciated.

**Comment by olikraus** [comment]
To reduce the executable size, you need to activate the linker garbage collection with your gcc toolchain.
Your gcc requires the following additional options:
```-ffunction-sections -fdata-sections -Wl,--gc-sections```

The first two options are for the c compiler the last options enables the linkre garbage collection.
