### ISSUE TITLE
u8g2.setPowerSave(1) or u8g2.clear()

### ISSUE THREAD

**Issue by droidprova** [olikraus/u8g2#1443]
Hi, I'm using your library to drive an oled SSD1309 with ESP8266. This is the constructor I use:

**U8G2_SSD1309_128X64_NONAME0_F_HW_I2C u8g2(U8G2_R0, U8X8_PIN_NONE, D1, D2);  // (oled DIYMORE SSD1309 2.42" I2C)**

I would like to ask you, to turn off the oled when I do not need it, to preserve its integrity and brightness over time, it is better to use this:

**u8g2.setPowerSave(1);**

or this:

**u8g2.clear();**

In general, what are the differences and any complications that the 2 methods have?

Thanks so much

**Comment by olikraus** [comment]
You can combine both methods.
clear() will clear the pixel, 
setPowerSave(1) will try to shut down the display charge pump. As a consequence setPowerSave(0) will require some time, because the charge pump has to be reactivated.
