### ISSUE TITLE
LCD DEM 128064Q FGH-PW Pin Connection

### ISSUE THREAD

**Issue by folny** [olikraus/u8g2#1454]
Hi

Please can someone tell me which pins I should use to connect this display with the UC1601 driver to work properly with the u8g2 library on STM32 and the connection using SPI thank you for the advice.

https://www.tme.eu/Document/59369f5729330dfc5cc7350507d991b2/DEM128064QFGH-PW-dte.pdf

**Comment by witc** [comment]
it looks like only I2C is possible

**Comment by folny** [comment]
According to these instructions, it should also work via SPI.

https://www.programmersought.com/article/31073708858/

**Comment by olikraus** [comment]
I think 8 bit SPI should bo no problem.
