### ISSUE TITLE
Garbled upper portion of display

### ISSUE THREAD

**Issue by mirozmrzli** [olikraus/u8g2#1462]
Hello all!

I am using this library on ESP32 and one of these cheap [displays](https://www.amazon.com/gp/product/B07X378P8X/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1). When the spi clock speed is 50khz, everything looks good, albeit slow. When I raise the spi clock even to 100khz, i get this:

![IMG_20210415_192958](https://user-images.githubusercontent.com/6167059/114963466-af793e00-9e21-11eb-80c2-39228fb26f2f.jpg)

    initArduino();
    SPI.begin(5, -1, 18, 4);
    U8G2_ST7920_128X64_F_HW_SPI u8g2(U8G2_R0, 4, U8X8_PIN_NONE);
    u8g2.setBusClock(100000);
    u8g2.begin();
    ...
    ...
    u8g2.clearDisplay();
    u8g2.clearBuffer();
    u8g2.setFont(u8g2_font_ncenB08_tr);
    u8g2.drawStr(0,50,"Hello World!");
    u8g2.sendBuffer();

Any ideas what's going on?

cheers,
Miro

**Comment by olikraus** [comment]
The ST7920 is very sensitive with respect to timing :-(
There is nothing much would you can do, but sometimes it helps to solder all wires and keep them as short as possible.
