### ISSUE TITLE
Question: unifont larger size, scaling?

### ISSUE THREAD

**Issue by tablatronix** [olikraus/u8g2#1463]
I hate asking a question in issues, but how can we have a larger unifont ? Is there any way to scale , I see 8x8 has a 2x glyph method..

What about just a larger unifont, what would it take to make, is there an original source and convert it ?

**Comment by olikraus** [comment]
Unifont is a pure Bitmap font. Scaling is not possible. The 2x2 functions could be applied, but they just duplicate pixel.

**Comment by tablatronix** [comment]
I think I will just find out how to recreate a few more sizes of unifont, find out where it came from etc

a pixel doubling ug82 method would be handy for bitmap font though I think also.
