### ISSUE TITLE
Pixel scaling

### ISSUE THREAD

**Issue by AntoRoni** [olikraus/u8g2#1469]
I am making a code that draws pixels on the ST7920 display, and I was wondering if there is any way to scale these pixels, for example, the following code prints a small "H" on the screen, is there any way to make it bigger without having to go writing pixel by pixel in hand?

```
void loop()
{
  u8g2.firstPage();
  do 
  {
    u8g2.setDrawColor(2);
    for (int c = 1; c < 7; c++)
    {
      u8g2.drawPixel(1, c);
      u8g2.drawPixel(2, c);
      u8g2.drawPixel(5, c);
      u8g2.drawPixel(6, c);
    }
    u8g2.drawPixel(3, 3);
    u8g2.drawPixel(3, 4);
    u8g2.drawPixel(4, 3);
    u8g2.drawPixel(4, 4);
  } while( u8g2.nextPage());  
  while(1);
}
```

**Comment by olikraus** [comment]
You could use drawBox instead

**Comment by AntoRoni** [comment]
Thanks I already solved the problem using drawLines, with a scale algorithm
