### ISSUE TITLE
U8G2_16BIT and compiler settings

### ISSUE THREAD

**Issue by antiprism** [olikraus/u8g2#1472]
Building on Ubuntu, the check for whether to define U8G2_16BIT is failing if a C++ language standard is set, because 'unix' isn't defined. See: https://stackoverflow.com/questions/57304931/unix-c-preprocessor-macro-is-undefined-with-std-c11

check_unix.cpp:
```
#include "./u8g2.h"
#include <stdio.h>

int main(int argc, char *argv[])
{
#ifdef unix
  printf("unix       defined\n");
#else
  printf("unix       not defined\n");
#endif

#ifdef __unix__
  printf("__unix__   defined\n");
#else
  printf("__unix__   not defined\n");
#endif

#ifdef U8G2_16BIT
  printf("UG82_16BIT defined\n");
#else
  printf("UG82_16BIT not defined\n");
#endif

  return 0;
}
```

Then (on Ubuntu)
```
$ g++ check_unix.cpp -o check_unix && ./check_unix
unix       defined
__unix__   defined
UG82_16BIT defined

$ g++ --std=c++11 check_unix.cpp -o check_unix && ./check_unix
unix       not defined
__unix__   defined
UG82_16BIT not defined
```

This was causing causing an issue for me as I built the U8g2 code as a library without a standard set, but my program code was built with a standard set, and the result was that I was unable to use "negative" coordinates as a start position for drawing text.

Adrian.

**Comment by olikraus** [comment]
Yes, thanks, for the feedback, see also #1405
