### ISSUE TITLE
HW SPI and Full Frame Buffer 

### ISSUE THREAD

**Issue by loschwa** [olikraus/u8g2#1475]
I am using u8g2 in the following configuration:

- full frame buffer mode with HW-SPI 
- ESP32 MCU and an EPSON S1D15721 display controller 
- I2C RTC using wire.h

After starting the MCU it reboots about every 100 ms with a flickering display.

The Arduino program:

int n;
U8G2_S1D15721_240X64_F_4W_HW_SPI u8g2(U8G2_R0, cs, dc, res); //full framebuffer, size = 2080 bytes
void setup(void) {
  Wire.begin();
  Serial.begin(115200);
  u8g2.begin();
  u8g2.setFont(u8g2_font_ncenB14_tr);
}

void loop(void) {
  u8g2.firstPage();
  do {
    u8g2.drawStr(0,20,"Loop:");
    u8g2.setCursor(60, 20);
    u8g2.print(String(n));
    u8g2.setCursor(0, 50);
    u8g2.print(PCF_getRTC());   // RTC access via HW-I2C
  } while ( u8g2.nextPage() );
  
  n++;
  Serial.println(n); 
  delay(1000);  
}

The Serial Monitor output:

4:50:59.379 -> ets Jun  8 2016 00:22:57
14:50:59.379 -> 
14:50:59.379 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
14:50:59.379 -> configsip: 0, SPIWP:0xee
14:50:59.379 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
14:50:59.379 -> mode:DIO, clock div:1
14:50:59.379 -> load:0x3fff0018,len:4
14:50:59.379 -> load:0x3fff001c,len:1044
14:50:59.379 -> load:0x40078000,len:8896
14:50:59.379 -> load:0x40080400,len:5816
14:50:59.379 -> entry 0x400806ac
14:50:59.544 -> 
14:50:59.544 -> Stack smashing protect failure!
14:50:59.544 -> 
14:50:59.544 -> abort() was called at PC 0x400d70ec on core 1
14:50:59.544 -> 
14:50:59.544 -> Backtrace: 0x4008c228:0x3ffb1ec0 0x4008c455:0x3ffb1ee0 0x400d70ec:0x3ffb1f00 0x400d0f7b:0x3ffb1f20 0x400d0ff3:0x3ffb1f80 0x400d3c19:0x3ffb1fb0 0x400889d9:0x3ffb1fd0
14:50:59.544 -> 

The logic Analyser output of the SPI-bus shows that after an initial data burst SCLK and MOSI are not controlled anymore:

![Full](https://user-images.githubusercontent.com/8566341/116563089-ff690200-a903-11eb-82c8-fe79b6a8769f.png)

When configuring to Buffer Size 1 (or 2) the MCU is not crashing but the display shows in addition to the expected text some pattern which seems to be depending on the text content (i.e. it changes with every display update).

![buffer_size_1](https://user-images.githubusercontent.com/8566341/116563447-52db5000-a904-11eb-9432-e4456d9b34d8.jpg)

When using SW-SPI and full frame buffer mode the MCU crashes also immediately after start. 

However, if the I2C RTC is not accessed (but keeping the wire.begin() in setup)  the program runs normal independent of HW or SW-SPI usage.

Any idea what is going wrong? Thanks for looking into this.

**Comment by loschwa** [comment]
Further tests show that if using a different constructor i.e. "U8G2_ST7565_64128N_1_4W_HW_SPI u8g2(U8G2_R0, cs, dc, res)" the SPI transfer continues without problem after the display init sequence. My assumption now is that the problem is related to the fact that the EPSON Controllers require during the init sequence commands with **two** arguments. All other controllers for which I checked the configuration files (e.g. u8x8_d_st7565.c), don't use commands with two arguments.

The funny thing is that u8g2 works in the SW-SPI configuration. The sequence:

// Sends Commands (3 Byte).
static void _lcd_cmd3(uint8_t cmd, uint8_t arg1, uint8_t arg2) {
  digitalWrite(PIN_CS,LOW);
  digitalWrite(PIN_A0,LOW);
  SPI.transfer(cmd);
  digitalWrite(PIN_A0,HIGH);
  SPI.transfer(arg1);
  SPI.transfer(arg2);
  digitalWrite(PIN_CS,HIGH);
}

should be the same, whether it is transfered by bit-banging or SPI HW.

**Comment by loschwa** [comment]
In contrast to what I had assumed initially, further tests have shown that the problem is not related to the utilisation of the HW-SPI but rather to the complexity of the called function and the fact that the function is placed as angument to the 'u8g2.print' statement or not. If a String variable holds the result of a function then 'u8g2.print(stringvariable);' works apparently without problem. However, if the function is placed as an argument to the print-statement then artifacts appear on the display. The Heap and Stack sizes seem not to be related to the problem since they are ~370k and ~6.8k respectively.

Above has been tested with Buffer Size 1 or 2. Full frame buffer mode only works, if no external function calls are made. For instance calling 'ESP.getFreeHeap()' or just 'Serial.print' crashes the MCU right after booting.

I realise that the problem I am experiencing is possibly related to the HW configuration I am using (ESP32 and EPSON S1D15721).

**Comment by olikraus** [comment]
Hmmm... Ok....
