### ISSUE TITLE
SSD1306 Menu using u8g2 Library

### ISSUE THREAD

**Issue by chandanchan0086** [olikraus/u8g2#1487]
Hi everyone,
I would like to create a little menu with this library. I did not found an example to do that soo can you please help me out with this?

I'm using ESP-32 Board and ESP-IDF Framework.

Is this possible to do the menu and selection from u8g2 library for ESP-IDF? How?

**Comment by olikraus** [comment]
Maybe this project is useful: https://github.com/neu-rah/ArduinoMenu
