### ISSUE TITLE
UC1601 128x64 Library

### ISSUE THREAD

**Issue by uuygun** [olikraus/u8g2#1488]
Hello, there are UC1601 128x32 codes in the library, but I am using UC1601 128x64 and there are no codes for this. And these codes are not working for my screen. What can I do about it?

**Comment by olikraus** [comment]
The UC1601 is almost compatible with many other controllers, especially the ST7565. 

https://github.com/olikraus/u8g2/blob/master/doc/controller_cmds.txt

My suggestion is to test the constructors with the ST7565 128x64 controller.

**Comment by olikraus** [comment]
Did you add the required 1uF caps for the charge pump? They should be as close as possible to the flex cable connector.

**Comment by uuygun** [comment]
Yes, i added the capacitor pretty close.

**Comment by olikraus** [comment]
Maybe you could still check with some other constructors.
