### ISSUE TITLE
Blank screen on RA8835 320x240 protocol 6800.

### ISSUE THREAD

**Issue by Finside** [olikraus/u8g2#1489]
I would really appreciate any help with RA8835 320x240 display with 8 bit parallel interface.  
I connect it to Arduino Mega 2560.

U8G2_16BIT uncommented and checked.

Installation:
1. Arduino IDE 1.8.12 from ZIP manually unpacked into new folder.
2. Into Arduino/libraries manually added folder with U8Glib2.

Didn't noticed this RA8835 chip and didn't check if it works with U8Glib2. Now my Boss will kill all 3 of us because of this display! Any help is highly appreciated.

The only working setup is
U8G2_RA8835_NHD_240X128_1_6800
but on 320x240 it works incorrectly.

Now we are trying to analyze both
U8G2_RA8835_320X240_1_6800
and
U8G2_RA8835_NHD_240X128_1_6800
to find differences and fix the problem.

![IMG-11dbd2f608a3c0bf0c7b724a641d4fe7-V](https://user-images.githubusercontent.com/13101372/117510288-7a7d8880-af94-11eb-90ea-17f45e3adbd1.jpg)

**Comment by olikraus** [comment]
Did you enable 16 bit mode for u8g2? See FAQ.

**Comment by olikraus** [comment]
Which constructor is visible on your picture? Is this the U8G2_RA8835_320X240_1_6800?

**Comment by ichetiva** [comment]
> I would really appreciate any help with RA8835 320x240 display with 8 bit parallel interface. I connect it to Arduino Mega 2560.
> 
> U8G2_16BIT uncommented and checked.
> 
> Installation:
> 
> 1. Arduino IDE 1.8.12 from ZIP manually unpacked into new folder.
> 2. Into Arduino/libraries manually added folder with U8Glib2.
> 
> Didn't noticed this RA8835 chip and didn't check if it works with U8Glib2. Now my Boss will kill all 3 of us because of this display! Any help is highly appreciated.
> 
> The only working setup is U8G2_RA8835_NHD_240X128_1_6800 but on 320x240 it works incorrectly.
> 
> Now we are trying to analyze both U8G2_RA8835_320X240_1_6800 and U8G2_RA8835_NHD_240X128_1_6800 to find differences and fix the problem.
> 
> ![IMG-11dbd2f608a3c0bf0c7b724a641d4fe7-V](https://user-images.githubusercontent.com/13101372/117510288-7a7d8880-af94-11eb-90ea-17f45e3adbd1.jpg)

Did you manage to display at least something on this screen?

**Comment by Finside** [comment]
Did you manage to display at least something on this screen?
//
Sorry, I haven't for the question. As you can see, there is some text on the screen.

**Comment by ichetiva** [comment]
> Did you manage to display at least something on this screen? // Sorry, I haven't for the question. As you can see, there is some text on the screen.

In image display 320x240?

**Comment by Finside** [comment]
Yes, 320x240 works fine, but very slow (2.8 sec) on Arduino Mega 2560 with 8 bit parallel interface.

![Uploading IMG_20211225_204748.jpg…]()

**Comment by Finside** [comment]
Image 
![IMG_20211225_204748](https://user-images.githubusercontent.com/13101372/147391695-b9ff881e-1c99-405f-a653-6608feaa0b38.jpg)

**Comment by Finside** [comment]
![vlad_480p](https://user-images.githubusercontent.com/13101372/147392028-8f483aad-8455-4260-a9d6-05090cf3b235.gif)
25 FPS 480p Video to .GIF

**Comment by ichetiva** [comment]
> ![vlad_480p](https://user-images.githubusercontent.com/13101372/147392028-8f483aad-8455-4260-a9d6-05090cf3b235.gif) 25 FPS 480p Video to .GIF

А Вы не знаете что делать если текст выводится зеркально?

**Comment by Finside** [comment]
- What to do if text is mirrored?

- I think we need to compare:
1. All connection lines Microcontroller -> Display
2. Display controller RA8835 
3. Library sttings (pins).

It is not possible to answer why text is mirrored without any additional info.

**Comment by ichetiva** [comment]
https://user-images.githubusercontent.com/81914195/147498471-47893670-740f-407f-b9df-d4d168a2583c.MOV

Watch this video, here is the example of "PrintUTF8"

**Comment by ichetiva** [comment]
What do you think is the matter?

**Comment by olikraus** [comment]
hmm no further feedback, closing...
