### ISSUE TITLE
SSD1306 128x64 I2C display offset

### ISSUE THREAD

**Issue by ros87** [olikraus/u8g2#149]
Arduino UNO with a noname ssd1306 128x64 I2C running the u8x8 helloworld example sketch.

U8X8_SSD1306_128X64_NONAME_SW_I2C u8x8(/* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE);

Display is offset -2 pixels to the left.

Any way to change the offset?

![dsc_0493-edited](https://cloud.githubusercontent.com/assets/24966194/21733119/16a21a68-d45d-11e6-8bc8-807a52ad73f3.jpg)

**Comment by olikraus** [comment]
This is a SH1106 OLED... Hmm.. I should add this to my FAQ list.

**Comment by ros87** [comment]
Ooh, if so I'm sorry. Seller listed it as SSD1306. I'll change the config and retry tomorrow.

**Comment by olikraus** [comment]
I have updated my draft version of the FAQ:
https://github.com/olikraus/u8g2/blob/master/doc/faq.txt

Let me know whether the SH1106 constructor works.

**Comment by ros87** [comment]
Ok thank you.

I see no SH1106 I2C constructor in the library (2.10.1)

**Comment by ros87** [comment]
Sorry, found it and tried:

U8X8_SH1106_128X64_NONAME_SW_I2C u8x8(2,0,U8X8_PIN_NONE);

No display at all.

**Comment by olikraus** [comment]
What about this?
U8X8_SH1106_128X64_NONAME_SW_I2C u8x8(/* clock=/ SCL, / data=/ SDA, / reset=*/ U8X8_PIN_NONE);

**Comment by ros87** [comment]
![dsc_0502](https://cloud.githubusercontent.com/assets/24966194/21745603/e8acecb8-d52f-11e6-9c5a-791f421b60c3.JPG)

**Comment by olikraus** [comment]
Thanks for the feedback :-)

**Comment by omegalotti** [comment]
for the record, I may also have the same oled 128x64 screen. Because mine also has VCC first, GND as the second in.
My version worked flawlessly with this one:
U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);

I also have a 128x32 display but the pin layout is GND+VCC+SCL+SDA 
It worked with U8G2_SSD1306_128X32_UNIVISION_F_HW_I2C u8g2(U8G2_R0);

Thank you Oli for such a great library and faq!

**Comment by olikraus** [comment]
:-)

**Comment by bjornstevens** [comment]
> 
> 
> What about this?
> I mean, in the original constructor, just replace SSD1306 with SH1106

This fixed it all for me!

**Comment by Icyrockton** [comment]
very useful 
**U8G2_SSD1306_128X64_NONAME_F_SW_I2C**

**U8G2_SH1106_128X64_NONAME_F_SW_I2C**
