### ISSUE TITLE
LCD Dot matrix with Toshiba T7932 and T7933 / HD44102

### ISSUE THREAD

**Issue by spi5498** [olikraus/u8g2#1492]
Hi!

I have this really nice LCD module that i pulled out of a old POS-terminal.
Could not find much on that particular module, however the controller consists of 3x T7932 chips, and one T7933 chip.
I take a shot in the dark and hope that this may be some "standard" already compatible with another driver?

What do you think? Datasheets: [https://www.alldatasheet.com/datasheet-pdf/pdf/31153/TOSHIBA/T7932.html](7932) & [https://pdf1.alldatasheet.com/datasheet-pdf/view/31154/TOSHIBA/T7933.html](7933)

Also, if you have a teory that it might be compatible with some other library, i will be happy to test it out

**Comment by spi5498** [comment]
Also, if you have a hunch that it could be compatible with something, ill happely try it and report back

**Comment by spi5498** [comment]
Hello again,

I found this: https://forum.arduino.cc/t/openglcd-hd44102-to-t7932/413755 
So it seems that would be a good starting point, does U8g2 have a driver for HD44102 or equivalent?

**Comment by olikraus** [comment]
Hmmm... never heard about hd44102 LCD. It is not supported :-(

**Comment by olikraus** [comment]
I will try to buy and add support for such a display with HD44102, but it might take 2-3 months (such displays are not easy to get...)

**Comment by spi5498** [comment]
That's great!
However, this week i will receive a FPC adapter for my module T7932/T7933. 
I'm no LCD-expert, but with a little assistance I will be more than happy to try and help out. 
Do you have any hunch on if there is a "base" module that might be good to use that is in the library right now when looking at the datasheet?

**Comment by olikraus** [comment]
Maybe the ks0108 could be a starting point.

**Comment by spi5498** [comment]
Thank you!

Will give that a shot when I get my adapter and report back!

**Comment by olikraus** [comment]
Some progress here. I might get a LM324 display with the HD44102 controller.

**Comment by spi5498** [comment]
Hi Oli!
Thank you very much for this update. 
In the last days I have received my FPC-adapterboard, that will make it possible to hook everything up to a breadboard without modifying anything. I will be happy to help with any sort of debugging that might be needed. Just let me know.

Will be documenting the pinout for this LCD also to aid anyone else that might stumble on them. They are very nice

**Comment by olikraus** [comment]
Great. It will probably take some more days until I receive the display itself.

**Comment by olikraus** [comment]
I recently got access to the display. After wiring with my Arduino it seems to work. U8g2 software development not yet started, I just wanted to see whether the adapter board works.

![IMG_20210725_203344588](https://user-images.githubusercontent.com/1084992/126909687-d32cf050-cfaf-4b67-a334-65d3c4cf0d37.jpg)

**Comment by spi5498** [comment]
Hello,

Thank you for your update! This is exciting

I have just traced my pinout for mine. Think i have them all, though, i have for some reason 3 NCs. These is the signal pins i was able to find:

VDD
VSS
E (/WR)
R/W (/RD)
D/I (Not sure how that one is handled)
DB0-7
CS 1-3
RST

Seems like the backlight on this one is permanently hooked to the supply.

Do you have any baseplate code that might give me some initial life from this one?

**Comment by olikraus** [comment]
This is the connection table for my current test setup. "D/I" is important and will be controlled by u8g2. Same is true for "E". "R/W" must be connected to GND permanently because U8g2 will only write but never read from the display. "Vee" must be a negative voltage (around -4..-5V). I have just used 4x AA cells to generate the negative voltage.

| Disp. Pin | Disp. Fn. | Arduino Pin | Wire Color  |
|---|---|---|---|
| 1 | GND | GND | black |
| 2 | +5V | +5V | red |
| 3 | Vee | VarPot | - |
| 4 | n.c. | - | - |
| 5 | n.c. | - | - |
| 6 | A (chip select) | A0 | purple |
| 7 | B (chip select) | A1 | purple |
| 8 | C (chip select) | A2 | purple |
| 9 | n.c. | - | - |
| 10 | E (write pulse) | 2 | yellow |
| 11 | R/W (read/write mode) | GND (12) | - |
| 12 | D/I (data/cmd mode) | 3 | green |
| 13 | DB0  | 4 | white |
| 14 | DB1  | 5 | brown |
| 15 | DB2  | 6 | white |
| 16 | DB3  | 7 | brown |
| 17 | DB4  | 8 | white |
| 18 | DB5  | 9 | brown |
| 19 | DB6  | 10 | white |
| 20 | DB7  | 11 | brown |

**Comment by olikraus** [comment]
![IMG_20210730_194809856](https://user-images.githubusercontent.com/1084992/127692617-629c44cb-2ea9-45e9-8aa4-82612ca16192.jpg)

My own display is actually not a real graphics display, it trippls every 8th row and inserts an empty column every 7th column

**Comment by olikraus** [comment]
Another example. U8g2 seems to work so far...

![1000592](https://user-images.githubusercontent.com/1084992/127713142-f7d747b3-1e51-4770-86d6-11ae1db19076.jpg)

**Comment by olikraus** [comment]
@spi5498 : I have created a new beta release 2.29.9. This release includes the constructor U8G2_T7932_150X32_1 in all of the example. Can you test this with your display? Will something be visible?

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by spi5498** [comment]
Wow, this is pretty exciting! I will try this out during the weekend and report back to you!

I see that my LCD module have a LMC7660 that is probably used to generate the VEE so thats why i couldnt find that when tracing the pinout.

**Comment by spi5498** [comment]
Hello!

Did hook up the LCD today.
Unfortunately  no luck with that.

I did confirm the connections once and they were correct from what I can find. Will need to confirm the pinout once more I guess!

not sure if there could be a tweak in the code necessary? There were no life at all

**Comment by olikraus** [comment]
Maybe you can share some more details (pictures, wiring, etc) so that I can also crosscheck your setup.

**Comment by spi5498** [comment]
I do have it soldered up on a prototype shield for the uno, so not sure how visible that will be.
However, i wonder since i have RST pin on my module, if that needs to be handled in the code?

**Comment by spi5498** [comment]
![9DA95752-6C25-4E31-8781-F3A88FC5A65C](https://user-images.githubusercontent.com/60155713/127905547-7e8f9bfb-0bf2-4ad1-af22-b45832507cc7.jpeg)

woho!

After some trial I found that RST needs to be set to high after power on, then it works!

just did it with a jumper wire manually, so need to add this to the code :)

this is very cool! Thank you so much for looking in to this!

**Comment by spi5498** [comment]
![Uploading 88A78FF7-CB6B-4C33-B7EC-B0046A828FD9.jpeg…]()

**Comment by spi5498** [comment]
![Uploading C9EBBF1B-12EE-48C2-99B3-195739B8CCC7.jpeg…]()

**Comment by spi5498** [comment]
![479ED93A-F160-40ED-BC0B-4DD2D5571623](https://user-images.githubusercontent.com/60155713/127906256-46935346-91e6-4738-b5fa-c22d954a1ef3.jpeg)

**Comment by olikraus** [comment]
Wow, looks great. 
Reset pin: You can connect the reset input of your display to any unused GPIO pin. Then pass the number of that GPIO pin as last argument to the u8g2 constructor.

**Comment by spi5498** [comment]
Yeah it is really nice! 
Great to see it alive.

Aha! So reset is already implemented in the code for this? Cool!

will also count all the available pixels(width and height) impossible without turning them on.
Haha!
