### ISSUE TITLE
ssd1305 support ZJY223S0700BG03

### ISSUE THREAD

**Issue by Sofronio** [olikraus/u8g2#1496]
I used "U8G2_SSD1305_128X32_NONAME_1_4W_SW_SPI" on HellowWorld, and this happened.
![zjy ssd1305](https://user-images.githubusercontent.com/11464550/118754175-14004080-b899-11eb-8813-0cd58f76beae.png)
Datasheet is here.
[ZJY223S0700BG03.pdf](https://github.com/olikraus/u8g2/files/6505729/ZJY223S0700BG03.pdf)
This manufactory is called ZJY.

Thank you.

**Comment by cranefist** [comment]
Isn't that just mirrored? Have you tried using U8G2_MIRROR ?

**Comment by olikraus** [comment]
After u8g2.begin() please insert the command `u8g2.sendF("c", 0xa0);`.
How will the image change with this?

**Comment by Sofronio** [comment]
It changed to this. Seems the text was compressed at least by half in height.
![test](https://user-images.githubusercontent.com/11464550/127410433-91e0022f-4b24-4601-a8dc-701902d06270.jpg)

**Comment by olikraus** [comment]
Did you also try the SSD1305_128X32_ADAFRUIT constructor?
