### ISSUE TITLE
Feature request, mcp230x pin extender as input

### ISSUE THREAD

**Issue by nordur** [olikraus/u8g2#150]
Hi, sorry if this is the wrong way (cant find another), but here´s a feature request:

MCP23xx pin extenders come in i2c and SPI variety and there seems to be just a little bit extra code needed to use a i2c pin extender as input for the display library, specifically the buttons for menu control.

for example:
`
u8x8.begin(/*Select=*/ mcp1.7, /*Right/Next=*/ mcp1.2, /*Left/Prev=*/ mcp1.1, /*Up=*/ mcp1.3, /*Down=*/ mcp1.4, /*Home/Cancel=*/ mcp1.6); 
`
and:
`
mcp1 = 0x21 // selectable address suffix 1(0-7), ic adress prefix 0x2(fixed)
`
for the front end, i2c bus comms are already builtin and one would need only a handful of registries to configure & read the i2c device responding to the configurable address and use the mcp23x-pins instead of arduino hardware pins.

I would also like to thank you for the awesome graphics library that im currently using (and trying to learn how to use)!
Great work!

**Comment by olikraus** [comment]
The menu procedures a just a little addon. No doubt there are many more input methods possible, so i think it does not make sense to add something specific here. You should better use a menu library.
