### ISSUE TITLE
U8G2 SlectionList questions

### ISSUE THREAD

**Issue by dreep** [olikraus/u8g2#152]
Hello,

Can we use SelectionList example with joystick&clic shield like [http://henrysbench.capnfatz.com/henrys-bench/arduino-sensors-and-input/arduino-ps2-joystick-tutorial-keyes-ky-023-deek-robot/](url) ?

When i try, i just go down and clic...
`u8g2.begin(/*Select= pin of switch button on joyctick shield*/ 38, /*Right/Next=*/ A1, /*Left/Prev=*/ A1, /*Up=*/ A3, /*Down= VRY*/ A0, /*Home/Cancel=*/ 8); // Arduboy 10 (Production)`
<img  src="https://i2.wp.com/henrysbench.capnfatz.com/wp-content/uploads/2015/09/Arduino-PS2-Joystick-Output-Orientation.png" border="0" alt="Image hébergée par servimg.com" />
X axe is on A1 pin
Y axe is on A0 pin
switch is on pin 38

And eventually, can we add title that can be update in then menu.
For example :
`char timetest = "00d00 00:00:00";
const char *string_list = 
  timetest  
  "Altocumulus\n"
  "Altostratus\n"
  "Cirrocumulus\n"
  "Cirrostratus\n"
  "Cirrus\n"
  "Cumulonimbus\n"
  "Cumulus\n"
  "Nimbostratus\n"
  "Stratocumulus\n"
  "Stratus";`
Where timetest is a variable we can update ?
Or perhaps, define manually the number of line to show on the screen... (if my screen can draw 5 rows + title, i could choose to draw only 4 raows + title and use the end of the screen for something else)...

So, this function will be update and optimize or will evolve ?
Thx a lot

**Comment by olikraus** [comment]
Hi
I added the selection list and other menu option just as a simple example. I think it should be a user task to add suitable user controll input methods. In fact it will beyond the scope of u8g2 to implement menu system. Goal is to support monochrome displays.
So please treat the selection list as an example. Of course you can reuse the code, etc.

**Comment by dreep** [comment]
ok, thx, for answer !!!
questions close !

**Comment by olikraus** [comment]
I think this is very similar to the issue #150. It would make up a complete new library to support all kind of input methods.
