### ISSUE TITLE
KS0108 Parallel 8080 communication pins

### ISSUE THREAD

**Issue by shriphoenix** [olikraus/u8g2#1528]
Hi,
I want to use KS0108 display in Arduino environment and ESP32 board for development.
Do we need D0 to D7 pins in sequence or D0 to D3 in sequence and D4 to D7 another sequence or D0 to D7 no sequence at all..

Please clarify my doubt..

Regards,

Shri

**Comment by olikraus** [comment]
Sequence does not at all. You can specify each individual pin.

**Comment by shriphoenix** [comment]
oh ok, gr8.. so I can use any pins then.. 
It will be helpful now, I can use it in my design since i do not have more than 3 pins in sequence, used by other circuitry...

Thanks a lot...
