### ISSUE TITLE
Any way of programmatically get u8g2.print(float variable) width for moving cursor?

### ISSUE THREAD

**Issue by DanteNahuel** [olikraus/u8g2#1534]
Hi
I'm currently using print to print some float variables, and I want to set the cursor automatically to the next coordinate by calculating the width of the float. However, getStrWidth of course only works for strings.
Is there any way to do this?

**Comment by olikraus** [comment]
Not sure what is available on Arduino, but usually there should be ways to convert a float to a string. In many cases this can be done with sprintf, dtostrf or gcvt. Then use this string to calculate the width and also to print the value.

**Comment by DanteNahuel** [comment]
Thank you!
