### ISSUE TITLE
Add feature getStrWidth() to U8G2_SSD1306_128X64_NONAME_F_HW_I2C

### ISSUE THREAD

**Issue by johnsmakar** [olikraus/u8g2#1535]
I was trying to use getStrWidth, but get...

`no matching function for call to 'U8G2_SSD1306_128X64_NONAME_F_HW_I2C::getStrWidth(String)'`

Can you add this feature?

**Comment by olikraus** [comment]
It is implemented:
https://raw.githubusercontent.com/olikraus/u8g2/master/cppsrc/U8g2lib.h

and described here:
https://github.com/olikraus/u8g2/wiki/u8g2reference#getstrwidth

**Comment by johnsmakar** [comment]
How come I get a no matching function error?

Note: I am using a Espressif Pico-D4

**Comment by olikraus** [comment]
Hmmm... I nither know your code nor do I know your environment. Do you use Arduino IDE?

**Comment by johnsmakar** [comment]
I am using the ArduinoIDE.

Is there an incorrect implementation code of code that would result with that error? Thanks in advance

**Comment by olikraus** [comment]
I am not aware of any issue here.

**Comment by olikraus** [comment]
Oh I just see, that you tried to pass a "String" object. You have to pass "string.c_str()" instead.
