### ISSUE TITLE
init sequence for st7586s displays missing U8X8_END_TRANSFER()

### ISSUE THREAD

**Issue by Plek324** [olikraus/u8g2#1538]
Hi,

I tried this library to connect the ERC240160 to an ESP32. This didn't work at first. After some digging around I found out that in the init sequence (u8x8_d_st7586s_erc240160_init_seq in u8x8_d_st7586s_erc240160.c) had an U8X8_END_TRANSFER() at the start, rather than at the end. The same seems to be true for the other st7586s based displays

Putting the U8X8_END_TRANSFER() at the end of the sequence worked for me.

**Comment by olikraus** [comment]
Strange. Thanks a lot for the feedback (actually this code was contributed, but I wonder how it ever could work).
I have fixed the init sequence but kept the initial CS change (not sure why the developer had added this).
