### ISSUE TITLE
请问有raspberrypi可以直接用的u8g2库！？

### ISSUE THREAD

**Issue by sorrya0** [olikraus/u8g2#1539]
你好
我是刚接触树莓派的初学者
想在python里调用u8g2
可以给个链接么！？

**Comment by wuhanstudio** [comment]
Hi,

The port for raspberry-pi and general arm-linux are available here:

https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#raspberry-pi

BTW, a kind suggestion, it's better to use English here if your are looking for help.

--------

你好，

在这里可以找到 raspberry-pi 和通用 arm-linux 的移植，不过似乎没有 python 支持。

顺便一提，如果是寻求帮助建议用英文，毕竟 github 开发者来自全球各地。
