### ISSUE TITLE
ST7920 shows garbage @ 20MHz

### ISSUE THREAD

**Issue by trashmaster9000** [olikraus/u8g2#156]
hi,

in my current project i use an ATMega328 standalone at 20MHz.
for easier programming i have the same Display connectetd to a Arduino nano.

on the Arduino nano my program works fine but on the ATmega it shows strange lines and dots.

a other programm (written with u8glib) works fine at 20Mhz.

The display is connected via SW SPI, on both controllers on the same pins.

![wp_20170114_17_11_41_pro](https://cloud.githubusercontent.com/assets/14186848/21956266/2b225bd0-da7d-11e6-8f81-7691c48898e1.jpg)

**Comment by olikraus** [comment]
Which constructor is this?

**Comment by trashmaster9000** [comment]
U8G2_ST7920_128X64_F_SW_SPI u8g(U8G2_R1, 6, 7, 8);

**Comment by olikraus** [comment]
I have slowed down speed a little bit.
Please download U8g2 from here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Install via Arduino IDE, Add lib zip file...

**Comment by trashmaster9000** [comment]
ok, it works now.
thanks ;)

**Comment by olikraus** [comment]
wow, fast response. thanks
