### ISSUE TITLE
Support for SSD1320_160x80

### ISSUE THREAD

**Issue by iggymayer** [olikraus/u8g2#1569]
Please support for SSD1320 160x80
PDF:https://mega.nz/file/VAtiGBhI#JzYLR97n2rpp0cLoAW398qBpbWTBK4IFhidjCue_bdw

Thank you!

**Comment by olikraus** [comment]
closed? So nothing is required here, right?

Reference: https://github.com/olikraus/u8g2/issues/1351

**Comment by iggymayer** [comment]
Sorry，I modified the design

**Comment by AristotleJunior** [comment]
I also need this support, I got the same screen, plz help me.
