### ISSUE TITLE
adding fonts to 8X8 font list?

### ISSUE THREAD

**Issue by mrbbp** [olikraus/u8g2#157]
Hello,

i would like to convert/add new font to 8X8 lib with fullset char. (lot are serif and old school)
Is there a tool to do that?

regards

**Comment by olikraus** [comment]
Yes, the tool is bdfconv:
https://github.com/olikraus/u8g2/tree/master/tools/font/bdfconv
You have to compile this on a linux machine. It will read the  myfont.bdf file and generate the internal format.
commandline option should be:
bdfconf -f 2 -b 3 -m '32-255>32 -n myfont -o myfont.c myfont.bdf
