### ISSUE TITLE
Add st7920 256x32 display support

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#1593]
https://github.com/olikraus/u8g2/pull/1545

**Comment by olikraus** [comment]
@shlyakpavel I have created beta release 2.32.2.

Maybe you can check the 256x32 constructor once...

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by shlyakpavel** [comment]
> You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip

Fine. I'll do it ASAP (most likely today)
Thanks a lot for your work!

**Comment by shlyakpavel** [comment]
Test done, everything works as expected
Thanks a lot!

**Comment by olikraus** [comment]
Thanks for the feedback

**Comment by olikraus** [comment]
pr closed, so i will also close this issue.
