### ISSUE TITLE
displayRotation

### ISSUE THREAD

**Issue by Warrior95** [olikraus/u8g2#1605]
Can you tell me what command i have to give to rotate nokia 5110 display 90
I am not able to understand how to use cmd setDisplayRotation

**Comment by olikraus** [comment]
Oh, maybe I missed this. 
As mentioned in the manual https://github.com/olikraus/u8g2/wiki/u8g2reference#setdisplayrotation , 
you have to use `u8g2.setDisplayRotation(U8G2_R1)`
