### ISSUE TITLE
New Battery Icon set 24x20px

### ISSUE THREAD

**Issue by pike2k** [olikraus/u8g2#1616]
![battery24_2](https://user-images.githubusercontent.com/471737/136170480-99670440-a073-4fb8-8e3b-8dd3d19433a0.png)

[Battery24.zip](https://github.com/olikraus/u8g2/files/7293973/Battery24.zip)

Do what you want with it :) The reason I made it was because I found many battery icon sets, but they were all payware. 
This set is all made from scratch, no copyright.

Content starts at 48, same as other Battery, but goes on until 7x something

**Comment by pike2k** [comment]
![243789711_2723143414654741_5064490940055491_n](https://user-images.githubusercontent.com/471737/136174131-62270493-ee7c-4f72-8be5-630d416722cf.jpg)

**Comment by olikraus** [comment]
Very nice picture. Cool design.

**Comment by pike2k** [comment]
> 
> 
> Created overview picture:
> 
> ![battery24](https://user-images.githubusercontent.com/1084992/136245812-3e9f5330-3f35-4efb-891a-c7d43c816d00.png)
> 
> Thanks for the donation. I will add this to the u8g2 fonts (https://github.com/olikraus/u8g2/wiki/fntgrpu8g).

Awesome, I was looking how to generate this overview but I have not yet learnt how to do it...

**Comment by olikraus** [comment]
closing this for now...
