### ISSUE TITLE
Storing charset in eeprom conected to i2c

### ISSUE THREAD

**Issue by pompetardo** [olikraus/u8g2#1623]
Hi, I'm learning to use this library, is there a way to store the charsets in an EEPROM to free program memory space? I'm using an RTC with I2C and as it also comes with the EEPROM with enough space. I think it can be done but I'm not sure if it's implemented or there is a timing restriction.
Thanks.

**Comment by olikraus** [comment]
There had been discussions on that already. But it is not possible with the current u8g2 core library.
