### ISSUE TITLE
SSD1306 + STM32F103 Alignment issue

### ISSUE THREAD

**Issue by ciko2k** [olikraus/u8g2#1625]
Hi,
i have an alignment issue. i use SSD1306 ,STM32F103, Rogerclark CORE. all welded and the OLED used with UNO and other library works.

connected to HW SPI it doesn'y work.  via SW SPI like under:
U8G2_SSD1306_128X64_NONAME_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ PA5, /* data=*/ PA7, /* cs=*/ PB15, /* dc=*/ PB13, /* reset=*/ PB12);
it works like in picture

Please help me..
thanks a lot

![PIC](https://user-images.githubusercontent.com/64307948/136684668-fbaf14df-f215-445d-a194-6ea9da262d22.jpeg)

**Comment by olikraus** [comment]
This is probably not a ssd1306, but instead a sh1106 display.
