### ISSUE TITLE
U8g2 custom Font 

### ISSUE THREAD

**Issue by ciko2k** [olikraus/u8g2#1627]
Hi, i would to ask, how i can do a custom U8g2 Font, from a bitmap?
thanks  a lot

**Comment by olikraus** [comment]
You could draw XBM bitmaps directly (no need to create a font). Use "gimp" to convert the picture into xbm format.
If you still need to convert bitmaps to font: I once created a tool which creates a bdf file from one or more png files:

https://github.com/olikraus/u8g2/blob/cd911cc8316c7e8d2ba50ba3229f5a1671955bbf/tools/font/png2bdf/png2bdf.c#L290-L298
