### ISSUE TITLE
320x240 LCD having controller RA8835A(controller equivalent to SED1335)

### ISSUE THREAD

**Issue by jhankhanagit** [olikraus/u8g2#1628]
Dear Sir,
I am working with 320x240 LCD having controller RA8835A(according to J68 Short: 6800 Family) interfaced with ATmega128A. _t's working ook with by default font but not able to use different fonts and images.
I am not able to understand how I can use the u8g2 library for the same. it would be a great help if you can guide me regarding the same.

Thanks in advance.

**Comment by jhankhanagit** [comment]
No, I saw that but...
I am using ATmega128 but IAR embedded workbench IDE and I was not able to understand How I can use the u8g2 library and that's why I am asking for help

**Comment by olikraus** [comment]
U8g2 is an Arduino lib. It will work out of the box for Arduino and Arduino is also the only supported Environment by me.
However there is a porting guide: https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform

Especially there is a section of AVR: https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#atmel-avr

There are also two video tutorials which might help here.

In your case only the gpio+delay callback (https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#the-uc-specific-gpio-and-delay-callback) will be needed.

Then use the u8x8_byte_8bit_8080mode communication callback together with your gpio+delay callback:

``` C
u8g2_t u8g2; // a structure which will contain all the data for one display
...
u8g2_Setup_ra8835_320x240_1(&u8g2, U8G2_R0, u8x8_byte_8bit_8080mode, my_u8x8_gpio_and_delay_cb);  // init u8g2 structure
u8g2_InitDisplay(&u8g2); // send init sequence to the display, display is in sleep mode after this,
u8g2_SetPowerSave(&u8g2, 0); // wake up display
```

**Comment by olikraus** [comment]
I am confused: `u8x8_byte_arduino_hw_spi` is not required in your case:
 * It is an Arduino specific function which will only work inside Arduino Environment
 * It is the byte level protocol for hardware SPI interface. According to your initial post you have an 6800 or 8080 interface, so you need `u8x8_byte_8bit_6800mode` or `u8x8_byte_8bit_8080mode` (here: https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#communication-callback-eg-u8x8_byte_hw_i2c)

Details on the arguments are also described here: https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform

I strongly recommend to read https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform
