### ISSUE TITLE
Swedish characters on a i2c OLED display 0.96 inch 128x64

### ISSUE THREAD

**Issue by ThomasVal** [olikraus/u8g2#1634]
I try to show Swedish characters like åäö ÅÄÖ on a i2c OLED display 0.96 inch, 128x64

I use  U8g2lib.h
U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);

I try different fonts and have no success. 

I use exempel u8g2 full_buffer and sketch Hello world.ino

Can you help me to solve my problem?

Best regards
Thomas Valstedt

**Comment by olikraus** [comment]
Swedish chars are part of the the "xxx_tf" fonts ("f" at the end):
![grafik](https://user-images.githubusercontent.com/1084992/137503437-83830bb5-377f-4949-a352-8219e91487f4.png)

Remember to use https://github.com/olikraus/u8g2/wiki/u8g2reference#enableutf8print and or https://github.com/olikraus/u8g2/wiki/u8g2reference#drawutf8

**Comment by ThomasVal** [comment]
Thank you olikraus!
Thank you for th quick answer.
Now it works fine

Best Regards
