### ISSUE TITLE
Aliexpress / Adafruit SSD1327 128x128 1.5" I2C OLED Support

### ISSUE THREAD

**Issue by cranefist** [olikraus/u8g2#1635]
I bought this OLED from Aliexpress : 

![image](https://user-images.githubusercontent.com/35430692/137536280-20d3b5aa-7a24-455c-adf6-2ee0e743774c.png)
https://www.aliexpress.com/item/1005002023675304.html

Seems its not yet supported by your library, i tested the two I2C SSD1327 128x128 constructors that were already in the library, neither worked.

But the Adafruit SSD1327 library works, all i needed to do is change the I2C address on it to 0x3C. So i assume you can do some of that "merging" from their library to add support for this display. 

https://github.com/adafruit/Adafruit_SSD1327

![image](https://user-images.githubusercontent.com/35430692/137536044-6f4670d6-9f97-4968-ac33-c7987b9fdd08.png)

**Comment by cranefist** [comment]
> Did you test all of the constructors?
> 
> * `U8G2_SSD1327_EA_W128128_1_SW_I2C`
> * `U8G2_SSD1327_MIDAS_128X128_1_SW_I2C`
> * `U8G2_SSD1327_WS_128X128_1_SW_I2C`
> 
> Did you set the correct I2C address? https://github.com/olikraus/u8g2/wiki/u8g2reference#seti2caddress Remember to multiply the address with 2 for u8g2.

Yes yes, my mistake :)

When i was trying to test this, i was struggling for a long time.. until i realized i had been using a wrong board type. And ofcourse, now when i tested.. all of them worked :) Well, expect the last one, as my version does not seem to have it. 

Sorry for wasting your time :)

**Comment by olikraus** [comment]
:)
