### ISSUE TITLE
Mixed format screen

### ISSUE THREAD

**Issue by shlyakpavel** [olikraus/u8g2#1637]
Hello!
I have another screen that I want to use with u8g2 here. It is also based on st7920 as #1593 was. However, it seems more complicated. 
The screen format is mixed. One half supports only graphics mode (two dot arrays one above another). You can see it display characters and numbers on the picture. The other half is seven-segment display. It looks like some pixels beyond the dot display are mapped to the segments.
How to support such mixed display with u8g2? Can it drive both dot matrix and seven-segment part? 
Sincerely,
Pavel
![IMGP1048](https://user-images.githubusercontent.com/19782228/137707402-bed5bc1d-27cd-4e2f-b170-3487be432196.jpeg)

**Comment by olikraus** [comment]
> > U8g2 can only drive the graphics part. The segments (if connected to the ST7920) could be update via u8g2.sendF low level command.
> 
> If I restrict resolution to dot matrix in u8g2, will I be able to write commands out of this area via u8g2.sendF?

Depends on the display, but probably yes.
