### ISSUE TITLE
ARM Linux: SPI mode on RPI

### ISSUE THREAD

**Issue by shlyakpavel** [olikraus/u8g2#1638]
Hello!
I think it's a Raspberry PI issue, but I have not checked it on other arm linux boards.
I have successfully connected my st7920 display to both Raspberry PI 4 hardware SPI and atmega32 hardware SPI with u8g2. However, unless I add `internal_spi_mode = 0;` on Raspberry here
https://github.com/shlyakpavel/u8g2/blob/3b6af74b565a1dd44734ac5513dc7ebd998281fa/sys/arm-linux/port/u8g2port.c#L322
I get an error:
```
can't set spi mode: Invalid argument
Aborted
```
I think that comes from RPI SPI driver unable to change SPI modes as they are set somewhere in the bootloader.
The SPI mode in the library is correct as everything works fine on my ATmega32 board. The possible solution could be to check if the system supports setting SPI mode form userspace and skipping this step if not (maybe with a warning). 
I'd love to hear your idea on correct implementation/workaround
Have a nice day!
P. S. for those who question about using RPI port instead of arm linux one: the RPI port is out of date and doesn't work. And I think it won't work on boards above RPI3

**Comment by sgjava** [comment]
@wuhanstudio OK, so I added debug info to your SPI 4 wire example and get:
```
u8g2_InitDisplay
CLK:255, DATA:255, CS:255, RST:199, DC:198
SDA:255, SCL:255
SPI Device Mode Set
spi mode: 0
bits per word: 8
max speed: 500000 Hz (500 KHz)
SPI Device Opened
RESET:199 1
RESET:199 0
RESET:199 1
DC:198 0
Buffering Data 1 
AE 
```
Reading documentation I see:
```
The following figures illustrate the recommended power ON and power OFF sequence of SSD1306
Power ON sequence:
1. Power ON VDD
2. After VDD become stable, set RES# pin LOW (logic low) for at least 3us (t1) (4) and then HIGH (logic
high).
3. After set RES# pin LOW (logic low), wait for at least 3us (t2). Then Power ON VCC.
(1)
4. After VCC become stable, send command AFh for display ON. SEG/COM will be ON after 100ms
(tAF).
```
So shouldn't 0xaf be sent instead of 0xae to turn on display? Also, RST pin should be 0, 1 instead of 1, 0, 1?

**Comment by wuhanstudio** [comment]
Hi, @sgjava 

Thanks for the debug info, I'll try to find out what causes the issue. This issue arises after introdusing fast gpio.

This commit works fine:

https://github.com/wuhanstudio/u8g2-arm-linux/tree/b2a1320acc115fd9a24f676ad96694468b2286b3

However, one commit after that introduces this issue:

![image](https://user-images.githubusercontent.com/15157070/139554336-ef0b5d2e-82a4-4f84-a90e-343c6751556a.png)

**Comment by sgjava** [comment]
@wuhanstudio how far out of sync is that with your sys/arm-linux in u8g2 project? If I can get SPI working then I can proceed to userspace stuff. I'll take a look at your commit and see if I can get working local.

**Comment by wuhanstudio** [comment]
> @wuhanstudio how far out of sync is that with your sys/arm-linux in u8g2 project? If I can get SPI working then I can proceed to userspace stuff. I'll take a look at your commit and see if I can get working local.

Hi,

I just created a PR that fixes this issue.

https://github.com/olikraus/u8g2/pull/1649

It turns out I forget to close the file descriptor after writing. 

Actually, this project keeps my latest port. If eveything works fine in this repo, I'll try to upstream it. So this project is always synced with the upstream.

https://github.com/wuhanstudio/u8g2-arm-linux

**Comment by sgjava** [comment]
@wuhanstudio one more thing, you need to change all the w+ to w in gpio.h. At least with Armbian 5.10 kernel.

**Comment by wuhanstudio** [comment]
Hi, @sgjava 

Thanks for your help. After running several tests, indeed, fopen with `w` works for both `ubuntu 5.4.0-1045-raspi` and `armbian 5.10.34-sunxi`.

I've updated my repo:

https://github.com/wuhanstudio/u8g2-arm-linux

And created a PR for this upstream repo:

https://github.com/olikraus/u8g2/pull/1650

**Comment by sgjava** [comment]
@wuhanstudio I'm working on the c-periphery replacement for your gpio.c. Once that's working I'll throw up a PR for you to bless. Then I'll replace spi and i2c with latest userspace stuff. Hopefully you should see a decent speed improvement especially with gpio.

**Comment by sgjava** [comment]
@wuhanstudio one thing I forgot is I also run everything without root. This is difficult with sysfs and udev to get it working right. The new GPIO will work as normal user.

**Comment by wuhanstudio** [comment]
That's interesting. Both `sysfs` and `devmem` require `sudo` or extra `gpio` being created.

https://raspberrypi.stackexchange.com/questions/40105/access-gpio-pins-without-root-no-access-to-dev-mem-try-running-as-root

**Comment by sgjava** [comment]
@wuhanstudio right, but I'm using the character device /dev/gpiochip0 now. No sudo required. Just some permissions in rc.local.

Take a look at https://github.com/sgjava/u8g2/commit/8d38070847f1b5fd5f87aee1e7c9be8de3242406 as I just refactored gpio code. And the SPI 4 wire example works as expected. I have some more work to do because I want to remove hard coded device. That should be 1 to 1 with pins, since you can have /dev/gpiochip1, 2, 3...

See https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/about for more info.

**Comment by sgjava** [comment]
@wuhanstudio so I've added a compiler directive to use GPIO character device or sysfs since c-periphery already supports this. The legacy (< 4.8) kernels can be used. I'll get everything working in my fork and have you take a look before I PR.

**Comment by wuhanstudio** [comment]
Thanks. It's nice to have a faster gpio so that software I2C and SPI can achive better performance.

**Comment by sgjava** [comment]
Yep and I'll switch I2C and SPI to use c-periphery since it will support all the various modes in userspace.
