### ISSUE TITLE
Support for ST75160 display

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#1642]
### Discussed in https://github.com/olikraus/u8g2/discussions/1641

<div type='discussions-op-text'>

<sup>Originally posted by **johngineer** October 18, 2021</sup>
Hello! I am working with a 160x96 monochrome display that uses an ST75160 controller. It would be great if you could add support for this chip to u8g2.

To that end, I am willing to provide a sample display + breakout PCB for test & eval. I just need to know where to send it.

Thanks!</div>

Is the datasheet of the controller available?

**Comment by olikraus** [comment]
Actually both would be perfect: The datasheet of the controller and the datasheet of the display.

**Comment by olikraus** [comment]
The ST75160 seems to have almost the same commands as the ST75256. I assume we could just update the ST75256 driver.
Can you already test any code with the display?

**Comment by johngineer** [comment]
Just a quick update on this. There was a customs delay in the shipping of the LCDs and breakout PCB, but I should receive them by the end of next week. Once I have them assembled, I will test the code and follow up with my feedback.

**Comment by olikraus** [comment]
no further feedback... closing for now...
