### ISSUE TITLE
T6963C 320x128 display

### ISSUE THREAD

**Issue by ankas2** [olikraus/u8g2#1655]
Hello, I try to  make new device with 320x128 pix, but it work as 240x128.
[U8g2_T6963C_320x128.zip](https://github.com/olikraus/u8g2/files/7456355/U8g2_T6963C_320x128.zip)

**Comment by olikraus** [comment]
Any datasheet available for your display?

**Comment by ankas2** [comment]
![EDT EW50404FLW my display config](https://user-images.githubusercontent.com/32437198/140176980-0ad83751-3183-4678-b74b-c28a5f432014.png)
I don't have datasheet.

**Comment by olikraus** [comment]
So your mod works as expected?

**Comment by ankas2** [comment]
![DSC_0504](https://user-images.githubusercontent.com/32437198/140411671-8b31a641-485f-400a-aa3e-b6a9f716588a.JPG)
![DSC_0505](https://user-images.githubusercontent.com/32437198/140411678-b6bf0258-e6e8-41a0-b4c0-a9086090bcfc.JPG)
![DSC_0507](https://user-images.githubusercontent.com/32437198/140411694-bbfc5ab7-7434-46ab-863f-0bc0b5dfd0b5.JPG)

**Comment by ankas2** [comment]
Something I miss, and don't find what.

**Comment by ankas2** [comment]
At last found what I miss.
In a few days send here all my info about display.

**Comment by olikraus** [comment]
Nice pictures. I still do not know how I could support. Shell I create an empty constructor for this?

**Comment by ankas2** [comment]
[EDT EW50404FLW_PINOUT.txt](https://github.com/olikraus/u8g2/files/7492953/EDT.EW50404FLW_PINOUT.txt)
[media.zip](https://github.com/olikraus/u8g2/files/7492954/media.zip)
[U8g2_my added-T6963C_320x128.zip](https://github.com/olikraus/u8g2/files/7492956/U8g2_my.added-T6963C_320x128.zip)


All my info about this display, library is working, my mistake was 16bit mode not enabled.
