### ISSUE TITLE
SSD1309 SPI not working with ESP32

### ISSUE THREAD

**Issue by farmlifefpv** [olikraus/u8g2#1663]
I have a SSD1309 2.42 inch OLED display, and its working fine on an arduino uno, but I cannot get it working on an ESP32 NodeMCU v3, using either VSPI or SPI. I have tried multiple combos of pins and none seem to work at all, and ideas?

**Comment by olikraus** [comment]
ok, not sure how I can support here.. Maybe reopen this topic in discussions area.
