### ISSUE TITLE
ST7920 - Real Time System

### ISSUE THREAD

**Issue by lebertagna** [olikraus/u8g2#167]
I'm using a 128x64 Display based on ST7920, the U8g2lib and a 8080 protocol to make a real time system, but I need the refresh rate to be faster. 

What do I have to do to make it faster?

![video](https://cloud.githubusercontent.com/assets/25107462/22168915/64eb0e50-df57-11e6-81c6-28c489051ec3.gif)

**Comment by olikraus** [comment]
Use full buffer HW_SPI with Arduino Zero.

**Comment by lebertagna** [comment]
It didn't work. 
I use the conecction: CS/RS = 3, reset = 4 and PSB = gnd.

What am I doing wrong?

**Comment by olikraus** [comment]
hmmm what about full buffer 8080 mode?

**Comment by lebertagna** [comment]
full buffer 8080 mode is what I'm using

**Comment by olikraus** [comment]
well then... you didn't wrote this... but anyway, it will be difficult to improve speed here...

**Comment by viti95** [comment]
It's possible to obtain ~15 fps using an ST7920 (full buffer HW SPI, also full buffer 8080) with an Arduino Mega, and ~25-30 fps with an Arduino Due. I can show you an example made by me (Assetto Corsa + Arduino Mega)

https://www.youtube.com/watch?v=sGgVgdKVZ4s

**Comment by olikraus** [comment]
Maybe you should post your code. Then i might be able to make some suggestions for speed improvements.

**Comment by olikraus** [comment]
no further input... closing this. Feel free to reopen this.

**Comment by lwFlyFish** [comment]
I have a bit of a problem, can I share your code?
