### ISSUE TITLE
Callback return codes

### ISSUE THREAD

**Issue by sgjava** [olikraus/u8g2#1681]
I'd like to return error code back, but couldn't find anything in the porting documentation. For instance all the callbacks return 0 by default or 1. What happen if you send back < 0? Looking for a clean way to avoid seg faults.

**Comment by olikraus** [comment]
There should be only 0 and 1 as a return value.
1: Message was handled
0: Message was not handled

There is no error code as such, however 0 could be interpreted as insuccessful attempt to handle the message.

Usually the U8x8 procedure do not check for the return value. And I also did not always use the above convention everywhere.

**Comment by sgjava** [comment]
Ok, so if I had an init error I should exit I suppose then? i.e. GPIO pin in use or I2C bus doesn't exist.

**Comment by olikraus** [comment]
Ahm... Well, it is not checked, u8x8/u8g2 would just continue.

**Comment by sgjava** [comment]
OK, so it makes sense to bail on error, thanks.
