### ISSUE TITLE
Support for SH1122 for U8X8

### ISSUE THREAD

**Issue by srg74** [olikraus/u8g2#1686]
Looks like SH1122 is supported by u8g2 library but not by u8x8. Is there a possibility to add support for SH1122?

**Comment by olikraus** [comment]
There are several display types which have a somehow unusual memory architecture: SH1122, LD7032, ST7920, ST7986, LC7981, T6963, SED1330, RA8835, MAX7219, LS0xx
For those displays u8x8 is not supported.
