### ISSUE TITLE
Linux hw SPI: Custom SPI mode for a display

### ISSUE THREAD

**Issue by shlyakpavel** [olikraus/u8g2#1689]
I need to setup custom SPI mode for a display. I have st7920 controller and I need to use mode 0 instead of 3. What I do now is a dirty hack:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/19782228/141937615-bb286511-3574-4c0f-a85c-6c79fcb7e879.png">
Is there a way to do it correctly?

**Comment by sgjava** [comment]
You mean like u8x8->display_info->spi_mode?

**Comment by sgjava** [comment]
OK, so that needs to be added to user info struct. Let me take a look at that.

**Comment by sgjava** [comment]
@shlyakpavel see https://github.com/olikraus/u8g2/pull/1692 I also added max_speed since I know you will ask for this next I bet. Go ahead and close @olikraus once you merge please.

**Comment by olikraus** [comment]
I think the PR is already closed.

**Comment by sgjava** [comment]
https://github.com/olikraus/u8g2/pull/1697, had to change name :)

**Comment by olikraus** [comment]
ok, done
