### ISSUE TITLE
U8glib to U8g2 Font conversion?

### ISSUE THREAD

**Issue by uriba107** [olikraus/u8g2#170]
Hi Oliver,
I'm having issues converting one of my project's custom fonts from bdf to u8g, it doesn't look the same, which means I'm either using the wrong TTF as source or I'm messing up something else.

However, I was wondering, is there and option to convert the U8G_FONT_SECTION directly to U8G2_FONT_SECTION? just to quicken up the process?

Thanks,
Uri

**Comment by olikraus** [comment]
Unfortunately there is no way to convert the old font structore to the new structure. 
However, the output of bdfconv should be the same.
Some discussion has happend here: #54 

You should use something like this:
./bdfconv -v -f 1 -m '32-255' myfont.bdf -o myfont.c -n myfont
