### ISSUE TITLE
Auto detect display

### ISSUE THREAD

**Issue by sgjava** [olikraus/u8g2#1707]
I know this probably isn't feasible, but is there a way to auto detect display type (i.e. probe) based on I2C or SPI connection. I'm not sure just checking the I2C address would be helpful across displays.

https://github.com/greiman/SSD1306Ascii/issues/59

**Comment by olikraus** [comment]
U8x8 doesn't read anything from the display. In fact many SPI devices do not allow read operation.

**Comment by sgjava** [comment]
That makes sense, so I guess I2C would be the only probing allowed and that is nebulous. Thought I'd at least ask. Too bad they never came up with a device ID standard :(
