### ISSUE TITLE
issue with bdf2u8g_101

### ISSUE THREAD

**Issue by teeshq** [olikraus/u8g2#1714]
Hi i try to convert
[hornet.zip](https://github.com/olikraus/u8g2/files/7629599/hornet.zip)
 but my output file dont look right im using this command `bdf2u8g_101.exe  bdfconv -v -f 1 -m '32-255' hornet.bdf -o hornet.c -n hornet`

please help im nooby with this type of coding

**Comment by teeshq** [comment]
nwm sorted

**Comment by olikraus** [comment]
You need this tool: https://github.com/olikraus/u8g2/blob/master/tools/font/bdfconv/bdfconv.exe
