### ISSUE TITLE
Can it be made smaller ?

### ISSUE THREAD

**Issue by AndKe** [olikraus/u8g2#172]
While the library is impressive, the simple graphics test using U8X8_SSD1306_128X64_NONAME_SW_I2C u8x8
compiles to 9032 bytes or  32% of a 328

**Comment by olikraus** [comment]
... which includes the huge Arduino Print and Wire libs

**Comment by olikraus** [comment]
I have compiled U8x8 Helloworld for the Uno with Arduino 1.8.0. I get this:
U8X8_SSD1306_128X64_NONAME_SW_I2C 5660 Bytes (17%)
U8X8_SSD1306_128X64_NONAME_HW_I2C 5696 Bytes (17%)
U8X8_SSD1306_128X64_NONAME_4W_SW_SPI 5538 Bytes (17%)
U8X8_SSD1306_128X64_NONAME_4W_HW_SPI 5460 Bytes (16%)

So one first question is: Why does your result deviate that much?

**Comment by olikraus** [comment]
Another interesting point is, that the Wire (TWI) lib is always included. It should be only included with U8X8_SSD1306_128X64_NONAME_HW_I2C, but is there also with all other constructors.

**Comment by olikraus** [comment]
U8X8_SSD1306_128X64_NONAME_4W_SW_SPI could be reduced to 4500 if the inclusion of Wire lib. Of course not an option for your, becasue you need the wire interface.

**Comment by AndKe** [comment]
I was referring to the u8x8/GraphicsTest  example,  compiling HelloWorld with 
```
U8X8_SSD1306_128X64_NONAME_SW_I2C u8x8(/* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE); 
```
for Pro Mini results in 5672 Bytes.  (so it's not that much off) 

your observation about TWI is essencial.

**Comment by olikraus** [comment]
ok... not sure what i can do here. Can we close this issue?

**Comment by AndKe** [comment]
ok, I thought SPI may been included when I2C was , and vice versa.  , but if you see nothing to improve , to make it smaller - I'll close the issuemyself.
Thank you for your time.
