### ISSUE TITLE
What’s the purpose of the .bdf Font files?

### ISSUE THREAD

**Issue by Wookbert** [olikraus/u8g2#1721]
Greetings!

We are trying to understand the difference between the **.bdf files** found in `u8g2/tools/font/bdf/` and the **.c files** found in `u8g2/tools/font/build/single_font_files/`.

Exactly where/when are those .bdf s used? In the Arduino code not, if we understood correctly.

We’d also like to use the U8g2 Simulator, but that one requires the files to be .bdf. Logisono for instance can't be found in the repo as .bdf, only as .c. Conversion required? How? We can't find anything in the documentation.

**Comment by olikraus** [comment]
If a font is available as .bdf file, then then the conversion is done by bdfconv: The .c file is generated directly from the .bdf font.
If a font is available as .ttf (like logisoso) then u8g2 font conversion will convert the .ttf to .bdf first by using otf2bdf tool:
- .ttf to .bdf with otf2bdf (https://github.com/olikraus/u8g2/tree/master/tools/font/otf2bdf)
- .bdf to .c with bdfconv (https://github.com/olikraus/u8g2/tree/master/tools/font/bdfconv)

All sources (.bdf and .ttf) should be available:
- https://github.com/olikraus/u8g2/tree/master/tools/font/bdf
- https://github.com/olikraus/u8g2/tree/master/tools/font/ttf

The .c file construction of the fonts is fully automatic and done by a c executable: https://github.com/olikraus/u8g2/blob/master/tools/font/build/build.c
