### ISSUE TITLE
Misaligned "3" in Logisoso font

### ISSUE THREAD

**Issue by Wookbert** [olikraus/u8g2#1722]
I just noticed that the number 3 in the Logisoso font sits 1 Pixel too low compared to all other numbers. This could be on purpose typographically, however I also could imagine this to be a rounding error in the rasterization process when coming from the vector font.

Here are just three different heights, all showing the same down shift (notice the base line at the bottom, only the "3" touches ground):

![image](https://user-images.githubusercontent.com/3104762/145645679-a9e260ef-af52-4704-a6a5-dcc4e46b36bc.png)

![image](https://user-images.githubusercontent.com/3104762/145645735-7dfceb68-6039-406f-bdaa-abbe8210c57b.png)

![image](https://user-images.githubusercontent.com/3104762/145645785-2c86f358-8a49-4719-ac31-9989730c1fc6.png)

It’s a very subtle, but noticeable defect, when designing for instance a timer with other objects close-by (one can see the 3 jump, compared to the other numbers). Perhaps you can explain us, how to fix the 3 (move it up by 1 px) in the .c file.

![image](https://user-images.githubusercontent.com/3104762/145646425-ca4a7c33-9bd8-4409-bbec-5074c6c32136.png)

(Look closely, and you see that the 3 in this example sits 1 px too low).

**Comment by olikraus** [comment]
see here: https://github.com/olikraus/u8g2/issues/1484

Please note that I am neither the author of the font nor the author of the font rasterization tool (which is otf2bdf, which in turn is based on the freetype engine). So: There is nothing what I can do.
