### ISSUE TITLE
Missing sources in CMakeLists.txt

### ISSUE THREAD

**Issue by MauAbata** [olikraus/u8g2#1726]
I'm compiling against ESP-IDF as a component, and found that `"csrc/u8x8_capture.c"` is missing from `CMakeLists.txt`. There may be others, as this list hasn't been updated since '18. 

I'll open a PR to add this in, and possibly add a tool to check in on this periodically, but I wanted to know if there is any dependency specific ordering to the files in this list, or if they've just been added arbitrarily?

**Comment by olikraus** [comment]
CMakeLists.txt is not official part of u8g2. It was contributed once I assume. I will not update the same, but I will accept your PR.
