### ISSUE TITLE
Invert screen capture. 

### ISSUE THREAD

**Issue by jakplugg** [olikraus/u8g2#1729]
Thank you for your great library! 

With OLED screens the screen capture results in black on white XBM file rather than white on black as it is on the screen. Is it possible to add an option to invert the bits of the output?

Thanks, JM

**Comment by olikraus** [comment]
Just before writing the image, you could set the draw color to 2 (https://github.com/olikraus/u8g2/wiki/u8g2reference#setdrawcolor) and draw a box over the complete display. This would invert the image.

**Comment by jakplugg** [comment]
Thats actually quite nice, the screen "flashes" to indicate a picture was sent.
thanks!

**Comment by olikraus** [comment]
😃, well yes, but you probably could avoid the flashing by not sending the buffer to the display or by drawing the box again to revert the inversion.
