### ISSUE TITLE
ox' may be used uninitialized in this function 

### ISSUE THREAD

**Issue by FanhuaCloud** [olikraus/u8g2#1731]
When I use the riscv32 compiler of esp-idf, the compiler will return the following questions:

../components/u8g2/csrc/u8g2_font.c: In function 'u8g2_GetStrX':
../components/u8g2/csrc/u8g2_font.c:1191:10: error: 'ox' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   return ox;
          ^~

**Comment by olikraus** [comment]
hmmm nice finding.

**Comment by FanhuaCloud** [comment]
I am using esp32-c3 platform, after commenting out this code, compile and run normally

**Comment by FanhuaCloud** [comment]
thank you for your reply!

**Comment by olikraus** [comment]
should be fixed now...

**Comment by FanhuaCloud** [comment]
ok, it's working fine
