### ISSUE TITLE
u8g2_Userinterfaceselectionlist() does not support Chinese fonts well

### ISSUE THREAD

**Issue by ueJone** [olikraus/u8g2#1738]
![image](https://user-images.githubusercontent.com/14084960/147401575-eeb88db1-57b1-4f32-81ac-7974504cd154.png)

```
u8g2_SetFont(&u8g2, u8g2_font_wqy12_t_gb2312);
u8g2_UserInterfaceSelectionList(&u8g2, "Title:设置", 1, "1.确认\n2.取消\n3.返回");
```
There are two questions:
1. The upper part of the title is not displayed. It use `8g2_GetAscent()` to get the height of title, but it only applies to ASCII.
2. The text of the options exceeds the background.

**Comment by olikraus** [comment]
You probably need to set a different ascent/descent height: https://github.com/olikraus/u8g2/wiki/u8g2reference#setfontrefheightall
Calling
`u8g2_SetFontRefHeightExtendedText` or `setFontRefHeightAll`
after `u8g2_SetFont` may work.

**Comment by ueJone** [comment]
> You probably need to set a different ascent/descent height: https://github.com/olikraus/u8g2/wiki/u8g2reference#setfontrefheightall Calling `u8g2_SetFontRefHeightExtendedText` or `setFontRefHeightAll` after `u8g2_SetFont` may work.

Perfect, thank you!
