### ISSUE TITLE
Setup commands

### ISSUE THREAD

**Issue by ichetiva** [olikraus/u8g2#1739]
Excuse me, can you tell me where the initial sending of commands to the display is to start it?

**Comment by olikraus** [comment]
for which constructor?

**Comment by ichetiva** [comment]
> for which constructor?

ra8835

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/blob/7d1108521680fbb14147a867e0ea15769119b78b/csrc/u8x8_d_sed1330.c#L296-L332

**Comment by ichetiva** [comment]
thanks
