### ISSUE TITLE
Display darker after write with SSD1327

### ISSUE THREAD

**Issue by resterampeberlin** [olikraus/u8g2#1748]
Good morning from Berlin,

I have a weird problem with a Waveshare SSD1327 OLED connected to a Arduino 33 IOT. The displayed text and graphics becomes significantly darker after the display is updated. It seems that it is displayed with full contrast when data is transferred and much darker when the transfer is completed. 

Surprisingly this is not the case for functions from u8g2log.

The constructor is as follows:
U8G2_SSD1327_WS_128X128_F_4W_HW_SPI u8g2(U8G2_R0, DISP_CS, DISP_DC, DISP_RESET);

I tried various things to analyze the issue:
Supplied the display with 5V instead of 3.3V -> no effect
used all kinds of buffering -> no effect.
setContrast(255) -> no effect
setPowerSave(0) -> no effect

Any ideas?

**Comment by olikraus** [comment]
Maybe power supply (current) is not sufficient.

**Comment by resterampeberlin** [comment]
I supplied it also from an external power supply without any change.

**Comment by olikraus** [comment]
Hmm I never heard about such a problem. I still would assume a hardware problem here.

**Comment by resterampeberlin** [comment]
You were totally right - the reason was a bad soldered ground pin on my PCB ;-(
