### ISSUE TITLE
Scrambled edge/corner radiuses of drawRFrame and drawRBox using XOR drawColor(2)

### ISSUE THREAD

**Issue by jacobdmoore** [olikraus/u8g2#1753]
I'm using u8g2 with an SSD 1320 controller (which I got working thanks to issue #1351) and have had a lot of success using your library - truly excellent work!

One issue that I haven't been able to figure out happens when I use drawRFrame and drawRBox in conjunction with setDrawColor(2) (XOR mode). It appears that the radiuses of the box/frame corners don't render correctly. You can see this in the photo - the left side of the screen uses setDrawColor(2) and the right side uses setDrawColor(1). If the radius is set to 0, the issue does not appear - otherwise it looks scrambled in the corner.

Is this a bug or is there possibly a setting I specified incorrectly that results in this symptom? Thank you!

![image](https://user-images.githubusercontent.com/47227108/149174776-78014d3d-ede4-444e-970e-85ed10a02141.png)

**Comment by olikraus** [comment]
hmm... the XOR mode was never tested with RFrame/RBox. The simple truth is: Do not use XOR mode with RFrame/RBox.
It probably will be very difficult to fix this.

**Comment by jacobdmoore** [comment]
I see -- using radius = 0 eradicates the problem for me, so I will use that for my application until this is fixed.

With your guidance, I'm happy to troubleshoot/test out any potential solutions. Also understand if this can't be done!

**Comment by olikraus** [comment]
As a workaround: Can you draw the RFrame/RBox in drawcolor 0 or 1 and then later add the text in mode 2?
This would probably work.

**Comment by jacobdmoore** [comment]
Worked like a charm 😄 I'll close this issue since this is a pretty easy and logical workaround

**Comment by 1183747933** [comment]
> As a workaround: Can you draw the RFrame/RBox in drawcolor 0 or 1 and then later add the text in mode 2? This would probably work.

Excuse me, can we fix this problem now

**Comment by 1183747933** [comment]
> As a workaround: Can you draw the RFrame/RBox in drawcolor 0 or 1 and then later add the text in mode 2? This would probably work.

May I ask if there is a way to solve this problem now?

**Comment by olikraus** [comment]
Like mentioned above, any fix is difficult and I assume it will never happen unless someone does some research on the midpoint algorithm (https://en.wikipedia.org/wiki/Midpoint_circle_algorithm). Additionally we would need to consider all conditions when concatenating arcs with lines or arcs with arcs.

The issue needs to be fixed here: https://github.com/olikraus/u8g2/blob/4b17158f4dd02ce386ac18f3fd30c20997a73871/csrc/u8g2_circle.c#L74-L107

But I don't have any idea how...
