### ISSUE TITLE
No other I2C traffic possible

### ISSUE THREAD

**Issue by AndKe** [olikraus/u8g2#176]
Using 
U8X8_SSD1306_128X64_NONAME_SW_I2C u8x8(/* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE);  on Arduino Nano.

when using :
```
u8x8.begin(); 
```
..accessing another I2C device crashes it.

While this (regardless of order):
```
  Wire.begin();  
  u8x8.begin();
```
stops display from showing anything (but the application runs)

- I am using I2C like this: 

```
 
  Wire.beginTransmission(deviceAddress);
  Wire.write(func);
  Wire.endTransmission(false);
  
  Wire.requestFrom(deviceAddress,2,true);
   while(Wire.available() 
  b1 = Wire.read();
...

 ```

**Comment by olikraus** [comment]
Please use
U8X8_SSD1306_128X64_NONAME_HW_I2C u8x8(reset=*/ U8X8_PIN_NONE);

**Comment by AndKe** [comment]
oops , my bad :)

**Comment by olikraus** [comment]
no problem, i should publish the FAQ more visible in the wiki.
