### ISSUE TITLE
Dual driver display

### ISSUE THREAD

**Issue by KPCKxd** [olikraus/u8g2#1763]
So I got myself @[this display](https://www.buydisplay.com/arduino-raspberry-pi-3-83-inch-oled-module-320x132-spi-16-level-grayscale) . It does work with SSD1320_160x132 settings, but it seems to be two displays sepated, Does exist any way I could connect these two displays to work, or appear, just as one? I need to display lines 5 lines of text, which are defined as chars.

**Comment by olikraus** [comment]
I made some suggestion here: See 10 Mar 2021 https://github.com/olikraus/u8g2/issues/1351

**Comment by KPCKxd** [comment]
I actually found that thread about half an hour later I wrote this issue and it solved what I needed. Thanks a lot! 😃
