### ISSUE TITLE
Questions about jlx256128，thanks！

### ISSUE THREAD

**Issue by return97** [olikraus/u8g2#1766]
I have a jlx256128 screen

The driver module is st75256

But I'm STM32F103's board

I use Arduino's ide to burn!

I configure it according to the file! But I can't drive it!

Can you tell me what's going on?

Thank you.

Look forward to your reply!

**Comment by olikraus** [comment]
Try 4W SW SPI and check your wiring.

**Comment by return97** [comment]
OK
THANKS SO MUCH
I CAN NOW!

**Comment by olikraus** [comment]
Great, however SW SPI might be slow compared to HW SPI.
