### ISSUE TITLE
Return when end of the display is reached

### ISSUE THREAD

**Issue by MauroWesthoven** [olikraus/u8g2#1780]
Is it possible to implement a function in the u8g2 library that when the end of a screen is reached, the text displayed on the screen is wrapped to the next line?

For example: you are displaying text on a 128x64 screen and when a letter reaches the 128th pixel the last word is wrapped to the next line maybe by also defining the X and Y position for the next line.

**Comment by olikraus** [comment]
https://github.com/olikraus/U8g2_for_Adafruit_GFX/issues/35
https://github.com/olikraus/u8g2/issues/1081
