### ISSUE TITLE
ESP32 - Poe - Olimex - SD CARD

### ISSUE THREAD

**Issue by GUAGGIO** [olikraus/u8g2#1787]
Good evening everyone.
I was working with an olimex ESP32 and in one of my projects I use both the display, connected to the UEXT port, and the integrated SD card reader. The problem arises when I start everything and he marks the password used to turn on the relay, where he saves the string on a file on the SD. As soon as I keep entering codes, both correct and incorrect, he gives me an error saying that he can no longer write the file. Now I don't understand for the first time he writes it and the following ones don't.
Thanks to anyone who answers.
P.S. I'm using the SD_MMC library because only the one with the integrated reader works.

**Comment by olikraus** [comment]
Do display and SD card share the same SPI pins?
If so, you MUST use the u8g2 HW SPI constructor (see FAQ).

**Comment by GUAGGIO** [comment]
The same pins are used. Sorry, what are you meaning for ?

**Comment by olikraus** [comment]
> The same pins are used. Sorry, what are you meaning for ?

As mentioned above, the u8g2 constructor must be a HW SPI constructor.
