### ISSUE TITLE
270 degree rotation [R3] & mirroring

### ISSUE THREAD

**Issue by cranefist** [olikraus/u8g2#1795]
Hello

I'm having an issue, none of the rotating, mirroring or flipmode options work for me.

I would need to rotate the display content by 270 degree = U8G2_R3

And then mirror the content, but i cant use R3 & MIRROR at the same time. And flipmode wont help me as its 180 degree flip.

If flipmode is the only option for rotation while using MIRROR, then it should have all the rotation options in it.

**Comment by olikraus** [comment]
Which controller / u8g2 constructor do you use?

**Comment by olikraus** [comment]
The SSD1327 should be able to do the mirror with help of its internal hardware.
Do the R3 change as usual and try to put the SSD1327 into mirror mode:
```
u8g2.sendF("ca", 0xa0, 0x41);
```
or
```
u8g2.sendF("ca", 0xa0, 0x52);
```
Will one of those commands work?

**Comment by cranefist** [comment]
> ```
> u8g2.sendF("ca", 0xa0, 0x41);
> ```

This solved the problem, thanks a lot!

It seemed to be the same registries as what the flipmode changed?

 ```
static const uint8_t u8x8_d_ssd1327_128x128_flip0_seq[] = {
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */
  U8X8_CA(0x0a2, 0x000),		/* display offset, shift mapping ram counter  */
  U8X8_CA(0x0a0, 0x051),		/* remap configuration 0x051 */
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};

static const uint8_t u8x8_d_ssd1327_128x128_flip1_seq[] = {
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */
  U8X8_CA(0x0a2, 0x000),		/* display offset, shift mapping ram counter */
  U8X8_CA(0x0a0, 0x042),		/* remap configuration 0x042 */
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};
 ```

**Comment by olikraus** [comment]
> It seemed to be the same registries as what the flipmode changed?

Yes, the display allows swapping the vertical and horizontal bit sequence. Doing both is equivalent to a 180 degree rotation.

**Comment by cranefist** [comment]
Is there a simple way for reinitializing the display? SSD1327 seems to be quite slow, its ok with the ```u8g2.setBusClock(400000);```
But much better if i set it at ```u8g2.setBusClock(1000000);``` But with this higher speed, it works for some time and then eventually goes corrupted.

And i noticed this in the datasheet:
![image](https://user-images.githubusercontent.com/35430692/156174783-782a83d7-317e-4d24-875a-daaf6492af20.png)

**Comment by olikraus** [comment]
You could call .begin() once again.
