### ISSUE TITLE
Icon menu example code using AVR(Atmega)

### ISSUE THREAD

**Issue by JOSSEP-ENG** [olikraus/u8g2#1797]
Hi, olikraus.

thank you so much for your effort about this useful library code.

the reason why I'm writing here is because I want to know Icon menu example code using AVR(Atmega).

I tried to write the code by changing some of the examples below, but it failed.
https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/IconMenu/IconMenu.ino

please, I want you to help me with this.

**Comment by olikraus** [comment]
Continued here: https://github.com/olikraus/u8g2/issues/1798
