### ISSUE TITLE
How to use Icon with text string

### ISSUE THREAD

**Issue by JOSSEP-ENG** [olikraus/u8g2#1798]
Hi, olikraus.

There were some problems, so I wrote here.

I want to express the text string below Icon.

u8g2_FirstPage (&u8g2);
do{
u8g2_SetFont(&u8g2,u8g2_font_open_iconic_all_4x_t);            
u8g2_DrawGlyph(&u8g2,10,40,123);
} while(u8g2_NextPage (&u8g2));

u8g2_SetFont(&u8g2, u8g2_font_7x13B_tf);
u8g2_DrawStr(&u8g2,10,60,"TIME");
u8g2_SendBuffer(&u8g2);

but it doesn't work, is there any solution?

![image](https://user-images.githubusercontent.com/58581167/155879490-fbcc5841-d5e3-47ea-9c4a-08e82a57c714.png)
![image](https://user-images.githubusercontent.com/58581167/155879496-8e4e868b-27b9-4187-880d-b1d09a1b1de8.png)
![image](https://user-images.githubusercontent.com/58581167/155879503-c34b60b7-c7d2-4432-a897-703fa0279588.png)

This is the screen I want to make.
The screen changes every time you press the button.

please, I want to get help on how to write the code to express the screen above.

**Comment by olikraus** [comment]
Do not mix FirstPage/NextPage with SendBuffer

Use this:
```
u8g2_FirstPage (&u8g2);
do{
u8g2_SetFont(&u8g2,u8g2_font_open_iconic_all_4x_t);
u8g2_DrawGlyph(&u8g2,10,40,123);
u8g2_SetFont(&u8g2, u8g2_font_7x13B_tf);
u8g2_DrawStr(&u8g2,10,60,"TIME");
} while(u8g2_NextPage (&u8g2));
```

**Comment by olikraus** [comment]
Can we close this issue?

**Comment by JOSSEP-ENG** [comment]
Thank you for replying.
I solved this problem.
Have a good day!
