### ISSUE TITLE
u8g2.getMenuEvent();

### ISSUE THREAD

**Issue by Odeku** [olikraus/u8g2#1803]
Hello, excuse me

    uint8_t u8x8_GetMenuEvent(u8x8_t *u8x8)
    { 
	    if(HAL_GPIO_ReadPin(KEY_GPIO_Port, KEY_Pin) == 0)
	    {
		    return U8X8_MSG_GPIO_MENU_PREV;			
	    }
	    while(HAL_GPIO_ReadPin(KEY_GPIO_Port, KEY_Pin) == 0);
	    
	    if(HAL_GPIO_ReadPin(KEY1_GPIO_Port,KEY1_Pin) == 0)
	    {
		    return U8X8_MSG_GPIO_MENU_NEXT;			
	    }
	    while(HAL_GPIO_ReadPin(KEY1_GPIO_Port,KEY1_Pin) == 0);
    }
Why don't I can return key value？
In IconMenu example.

**Comment by Odeku** [comment]
How do I know what button I pressed

**Comment by Odeku** [comment]
uint8_t u8x8_GetMenuEvent(u8x8_t *u8x8)
{ 
	if(HAL_GPIO_ReadPin(KEY_GPIO_Port, KEY_Pin) == 0)
	{
		return U8X8_MSG_GPIO_MENU_PREV;			
	}
	while(HAL_GPIO_ReadPin(KEY_GPIO_Port, KEY_Pin) == 0);
	
	if(HAL_GPIO_ReadPin(KEY1_GPIO_Port,KEY1_Pin) == 0)
	{
		return U8X8_MSG_GPIO_MENU_NEXT;			
	}
	while(HAL_GPIO_ReadPin(KEY1_GPIO_Port,KEY1_Pin) == 0);
}

**Comment by olikraus** [comment]
I don't know this code. The official supported code is here:

https://github.com/olikraus/u8g2/blob/33843d4ea87ca23d9d0c937d27119262ae23ece2/cppsrc/U8x8lib.cpp#L164-L172
