### ISSUE TITLE
Is 2.7 inch Tripple-color 264x176 pixels e-Ink display shield from Seeed supported?

### ISSUE THREAD

**Issue by ngmacha** [olikraus/u8g2#1807]
Hi Oli, thank you very much for a great library! 

I'm having difficulty to find out if this ePaper display supported by your library, and if yes, which constructor to use?
https://www.seeedstudio.com/2-7-Triple-Color-E-Ink-Shield-for-Arduino-p-4069.html

Thank you and kind regards - Mac Ha

**Comment by olikraus** [comment]
I have stopped supporting EPDs. There are probably better libs out there like the [GxEPD2](https://github.com/ZinggJM/GxEPD2) Arduino lib from @ZinggJM

**Comment by ngmacha** [comment]
Thank you very much for the reply, seems exactly what I was looking for!
Closing the issue
