### ISSUE TITLE
Support for CH1116 - Oled 1.3"

### ISSUE THREAD

**Issue by alainm** [olikraus/u8g2#1808]
These new Oled has replaced the SH1106 on the market and I am unable to use them :(

**Comment by olikraus** [comment]
Is any further documentation available?
Link to any product?

**Comment by alainm** [comment]
Please forgive me, it works with U8g2lib from the hello world example.
The problem in fact is initialization. On Arduino, I need to power it up repeatedly, up to 4 times, to get it working.
I am moving to the STM32 port now

**Comment by olikraus** [comment]
Ah, ok
