### ISSUE TITLE
How to PRINT integer

### ISSUE THREAD

**Issue by skartalov** [olikraus/u8g2#1810]
Dumb question, but I can not figure it out:

int i= 50;
u8g2.print(i);

Does not work! How the Heck do I print intereger?

**Comment by olikraus** [comment]
Did you set font and Cursor? Please share the complete code.

**Comment by skartalov** [comment]
Hmm, when I load shorter program, it works. Must be something's wrong with the compiler as my program almost takes all the memory of Arduino NANO.

**Comment by olikraus** [comment]
Do you use the picture loop constructor? It requires lesser RAM
