### ISSUE TITLE
1.3" OLED (SH1106): Scrambled display output via SPI?

### ISSUE THREAD

**Issue by Wookbert** [olikraus/u8g2#1818]
We are successfully driving the 1.3" SH1106 OLED via I2C, but having a serious problem with its SPI sibling: The display is scrambled, as shown in the image below. CPU is an ESP8266 (Wemos D1 mini, 4 MB). We've tried Software and Hardware interface buffer, 3 wire and 4 wire, yet can't resolve the issue.

Any idea what we are doing wrong, how to fix this?

<img width="542" alt="image" src="https://user-images.githubusercontent.com/3104762/159488016-c6233485-80e1-47fb-9232-454e9c964ced.png">

**Comment by Wookbert** [comment]
Our bad: Interference from Touch Sensor button. 🤦🏼‍♂️

**Comment by olikraus** [comment]
:-)
