### ISSUE TITLE
Cannot be find

### ISSUE THREAD

**Issue by KagurazakaSarah** [olikraus/u8g2#1819]
The code is not highlighted.And the following is the error information:
sketch_mar25a:5:10: fatal error: U8g2lib .h: No such file or directory
    5 | #include <U8g2lib .h>
      |          ^~~~~~~~~~~~
compilation terminated.
exit status 1
U8g2lib .h: No such file or directory

**Comment by KagurazakaSarah** [comment]
I am sure that I'm installed this library

**Comment by olikraus** [comment]
closed, see #1820
