### ISSUE TITLE
I am sure that I have installed this library

### ISSUE THREAD

**Issue by KagurazakaSarah** [olikraus/u8g2#1820]
I am sure that I'm installed this library

_Originally posted by @KagurazakaSarah in https://github.com/olikraus/u8g2/issues/1819#issuecomment-1079568758_

**Comment by KagurazakaSarah** [comment]
<img width="122" alt="image" src="https://user-images.githubusercontent.com/77180635/160221119-c56618b8-1010-4707-95b8-94d772495309.png">

**Comment by olikraus** [comment]
What is the problem? How can we help? You can install u8g2 via the install library menu of the Arduino IDE.

**Comment by KagurazakaSarah** [comment]
But I installed in this way，The problem still exists.

**Comment by olikraus** [comment]
I suggest to (re)install the library.

**Comment by KagurazakaSarah** [comment]
Ok.Problem has been solved.Thanks
