### ISSUE TITLE
Support for Winstar WO12864a1

### ISSUE THREAD

**Issue by JartX** [olikraus/u8g2#1832]
Hi! i want to use that tft, but not works, am using a st7565 for it, have tried all constructors and none of them works,  the screen shows nothing, only can read the "hello world", anything if replug gnd many times, think that have to code the init seqs like: u8x8_d_st7565_lm6059_init_seq[] and u8x8_st7565_lm6059_display_info but dont know to do it.

Many thanks for your time

#include <Arduino.h>
#include <SPI.h>
#include <U8x8lib.h>
U8X8_ST7565_LM6059_4W_SW_SPI u8x8( /* clock=*/ 8, /* data=*/ 9, /* cs=*/ 5, /* dc=*/ 7, /* reset=*/ 6);

void setup(void) {
  u8x8.begin();
}

void loop(void) {
  u8x8.setFont(u8x8_font_chroma48medium8_r);
  u8x8.drawString(0,0,"Hello World!");
  }

Have the datasheet
[11929126.pdf](https://github.com/olikraus/u8g2/files/8445759/11929126.pdf)

**Comment by olikraus** [comment]
> have tried all constructors and none of them works

There seems to be a hardware problem. Check your wiring, connecton, powersupply.

**Comment by JartX** [comment]
@olikraus 
hi! can you check this init code or adapt it? 

The init code has been sent by Winstar
https://pastebin.com/XXUNk4hN

**Comment by JartX** [comment]
![PXL_20220411_133313096 MP](https://user-images.githubusercontent.com/8399211/162751722-a9c23859-5ced-4d4c-9dc7-4237af740ab5.jpg)

**Comment by JartX** [comment]
> looks ok. altough the reason for some resistors are not so clear to me, however, the shouldn't harm. The next question is: How did you solder everything? Additionall: Which Arduino board do you use?
Hi! Arduino Uno

**Comment by olikraus** [comment]
Still looks like a wiring issue...

**Comment by JartX** [comment]
> Still looks like a wiring issue...

I have checked the wiring, I see no errors, any idea?

**Comment by JartX** [comment]
> Still looks like a wiring issue...

Check this video please: https://drive.google.com/file/d/1niOFoMQNFaPg1N1O2fBiV3_Osk4lY9rN/view?usp=sharing

**Comment by JartX** [comment]
https://drive.google.com/file/d/1IVZwIkeP0mjKJLs2W0A3iCJgfwBddg7D/view?usp=sharing

**Comment by olikraus** [comment]
What else can I say? A wiring issue?

**Comment by JartX** [comment]
> What else can I say? A wiring issue?

I have the complete code sent by winstar, could you try to get a constructor? I don't see how to make the screen work, because something only appears when GND is reconnected multiple times

**Comment by olikraus** [comment]
> I have the complete code sent by winstar, could you try to get a constructor? 

constructor? for what? I thought your constructor is "U8X8_ST7565_LM6059_4W_SW_SPI" 
And moreover: The constructor seems to work already.

**Comment by JartX** [comment]
> > I have the complete code sent by winstar, could you try to get a constructor?
> 
> constructor? for what? I thought your constructor is "U8X8_ST7565_LM6059_4W_SW_SPI" And moreover: The constructor seems to work already.

I don't know if it works correctly, from what I show you in the video, maybe some sequence is failing, because the Winstar is different, I used the lm6059 as an example.

https://pastebin.com/wfDsm2wf WO12864a1 example file of winstar for this screen

**Comment by olikraus** [comment]
I checked this already (see above). The constructor should be ok.
I think in your video some text was visible for a moment. This already proves, that the software works correctly.
There is a hardware problem.

**Comment by a8tor** [comment]
how do you solve? is your schematic correct?
