### ISSUE TITLE
SSD1351 support

### ISSUE THREAD

**Issue by dpsproservices** [olikraus/u8g2#1834]
Looking to add support for SSD1351 which is for 1.5inch RGB OLED Display Module, 65K RGB Colors, 128×128, SPI

**Comment by olikraus** [comment]
u8g2 is a library for monochrome displays only.

**Comment by dpsproservices** [comment]
Okay I did not realize that the library is monochrome displays only until looking at the list in the code. Let me know if there will be any future plan to expand into RGB displays. thank you

**Comment by olikraus** [comment]
U8g2 will stay a monochrome lib ;-)
