### ISSUE TITLE
Can I save the prepared font file in Littlefs of esp8266 and call it again

### ISSUE THREAD

**Issue by jie326513988** [olikraus/u8g2#1838]
Can the generated font file be saved to the file system of esp8266? After all, there is up to 3MB of space.

const uint8_t chinese_gb2312[253178] U8G2_FONT_SECTION("chinese_gb2312") = 
  "\272\0\3\2\4\5\5\5\5\17\22\377\375\11\375\12\376\1\235\3\64\7\63\14\6\0 \264\0\15\6\0"
  "\246\243\0 \6\0 \244\0!\10\261\246\273\70D\2\42\10\64\342\265\210L\1#\17\266\340\273\211z"
  "-\315\251\230\14\11\0\64\20\226 \";

**Comment by olikraus** [comment]
You can just add the array to your code.
