### ISSUE TITLE
COMPILING the library U8g2

### ISSUE THREAD

**Issue by paolovr70** [olikraus/u8g2#1843]
Hi,
compiling the library U8g2 the compiler says:

C:\Arduino\libraries\U8g2\src\clib\u8x8_d_s1d15721.c: In function 'u8x8_d_s1d15721_common':
C:\Arduino\libraries\U8g2\src\clib\u8x8_d_s1d15721.c:71:14: warning: variable 'y' set but not used [-Wunused-but-set-variable]
   uint8_t x, y, c;
              ^

Can you fix the bug? 
thanks.
p.

**Comment by olikraus** [comment]
This isn't a bug and can be ignored. I will look into this

**Comment by olikraus** [comment]
looks like that was fixed in #1802 
closing...
