### ISSUE TITLE
Add T6963 128x128 screen mode.

### ISSUE THREAD

**Issue by ospilos** [olikraus/u8g2#1848]
Dear Sir,
Your world-renown graphic library seems to missing support of just and only 128x128 resolution for T6963 based LCDs.
Unfortunately that is exactly what I would find very usefull to me should you've added it.
Nevertheless, I really admire your work anyway, so thank you for devoting your time and effort to the community.
Best regards!
Tomas

**Comment by olikraus** [comment]
Will the 240x128 work for you? If so I could create a constructor for 128x128 based on the 240x128 constructor.

**Comment by olikraus** [comment]
Any feedback back on this? If so, please reopen.
