### ISSUE TITLE
Please provide a way to disable Wire.setClock() in each transaction without modifying the u8g2 library

### ISSUE THREAD

**Issue by Bodobolero** [olikraus/u8g2#1850]
Rationale and a suggested solution are given in this pull request https://github.com/olikraus/u8g2/pull/1849

**Comment by olikraus** [comment]
I2C needs to be tested here.

**Comment by Bodobolero** [comment]
Thanks for your quick response and for incorporating my suggestion.

**Comment by olikraus** [comment]
This seems to be done, so closing...
