### ISSUE TITLE
Query For other language

### ISSUE THREAD

**Issue by I-AM-Tushar-chauhan** [olikraus/u8g2#1857]
Hello sir..
I need some other languages like Hindi,Punjabi,Gujrati etc, but I don't know how the encoding or decoding are done in it.
can you explain me how is it working in u8g2 with english language??

**Comment by olikraus** [comment]
U8g2 support UTF-8, which is the default encoding of gcc and Arduino IDE. In other words you can just enter Hindi or any other glyph as they are and it will be displayed with u8g2.

First step for any language support is to figure out the unicode range of your desired language: For Hindi you need Devanagari glyphs as described here: https://en.wikipedia.org/wiki/Devanagari_(Unicode_block)
The range would be U+0900..U+0954. The next step is to select a suitable font which contains those glyphs.
Unifont is such a font. Once you have there two things, then we can construct the font for u8g2.
In your case Hindi font is already included in u8g2: 

![https://github.com/olikraus/u8g2/wiki/fntpic/u8g2_font_unifont_t_devanagari.png](https://github.com/olikraus/u8g2/wiki/fntpic/u8g2_font_unifont_t_devanagari.png)

**Comment by I-AM-Tushar-chauhan** [comment]
Hello sir,
Thanks for the reply, I can't find out how this (u8g2_font_unifont_t_devanagari) is working because I was accessing the unifont.bdf file and I was making changes into it but I can't find out this type of file (u8g2_font_unifont_t_devanagari)
for unifonts. can you please guide me on how to make it or how to make changes to it??




/*
  Fontname: -gnu-Unifont-Medium-R-Normal-Sans-16-160-75-75-c-80-iso10646-1
  Copyright: Copyright (C) 2014 Roman Czyborra, Paul Hardy, Qianqian Fang, Andrew Miller, et al. Licensed under the GNU General Public License; either version 2 or (at your option) a later version, with the GNU Font Embedding Exception.
  Glyphs: 305/57086
  BBX Build Mode: 0
*/
const uint8_t u8g2_font_unifont_t_devanagari[6002] U8G2_FONT_SECTION("u8g2_font_unifont_t_devanagari") = 
  "\61\0\4\2\5\5\5\5\6\20\20\0\376\12\376\13\377\1\270\3y\5k \6\0@\217\2!\10A"
  "Q\210\302AB\42\11\205H\214B\306M\0#\21FE\210JO\6\203D\244\305`\20\351\11\0$"
  "\24GE\210Nh\240\210D$\241\331(\42\251\30\210\62\0%\27GE\210\206F\222(ID\24\251"
  "X*!ID\22%\32\5\0&\24GE\210\312\246$S\21\22%\42\232\204(\221\221L\2'\7"
  "\201P\214\302 (\15\203\315\207J\42\222\210\364&\222\11)\16\203\311\207B&\222\211\364\42\222\210\0"
  "*\16\347\304\210NIE\233M\242IM\6+\15\347\304\210N\254f\60\310\304j\0,\11\202L\207"
  "\202\42\241\0-\7$H\212\302 .\7BL\210\302 /\15FE\210VQU(\25\252J\1\60"
  "\17FE\210\212&\222\10\371(\21\311H\0\61\14EI\210JF\222\10\365\311@\62\20FE\210\306"
  " \21\22\245\62\232PUj\60\63\22FE\210\306 \21\22\245\42\263\224H\224\30$\0\64\22FE"
  "\210RH\223\210Td\22\231\304`\224\252\0\65\20FE\210\302A\252j K\245D\211A\2\66\20"
  "FE\210\312$\224J\15\24!G\211A\2\67\14FE\210\302UQ\252(\325\4\70\21FE\210\306"
  " \21\62J\14\22!G\211A\2\71\20FE\210\306 \21\62J\14T\215\42\23\0:\11\342\314\210"
  "\302 \66\10;\13\42\315\207\302 \246H(\0<\11%I\210R\246\253\16=\11\246D\211\302=f"
  "\60>\12%E\210B\252\233\216\0\77\17FE\210\306 \21\22\245BU\331T\4@\25FE\210\312"
  "$#I(\22\213\210\42\242\210H\26\261A\0A\17FE\210\212&\322\42$\32\14D\216\2B\20"
  "FE\210\302@\21\62\32,B\216\6\13\0C\17FE\210\306 \21\262\352H\224\30$\0D\17F"
  "E\210\302 \222I\204\374&\61\210\0E\16FE\210\302A\252j\240H\265\32\14F\15FE\210\302"
  "A\252j\240Hu\5G\20FE\210\306 \21\262*\31\204l\24\213\0H\14FE\210B\310\321`"
  " \362(I\14EI\210\302@\22\352'\3\1J\17GE\210\312@\24\353I&\222\311l\0K\23"
  "FE\210BH\223\210TdD\242D&R\223\10\5L\12FE\210B\252\277\32\14M\16FE\210"
  "BH\64\31D\26\36\71\12N\22FE\210Bh\263QD\24\21IB\222\320\34\5O\15FE\210"
  "\306 \21\362G\211A\2P\16FE\210\302@\21\62\32,R]\1Q\31g\305\207\306 \22J\204"
  "\22\241D(\21J\204\22\11EB\42\31\344\4R\22FE\210\302@\21\62\32,\42\65\211L\42$"
  "\12S\17FE\210\306 \21\62s$J\14\22\0T\13GE\210\302A&\326\337\0U\14FE\210"
  "B\310\77J\14\22\0V\23GE\210B\312*\221\211d\42\231\212P\42\25\313\0W\16FE\210B"
  "\310\13\27\223Ad$\12X\21FE\210BH\224\210\264\21i\42-B\242\0Y\20GE\210BJ"
  "\225\310D\62\25\251X\67\0Z\14FE\210\302UQ\257R\203\1[\12\203\321\207\302 \322\77\31\134"
  "\15FE\210B*V\25K\305\252\2]\12\203\305\207\302\244\177\62\10^\12f\304\214\212&\222\10\5"
  "_\10'\304\207\302A\0`\10cH\215B\246\0a\17\6E\210\306 \21J%\6#\33\305\42b"
  "\17fE\210B\252\305B#r\264Q,\0c\16\6E\210\306 \21Ru\224\30$\0d\15fE"
  "\210V\213\205f\344\215b\21e\20\6E\210\306 \21\22\15\6\252\242\304 \1f\15eE\210\216$"
  "T\62\220\204z\2g\25fE\207Vb\241Id\22\231\310&\65H\204D\211A\2h\15fE\210"
  "B\252\305B#\362Q\0i\14eI\210J((\352\223\201\0j\15\245E\207R\241\250\217$\21\11"
  "\0k\22fE\210B\252M\42R\221\21%\62\221\232D(l\12eI\210\206\250\177\62\20m\24\7"
  "E\210\302B\21\211H\42\222\210$\42\211H\42\222\2n\13\6E\210Bb\241\21\371(o\15\6E"
  "\210\306 \21\362Qb\220\0p\20FE\207Bb\241\21\71\332(\26\251\24\0q\15FE\207\306B"
  "\63\362F\261H\25r\14\6E\210Bb\241\21\251\272\2s\16\6E\210\306 \21\222\71J\14\22\0"
  "t\14EE\210J\250d \11u%u\13\6E\210B\310o\24\213\0v\15\6E\210B\310(\21"
  "\351\215H\2w\23\7E\210BJ\22\221D$\21ID\22\221TX\0x\20\6E\210BH\224\210"
  "dD\232H\42$\12y\17FE\207B\310\243D\304\42U\61H\0z\13\6E\210\302U\250W\203"
  "\1{\17\203\315\207\306$\23ID\62\221D$#|\10\301Q\207\302\7\2}\20\203\311\207\202&\222"
  "\210d\42\211H&\262\0~\13gD\214\206F\22\321(\0\177&\20B\7C\242\337#\364\4z\304"
  "d\220\310L\22\241T$\61Hd&\211Pj\62H\14\366\4z\2=\242\77\200'\20B\7C\242"
  "\337#\364\4z\304F\262\230$\42\211H\344 \21\31\204\42\211HQ$\261\320\23\350\11\364\210\376\0"
  "\0\0\0\10\11d\11\206\377\377\11\0\16\210\320\14\317(\243H(&\32\0\11\1\16\210\320\14CD"
  "\224\60\311h&\0\11\2\10B\334\15\303 \11\3\12\242\360\11\303 \62\10\11\4$\356\311\7K|"
  " \317M\6\203D&\242\214\10%\262\215\60#\12\15D!\205*\262\220\15\42bu\10\11\5 \217"
  "\305\7\313\301@\221\211H#J\211n\243\314\250B\3UH!\213,t\203\210Z\236\2\11\6'\217"
  "\305\7\313\301@\221\211\230E\254$\66\33\211*#Q\204\6\22EH!\221D\26\22\315 b)\221"
  "f\22\0\11\7\34\260A\7\303\17\202r\351`)\327\3\16\362\0\251D\231\260\34\314\363\210\24\0\11"
  "\10!\20B\7\333 \253\11\7\7\37\4\345\322\301R\256\7\34\344\1R\211\62a\71\230\347\21)\0"
  "\11\11\32\220\301\7\303\17rz\200\134=\35\10S\302\230\60\245\14I#\333A\16\11\12\36\220\301\7"
  "\303\17rz\200\134=\35H\66)\205\244lS%*\322\250\42\233\334 \7\11\13$\260A\7\303\17"
  "r\312\211P\222\220('\302\301@\66\330\244&\232TH\262TL\25\351D\36\61H\0\11\14!\220"
  "\301\7\303\17\242y@n\25[D\6\42\315 \242\61\62T\245\6\71\211\70\221G\14$\0\11\15!"
  "\20B\7cD\274G\15>\10\31\212\204\42\241H\250\221\346\21y\204\36\241G\344\1r\15\0\11\16"
  "#\20B\7O\36\61\30\344\21\241\301\7!C\221P$\24\11\65\322<\42\217\320#\364\210<@\256"
  "\1\11\17\34\260A\7\303\17B\206\42\241H(\22j\244yD\36\241G\350\21y\200\134\3\11\20\42"
  "\20B\7\323 \217\310#b\203\17B\206\42\241H(\22j\244yD\36\241G\350\21y\200\134\3\11"
  "\21,\357\305\7gD;\310c&\203\201\42\23\61\213XIl\66\22UF\242\10\15$\212\220B\42"
  "\211,$\232A\304R\42\315$\0\11\22-\357\305\7[\36\60\320\3B\223\301@\221\211\230E\254$"
  "\66\33\211*#Q\204\6\22EH!\221D\26\22\315 b)\221f\22\0\11\23,\357\305\7\337\36"
  "\220\7\244&\203\201\42\23\61\213XIl\66\22UF\242\10\15$\212\220B\42\211,$\232A\304R"
  "\42\315$\0\11\24,\357\305\7\343v\221N\204&\203\201\42\23\61\213XIl\66\22UF\242\10\15"
  "$\212\220B\42\211,$\232A\304R\42\315$\0\11\25\37\220\301\7\303\17rr\351B)\31\350\62"
  "\223Xd\20\221-$R\211T\42\325\3r\0\11\26!\220\301\7\303\17B\61]L\27Y\250\26\222"
  "\325\42$\213df\231\205.&\24I%z@\6\11\27\33\220\301\7\303\17r\22\251D*\221J\204"
  "\203\210r\42\225h#r{@\6\11\30\35\220\301\7\303\17B*\235J\70P(C\302\224\60\64\314"
  "\14\222\203\204\334\36\220\1\11\31\32pA\10\303\17\222r\345`\20\224\13c\203\311T\222J)C\322"
  "\201\14\11\32\32\220\301\7\303\17\262r\263\301AR#\324\14%\203\344 !\267\7d\0\11\33$\260"
  "A\7\303\17\262y@l\220\31\204N\62*M(\226I\15$\11\231J\246\232\211$\271AH\256\0"
  "\11\34\34\220\301\7\303\17\262r\313\301 \226\221\350\62\12]F!\34D\344\366\200\14\0\11\35\42\220"
  "\301\7\303\17b\32\245F\66\320\250t*\235lp\20\315\350\24\31YB$[d\264\231\14\0\11\36"
  " \220\301\7\303\17\262r\341F\230\220\250B\212Uh\260\12-d\221\211n\220\221\353\1\31\0\11\37"
  "\25pA\10\303\17\202r\333\201T-\267\7\250\222\203\25\0\11 \31\220\301\7\303\17rr\353\361B"
  "\251\12\306t\61]j\230\231\16T\0\11!\31pA\10\303\17\262r\345`\20\224\353\1\367\0aJ"
  "\31\222\16D\0\11\42\34\220\301\7\303\17\222r\351`\251\226k\224\22E\62\222I&\62Q\211v\220"
  "\2\11#\32\220\301\7\303\17\62\22\63\211\231\304Lb&\261\213\30n\344\356\1\31\0\11$\33\220\301"
  "\7\303\17\262r\303\301@\67\322\251t*\241H\31\222f\264\231\14\0\11%\34\215\315\7\303fp\241"
  "\61\61\212\230MD\203\214H\264\312\14b\203\204\326\70\3\11&\30\220\301\7\303\17\262r\323\301\62n"
  "\244\314$\242\3=\42\217\210\0\11'\35\215\315\7\307dp\222\61\323\310D*\331D%\262\22\211F"
  "\232Al\220\20g\0\11(\26\220\301\7\303\17\262r\303\301@(\22\212\224!\271{@\6\11)\32"
  "\220\301\7\303\17\262r\303\301@(\22\212\224!\271\64\243\234HC\31\0\11*\31\220\301\7\303\17R"
  "\42\241H(\22\212\204\42ef\272\220\273\7d\0\11+ \220\301\7\303\17\42\32\245F\251Qj\6"
  "\62\315$\26\31\305\6\242\244(\251Qj\244\71\0\11,\36\220\301\7\303\17\262r\341@\241\233\14r"
  "\212\214N\22\321i\6\301\301@n\17\310\0\11-\37\216\311\7\303fp\220\20i$!QD\243\32"
  "dt\32\331` \333\350\64b\353\14\0\11.\33\220\301\7\303\17R\42\241H(\22\212\204\42\335\340"
  "P\244\14\311\355\1\31\0\11/\34\220\301\7\303\17b\32\245F\251Qj\204\42ah\230\31$\7\11"
  "\271= \3\11\60\27\220\301\7\303\17\202r\343Ax=\317#\362\210<\42\217\320\0\11\61\27\220\301"
  "\7\303\17\202r\343Ax=\317#\302\231\350&\232\322\0\11\62\36\220\301\7\303\17\262r\331h\265H"
  "\14T\232\205J#\221\331\305\204)\245F\17\310\0\11\63\34pA\10\303\17\242r\365p!\211I\64"
  "\42\215\221\306H#\221E\24\303%\0\11\64\36\260A\7\303\17\242r\365p!\211I\64\42\215\221\306"
  "H#\221E\24\303=D.\3\11\65\34\220\301\7\303\17\262r\345 \241\33Dv*\235h\230\31$"
  "\7\11\271= \3\11\66 \220\301\7\303\17R\42\241H\66\320H%R\211Lb\226\250\221\15B\312"
  "\220\64\243\315d\0\11\67\35\220\301\7\303\17B*\335H\247\310\350$\21\235&\241\23\15\65\323\205\334"
  "\36\220\1\11\70 \220\301\7\303\17b\32\245F\251\321%\64\272AF\267\30\10S\302\224\62$\315h"
  "\63\31\0\11\71\33\220\301\7\303\17\262r\341`\240\223\353\1\212AV\242\324D\365\0=\340\4\11:"
  "\11\202\134\15\303\201\0\11;\17\6j\7\213\310d\60\21\371_E\0\11<\10B\334\7\303 \11="
  "\23i]\10\313`\220\10\6\35\6u\232\310h\20\2\11>\14\246i\7\303\211\310\377*\2\11\77\22"
  "\310A\10\313 \243\311h\6\203\220\314\277\13\1\11@\22\11^\7\307 T\23\212\15V:\377\303\10"
  "\0\11A\14f\320\7CD\222\211,\0\11B\13f\330\7\307$\23\221\4\11C\11d\330\7\207\42"
  "\64\11D\11\243\330\7\307f#\11E\14eT\15C&\21\211(\0\11F\11eP\15Cj\25\11"
  "G\11eP\15\303\252\0\11H\13\206\314\14\307,\61\311\14\11I\21\6j\7C&\62\310\15&\42"
  "\377\253\10\0\11J\21\10b\7Cp\20\14\15F\62\377\273\10\0\11K\20\10b\7\303 X\64\30"
  "\311\374\357\42\0\11L\23\11^\7\307 \64H\344\22\251\301J\347\177\30\1\11M\11e\330\7\303\252"
  "\0\11N\13\244I\7\303\211\377I\6\11O\24\351\335\7Kr\20\211E\6\12\231h\240\363\17\23\0"
  "\11P\42\216\305\10WD\232\260\231d$\231\310\60,\332\214\42\242\214d\64\210\14B\222A$\262\34"
  "\4\1\11Q\10a`\15\303\0\11R\10$X\10\303 \11S\11cX\15C\246\0\11T\11c\134"
  "\15K\242\4\11U\15\245T\14C&\21\211\310\6\2\11V\13FL\7C(\61H\0\11W\17\210"
  "H\7G(\63\210\304\22\203\5\0\11X!\260A\7\303\17\202r\351B)\31\314\62\223Xd\20\221"
  "-$R\211T\242\213H'\331(\0\11Y\42\260A\7\303\17B\61]L\27Y\250\26\222\325\42$"
  "\213df\231\205.&Li#\322I\66\7\11Z\36\260A\7\303\17r\22\251D*\221J\204\203\210"
  "r\42\225h#rmD:\311\346\0\11[\36\260A\7\303\17\262r\313\301 \226\221\350\62\12]F"
  "!\34D\344\332\210t\222\315\1\11\134\32\260A\7\303\17\262r\345`\20\224\353\1\367\0aJ\71\330"
  "\243\345\62\0\11]\34\260A\7\303\17\222r\351`\251\326\14%\222\234$\23TD\224\203=Z\256\3"
  "\11^\42\260A\7\303\17\42\32\245F\251Qj\6\62\315$\26\31\305\6\242\244(\251\221E\64\252I"
  "\66\13\11_\37\260A\7\303\17b\32\245F\251Qj\204\42ah\230\31$\7\11\271\64\243\334D\203"
  "\0\11`#\260A\7\303\17br\251D#\212$$\211\340`\20\34dT\22Q\221F)\221j\226"
  "\231<b\1\11a!\260A\7\303\17\242y@p\20\231i$*\215D\26\23\206\244\21=b\20\225"
  "\353\21\203\10\0\11b\17\250\320\7G$\23\251HE\62A\1\11c\20\310P\7G$\23\251\10e"
  "B\252\240\0\11d\14\202\335\7Cb\360\3E\0\11e\34\205\331\7C$\241\30$\6\211Ab\220"
  "\30$\6\211Ab\220\30$\24\221\0\11f\24\350P\11\313 \23Yh\6\242\201F\61\311\14\42\0"
  "\11g\23\246U\7\307d\221\220\14\42\212\210d\220q\25k\11h\22\251Q\7\303\315&\31\254\323("
  "D\11\325\262\3\11i\24\250Q\7\303\311&W\63\10\226\230$\66\203\134\260\0\11j\31\214\311\7C"
  "\64\21\224\304D!YD\270\264\10Ft\21]D\70\2\11k\27\250Q\7\203L\64\10)B\222\201"
  "J\246Q\204\22\242A\260\1\11l\27\250Q\7\313 \42\313\351\6\252X.#\61\32\244r\301\4\0"
  "\11m\35kM\10C\64\264\311,\24\31M$\223Q\204\6\212`$\27\211\205\64\262\15\0\11n\25"
  "J\315\10\303\203H\260\262J\22\32D\6\222\314&\231\0\11o\25\210\321\7\313H\222\321DD\221\334"
  "(\222\221\31\6\7\2\11p\14\205\330\11\307\42\243I,\0\11q\10B`\13\303 \11r%\357\305"
  "\7[\36\20\11\353&\203\201\42\23\221F\224\22\335F\231Q\205\6\252\220B\26Y\350\6\21\265<\5"
  "\11s#\357\305\7\243\332n\62\30(\62\21iD)\321m\224\31Uh\240\12)d\221\205n\20Q"
  "\313S\0\11t)\357\305\7\263\332f\62\30(\62\21\263\210\225\304f#Qe$\212\320@\242\10)"
  "$\222\310B\242\31D,%\322L\2\11u-\357\305\7c\36\60\10\306\62\223\201B\221\211\311\62\3"
  "\225\304f#Qe$\212\320@\242\10)$\222\310B\242\31D,%\322L\2\11v(\17F\7["
  "\36\20\11\353&\203\201\42\23\221F\224\22\335F\231Q\205\6\252\220B\26Y\350\6\21y.\24\35\4"
  "\1\11w(\17F\7[\36\20\11\353&\203\201\42\23\221F\224\22\335F\231Q\205\6\262\310B\67\210"
  "\350B\303A\62\26\34\354\0\11x\22\220\301\7\303\17\62r\353\301\335h\356\265<\6\11y\36\220\301"
  "\7\303\17\262r\313\301 \226\221\350\62\12]F!\34D\344\272LD\231\312\0\11z\35\220\301\7\303"
  "\17b\32\245F\251QN\204\222\204\60\64\314\14\222\203\204\334\36\220\1\11{\34\220\301\7\303\17r\22"
  "\251D*\221J\204\203\210r\42\225h#r\273\301\15\0\11|\35\220\301\7\303\17\262r\313\301 \226"
  "\221\350\62\12]F!\34D\344f\203\203\14\0\11}\25\250Q\7\307@\262I\250re\222\201f\20"
  "\222\271\13\1\11~\34\260A\7\303\17\262r\345`\20\224\353\1\367\0aJ\31\222\16\364\310\301\201\2"
  "\11\177\36\220\301\7\303\17\262r\341@\241\233\14r\212\214N\22\321i\6\301\301@n\67\270\1\34\320"
  "\12e\330\15K&Q\23\34\321\12e\330\15Kf\321\0\34\322\10%X\16\303@\34\323\14fT\15"
  "KE$\21\211\0\34\324\10#h\13\303\0\34\325\16hP\7C&\222\210\224(\24\0\34\326\11F"
  "T\7Cj\60\34\327\12fT\7\207&\66\20\34\330\14fT\7C(\221\211,\0\34\331\12eX"
  "\7K&Q\23\34\332\11c\334\15C\302\42\34\333\14e\330\15C\42\241H(\12\34\334\10a`\7"
  "\303\0\34\335\10!\340\7C\0\34\336\10$\334\7C$\34\337\11'\324\7C\244\0\34\340\12f\340"
  "\15\307`\246\1\34\341\20\10b\7\223*\22\312\324\365\77\32\204\0\34\342\15\246\324\11G$\67\330E"
  "\22\0\34\343\13\244\344\12G\250f\220\0\34\344\12\244\314\12K\233\320\0\34\345\13\244\314\10\307 \23"
  "\252\0\34\346\13\244\344\10\303(\23)\1\34\347\15\345\344\12\213\244\42U\224\230\0\34\350\16\345\310\7"
  "\313\42\224\252\210D$\0\34\351\27+\311\10\213F\23ID\22\11\215Bi\231\310eR\251\201\6\34"
  "\352\25I\315\10K\246\242I\242M\253D\316.\221\312\14$\0\34\353\27I\315\10KF\222(I\224"
  "LR\211\230\316.\221\312\14$\0\34\354\35K\315\10K\62\221\11%\42\211P&\221IIr\212\134"
  "B\26I\204\42\231A\12\34\355\11\204\134\7C\250\1\34\356\21'Q\11\307 \22\253\233$b\65\231"
  "\11\0\34\357\24&Q\11\307 \21\222db\203D*\221\211d$\0\34\360\26gU\11\213(\222\311"
  "e\42\242HQ\42\224\10E\212\64\0\34\361\21(\321\10K\254(\22\34\14#\241X\11\0\34\362\14"
  "\244\360\11C$!SD\2\34\363\13\204p\12C(Q\241\1\34\364\14fL\15C(\221\211,\0"
  "\34\365\22%\331\10CF\223(Id*\42\211\32M\0\34\366\21\7\315\10C$\42\251\260GXD"
  "\42\222\2\34\367)\316\305\7\303_\14\62\3\311bpqpq\60\320\34\374\17D\242Ab\60P\14"
  "\62\3\305@\61X\14\26\203\305\340\7\34\370\14\204\324\14\207\42\42I(\0\34\371\21\213\310\14\207J"
  "\21\311D$\231HB\245\0\34\372+\316\305\7\303_\14\62\3\311bpqpq\60\320\34\374\17D"
  "\242Ab\240P\14\62\243Ab\240P\14\22\3\205b\360A\0\34\373)\316\305\7\303_\14\62\3\311"
  "bpqpq\60\320\34\374\17D\232\201b\240P\14\62\7\212\201B\61H\14\64\203\17\4\34\374+"
  "\316\305\7\303_\14\62\3\311bpqpq\60\320\34\374\17D\233Ab\240\30\14\62\213\301 \61P"
  "\14\6\211\301f\360A\0\34\375+\316\305\7\303_\14\62\3\311bpqpq\60\320\34\374\17D\232"
  "\201b\240P\14\62\13\305 \61P(\6\211\201f\360\201\0\34\376)\316\305\7\303_\14\62\3\311b"
  "pqpq\60\320\34\374\17D\242Ab\240\30\14\62\7\212\201b\60H\14D\203\17\2\34\377)\316"
  "\305\7\303_\14\62\3\311bpqpq\60\320\34\374\17D\242Ab\240\30\14\62\7\212\201b\60H"
  "\14\24\203\37\4\250\340\14\204\330\14\207\42\42I(\0\250\341\13\304X\14\207\42\222\60*\250\342\13\304"
  "X\14\207\42\322\250\0\250\343\14\344\334\13\203(!J\210\12\250\344\15\245T\14C&QS\221\211\0"
  "\250\345\17&\335\12C\252$\263\212\245b\251\0\250\346\15\345\334\13\207$%I\215R\1\250\347\17\246"
  "\324\14C&\21Ih\24\231\310\2\250\350\13\244\334\14K\233HB\1\250\351\15\304\134\14\207\42\222\320"
  "\204\62\1\250\352\21\251\310\14\307d\24\311h\22\231Ad\223\0\250\353\16\246\324\14\303Q\42\222\211d"
  "$\0\250\354\20\310P\14\303\201(\65\212l&\241H\0\250\355\16\346\324\13\303Qd\220\310\244Z\0"
  "\250\356\14\306P\14\303E\244\315\252\2\250\357\14\306T\14\303MH\24\253\0\250\360\23\347\320\13\213("
  "\65\30$\42\222DID\222I\0\250\361\14\245\334\14\313\42\25)\221\0\250\362\17\210P\13C&\222"
  "HE\64\241\5\0\250\363\21IQ\10C&R\225\321\244\366\200ea\1\250\364\24\210U\7C&\21"
  "\321\204\246\231DD\23\232\13\353\2\250\365\22i\321\7C&R\225\321\244\366\200e\60\246,\250\366\25"
  "\210Q\7C&\222HE\64\241\365\60\64\14\315\202\11\0\250\367\24HQ\10C&\222HE\64\241\365"
  "(\230\212\244\64\0\250\370\26*\321\10\307F\221\212\250\42\211MB\67\324ER\241\201\6\250\371\22*"
  "\321\10\333,\223\254X\11u\221Th\240\1\250\372\13e\330\14C&Q\23\1\250\373\11\60@\15\303"
  "\17\2\250\374,\316\305\7\303\17B\223\201\302\305 \64\31(\134\14\22\212\311\340\377h\63H\14\24\203"
  "Af\61\30$\6\212\301 \61\330\14>\10\250\375,\316\305\7\303\17B\223\201\302\305 \64\31(\134"
  "\14\22\212\311\340\377H\63P\14\24\212Af\241\30$\6\12\305 \61\320\14>\20\250\376+\316\305\7"
  "\303\17B\223\201\302\305 \64\31(\134\14\22\212\311\340\377H\64H\14\24\203A\346@\61P\14\6\211"
  "\201h\360A\0\250\377+\316\305\7\303\17B\223\201\302\305 \64\31(\134\14\22\212\311\340\377H\64H"
  "\14\24\203A\346@\61P\14\6\211\201b\360\203\0\0";

**Comment by olikraus** [comment]
>  I can't find out how this (u8g2_font_unifont_t_devanagari) is working 

use `u8g2.setFont(u8g2_font_unifont_t_devanagari)`

**Comment by I-AM-Tushar-chauhan** [comment]
file-path
u8g2->csrc->u8g2_fonts.c 

> use `u8g2.setFont(u8g2_font_unifont_t_devanagari)`
this Devanagari fonts are coming from the file path which I mentioned above. basically, I need to know how that file is generated so I will change the text's height and width and shape.

**Comment by olikraus** [comment]
> I need to know how that file is generated ...

https://github.com/olikraus/u8g2/blob/2005154785e5c9431770348b93a399c928622052/doc/faq.txt#L252-L272

**Comment by I-AM-Tushar-chauhan** [comment]
> 

Thank you, sir,
you gave me your precious time.
