### ISSUE TITLE
How to setup u8g2 library for the chinese LED matrix panels

### ISSUE THREAD

**Issue by Nischal-Poudel** [olikraus/u8g2#1859]
Hello, I am using the PXMatrix library to control the P2.5 128*64 LED panel from China, and I want to use this library to display the Devanagari characters into the display but here in the library, I noticed that you have made a constructer for each display, so here, how can I add my led panel and get it working. I hope you will respond back soon

**Comment by olikraus** [comment]
Any link?

**Comment by olikraus** [comment]
U8g2 does not support RGB Displays

**Comment by Nischal-Poudel** [comment]
can I use just a single colour and display the Devanagari fonts??

**Comment by olikraus** [comment]
Please check the list of supported display controllers.
