### ISSUE TITLE
u8g2 support for 2.9" eInk ePaper Display with SSD1675A controller?

### ISSUE THREAD

**Issue by Wookbert** [olikraus/u8g2#1863]
Besides a [1.54" eInk SSD1681 display](https://www.buydisplay.com/black-1-54-inch-200x200-e-paper-display-module-for-arduino-raspberry-pi) which [obviously seems to be supported](https://github.com/olikraus/u8g2/issues/1717), we've just purchased a 2.9" eInk SSD1675A display.

The SSD1675A IC ([datasheet](https://www.buydisplay.com/download/ic/SSD1675A.pdf)) is unfortunately not included in the [full list of currently supported controllers](https://github.com/olikraus/u8g2/wiki/u8g2setupcpp).

Any chance to get support for this display?

![image](https://user-images.githubusercontent.com/3104762/168072657-a130ab11-12c2-452a-a265-d2dbc3bf4873.png)
![image](https://user-images.githubusercontent.com/3104762/168072716-04d6c3fa-074a-40f8-8ae4-d3ad3fe326f8.png)

**Comment by Wookbert** [comment]
Saw meanwhile in another issue here, that you've recommended other eInk libs already back in 07.2020. Back then you'd mentioned [GxEPD2](https://github.com/ZinggJM/GxEPD2). Still your recommendation?

**Comment by olikraus** [comment]
Yes. U8g2 Fonts can be used via u8g2 for adafruit gfx lib.

**Comment by Wookbert** [comment]
Do you by chance know if GxEPD2 supports eInks from other manufacturers which have the same specs and in particular use the same driver IC? (I'd ask in the GxEPD2 reposititory, but it seems that they have "Issues" diabled).

To be specific: Bought BuyDisplay(EastRising) [ER-EPM027-1B](https://www.buydisplay.com/black-2-7-inch-e-paper-display-module-for-arduino-raspberry-pi), which is very similar to the supported Good Display [GDEW027W3](https://www.good-display.com/product/235.html) (both driven by [EK79652](https://www.buydisplay.com/download/ic/EK79652AC.pdf)). Sorry for asking.

**Comment by olikraus** [comment]
I think you could just try that display. Maybe @ZinggJM can tell...

**Comment by Wookbert** [comment]
In case @ZinggJM should actually see this, there are two displays which we’d like to run with GxEPD2:

- 1.54": BuyDisplay(EastRising) [ER-EPM0154-2B](https://www.buydisplay.com/black-1-54-inch-200x200-e-paper-display-module-for-arduino-raspberry-pi) ... very similar to Good Display [GDEY0154D67](https://www.good-display.com/product/388.html) (both driven by [SSD1681](https://www.buydisplay.com/download/ic/SSD1681.pdf))
- 2.7": BuyDisplay(EastRising) [ER-EPM027-1B](https://www.buydisplay.com/black-2-7-inch-e-paper-display-module-for-arduino-raspberry-pi) ... very similar to Good Display [GDEW027W3](https://www.good-display.com/product/235.html) (both driven by [EK79652](https://www.buydisplay.com/download/ic/EK79652AC.pdf))

**Comment by ZinggJM** [comment]
@Wookbert Hi,
Yes, I noticed it, I think I am subscribed and get an e-mail notification.
The best place to look for supported displays and controllers in GxEPD2 is
https://github.com/ZinggJM/GxEPD2/blob/master/examples/GxEPD2_Example/GxEPD2_display_selection_new_style.h

I am currently in medical treatment at a place far from home, and I just have my notebook with me.
I will need to reduce my engagement for support of e-paper displays a bit, to reduce the amount of time used for this.
I am still interested in supporting displays that are similar to the Good Display or Waveshare ones, but this will be slower than I would like to. Actually I have about 6 displays donated to me, waiting for support.

Jean-Marc

**Comment by Wookbert** [comment]
@ZinggJM Thanks for your swift reply ... and hope you get better and recover quickly.

I've checked the compatibility list of course, and it's clear that your focus so far have been on the eInk modules from Good Display and Waveshare.

But anyhow: My mentioned modules from
BuyDisplay use the same driver IC as the same spec Good Display modules, so couldn't it be that your library just works right out of the box, without further modification?

**Comment by ZinggJM** [comment]
@Wookbert Thank you for your wishes. I am in the process of recovery. One sign for this is my answer:

> so couldn't it be that your library just works right out of the box, without further modification?

Yes, that may well be the case. But  right now this is easier for you to check than for me.

**Comment by Wookbert** [comment]
The displays are on their way from China. We'll give it a try and report here.
