### ISSUE TITLE
How to prepare commit to release?

### ISSUE THREAD

**Issue by pikot** [olikraus/u8g2#1864]
Hi! I try to adapt my code which I added to u8g2_arduino library https://github.com/olikraus/U8g2_Arduino/pull/10 to main u8g2 library.
Is any good practices to prepare code to release exist?   Correct me if i'm wrong about workflow:
1)  I add  my driver to tools/codebuild/codebuild.c, 
 2)  I prepare release for arduino by this script tools/release/arduino/create_release.sh
3) I test it on my device

maybe some uinttests exist, which I haven't found? )

**Comment by olikraus** [comment]
Pull requests should go to u8g2.
I can do the code build topics for you.

**Comment by pikot** [comment]
I created pull request -> https://github.com/olikraus/u8g2/pull/1866. It tested with generated Arduino library in my project)

**Comment by olikraus** [comment]
I like the work on codebuild.c
But I probably need some time to investigate this. Unfortunately I have not much time for this project at the moment..

**Comment by olikraus** [comment]
Due to increased code size, I decided not to include the PR. Please excuse.
