### ISSUE TITLE
Support st7920 with 160x32

### ISSUE THREAD

**Issue by BrainHunter** [olikraus/u8g2#1873]
Hi there,

Can you please add support for the ST7920 with 160x32 Pixels?

I tested the helloworld example with the 192x32 Mode which works, but this wastes some RAM and i have No idea If there are other downsides.

For reference:
https://www.pollin.de/p/grafik-lcd-powertip-pg-16032lru-bwh-h-p2-121826

Thanks

**Comment by olikraus** [comment]
Any image of the 192x32 constructor? Is everything displayed correctly?
If so, I can indeed just reduce the width from192 to 160

**Comment by shlyakpavel** [comment]
Please, keep 192
We use it!

**Comment by olikraus** [comment]
I would have created a 160x32 constructor ADDITIONALLY.
Is the 160x32 still needed?

**Comment by BrainHunter** [comment]
Hi there,

With the 192x32 constructor everything looks fine for me, so it would be nice if you could add the 160x32 constructor. 
Thanks!

Sorry for the Closing and reopen.

**Comment by olikraus** [comment]
I have created u8g2 beta release 2.33.4. It includes the 160x32 constructor. 
Can you do a test with the new constructor? If you run the flipmode example in page mode, then there should be a frame visible all the time close to the border.

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by BrainHunter** [comment]
Hi there,
i finally got to test the new constructor.
Works fine!

Thanks for your fast help and of course for the great library!

**Comment by olikraus** [comment]
Great, thanks for the feedback
