### ISSUE TITLE
drawButtonUTF8 changes the font mode

### ISSUE THREAD

**Issue by f-zach** [olikraus/u8g2#1880]
https://github.com/olikraus/u8g2/blob/b126be4ea7379cdb1e26d2bc8c48809d6f3b0341/csrc/u8g2_button.c#L189

Hey there,
it would be very nice if it was mentioned in the documentation that `drawButtonUTF8` will change the font mode. It caused me a little confusion at first, especially since nothing about it is the reference manual. Or is there a possibillity to change the function in a way that the font mode is changed back the original setting, before the funciton is called?
Not a huge problem in my opinion, but it would avoid confusion when using the function

**Comment by olikraus** [comment]
Thanks for pointing this out. I have updated the documentation.
