### ISSUE TITLE
Virtural Display and SSD1320

### ISSUE THREAD

**Issue by BiatuAutMiahn** [olikraus/u8g2#1895]
Hello I am currently attempting to create a virtual buffer with the size of 320x132, and draw 0,0,160,132 to one display and 160,0,160,132 to the other display. yet I can't seem to find anyway to even create a virtual display/buffer.

Any pointers? Thank you

**Comment by olikraus** [comment]
> Any pointers? Thank you

Multiple approaches are thinkable:
 - Create your own low level device which in turn redirects messages to both sub displays except for DRAW_TILE which is sent to only one display depending on the tile position. Buffer allocation would happen via codebuild.c generated  function. Solution must be found to avoid that the sub displays share the same memory.
 - Create your own u8g2_ll_hvline_vertical_top_lsb which then draws to one of the real displays (or both). Probably no extra buffer required, but still we have to ensure that the sub displays do not share memory.
 - Create an high level api, similar to the existing u8g2 interface, where both displays are accessed (similar to the examples in the original issue). No buffer allocation required. Solving the buffer sharing of the sub displays may simplify the code (only one loop required).
