### ISSUE TITLE
Project dependant u8g2.h (U8G2_16BIT)

### ISSUE THREAD

**Issue by softfoot** [olikraus/u8g2#1899]
I have a number of projects some of which have LCDs that need U8G2_16BIT to be uncomented in U8G2.h

Rather than modify the copy in the library is it possible to have a local copy with the arduino project code ??
If so, how ??

I tried including a copy from the local directory into the project code with "" but it didnt seem to work.

Dave

**Comment by olikraus** [comment]
Most user just modify the local copy of u8g2. Of course your local update gets overwritten with any update of u8g2.
