### ISSUE TITLE
some font request

### ISSUE THREAD

**Issue by leonardowolf** [olikraus/u8g2#1904]
I'm having a hard time porting my own fonts since um using a 256x64 display wich would need a 12x16 font to work as 4 lines. The U8G2 lib have a great set of pre-loaded fonts but none of those could fulfill my need since i'm looking for a monospaced with no transparent background. So i was wondering if theres a way to use some of those:
https://github.com/lynniemagoo/oled-font-pack
http://www.rinkydinkelectronics.com/r_fonts.php
wich are already in C-type standard font, but the matrix style on the font files show me that they are different from those fonts in the u8g2 lib
is there a way to convert them?

**Comment by olikraus** [comment]
> ith no transparent background.

Transparency can be controlled with the FontMode command. 

The mentioned fonts can not be converted with existing tools.
Maybe you can describe a little bit better your problem.

**Comment by leonardowolf** [comment]
I thank your help, did manage to create my own fonts using this tutorial:
https://learn.adafruit.com/custom-fonts-for-pyportal-circuitpython-display/conversion
and the bdfconv on my linux env

my trouble were to use this display:
https://octopart.com/nhd-3.12-25664ucb2-newhaven+display-20012482?gclid=EAIaIQobChMInMLR2qvG-AIVGNWRCh0few72EAAYASAAEgJolPD_BwE

and i couldn't figure out how to make the available fonts not transparent, even with the fontmode cmd. I found out that the Monospaced fonts had the "glyph background" setted to zero but the fonts in which there is no "_m_" on the font name the font transparency where applied. My application relies on this nontransparent mode to update the screen only on certain regions (...a very specific application requirement...)

Thank you for your support and for this amazing library, works like a charm on my STM32 projects
