### ISSUE TITLE
multiple i2c devices

### ISSUE THREAD

**Issue by hbrezner** [olikraus/u8g2#1906]
any known issues with using u8g2/u8x8 in i2c mode with another i2c device on same bus?

**Comment by olikraus** [comment]
There might be two issues:
 1. Mixing HW I2C with software emulated I2C: If you use SW_I2C U8g2 constructor, then the I2C is emulated via software bit banging. This usually will not work with other I2C devices on the same pins (see also the U8g2 FAQ). 
 2. Mixing devices with different speed: Displays usually support fast I2C which is then also enabled by u8g2. On the other side many sensors do not support fast I2C. It might be required to advice U8g2 to use slow speed (setBusSpeed, see U8g2 User Manual)
