### ISSUE TITLE
SSD1309

### ISSUE THREAD

**Issue by NA7KR** [olikraus/u8g2#1916]
The display is only shown the top 1/2 of the words and the second line is not displayed.( if remove second line still same)
```
//U8G2_SSD1309_128X64_NONAME0_1_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 18, /* data=*/ 23, /* cs=*/ 5, /* dc=*/ 16, /* reset=*/ 17);  
U8G2_SSD1309_128X64_NONAME0_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 5, /* dc=*/ 16, /* reset=*/ 17); 

void setup(void) {
  Serial.begin(115200);
  u8g2.begin();
}

void loop(void) {
  u8g2.setFont(u8g2_font_ncenB14_tr);
  u8g2.setCursor(0, 14);
  u8g2.print("Hello 1");
  u8g2.setCursor(0, 28);
  u8g2.print("Hello 2");
  u8g2.sendBuffer();
}
```
Tried different fonts and Cursor settings 
Screen is https://www.amazon.com/dp/B09LND6QJ1?psc=1&ref=ppx_yo2ov_dt_b_product_details

>
![2022-07-20 10_25_26-IMG_1227 (002) jpg ‎- Photos](https://user-images.githubusercontent.com/6289433/180045000-5b771f56-2f16-408c-a347-0fd46cbf3f3c.png)

Same with, is the screen bad? 
```
#include <Arduino.h>
#include <U8g2lib.h>

U8G2_SSD1309_128X64_NONAME0_1_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 18, /* data=*/ 23, /* cs=*/ 5, /* dc=*/ 16, /* reset=*/ 17);  
//U8G2_SSD1309_128X64_NONAME0_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 5, /* dc=*/ 16, /* reset=*/ 17);  
//U8G2_SSD1309_128X64_NONAME2_1_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);  
//U8G2_SSD1309_128X64_NONAME2_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8); 

void setup(void) {
  u8g2.begin();
}

void loop(void) {
  u8g2.clearBuffer();					// clear the internal memory
  u8g2.setFont(u8g2_font_ncenB08_tr);	// choose a suitable font
  u8g2.drawStr(0,10,"Hello World!");	// write something to the internal memory
  u8g2.sendBuffer();					// transfer internal memory to the display
  delay(1000);  
}
```

**Comment by olikraus** [comment]
Use the F (full buffer) constrictor.

**Comment by NA7KR** [comment]
I have tried all 4 1309

**Comment by NA7KR** [comment]
I see U8G2_SSD1309_128X64_NONAME0_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 5, /* dc=*/ 16, /* reset=*/ 17); 
I have to edit 1 to F 

Thanks

**Comment by olikraus** [comment]
Further reading: 

https://github.com/olikraus/u8g2/blob/7395c6857f3ade38a636b67365427178ad528dfa/doc/faq.txt#L134-L142

full buffer drawing:
https://github.com/olikraus/u8g2/wiki/u8g2reference#sendbuffer
page buffer drawing:
https://github.com/olikraus/u8g2/wiki/u8g2reference#firstpage
