### ISSUE TITLE
Display shows empty line

### ISSUE THREAD

**Issue by klerone** [olikraus/u8g2#1917]
Hello Oliver, great job with this library thank you for sharing your work with us.

I have a problem with an lcd PCD8544 that leave an empty line when printing text or anything other than drawFrame and drawLine.

Here i attach a picture to show you the problem I already look over the internet but cannot find anything related. 

It is connected to 3.3V, hardware SPI, 3.3V @8Mhz atmega328P. 

![image](https://user-images.githubusercontent.com/13896253/180407229-27030319-bf92-4e85-b9ad-449aa04003af.jpeg)
![image](https://user-images.githubusercontent.com/13896253/180407396-4e40b1b0-2010-4d69-b75c-976b385b8ad8.jpeg)
![image](https://user-images.githubusercontent.com/13896253/180407539-fbd2c464-344d-4518-b526-543f8bfda3cd.jpeg)

Also i have the same problem with an LcD with ST7588 over I2C 

I am not sure if this may be a hardware related problem.

**Comment by olikraus** [comment]
strange... I have never seen such bugs

**Comment by klerone** [comment]
Well, I will get some samples soon to test. I will let you know.

Best regards.

Fran Calero.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
