### ISSUE TITLE
如何驱动1315

### ISSUE THREAD

**Issue by SunchinSekian** [olikraus/u8g2#1920]
网上说和1306兼容，但我自己测试发现似乎不是这样

**Comment by olikraus** [comment]
English please

**Comment by SunchinSekian** [comment]
> English please

sorrry,my English is poor.I want to say that are ssd1315 and ssd1306 compatible.I search the internet,somepeople said yes,but i can't make it

**Comment by olikraus** [comment]
My own English is also not good 🤪
In order to help we need more information, like the code you have used and a picture of your setup / wiring.
