### ISSUE TITLE
User selection list get flip the whole content, when cursor reach second option

### ISSUE THREAD

**Issue by Mohammad1098** [olikraus/u8g2#1924]
Hi,

I'm using SSD1309 with buffer (_f) and custom MCU interface (8080 parallel port)
used font : u8g2_font_t0_14_tr

I'm a little bit confusing, when I use `UserInterfaceSelectionList()` with fonts less than 14 height, all content on OLED get flipped when I press next button (reach second option), However if I press previous button (reach to last option) everything looks good, but it's also get flipped when I press previous button again (reach to before last option).

I tried to follow the implementation of this function, I found when I increment the return value of `u8g2_draw_selection_list_line` by +3 this fix the issue for me.

any suggestions why this issue is happen to me?

**Comment by olikraus** [comment]
I have tested this with a very tiny font but still all is ok. Can you provide the source code?
