### ISSUE TITLE
Add support for LC7981 with monochromatic 240x128

### ISSUE THREAD

**Issue by premekj** [olikraus/u8g2#193]
Hi,
    could you please add support for LC7981 with monochromatic 240x128 display? I am currently using u8glib (U8GLIB_LC7981_240X128) on two projects and I would like to migrate to new library.
Thanks!

**Comment by olikraus** [comment]
ok, i will have a look.

**Comment by olikraus** [comment]
I have added support for the 240x128... please do some tests:

https://github.com/olikraus/U8g2_Arduino/archive/master.zip

Install the zip lib via Arduino Lib Manager in the Arduino IDE.

**Comment by premekj** [comment]
I did some tests on fonts, lines, etc and it works perfectly, really big thanks!

**Comment by olikraus** [comment]
Great, thanks for the feedback.

**Comment by olikraus** [comment]
Close
