### ISSUE TITLE
Can it be adapted to JLX384160G?

### ISSUE THREAD

**Issue by sddtly** [olikraus/u8g2#1932]
ST7586S

**Comment by sddtly** [comment]
`
u8g2.drawLine(0, 0, 383, 159);
u8g2.drawLine(0, 159, 383, 0);

u8g2.setFont(u8g2_font_ncenB24_te);
u8g2.drawStr(30,60,"Hello World!");

u8g2.drawFrame(10, 10, 363, 139);
`


U8G2_ST7586S_S028HN118A_F_4W_HW_SPI u8g2(U8G2_R0, 5, 4 ,2);

![Uploading QQ图片20220812172709.png…]()

**Comment by sddtly** [comment]
U8G2_ST7586S_ERC240160_F_4W_HW_SPI u8g2(U8G2_R0, 5, 4 ,2);

![20220812173413](https://user-images.githubusercontent.com/43664310/184327405-b5616169-0543-4131-b3a9-0d08a883256d.jpg)

**Comment by sddtly** [comment]
U8G2_ST7586S_YMC240160_F_4W_HW_SPI u8g2(U8G2_R0, 5, 4 ,2);

![20220812173639](https://user-images.githubusercontent.com/43664310/184327833-b4d37712-2548-466b-a984-26455ae19a61.jpg)

**Comment by sddtly** [comment]
All photos were taken after power off and restart

**Comment by olikraus** [comment]
So your request is to get a new constructor for your display, right?
We could use the first constructor as a base for this: https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_st7586s_s028hn118a.c

Is there any datasheet for your display available?

**Comment by sddtly** [comment]
thank you but it doesn't seem to work

[u8x8_d_st7586s_s028hn118a.c.txt](https://github.com/olikraus/u8g2/files/9316224/u8x8_d_st7586s_s028hn118a.c.txt)

**Comment by sddtly** [comment]
> 谢谢，但它似乎不起作用

谢谢，但它似乎不起作
[u8x8_d_st7586s_s028hn118a.c.txt](https://github.com/olikraus/u8g2/files/9316254/u8x8_d_st7586s_s028hn118a.c.txt)
用

**Comment by sddtly** [comment]
> So your request is to get a new constructor for your display, right? We could use the first constructor as a base for this: https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_st7586s_s028hn118a.c
> 
> Is there any datasheet for your display available?

thank you but it doesn't seem to wor
[u8x8_d_st7586s_s028hn118a.c.txt](https://github.com/olikraus/u8g2/files/9316257/u8x8_d_st7586s_s028hn118a.c.txt)
k

**Comment by sddtly** [comment]
[JLX384160G-973-PN(不带字库).pdf](https://github.com/olikraus/u8g2/files/9316295/JLX384160G-973-PN.pdf)

**Comment by sddtly** [comment]
> 所以你的要求是为你的显示器获取一个新的构造函数，对吧？ 我们可以使用第一个构造函数作为基础：[https ://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_st7586s_s028hn118a.c](https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_st7586s_s028hn118a.c)
> 
> 是否有适用于您的显示器的数据表？

![20220813014631](https://user-images.githubusercontent.com/43664310/184414796-76eb5ce3-ab88-4589-9134-bc5da0560325.jpg)
[u8x8_d_st7586s_s028hn118a.c.txt](https://github.com/olikraus/u8g2/files/9328912/u8x8_d_st7586s_s028hn118a.c.txt)

**Comment by sddtly** [comment]
已解决，感谢，修改u8g2_m_48_17_f的参数

**Comment by olikraus** [comment]
> Solved, thanks, modify the parameters of u8g2_m_48_17_f

It is more complicated. My plan is to update the code in u8g2 accordingly and create a new constructor for you.

**Comment by sddtly** [comment]
> 

thank you very much

**Comment by olikraus** [comment]
I have created new beta release 2.33.10
It includes the new constructor U8G2_ST7586S_JLX384160...
Can you test the FlipMode example for the page mode examples list? There should be a solid frame at the display border all the time. Remember to put u8g2 into 16 bit mode (see FAQ)

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by sddtly** [comment]
U8G2_ST7586S_S028HN118A_F_4W_HW_SPI u8g2(U8G2_R0, 5, 4 ,2);

u8g2.drawLine(0, 0, 383, 159);
    u8g2.drawLine(0, 159, 383, 0);

    u8g2.setFont(u8g2_font_ncenB24_te);
    u8g2.drawStr(30,30,"Hello World!");

    u8g2.drawFrame(10, 10, 363, 139);
    u8g2.drawFrame(0, 0, 384, 160);

    u8g2.setFont(u8g2_font_6x13_mr);
    u8g2.setCursor(15, 70);
    u8g2.printf("getDisplayHeight: %d",u8g2.getDisplayHeight());
    u8g2.setCursor(15, 85);
    u8g2.printf("getDisplayWidth:  %d",u8g2.getDisplayWidth());

    u8g2.setCursor(15, 100);
    u8g2.printf("getBufferTileHeight: %d",u8g2.getBufferTileHeight());
    u8g2.setCursor(15, 115);
    u8g2.printf("getBufferTileWidth:  %d",u8g2.getBufferTileWidth());
![20220814114634](https://user-images.githubusercontent.com/43664310/184521635-9b0675bf-ac41-48e2-ae22-aa1fc31f733b.jpg)

**Comment by sddtly** [comment]
U8G2_ST7586S_JLX384160_F_4W_HW_SPI u8g2(U8G2_R0, 5, 4 ,2);

![20220814114634](https://user-images.githubusercontent.com/43664310/184521686-99b0b65a-b042-45c7-a753-aabf797b938b.jpg)
[main.txt](https://github.com/olikraus/u8g2/files/9332665/main.txt)

**Comment by sddtly** [comment]
u8x8_d_st7586s_jlx384160.c    
line 173            U8X8_A(0x087), // should be 0x87 but caused flicker 0x9F 
Normal after changing 0x87 to 0x9f

**Comment by sddtly** [comment]
> FlipMode
谢谢你，现在看起来一且正常
![20220814121328](https://user-images.githubusercontent.com/43664310/184522200-06c20a43-a3b1-46f8-bbca-862814b1df09.jpg)

**Comment by olikraus** [comment]
Ah, I will change this, thanks

**Comment by sddtly** [comment]
> thanks

thanks

**Comment by sddtly** [comment]
> Ah, I will change this, thanks



> thanks



> Ah, I will change this, thanks

thanks

**Comment by sddtly** [comment]
> Ah, I will change this, thanks

thanks

**Comment by olikraus** [comment]
I have created beta 2.33.11

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by sddtly** [comment]
> I have created beta 2.33.11
> 
> You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip Arduino IDE:
> 
> 1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
> 2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).
> 
> PlatformIO: `platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include
> 
> ```
> lib_deps =
>   u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
> ```

olikraus/U8g2@^2.33.11
very perfect，thank you for your dedication
![20220815094447](https://user-images.githubusercontent.com/43664310/184564460-f73b7732-87c3-4f91-9da0-6a2e7bdfc1a0.jpg)

**Comment by olikraus** [comment]
nice, thanks for testing

**Comment by mspudi** [comment]
> > 我已经创建了测试版 2.33.11
> > 您可以从这里下载最新的U8g2测试版：https://github.com/olikraus/U8g2_Arduino/archive/master.zip Arduino IDE：
> > 
> > 1. 删除现有的U8g2_Arduino库 （https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
> > 2. 通过Arduino IDE安装U8g2_Arduino Zip文件，添加zip库菜单（https://www.arduino.cc/en/Guide/Libraries）。
> > 
> > PlatformIO：（https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps）应包括`platformio.ini`
> > ```
> > lib_deps =
> >   u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
> > ```
> 
> 奥利克劳斯/U8g2@^2.33.11 非常完美，感谢您的奉献 ![20220815094447](https://user-images.githubusercontent.com/43664310/184564460-f73b7732-87c3-4f91-9da0-6a2e7bdfc1a0.jpg)

这个怎么操作成功的，我始终点不亮，能分享一下TEST么
