### ISSUE TITLE
i2c support was removed for HEM6432 (and other ST7567 based displays)

### ISSUE THREAD

**Issue by obaterspok** [olikraus/u8g2#1939]
Hi,

In commit 
https://github.com/olikraus/u8g2/commit/5b611bc602eccb07b3b1e116808900903a86d17a

The i2c support was removed for HEM6432. Any reason for this?

-- john

**Comment by olikraus** [comment]
Hmm I don't remember. I do not have proper access to the repo, so I will check this in the next days.

**Comment by olikraus** [comment]
not sure why this has happend... will be fixed...

**Comment by olikraus** [comment]
I have created beta release 2.33.13, maybe you can confirm that this works again...

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by olikraus** [comment]
I will close this for now, nevertheless any feedback on this is welcome.

**Comment by obaterspok** [comment]
Works perfect with esp32-c3 for both sw & hw i2c.

U8G2_ST7567_HEM6432_1_SW_I2C u8g2(U8G2_R2, PIN_SCL, PIN_SDA, U8X8_PIN_NONE);
U8G2_ST7567_HEM6432_1_HW_I2C u8g2(U8G2_R2, U8X8_PIN_NONE, PIN_SCL, PIN_SDA);

Thanks a lot!

**Comment by olikraus** [comment]
Great, thanks a lot for pointing out this issue and for your feedback.
