### ISSUE TITLE
u8g2_font_logisoso30_tn bad baseline alignment of the number 3

### ISSUE THREAD

**Issue by ask6483** [olikraus/u8g2#1942]
Number 3 glyph baseline is lowered by 1 pixel.
![screenshot-0000](https://user-images.githubusercontent.com/72493041/187875237-a9dd726a-321a-4ab6-aa88-a91e5686e953.png)

**Comment by ask6483** [comment]
Another example
![screenshot-0000](https://user-images.githubusercontent.com/72493041/187875651-750194d8-4c01-4ae4-a55b-7d2353274d80.png)

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/issues/1722
https://github.com/olikraus/u8g2/issues/1484
