### ISSUE TITLE
using different fontSize in same drawing?

### ISSUE THREAD

**Issue by zenz** [olikraus/u8g2#195]
I'd give it a try but cannot make it. While I first set it to bigger font size, and drawStr something, and then set it to smaller font size and drawStr something.  the bigger strings will move up to the top of the screen.

If it's possible, can you show a sample how to make it work?

Best regards

**Comment by olikraus** [comment]
can you post the related non working code?

**Comment by zenz** [comment]
please check below code.

#include "U8g2lib.h"
#include <Wire.h>

U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ 12, /* data=*/ 14, /* reset=*/ U8X8_PIN_NONE);

void setup() {
  // Init oled
  u8g2.begin();
  u8g2.setDrawColor(1);
  u8g2.setFontPosTop();
  u8g2.setFontDirection(0);
}

void loop() {
    u8g2.clearBuffer();
    u8g2.setFont(u8g2_font_logisoso34_tf);
    u8g2.drawStr( 5, 12, "20");
    u8g2.drawStr( 54, 12, "|");
    u8g2.drawStr( 79, 12, "40");
    // here mass the display
    u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.drawStr(10,10,"T");
    u8g2.sendBuffer();
}

**Comment by olikraus** [comment]
Can you post a picture also?

**Comment by olikraus** [comment]
Just to ensure, that this is not a font mode issue:
Did you play around with this command also?
u8g2_SetFontMode(u8g2_t *u8g2, uint8_t is_transparent);

https://github.com/olikraus/u8g2/wiki/u8g2reference#setfontmode

**Comment by zenz** [comment]
<img width="234" alt="2017-02-14 8 59 52" src="https://cloud.githubusercontent.com/assets/301676/22929833/92ec24ba-f2f8-11e6-94e3-62141f025f2a.png">
the above makes a correct display with only one font

<img width="266" alt="2017-02-14 8 57 11" src="https://cloud.githubusercontent.com/assets/301676/22929854/ae0ce59a-f2f8-11e6-9569-38b998c8a49e.png">
this one like a mass if using two different font

**Comment by zenz** [comment]
it's not the issue of setFontMode, please check above post for the image.

**Comment by zenz** [comment]
I'm using NodeMCU(ESP8266-12E) as MCU

**Comment by olikraus** [comment]
I agree, this looks odd.
Let me try to reproduce the problem on my own systems.

**Comment by olikraus** [comment]
I think the software behaves correctly and there is no problem. The only issue is, that setFont will reset the setFontPosTop command. This means, you need to call u8g2.setFontPosTop(); after each font change.
```
void loop() {
u8g2.clearBuffer();
u8g2.setFont(u8g2_font_logisoso34_tf);
u8g2.setFontPosTop();
u8g2.drawStr( 5, 12, "20");
u8g2.drawStr( 54, 12, "|");
u8g2.drawStr( 79, 12, "40");
// here mass the display
u8g2.setFont(u8g2_font_ncenB14_tr);
u8g2.setFontPosTop();
u8g2.drawStr(10,10,"T");
u8g2.sendBuffer();
for(;;)
  ;
}
```
I agree, that is should either document this behavior or change the behavior of the code itself.

**Comment by olikraus** [comment]
ok, i have changed the code

https://github.com/olikraus/u8g2/commit/51983b5485a4cf8cd599a49badd6b213d4d97a3a

Thanks for this issue.

**Comment by zenz** [comment]
thanks for solving this bug so quick!

**Comment by zenz** [comment]
Sorry that I had to re-open this issue.
It fixs the problem which cannot use different fontSize in same drawing, but creates another problem.

While using the new solution, the display will be freeze... without any update.

**Comment by olikraus** [comment]
Any example code which demonstrates the freezing?

**Comment by olikraus** [comment]
Did you update the init code also? 

I have placed the beta release here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip

Install the zip lib via the Arduino IDE Add Zip Lib menu.

**Comment by zenz** [comment]
Sorry, my fault, I forgot to modify the u8g2_setup.c file together, now all things running smooth.
Thank you for fixing the bug again!
