### ISSUE TITLE
GU800 160X16 with U8G2_GU800_128X64

### ISSUE THREAD

**Issue by chicho70** [olikraus/u8g2#1970]
Hi,

I have a Noritake GU800-160X16.

In U8X8 i can write two lines of 20 chars each. No problems. Only 1X1 and 2X2 fonts.

But with U8G2 a can only use 128 bits (trunked to 16 chars). I only can write in the first 128 pixels (from 129 to 160 are blank)

I use this constructor:
U8G2_GU800_128X64_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ SS, /* dc=*/ 4, /* reset=*/ 15);

In u8x8_d_gu800.c file I did some modifications:
		
```  C++
/* sck_clock_hz = */ 8000000UL,  	   <--
/* spi_mode = */ 3,            	                  <-- 
/* i2c_bus_clock_100kHz = */ 4,           /* GU800: Not used */
/* data_setup_time_ns = */ 40,    
/* write_pulse_width_ns = */ 150, 
  /* tile_width = */ 16,                             <--
  /* tile_hight = */ 8,             
  /* default_x_offset = */ 0,       
  /* flipmode_x_offset = */ 0,      
  /* pixel_width = */ 160,                      <--
  /* pixel_height = */ 16                       <--
};
```

Thanks and best regards.

**Comment by olikraus** [comment]
Shell we create a new constructor with your modifications?

**Comment by chicho70** [comment]
yes, i changed SPI from 2 to 3. I found information about it.
With SPI =2  not ok.

i could be fine a new constructor for NORITAKE GU800 160X16.

**Comment by chicho70** [comment]
U8X8 Results: Full Screen
/Users/fausto/Desktop/carpeta sin título/pic1.jpg

**Comment by chicho70** [comment]
U8G2 Results: Max to 128 pixels and overlapped.
![pic2](https://user-images.githubusercontent.com/52011214/193801582-39a240cf-3ecf-4e63-b0fa-07160c82e99d.jpg)

**Comment by chicho70** [comment]
I leave more info for you:
[Noritake Display GU160X16-800A.pdf](https://github.com/olikraus/u8g2/files/9706282/Noritake.Display.GU160X16-800A.pdf)
[GU128X32-800B.pdf](https://github.com/olikraus/u8g2/files/9706283/GU128X32-800B.pdf)

**Comment by chicho70** [comment]
Thanks so much.

**Comment by olikraus** [comment]
I have created a new constructor GU800_160X16.
Please have a look.
You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```
#

**Comment by chicho70** [comment]
Hi Oliver,
Works so pretty.
Thanks so much.
Best regards.

Noritake GU160X16-800A display mounted in GPS TRUETIME / Symmetricom MODEL XLi TIME & FRECUENCY SYSTEM


![Thanks](https://user-images.githubusercontent.com/52011214/195866261-30f6fade-bab8-4649-ba97-77518ee5d031.jpg)

**Comment by chicho70** [comment]
Oliver, 
When you have time, please, if you can, take a look at this display.
I have tried to adapt the original Noritake library developed for AVT to ESP32 but it is impossible for me.
The original library is supported by these three files:

#include <util/delay_basic.h>
#include <util/delay.h>
#include <avr/pgmspace.h>

I leave you the original library in case it helps you for this display (GU256X32D-3900B).
I also send you the PDF file of the display information to help you.

It is possible that one of the constructors in your u8g2 project can fit this display.

This Noritake display, model GU256X32D-3900B, was installed on a GPS Symmetricom MODEL XLi TIME & FREQUENCY SYSTEM and with the GU160X16 I want to make a small weather station using the Sensirion SCD41 sensor.

Once again, thank you very much.


![GU256X32D-1](https://user-images.githubusercontent.com/52011214/195877320-3bdaeb42-0b2f-4e25-99c3-7659b32adda5.jpg)


![GU256X32D-2](https://user-images.githubusercontent.com/52011214/195877374-961d15a4-164d-4654-a2f6-e70ef3be929a.jpg)

**Comment by olikraus** [comment]
Thanks for the feedback.

**Comment by chicho70** [comment]
Dear Oliver,
I´ve checked with this constructor with GU160X16-800A (Paralell M68/68000) & ESP32 DEVKIT V1 ... and works fine. 
Thanks and regards. 

U8G2_GU800_160X16_F_6800 u8g2(U8G2_R0, /*d0*/4, /*d1*/16, /*d2*/17, /*d3*/18, /*d4*/19, /*d5*/21, /*d6*/22, /*d7*/23, /*ENABLE-ENCK*/27, /*CS-CSS*/14, /*DC-C/D*/26, /*reset*/13);

REMARKS: PIN 17 (R/W)  GU160X16 to GND to force WRITE.

![Conexión ESP32 DEVKIT M68-68000 con Noritake GU160X16-800A](https://user-images.githubusercontent.com/52011214/198325670-78f19e49-832e-4ccd-b560-caff9f6b275a.png)

**Comment by olikraus** [comment]
Thanks for the feedback!
