### ISSUE TITLE
u8x8_d_sdl_128x64.c compilation error

### ISSUE THREAD

**Issue by MS10755** [olikraus/u8g2#1979]
Hello olikraus!
I'm trying to compile u8g2 on windows. but DOC [**sys/sdl/common/u8x8_d_sdl_128x64.c**](https://github.com/olikraus/u8g2/blob/master/sys/sdl/common/u8x8_d_sdl_128x64.c) has a little compile error.
line 52: `ptr = u8g_sdl_screen->pixels + offset;`

void * has an inexplicit size(u8g_sdl_screen->pixel),so cannot calculate pixels + offset.
![image](https://user-images.githubusercontent.com/42739344/195020171-4297c35e-69c9-4918-b004-aef64b14db94.png)

following is my fix code.
![image](https://user-images.githubusercontent.com/42739344/195019628-6ff0f41e-4664-4f95-94f7-bbb41f994c47.png)

**Comment by olikraus** [comment]
hmmm nice finding.
However, the proper cast should be: 
```
      ptr = (uint32_t *)(((uint8_t *)(u8g_sdl_screen->pixels)) + offset);
```
