### ISSUE TITLE
Measure Text before Drawing

### ISSUE THREAD

**Issue by roomtek** [olikraus/u8g2#198]
Is there a function to measure the size (width) of  the drawn object using a certain font before I call the drawStr command?

basically, I want to center a large text on the screen, where the text could be 3 to 5 characters long. So if I could get the drawn width before I actually draw, I can calculate the x parameter.

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/wiki/u8g2reference#getstrwidth

**Comment by roomtek** [comment]
works as described!

**Comment by olikraus** [comment]
Great :-)
