### ISSUE TITLE
Request a HW I2c method for ST7567S 128/64 LCD

### ISSUE THREAD

**Issue by LeonardoLisa** [olikraus/u8g2#1983]
Hi,
I'm using this code running on Arduino UNO to test the display: https://it.aliexpress.com/item/1005004237282931.html
Using the code from issue https://github.com/olikraus/u8g2/issues/1844

Because I have multiple I2c devices I would like know if is possibile to have an hardware version for the U8G2_ST7567_ENH_DG128064I_1_SW_I2C constructor. Thanks in advance. 

#include <Arduino.h>
#include <U8g2lib.h>

#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif

U8G2_ST7567_ENH_DG128064I_1_SW_I2C u8g2(U8G2_R0, SCL, SDA, U8X8_PIN_NONE);

void setup(void) {
  u8g2.setI2CAddress(0x3F * 2);
  u8g2.begin();
  u8g2.enableUTF8Print();

  randomSeed(analogRead(0));
}
void loop(void) {
  float rand1 = 123 + random(200)/100.0;
  float rand2 = 123 + random(200)/100.0;
  delay(1000); 

  u8g2.firstPage();
  do {
    u8g2.setFont(u8g2_font_ncenB10_tr);
    u8g2.setCursor(0, 15);
    u8g2.print(F("Random1"));
    u8g2.setCursor(0, 30);
    u8g2.print(rand1);
    u8g2.setCursor(0, 45);
    u8g2.print(F("Random2"));
    u8g2.setCursor(0, 60);
    u8g2.print(rand2);
    u8g2.drawFrame(0, 0, 128, 64);
  } while ( u8g2.nextPage() );
  
  delay(1000);  
}

**Comment by olikraus** [comment]
The hardware I2C constructor should be available: U8G2_ST7567_ENH_DG128064I_1_HW_I2C
