### ISSUE TITLE
help to find lcd driver model :)

### ISSUE THREAD

**Issue by mohammad0663** [olikraus/u8g2#1984]
hi olikraus .
i have a graphic lcd 12864 (monochorom) . i do finde pin out and hex whith logic analayzer . but can't finde driver !
at down , i did write otp (i did finde with logic analayzer) :

  LcdWrite(LCD_C, 0x28);
  LcdWrite(LCD_C, 0x23);
  LcdWrite(LCD_C, 0xa0); 
  
  
  LcdWrite(LCD_C, 0x2f);
  LcdWrite(LCD_C, 0x81);
  LcdWrite(LCD_C, 0x4b);
  
  
  LcdWrite(LCD_C, 0x24);
  LcdWrite(LCD_C, 0xeb);
  LcdWrite(LCD_C, 0xc4);
  
  
  LcdWrite(LCD_C, 0xb0);
  LcdWrite(LCD_C, 0x10);
  LcdWrite(LCD_C, 0x04);
  LcdWrite(LCD_C, 0x40);
  
  
  LcdWrite(LCD_C, 0xa4);
  LcdWrite(LCD_C, 0xa6);
  LcdWrite(LCD_C, 0x88);
  
  
  LcdWrite(LCD_C, 0xaf);
  
  
  LcdWrite(LCD_C, 0xb0);
  LcdWrite(LCD_C, 0x10);
  LcdWrite(LCD_C, 0x04);

What driver model is this otp For ?

What driver can I use?

**Comment by olikraus** [comment]
I don't know how I can help here.

**Comment by mohammad0663** [comment]
Tell me whte dirver number ?

**Comment by olikraus** [comment]
Impossible without datasheet. But it could be a ST7565.

**Comment by mohammad0663** [comment]
I do test . Thank you

**Comment by mohammad0663** [comment]
Hello, I tested it and it was uc1601
