### ISSUE TITLE
How to increase the update frequency on LCD display?

### ISSUE THREAD

**Issue by mianqi2016** [olikraus/u8g2#1985]
My LCD display refresh frequency is now 1.5Hz by "sendBuffer()", how to increase it to 2Hz?

**Comment by olikraus** [comment]
Which constructor do you use?

**Comment by mianqi2016** [comment]
`	u8g2_Setup_st7920_s_128x64_f(&u8g2, U8G2_R0, u8x8_byte_4wire_sw_spi, u8x8_avr_gpio_and_delay);
	u8g2_InitDisplay(&u8g2);
	u8g2_SetPowerSave(&u8g2, 0);`

**Comment by olikraus** [comment]
Software emulated SPI is slow. You probably need to use HW SPI. There is a ready to use constructor for Arduino Environment.
