### ISSUE TITLE
u8g2 cannot display Chinese fonts

### ISSUE THREAD

**Issue by W-Dany** [olikraus/u8g2#1987]
Hi
   I ported the u8g2 on the stm32. Currently, it can display English, numbers, and characters etc,But it cannot display Chinese characters.
Please give me some suggestions.

The following code:
void LcmdInit(void)
{
	//注册驱动芯片回调函数，并配置屏幕的显示方向
	u8g2_Setup_st7565_lx12864_f(&u8g2_h,U8G2_R0,u8x8_byte_4wire_sw_spi,u8x8_gpio_and_delay); 
	//显示状态初始化
	u8x8_InitDisplay(u8g2_GetU8x8(&u8g2_h));
	//省电模式配置
       u8x8_SetPowerSave(u8g2_GetU8x8(&u8g2_h), 0);  
	//清除缓存区
       u8g2_ClearBuffer(&u8g2_h);
}

void testShowChinese(u8g2_t *u8g2)
{
	int t = 1000;
	
	u8g2_ClearBuffer(u8g2);
	
	u8g2_SetFont(&u8g2_h, u8g2_font_wqy12_t_chinese1);
	u8g2_SetFontDirection(&u8g2_h, 0);
	u8g2_DrawStr(u8g2,0,48,"abcdefGKLMN");
	u8g2_DrawUTF8(u8g2,0,16,"你好世界!!!");
//	u8g2_DrawGlyph(u8g2,0,16,0x4F60);//0x4F60-你
//	u8g2_DrawGlyph(u8g2,16,16,0x597D);//0x597D-好
//	u8g2_DrawGlyph(u8g2,32,16,0x4e16);//0x4e16-世
//	u8g2_DrawGlyph(u8g2,48,16,0x754c);//0x754c-界
//	u8g2_DrawStr(u8g2,64,16,"!!!");
	
	u8g2_DrawGlyph(u8g2,48,32,0x4E3B);//0x4E3B-主
	u8g2_DrawGlyph(u8g2,64,32,0x83DC);//0x4e2d-菜 
	u8g2_DrawGlyph(u8g2,80,32,0x5355);//0x5355-单
	SEND_BUFFER_DISPLAY_MS(u8g2,t);
}

![无标题](https://user-images.githubusercontent.com/27724491/196397983-ea299d7d-7840-49d2-9f03-7da3f8614b4c.png)

**Comment by olikraus** [comment]
In order to save memory, there are different variants of the same fonts. In your case there are:
u8g2_font_wqy12_t_chinese1
u8g2_font_wqy12_t_chinese2
u8g2_font_wqy12_t_chinese3
u8g2_font_wqy12_t_gb2312
u8g2_font_wqy12_t_gb2312a
u8g2_font_wqy12_t_gb2312b

The number of glyphs included in these fonts is given here (first column):
       317   2221 chinese1.map
       619   4341 chinese2.map
      1122   7894 chinese3.map
     3947  27630 gb2312a.map
     4437  31060 gb2312b.map
     7445  52116 gb2312.map

So, u8g2_font_wqy12_t_gb2312 is the biggest font with the most number of glyphs included (all 7445 of version GB/T 2312-1980). "a" and "b" variants include lesser glyphs.
The map files are part of this project and located for example here: https://github.com/olikraus/u8g2/blob/master/tools/font/build/gb2312.map
The map files include the unicode of the glyphs included in the font.

**Comment by W-Dany** [comment]
Thank you very much for the answer from Olikraus！
I looked at the map file of the font, used the u8g2_DrawUTF8() function to call the font present in the map file, but it still does not display, using the u8g2_DrawGlyph() function to write hexadecimal code can display。I don't understand why

**Comment by olikraus** [comment]
Any code?

**Comment by W-Dany** [comment]
Yes, all characters except Chinese can be displayed.  Call “u8g2_DrawUTF8()” function

**Comment by olikraus** [comment]
If you want me to support, then please post the none working code.

**Comment by W-Dany** [comment]
Thank you very much for your support。

Below is my code：

#include "drv_u8g2.h"


u8g2_t  u8g2_h;


#define u8g2_ms_delay(x)				HAL_Delay(x)


void u8g2_ns_delay(uint16_t dly)
{
	
	while(dly--)
	{
		__NOP();	
	}
}

//==================================================================
//函数名：  
//作者：    Dany
//日期：    
//功能：    
//输入参数：
//返回值：	 
//修改记录：
//==================================================================
uint8_t u8x8_gpio_and_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
	uint16_t i = 0;
	
	switch (msg)
	{	
			
			case U8X8_MSG_GPIO_AND_DELAY_INIT: 
					Drv_DisplayInit();    //lcd接口初始化
					break;
			case U8X8_MSG_DELAY_NANO: //u8g2_ns_delay()内部使用的_nop延时ns和us
					u8g2_ns_delay(1);			//此延时过长会影响显示效果
					break;
			case U8X8_MSG_DELAY_100NANO: //100ns
					u8g2_ns_delay(arg_int);
					break;
			case U8X8_MSG_DELAY_10MICRO: //10ms
					u8g2_ns_delay(arg_int);
					break;
			case U8X8_MSG_DELAY_MILLI: /*延时函数*/
					u8g2_ms_delay(arg_int);     
					break;
			case U8X8_MSG_GPIO_CS: /*片选信号*/ 
					Lcd_SetCS(arg_int);
					break;
			case U8X8_MSG_GPIO_DC: /*设置DC引脚,表明发送的是数据还是命令*/
					Lcd_SetA0(arg_int);
					break;
			case U8X8_MSG_GPIO_RESET: //复位引脚
					Lcd_SetRst(arg_int);
					break;
			case U8X8_MSG_GPIO_SPI_CLOCK: //时钟
					Lcd_SetSCK(arg_int);
					break;
			case U8X8_MSG_GPIO_SPI_DATA:  //数据
					Lcd_SetSDA(arg_int);
					break;
	}
	return 1;
}


//==================================================================
//函数名：  
//作者：    Dany
//日期：    
//功能：    
//输入参数：
//返回值：	 
//修改记录：
//==================================================================
void Drv_LcmdInit(void)
{
	//注册驱动芯片回调函数，并配置屏幕的显示方向
	u8g2_Setup_st7565_lx12864_f(&u8g2_h,U8G2_R0,u8x8_byte_4wire_sw_spi,u8x8_gpio_and_delay); 
	//显示状态初始化
	u8x8_InitDisplay(u8g2_GetU8x8(&u8g2_h));
	//省电模式配置
  u8x8_SetPowerSave(u8g2_GetU8x8(&u8g2_h), 0);  
	//清除缓存区
  u8g2_ClearBuffer(&u8g2_h);
}


//==================================================================
//函数名：  
//作者：    Dany
//日期：    
//功能：    
//输入参数：
//返回值：	 
//修改记录：
//==================================================================
void TestDraw(u8g2_t *u8g2)
{
#if 0
    u8g2_SetFontMode(u8g2, 1); /*字体模式选择*/
    u8g2_SetFontDirection(u8g2, 0); /*字体方向选择*/
    u8g2_SetFont(u8g2, u8g2_font_inb24_mf); /*字库选择*/
    u8g2_DrawStr(u8g2, 1, 30, "U");
    
    u8g2_SetFontDirection(u8g2, 1);
    u8g2_SetFont(u8g2, u8g2_font_inb30_mn);
    u8g2_DrawStr(u8g2, 20,5,"8");
        
    u8g2_SetFontDirection(u8g2, 0);
    u8g2_SetFont(u8g2, u8g2_font_inb24_mf);
    u8g2_DrawStr(u8g2, 50,30,"g");
    u8g2_DrawStr(u8g2, 65,30,"\xb2");//
    
    u8g2_DrawHLine(u8g2, 5, 35, 47);
    u8g2_DrawHLine(u8g2, 6, 36, 47);
    u8g2_DrawVLine(u8g2, 40, 30, 12);
    u8g2_DrawVLine(u8g2, 41, 31, 12);

#else
		u8g2_SetFont(u8g2, u8g2_font_wqy12_t_gb2312b);
		u8g2_SetFontDirection(u8g2, 0);
		u8g2_DrawStr(u8g2,0,48,"abcdefGKLMN");
		u8g2_DrawUTF8(u8g2,0,16,"你好世界!!!");

//		u8g2_DrawGlyph(u8g2,0,16,0x4F60);//0x4F60-你
//		u8g2_DrawGlyph(u8g2,16,16,0x597D);//0x597D-好
//		u8g2_DrawGlyph(u8g2,32,16,0x4e16);//0x4e16-世
//		u8g2_DrawGlyph(u8g2,48,16,0x754c);//0x754c-界
//		u8g2_DrawStr(u8g2,64,16,"!!!");
		
		u8g2_DrawGlyph(u8g2,48,32,0x4E3B);//0x4E3B-主
		u8g2_DrawGlyph(u8g2,64,32,0x83DC);//0x4e2d-菜 
		u8g2_DrawGlyph(u8g2,80,32,0x5355);//0x5355-单
#endif		

}

void SysSetupHardware(void)
{
	
	BSP_McuPwrClockInit();		//mcu内部电源、时钟等初始化	
	Drv_LcmdInit();

}

int main(void)
{

	SysSetupHardware();
	
	while(1)
	{
		u8g2_FirstPage(&u8g2_h);
		do
		{
				TestDraw(&u8g2_h);
		} while (u8g2_NextPage(&u8g2_h));
	}

}

**Comment by olikraus** [comment]
So you say, that u8g2_DrawGlyph(u8g2,48,32,0x4E3B); is not displayed?
From my perspective the code looks ok.

**Comment by W-Dany** [comment]
u8g2_DrawGlyph(u8g2,48,32,0x4E3B); This function can be displayed. 
u8g2_DrawUTF8 (u8g2,0,16, "你好世界!!!"); This is not displayed.

**Comment by W-Dany** [comment]
It can display Chinese characters

**Comment by olikraus** [comment]
So "u8g2_DrawUTF8 (u8g2,0,16, "\xE4\xBD\xA0\xE5\xA5\xBD\xE4\xB8\x96\xE7\x95\x8C\x21\x21\x21"); " will display  "你好世界!!!" ?

If so, then there is an issue with your c-compiler or your editor because "你好世界!!!" must be "translated" into "\xE4\xBD\xA0\xE5\xA5\xBD\xE4\xB8\x96\xE7\x95\x8C\x21\x21\x21" by your editor.

**Comment by W-Dany** [comment]
Thank you for your suggestion, the used c-compiler is Keil uVsion5, I will check the reason from this compiler

**Comment by W-Dany** [comment]
Indeed the case，After the editor configuration uses UTF-8 encoding, it can be displayed normally。
Thanks again for your patience

**Comment by olikraus** [comment]
👍

**Comment by fuyuqingfeng** [comment]
Hi olikraus
    I want to display characters in reverse white, but I can't find such a processing function in u8g2 library. Does u8g2 library support characters in reverse white？

**Comment by W-Dany** [comment]
Hi olikraus
     I want to display characters in reverse white, but I can't find such a processing function in u8g2 library. Does u8g2 library support characters in reverse white?

**Comment by olikraus** [comment]
There are many options to do this:
1. Get a different display type with inverted pixels
2. Use `u8g2.sendF("c", 0x0a7);` (https://github.com/olikraus/u8g2/wiki/u8g2reference#sendf) which may invert your display, if the 0xa7 command is supported by your display (maybe your display has a different command for inversion)
3. Draw a box on the display screen with draw color 1, then draw the characters in draw color 0 (https://github.com/olikraus/u8g2/wiki/u8g2reference#setdrawcolor)

**Comment by W-Dany** [comment]
Thanks for support, I'll try it again
