### ISSUE TITLE
I have a problem compiling with SED1520

### ISSUE THREAD

**Issue by trymrock** [olikraus/u8g2#1990]
Hello friends
I have a problem compiling with screen
T8G2_SED1520_122x32_F
Thanks for your help
Thank you
![image](https://user-images.githubusercontent.com/959979/197352562-8a38596c-bf41-42e0-97bb-352b221b380d.png)

**Comment by olikraus** [comment]
Which Arduino Version did you use?

**Comment by trymrock** [comment]
sorry.
I just upgraded to Arduino 1.8.19 (old version 1.8.18 is buggy)
Now the screen works stably
Thank you

**Comment by olikraus** [comment]
,,👍
