### ISSUE TITLE
Cannot get Contructor to work  properly for RA8835

### ISSUE THREAD

**Issue by Swejjj** [olikraus/u8g2#1991]
Hello,

I have been trying to get a 240x320 LCD with an RA8835 driver to work. I am using this constructor:

U8G2_RA8835_320X240_F_8080(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

When I run the code, I get the error that pinouts (d0-d7) are not declared in the scope. What I have already tried to do.

- Used the newest version of u8g2, tried a different constructor with the same driver: 

U8G2_RA8835_NHD_240X128_F_8080 u8g2(U8G2_R0, 8, 9, 10, 11, 4, 5, 6, 7, /*enable=*/ 17, /*cs=*/ 14, /*dc=*/ 15, /*reset=*/ 16); // Connect /RD = E with +5V, enable is /WR = RW, FG with GND, 14=Uno Pin A0

Which does compile but does not run.

I am using an arduino mega 2560 to interface, I have also attached the code I am trying to run (Basic hello world). To whoever sees this, thank you for taking the time to look.

Here is the error log:

Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

HelloWorld:290:33: error: 'rotation' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                 ^~~~~~~~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:33: note: suggested alternative: 'static'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]
[HelloWorldRA8835.txt](https://github.com/olikraus/u8g2/files/9848739/HelloWorldRA8835.txt)

                                 ^~~~~~~~

                                 static

HelloWorld:290:43: error: 'd0' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                           ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:43: note: suggested alternative: 'A0'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                           ^~

                                           A0

HelloWorld:290:47: error: 'd1' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                               ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:47: note: suggested alternative: 'A1'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                               ^~

                                               A1

HelloWorld:290:51: error: 'd2' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                   ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:51: note: suggested alternative: 'A2'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                   ^~

                                                   A2

HelloWorld:290:55: error: 'd3' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                       ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:55: note: suggested alternative: 'A3'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                       ^~

                                                       A3

HelloWorld:290:59: error: 'd4' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                           ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:59: note: suggested alternative: 'A4'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                           ^~

                                                           A4

HelloWorld:290:63: error: 'd5' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                               ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:63: note: suggested alternative: 'A5'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                               ^~

                                                               A5

HelloWorld:290:67: error: 'd6' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                   ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:67: note: suggested alternative: 'A6'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                   ^~

                                                                   A6

HelloWorld:290:71: error: 'd7' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                       ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:71: note: suggested alternative: 'A7'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                       ^~

                                                                       A7

HelloWorld:290:75: error: 'enable' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                           ^~~~~~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:75: note: suggested alternative: 'rename'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                           ^~~~~~

                                                                           rename

HelloWorld:290:83: error: 'cs' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                                   ^~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:83: note: suggested alternative: 'cos'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                                   ^~

                                                                                   cos

HelloWorld:290:87: error: 'dc' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                                       ^~

HelloWorld:290:91: error: expected primary-expression before ',' token

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                                           ^

HelloWorld:290:93: error: 'reset' was not declared in this scope

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                                             ^~~~~

C:\Users\AppData\Local\Temp\arduino_modified_sketch_323604\HelloWorld.ino:290:93: note: suggested alternative: 'memset'

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                                             ^~~~~

                                                                                             memset

HelloWorld:290:101: error: expected ',' or ';' before '[' token

 U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

                                                                                                     ^

exit status 1

'rotation' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by olikraus** [comment]
What is the original source code here?

**Comment by Swejjj** [comment]
> What is the original source code here?

Thanks for the quick reply! 

I am using the hello world example from the u8g2 library. u8g2>Fullbuffer>helloworld. Running it with no additional code.
I should note that it does not have the constructor listed for my LCD driver (RA8835 320x240, does have it for 240 x 128) but you do provide the constructor code for a 320 x 240 on your full list of constructor references which I added.

**Comment by olikraus** [comment]
Ok, so how does your constructor line look like?

**Comment by Swejjj** [comment]
> Ok, so how does your constructor line look like?

U8G2_RA8835_320X240_F_8080 u8g2(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc [, reset]) [full framebuffer, size = 9600 bytes]

**Comment by olikraus** [comment]
Look very wrong. Please check the existing commented constructors for proper arguments. See also the user manual. Please note that the square brackets describe optional arguments. You need to use or remove the arguments. Square brackets must be removed.
