### ISSUE TITLE
Arabic printing Issue while passing as  HEX values of corresponding Arabic letters.

### ISSUE THREAD

**Issue by Vineeth-B007** [olikraus/u8g2#1995]
@RobotGB
Output :
`u8g2.drawExtUTF8(120, 15, 1, NULL, "\x0633\x0644\x0627\x0645\x0020\x062C\x0647\x0627\x0646");`

![img_20180425_233949](https://user-images.githubusercontent.com/8011806/39267630-a0c0bcae-48e2-11e8-8f55-b58dfd54750e.jpg)

**Another interesting case**
[Korean.ino](https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/Korean/Korean.ino) file output :

![photo_2018-04-25_23-46-17](https://user-images.githubusercontent.com/8011806/39267737-f64c91d4-48e2-11e8-821f-be5e7e18ff14.jpg)

_Originally posted by @idreamsi in https://github.com/olikraus/u8g2/issues/588#issuecomment-384403231_

Dear Sir,

I'm facing an issue while passing the Arabic words converted into corresponding 2byte HEX values. It prints okay while I hardcode the Arabic word as it is.

How can I do printing with passing corresponding 2byte Hex values with this,

u8g2.drawExtUTF8(120, 15, 1, NULL, "\x0633\x0644\x0627\x0645\x062C\x0647\x0627\x0646");

thankyou

**Comment by olikraus** [comment]
This is not possible. You need to pass a proper UTF--8 code sequence.
