### ISSUE TITLE
Question about ST7586S JLX384160

### ISSUE THREAD

**Issue by iggymayer** [olikraus/u8g2#1996]
Hello, this screen can be displayed normally when using U8G2_ST7586S_JLX384160_F_4W_SW_SPI, but it does not display when using U8G2_ST7586S_JLX384160_F_4W_HW_SPI, how can I solve it?

PDF:    https://mega.nz/file/oYcECJSZ#P036G_CpZyAGgw11exOEUfbBO51KS-qY5-ggvm0yI30

ESP32-C3&platformIO&VSCode

**Comment by olikraus** [comment]
Probably you need to connect your display to the SPI lines of your board.

**Comment by iggymayer** [comment]
Thank you so much！
