### ISSUE TITLE
SH1108 128x160

### ISSUE THREAD

**Issue by fritolays** [olikraus/u8g2#1998]
Hello,

The SH1108 160x160 constructor does work with the screen I have, but things get cut off.
If you could kindly add the 128x160 resolution please and thanks.

![SH1108 128x160 Cutoff](https://user-images.githubusercontent.com/855555/199869400-3fbc4311-4e71-463a-95f2-73dfe670a063.jpg)
![PSH1108 128x160 Rear](https://user-images.githubusercontent.com/855555/199869417-21c080f6-2a82-4a73-a67f-a09ebb0245b4.jpg)

**Comment by olikraus** [comment]
Hmm... in the demo code from here: https://www.buydisplay.com/white-1-92-inch-128x160-oled-display-sh1108-controller-spi-i2c
they are using an offset of 16. Can you confirm this?

**Comment by fritolays** [comment]
You are correct.
An offset of 15 no pixel visible.
Offset of 16, pixel visible on left side of screen.

![SH1108 With 16 Pixel Offset](https://user-images.githubusercontent.com/855555/200006278-8eb35a23-4193-44d6-9523-e1f91156b02b.jpg)

**Comment by olikraus** [comment]
I have created beta 2.34.5.
Can you test the "FlipMode" example? It should always show a solid border.

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by fritolays** [comment]
The border looks to be correct.

![SH1108 Border Test](https://user-images.githubusercontent.com/855555/200148611-ec75e35b-6739-438d-be31-7f3df7e86f29.jpg)

**Comment by olikraus** [comment]
The text changes 8 times, is the border always correct?

**Comment by fritolays** [comment]
Sorry, yes the border is correct in all 8 iterations.

**Comment by olikraus** [comment]
Super, then the new constructor should work for you. Thanks for testing.
