### ISSUE TITLE
Sending raw commands

### ISSUE THREAD

**Issue by hazarkarabay** [olikraus/u8g2#201]
Hi,

Is there a way to use raw display commands in sketch? I use a SSD1306 display and would like able to control its internal charge pump. 

While using adafruit library, I can use following:
```
display.ssd1306_command(SSD1306_CHARGEPUMP); //0x8d
display.ssd1306_command(0x10);
```

I tried following with u8g2 with no avail
```
U8X8_START_TRANSFER();
U8X8_CA(0x8d, 0x10);
U8X8_END_TRANSFER();
U8X8_END();
```

Note: I'm trying to use this commands in my main loop().

Any information would be greatly appreciated. Thanks.

**Comment by olikraus** [comment]
u8x8_cad_StartTransfer(u8g2.getU8x8());
u8x8_cad_SendCmd( u8g2.getU8x8(), 0x8d);
u8x8_cad_SendArg( u8g2.getU8x8(), 0x10);
u8x8_cad_EndTransfer(u8g2.getU8x8());

**Comment by hazarkarabay** [comment]
Thank you.
