### ISSUE TITLE
Cant add ssd1306 128x64

### ISSUE THREAD

**Issue by brunofmc50** [olikraus/u8g2#2020]
hi, i cant add my oled display 128x64, what should i do?
![image](https://user-images.githubusercontent.com/117109071/203126852-5f5a25d1-6354-49ad-a7d3-fec0d23702ae.png)

**Comment by olikraus** [comment]
you need to remove the line 
``` C++
u8g2_t u8g2;
```

**Comment by brunofmc50** [comment]
It keeps giving error... My oled display is 128x64.
![image](https://user-images.githubusercontent.com/117109071/203132745-a4e565a0-a231-42f9-b090-f05161c8444e.png)

**Comment by olikraus** [comment]
1. You should call the constructor outside the main function (like in your initial post)
2. You need to include <U8g2lib.h>

But it looks like you are not in an Arduino environment, so you need to follow the instructions from here: https://github.com/olikraus/u8g2/wiki/u8g2setupc

Also have a look at my example here: https://github.com/olikraus/u8g2/blob/master/sys/avr/as7/main.c

Which was referenced here: https://github.com/olikraus/u8g2/wiki/u8g2as7
