### ISSUE TITLE
`CMakeLists.txt` is missing `u8g2_button.c` (undefined reference to `u8g2_DrawButtonUTF8`)

### ISSUE THREAD

**Issue by m3y54m** [olikraus/u8g2#2023]
Hello,

I got this error while compiling U8g2:

![image](https://user-images.githubusercontent.com/1549028/203409312-3159b3ff-0912-4e2a-9f6f-1b08759f1b1f.png)

The `u8g2_DrawButtonUTF8()` function is defined in `csrc/u8g2_button.c` source file.

After reviewing source files I noticed that the main `CMakeLists.txt` is incomplete and `csrc/u8g2_button.c`  is missing in the `COMPONENT_SRCS` variable.

After adding it, the error was fixed.

**Comment by olikraus** [comment]
Ok ..
