### ISSUE TITLE
Driver selection for CFAG12864B-TMI-V display

### ISSUE THREAD

**Issue by leansrl** [olikraus/u8g2#2027]
Dear All,

I have a [CFAG12864B-TMI-V](https://www.crystalfontz.com/product/cfag12864btmiv-lcd-module-128x64-graphic) display which has a Neotec NT7108 COG controller.

- Is this display compatible with this library?
- Which driver should I select to make it work?
 
Thank you for your attention.

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#ks0108-128x64
