### ISSUE TITLE
SSD1362 256x64 driver Winstar WEA025664A

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#2051]
### Discussed in https://github.com/olikraus/u8g2/discussions/2043

<div type='discussions-op-text'>

<sup>Originally posted by **provitek** December  9, 2022</sup>
Hi,
I wanted to make project with WInstar WEA025664A 256x64 oled display. SSD1362 controller.
unfortunately it is not directly compatible with u8g2.
Does anyone know what controller it is compatible with or closest to?
What would need to be changed?
Could it be added in the next release?
https://www.winstar.com.tw/pl/products/oled-module/graphic-oled-display/wea025664a.html
THX</div>

**Comment by olikraus** [comment]
SSD1362 doesn't need the 0x5c to enable RAM write:

https://github.com/olikraus/u8g2/blob/cd5b4704a873a375882917c97cd33f4470b379cb/csrc/u8x8_d_ssd1322.c#L205 

The logic level for the DC line for command arguments is inverted. As a result we need "cad_001" for SSD1362 (instead of "cad_011").

https://github.com/olikraus/u8g2/blob/cd5b4704a873a375882917c97cd33f4470b379cb/tools/codebuild/codebuild.c#L1847

**Comment by olikraus** [comment]
Proposed init sequence:
``` C++
static const uint8_t u8x8_d_ssd1322_256x64_init_seq[] = {
    
  U8X8_DLY(1),
  U8X8_START_TRANSFER(),             	/* enable chip, delay is part of the transfer start */
  U8X8_DLY(1),
  
  
  U8X8_C(0xae),		                /* display off */
  U8X8_C(0XFD), //Set Command Lock
  U8X8_C(0X12), //(12H=Unlock,16H=Lock)

  U8X8_C(0XAE), //Display OFF(Sleep Mode)

  U8X8_C(0X15), //Set column Address
  U8X8_C(0X00), //Start column Address
  U8X8_C(0X7F), //End column Address

  U8X8_C(0X75), //Set Row Address
  U8X8_C(0X00), //Start Row Address
  U8X8_C(0X3F), //End Row Address

  U8X8_C(0X81), //Set contrast
  U8X8_C(0x2f),

  U8X8_C(0XA0), //Set Remap
  U8X8_C(0Xc3),

  U8X8_C(0XA1), //Set Display Start Line
  U8X8_C(0X00),

  U8X8_C(0XA2), //Set Display Offset
  U8X8_C(0X00),

  U8X8_C(0XA4), //Normal Display

  U8X8_C(0XA8), //Set Multiplex Ratio
  U8X8_C(0X3F),

  U8X8_C(0XAB), //Set VDD regulator
  U8X8_C(0X01), //Regulator Enable

  U8X8_C(0XAD), //External /Internal IREF Selection
  U8X8_C(0X8E),

  U8X8_C(0XB1), //Set Phase Length
  U8X8_C(0X22),

  U8X8_C(0XB3), //Display clock Divider
  U8X8_C(0XA0),

  U8X8_C(0XB6), //Set Second precharge Period
  U8X8_C(0X04),

  U8X8_C(0XB9), //Set Linear LUT

  U8X8_C(0XBc), //Set pre-charge voltage level
  U8X8_C(0X10), //0.5*Vcc

  U8X8_C(0XBD), //Pre-charge voltage capacitor Selection
  U8X8_C(0X01),

  U8X8_C(0XBE), //Set cOM deselect voltage level
  U8X8_C(0X07), //0.82*Vcc

  U8X8_C(0XAF), //Display ON

  U8X8_DLY(1),					/* delay 2ms */

  
  U8X8_END_TRANSFER(),             	/* disable chip */
  U8X8_END()             			/* end of sequence */
};
```

**Comment by olikraus** [comment]
@provitek I have created a new beta 2.34.8 with a new constructor `U8G2_SSD1362_WS_256X64_1_4W_HW_SPI`

Can you test whether this works. If not: Please send a screenshot of the display content.
You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by provitek** [comment]
thanks,
unfortunately I can't do it for arduino right now. I copied csrc to my project in STM32cubeIDE, modified main.c, set 16 bit mode.
```c
u8g2_Setup_ssd1362_ws_256x64_f(&u8g2, U8G2_R0, u8x8_byte_stm32_hw_spi, u8x8_stm32_gpio_and_delay);
````
![beta-1](https://user-images.githubusercontent.com/50798040/207746444-3cea3299-3abf-414d-9bc0-da94221be82c.jpg)

**Comment by provitek** [comment]
I don't knows, maybe it helps:
functions from winstar demo:
```c
//-------------------------------------------------
//          Write Data Function
//-------------------------------------------------
void Write_data(uint8_t datap)
{
	OLED_CS_LOW;
	OLED_DC_HIGH;

	HAL_SPI_Transmit(&hspi2, &datap, 1, 100);


	OLED_DC_LOW;
	OLED_CS_HIGH; //	LCM_CS1 = 1;
}
//-------------------------------------------------
//     WRITE_COMMAND
//-------------------------------------------------
void Write_command(uint8_t command)
{

	OLED_CS_LOW;
	OLED_DC_LOW;

	HAL_SPI_Transmit(&hspi2, &command, 1, 100);

	OLED_DC_HIGH;
	OLED_CS_HIGH; //	LCM_CS1 = 1;
}
```c

**Comment by olikraus** [comment]
great, looks better already.
I have updated https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_ssd1362.c
Can you test the new code again and send me a picture of it?

**Comment by provitek** [comment]
much better now :)
![20221215_075754](https://user-images.githubusercontent.com/50798040/207794108-8533281f-e434-48f8-83a3-34467766ee5b.jpg)

**Comment by olikraus** [comment]
well, yes, but I think the remap is still somehow wrong. I need more help from your end. Can you locate this line in your code:

https://github.com/olikraus/u8g2/blob/ad26a8f68c8d1e5b250085f8b25d41d7fb64842a/csrc/u8x8_d_ssd1362.c#L438-L440

Then replace 0xc3 by one of the following values: 0x03 0x83 0x13 0x93

Will any value improve the picture? Or is there even a value which makes it perfect?

It looks like the remap is another huge difference to the SSD1322, so we need to kind of reverse engineer the correct values.

**Comment by provitek** [comment]
I'll check tonight and let you know

**Comment by provitek** [comment]
Hi, 
I have tested with values as you give: (first - bitmap displayed via demo Winstar code, second - u8g2) 
0xC3
![0x03-bitmap](https://user-images.githubusercontent.com/50798040/207984304-d21600ed-34db-4c84-a824-02ade3c0b060.jpg)
![0x03-hello](https://user-images.githubusercontent.com/50798040/207984326-24940686-3f50-455f-8971-b623a2ba0fb2.jpg)

0x03
![0x03-bitmap](https://user-images.githubusercontent.com/50798040/207984390-341fb6ce-9a77-4542-9285-43ff81c2be8e.jpg)
![0x03-hello](https://user-images.githubusercontent.com/50798040/207984400-d5ac797e-502f-401d-ab88-a2ae9d4cc9f3.jpg)

0x13
![0x13-bitmap](https://user-images.githubusercontent.com/50798040/207984497-eb9b4cd3-da39-484f-8dff-30cd780db84c.jpg)
![0x13-hello](https://user-images.githubusercontent.com/50798040/207984505-a8cefda4-3335-4aa2-8c08-c9351004e2cd.jpg)

0x83
![0x83-bitmap](https://user-images.githubusercontent.com/50798040/207984529-f014488b-622b-
![0x83-hello](https://user-images.githubusercontent.com/50798040/207984537-c31894f9-5178-4651-ba24-c0a98da91a5b.jpg)
4710-8e9a-4dce34c221f8.jpg)

0x93
![0x93-bitmap](https://user-images.githubusercontent.com/50798040/207984574-c8565487-5dc0-4d2b-a865-373218029f73.jpg)
![0x93-hello](https://user-images.githubusercontent.com/50798040/207984589-1443c7b0-ad52-4391-9d55-3500d183f594.jpg)

**Comment by provitek** [comment]
Winstar demo code:
```c
//=========================================ȡģ��ʾ����
void White_IMAGE(unsigned char *p)
{
	unsigned int x,y;

	Write_command(0X15); //Set column Address
	Write_command(0X00); //Start column Address
	Write_command(0X7F); //End column Address

	Write_command(0X75); //Set Row Address
	Write_command(0X00); //Start Row Address
	Write_command(0X3F); //End Row Address
	
	for(y = 0;y < 64;y ++)
	{   
    	for(x = 0;x < 32;x ++)
		{
			write_4_data(*p++);
		}		
	} 
}
void write_4_data(unsigned char dispdata)		 //?4?����
{ 
	unsigned char i,temp0,temp1,temp2[4]; 

	temp0=dispdata;
	for(i=0;i<4;i++)
		{
   	    temp1=0xc0&temp0;		 // temp0�c0xc0���c��temp1�ĽY������߃�λ���ֲ�?�����Nλ��0�F
		switch(temp1)			 //�l���x��
			{
			case 0x00:			 //temp1=0x00
			temp2[i]=0x00;
			break;
			case 0x40:			 //temp1=0x40
			temp2[i]=0x0f;
			break;
    		case 0x80:			 //temp1=0x80
			temp2[i]=0xf0;		 
			break;
			case 0xc0:			 //temp1=0xc0
			temp2[i]=0xff;
			break;
			default:                           
   			break;
 			}
		temp0=temp0<<2;			 //���ƃ�λ
		Write_data(temp2[i]);				 //����?��һ�M������4?��
		}
}

//=========================================ȫ��/ȫ����ʾ����
void White_IMAGE1(unsigned char dat)
{
	unsigned int x,y;

	Write_command(0X15); //Set column Address
	Write_command(0X00); //Start column Address
	Write_command(0X7F); //End column Address

	Write_command(0X75); //Set Row Address
	Write_command(0X00); //Start Row Address
	Write_command(0X3F); //End Row Address
	
	for(y = 0;y < 64;y ++)
	{   
    	for(x = 0;x < 128;x ++)
		{
			Write_data(dat);
		}		
	} 
}

//=========================================	50%������ʾ����
void White_IMAGE2(unsigned char dat1,unsigned char dat2)
{
	unsigned int x,y,z;

	Write_command(0X15); //Set column Address
	Write_command(0X00); //Start column Address
	Write_command(0X7F); //End column Address

	Write_command(0X75); //Set Row Address
	Write_command(0X00); //Start Row Address
	Write_command(0X3F); //End Row Address
	
	for(y = 0;y < 32;y ++)
	{
		for(z=0;z<2;z++)
		{
    		for(x = 0;x < 32;x ++)
			{
				Write_data(dat1);
			}
			for(x = 0;x < 32;x ++)
			{
				Write_data(dat2);
			}		
		}  
	}
	for(y = 0;y < 32;y ++)
	{
		for(z=0;z<2;z++)
		{
    		for(x = 0;x < 32;x ++)
			{
				Write_data(~dat1);
			}
			for(x = 0;x < 32;x ++)
			{
				Write_data(~dat2);
			}		
		}  
	}
}

**Comment by olikraus** [comment]
Thanks for your effort. I think I need to order one of the displays. Looks like more effort to understand the internal memory architecture.
Is this one of the items? https://de.aliexpress.com/item/32259159336.htmlhttps://de.aliexpress.com/item/32259159336.html

**Comment by olikraus** [comment]
I have ordered the OLED. It will arrive in 4 weeks.

**Comment by provitek** [comment]
Thank you! My pleasure :)
Sorry I couldn't help.
Its different display, hope it will work. Fingers crossed :)
mine is: https://www.winstar.com.tw/pl/products/oled-module/graphic-oled-display/wea025664a.html
THX
![disp](https://user-images.githubusercontent.com/50798040/208047825-00ffd579-519e-4079-83df-26ec1e62ec49.jpg)

**Comment by olikraus** [comment]
I think there is something I missed.i need to debug the display controller more closely.

**Comment by olikraus** [comment]
Added support for my ordered display: ![https://github.com/olikraus/u8g2/wiki/img/ssd1362_zjy_256x64.jpg](https://github.com/olikraus/u8g2/wiki/img/ssd1362_zjy_256x64.jpg)

All updates should be in the u8g2 repo now.

**Comment by olikraus** [comment]
I have also created a new beta release 2.34.11...

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by olikraus** [comment]
Note: I have change the constructor name a little bit: U8G2_SSD1362_256X64_1_4W_HW_SPI

https://github.com/olikraus/u8g2/wiki/gallery#3-jan-2023-ssd1362-256x64-and-206x36

**Comment by provitek** [comment]
It works! :)
Thank you! 
![ssd1362](https://user-images.githubusercontent.com/50798040/210423414-4e0453ac-26da-4b29-88cb-e32b325ee906.jpg)

**Comment by olikraus** [comment]
Nice :-)

**Comment by olikraus** [comment]
A new issue might be better. Also a picture, constructor, code, Arduino Board...

**Comment by NixieGuy** [comment]
Sorry, all this is new for me. I'll start again. (Opening an issue makes me feel bad, like I'm bothering _everyone_ for no reason) Also, it's related to code in this thread.

So, while trying to use the screen MDOB256064D1Y-YS that also uses the SSD1306, using an STM32F103C8T6, Platform.io on Visual Studio Code.  I could not make it work, until I notticed that the descriptor written in this thread was:

U8G2_SSD1362_256X64_1_4W_HW_SPI

But the SSD1362 examples in the library had a 1 substituted by an F.

U8G2_SSD1362_256X64_F_4W_HW_SPI

 When I changed that in my code the screwn worked beautifully.

![a7dabc187b57f226-1](https://github.com/olikraus/u8g2/assets/58027912/196444c3-342a-4503-a392-69e6d4c79099)

**Comment by IFYBB** [comment]
Hello everyone. 

I'm trying to display text on the display WEA025664AWAP3N (SSD1362). I use the recommendations from the message https://github.com/olikraus/u8g2/issues/2051#issuecomment-1369275575, But that doesn't solve the problem.
Code:
```
#include <Arduino.h>
#include <U8g2lib.h>
#include <SPI.h>
#include <Wire.h>

U8G2_SSD1362_256X64_1_4W_HW_SPI u8g2(U8G2_R0, 10, 9, 8); // [page buffer, size = 256 bytes] for Arduino Mega

void setup(void) {
  u8g2.begin();
}

void loop(void) {
  u8g2.firstPage();
  do {
    u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.drawStr(5, 5,"Hello!");
  } while ( u8g2.nextPage() );
}
```

Nothing appears on the display. Where am I going wrong?
