### ISSUE TITLE
ssd 1322 256*64 does not fullfill entire display

### ISSUE THREAD

**Issue by deg87** [olikraus/u8g2#2054]
Hi, sorry to bother, i notice that using ssd1322 on 256*64 oled display it is impossible to fullfill the entire display.
i mean that i can only print on a 228*64 and some column on the right of the display is unutilized, can you please give an eye to this?
i suspect that these last colum are mapped before the first column.

**Comment by olikraus** [comment]
Did you enable 16 bit Mode? See FAQ

**Comment by deg87** [comment]
got it
