### ISSUE TITLE
Full Page buffer after send 

### ISSUE THREAD

**Issue by VitaliGN** [olikraus/u8g2#207]
Hello again, I am in the phase of experiment and would ask one thing that I do not know how to check. 

I use full page buffer type, first clear, then send. the question is: would it have a positive effect, or there will no be difference if I clear buffer right after send? Will it free some memory until next buffer send? or it is constantly used, even when cleared?

`
	
	Oled1.clearBuffer();
	Oled1.setFont(u8g_font_profont12);
	Oled1.drawStr(0, 20, "Hello");
	
	Oled1.sendBuffer();

	Oled1.clearBuffer();	// and clear the buffer - I am just curious will it make my program clean or opposite it will add more commands which not needed
`

**Comment by olikraus** [comment]
You can clear the buffer at any time. It would not make a difference. There is no dynamic memory allocation. U8g2 will use a static buffer only.

**Comment by VitaliGN** [comment]
thank you

**Comment by olikraus** [comment]
No problem
