### ISSUE TITLE
Software I2C to slow on SH1106 OLED

### ISSUE THREAD

**Issue by Blo0dR0gue** [olikraus/u8g2#2074]
hello,

we try to use two SH1106 displays in our project - one with hardware i2c and one with software i2c (on other pins). 
We noticed that the software I2C is very slow with about 500ms (only the sendBuffer() function measured). 
As a controller we use a Pro Micro, which has only one hardware i2c bus and to change the i2c address on the second display is currently not possible. 
We tried to setBusClock with now effect.
Is that normal that the software i2c takes so much longer or is there something we can do about it?

**Comment by olikraus** [comment]
Yes, Software emulated i2c is usually much slower.
