### ISSUE TITLE
non-functional code example 'u8g2_hw_i2c.cpp' with potential to destroy controller

### ISSUE THREAD

**Issue by FrederikWolter** [olikraus/u8g2#2076]
Hi,

trying to figure out how the `setI2CAddress()`-method works i came across the [u8g2_hw_i2c.cpp](https://github.com/olikraus/u8g2/blob/7a2f24fb5b4154588a6072d066c082ce17daea2d/sys/arm-linux/examples/cpp-examples/u8g2_hw_i2c_cpp/u8g2_hw_i2c.cpp) example.
Attempting to compile it, I get errors due to several methods not being part of the used class: 
`u8g2.initI2cHw(I2C_BUS);`, `u8g2.sleepMs(5000);`; `u8g2.doneI2c();` and `u8g2.doneUserData();` throw the **error** `'class U8G2_SSD1306_128X64_NONAME_F_HW_I2C' has no member named ...`.

**Commenting** these lines out, made me not being able to flash my Arduino Pro Micro any more.
I think this is because there is not enough delay before the Arduino starts the powersave and not responding to flash attempts.

To save others from the struggle trying to reset their controller boars, maybe it would be worth changing this example.

Thanks for your work!
Frederik

**Comment by olikraus** [comment]
Well, this is external contributed code... It should not be required and will probably not run under the Arduino Environment.
