### ISSUE TITLE
Improve Wiki description: Chapter "Setup Naming Convention"

### ISSUE THREAD

**Issue by tusker-tools** [olikraus/u8g2#2083]
Hello,
first of all thank you Oliver for this great project! Especially the good documentation in the Wiki is a big help!

I recently managed to get a ST7920 128x64 display working. I used a STM32F103 µC (Blue-Pill board) with HW-SPI. As IDE I used STM32CubeIDE with bare-metal C.

One thing which took me a bit of time to debug was the setup procedure.
I read carefully the instruction, which stated that for HW SPI, the setup procedure without "i2c" in the name should be used:
![image](https://user-images.githubusercontent.com/82545992/213545979-7118cf5a-c51b-4eb5-93c0-406a2c1df900.png)
So I used `u8g2_Setup_st7920_128x64_f(...)`, which was actually the wrong one.
After several time of debugging (and by comparing to examples found in the internet), I noticed that actually `u8g2_Setup_st7920_s_128x64_1(...)` was the correct function to use. Afterwards, everything worked fine.

I propose to change the description here to make it more clear that:
`<i2c>` is for displays connected via I2C display 
`<s>` is for displays connected via SPI 
`<>` No letter at all is for ???

Maybe it would also be helpful to mention the specific interface (spi/i2c/...) in the chapter description of each display (where I put a yellow marking in the screenshot):
![image](https://user-images.githubusercontent.com/82545992/213548408-e342245a-d06e-4c27-b3e1-7cb7df6e535e.png)

Best regards,
Philipp

**Comment by olikraus** [comment]
I think this applies to u8g2 instead of u8glib: Transfered.

I fully agree, that this is a little bit confusing. Indeed the ST7920 is an exception and the <s> actually denots the special ST7920 serial communication, which is unique somehow. 
The C++ / Arduino interface is more consistent. Well, doesn't help here. Let me see what I can do here.
Thanks for the hint.

**Comment by olikraus** [comment]
Added some clarification
