### ISSUE TITLE
There is  an optimization in the U8g2 Contructor List 

### ISSUE THREAD

**Issue by Tiky169** [olikraus/u8g2#2093]
Hello olikraus,
    I am very sorry that I forgot to tell you that the OEL1M0201 does not support SPI mode, and their default pinout, when I pulled the request earlier. Here is the corrected and tested list, could you please update it? Thanks!

`
U8G2_SH1107_HJR_OEL1M0201_96X96_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ 2, /* data=*/ 0, /* reset=*/ U8X8_PIN_NONE);
U8G2_SH1107_TK078F288_80X128_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 15, /* dc=*/ 0, /* reset=*/ U8X8_PIN_NONE);
`

**Comment by olikraus** [comment]
I am confused. Can you link the PR you mentioned?

**Comment by Tiky169** [comment]
PR is no problem. You have this default list in every example in U8G2.
The default list should be 
`U8G2_SH1107_HJR_OEL1M0201_96X96_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ 2, /* data=*/ 0, /* reset=*/ U8X8_PIN_NONE); U8G2_SH1107_TK078F288_80X128_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 15, /* dc=*/ 0, /* reset=*/ U8X8_PIN_NONE);`

and not : 
`
U8G2_SH1107_HJR_OEL1M0201_96X96_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);
U8G2_SH1107_TK078F288_80X128_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);
`
because  the OEL1M0201 is not an SPI LCD, it is an IIC type LCD.

**Comment by olikraus** [comment]
Reference: https://github.com/olikraus/u8g2/issues/1897

Done...
