### ISSUE TITLE
ESP8266 compatibility most wanted :)

### ISSUE THREAD

**Issue by aShure** [olikraus/u8g2#21]
I remember there were problems with the non existing garbage collection with u8g. Not sure if this new version still has those requirements, in any case, an ESP port would be great!

**Comment by aShure** [comment]
I shall test software before posting feature requests.
I shall test software before posting feature requests.
I shall test software before posting feature requests.
I shall test software before posting feature requests.
I shall test software before posting feature requests.

**Comment by olikraus** [comment]
hehe
