### ISSUE TITLE
setBusClock() not correctly setting bus clock

### ISSUE THREAD

**Issue by ken830** [olikraus/u8g2#2106]
I'm driving a running an I2C OLED screen with a WeMos D1 Mini and I have a minor issue, but I'm wondering if there is something I'm overlooking here. I know I2C clock rates aren't exact. At the default 400kHz, I'm seeing maximum clock periods of approximately 392kHz. When I call `setBusClock(1000000)` to set to 100kHz, I'm observing maximum clock periods of 76kHz. That's quite a bit off. I tried various settings and this is what I'm seeing:

| set 	| actual 	| %    	|
|-----	|--------	|------	|
|  75 	|   55.5 	| 0.74 	|
| 100 	|     76 	| 0.76 	|
| 133 	|    104 	| 0.78 	|
| 200 	| 154.75 	| 0.77 	|
| 250 	|  197.5 	| 0.79 	|
| 300 	|    282 	| 0.94 	|
| 400 	|    392 	| 0.98 	|

I thought there would be a fixed offset or a linear relationship with a scaling factor, but it just seems like there is a bend point and any setting below 300kHz is quite a bit off.

Is there a good explanation for this? Thanks!

**Comment by olikraus** [comment]
U8g2 just calls the corresponding Arduino procedures for clock setup.
The Arduino procedures probably will setup the clock speed as close as possible but it actually depends on the uC hardware how much the real clock frequency deviates from the desired frequency.
All in all, there is nothing mich what U8g2 can do here.
