### ISSUE TITLE
ST7567 has no I2C constructors available in U8x8

### ISSUE THREAD

**Issue by jonathanmlang** [olikraus/u8g2#2108]
I have my display working nicely in u8g2 but I want to run it in text only mode with no buffer, seems like there is no way of doing this.

Works in full buffer mode with this constructor:
U8G2_ST7567_ENH_DG128064_F_SW_I2C u8g2(U8G2_R0, SCL, SDA, U8X8_PIN_NONE);

This does not work:
U8G2_ST7567_ENH_DG128064_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);

This constructor does not exist in the u8X8 library but I think it should?
U8X8_ST7567_ENH_DG128064_F_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);

The display I am trying to use:
https://www.aliexpress.com/item/1005004237282931.html

Thanks in advance for your time!

**Comment by olikraus** [comment]
1. If you use ESP uC try to use pin remap with the HW constructor.
2. Some displays are not supported by u8x8 due to a different memory architecture.

**Comment by jonathanmlang** [comment]
Hello, Thanks for replying quickly. Im using an arduino uno board.
This display appears to have a constructor available in u8x8 but for SPI mode only, eg
U8X8_ST7567_ENH_DG128064I_4W_HW_SPI u8x8(/* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8); 
But my display doesnt have the spi pins exposed, just I2c, so im wondering if it would be possible to make an i2c constructor?

**Comment by olikraus** [comment]
They do exist:
U8X8_ST7567_ENH_DG128064I_HW_I2C
U8X8_ST7567_ENH_DG128064I_SW_I2C

See also https://github.com/olikraus/u8g2/wiki/u8x8setupcpp

**Comment by jonathanmlang** [comment]
Thanks for your help, I have managed to get it working with the sw i2c but still no luck with the hw i2c. 
U8X8_ST7567_ENH_DG128064I_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE, SCK, SDA); is what i used to try hw i2c

**Comment by olikraus** [comment]
Uno Board has fixed clock and data lines. Remove the last two arguments and connect i2c to the i2c lines of uno (I think A4 and A5)

**Comment by jonathanmlang** [comment]
Yep, thats where I connected the lcd.
U8X8_ST7567_ENH_DG128064I_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);
Still nothing from the lcd.

**Comment by olikraus** [comment]
Hmmm did you add 10k pull up resistors?

**Comment by jonathanmlang** [comment]
Hello, Ive solved the problem. I had to set the i2c clock 
u8x8.setBusClock(200000UL);
That got it working, seems this display doesnt like fast data rates.

**Comment by olikraus** [comment]
Oh, nice finding

**Comment by jonathanmlang** [comment]
Indeed, Thanks for you help here though. More often ill post an issue on other peoples programs and not get a reply or get one unhelpful answer and nothing more after weeks. So im very appriciative of your quick replies.

**Comment by olikraus** [comment]
Thanks
