### ISSUE TITLE
error: this condition has identical branches [-Werror=duplicated-branches]

### ISSUE THREAD

**Issue by aneox** [olikraus/u8g2#2132]
https://github.com/olikraus/u8g2/blob/4d9f63394f070a9f6e079ae8bccb97bad5967481/csrc/u8x8_d_st75256.c#L1895

**Comment by olikraus** [comment]
nice finding

**Comment by olikraus** [comment]
This might be related to #2058

**Comment by olikraus** [comment]
should be fix now, however the code itself is not finished.
