### ISSUE TITLE
Please add support ELW0901AA (LD7032)

### ISSUE THREAD

**Issue by iggymayer** [olikraus/u8g2#2135]
https://mega.nz/file/AF0QSAYR#xLxlIQQKIUClCdAZPUkWpPQ64zNi-doQkAz_ZGgTioM
Please add support ELW0901AA,Driver IC:LD7032.
If you can,please support both I2C & SPI interfaces,Thank you!

**Comment by olikraus** [comment]
The init sequence in the above datasheet implies, that you will drive the display logic power with 1.8V and you will provide an external 18V power supply for the OLED itself, correct?

**Comment by olikraus** [comment]
I have created a new beta release with the new constructor "U8G2_LD7032_128X36..."

Can you check whether the new constructor works?



You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by iggymayer** [comment]
I will test it after receiving the PCB next month，Thank you!

**Comment by olikraus** [comment]
Any feedback on this?

**Comment by iggymayer** [comment]
Set Address 0x6E
Can be lit but cannot be displayed normally.

**Comment by olikraus** [comment]
which constructor did you use? which code/example did you run?

**Comment by iggymayer** [comment]
> which constructor did you use? which code/example did you run?

> Hello World
#include <Arduino.h>
#include <U8g2lib.h>
#include <Wire.h>

U8G2_LD7032_128X36_F_HW_I2C u8g2(U8G2_R0, 9, 8, 1);

void setup(void)
{
  u8g2.setI2CAddress(0x6E);
  u8g2.begin();
}

void loop(void)
{
  u8g2.clearBuffer();                   // clear the internal memory
  u8g2.setFont(u8g2_font_ncenB08_tr);   // choose a suitable font
  u8g2.drawStr(10, 10, "Hello World!"); // write something to the internal memory
  u8g2.sendBuffer();                    // transfer internal memory to the display
  delay(1000);
}

**Comment by iggymayer** [comment]
> hello world
#include <Arduino.h>
#include <U8g2lib.h>
#include <Wire.h>

U8G2_LD7032_128X36_F_HW_I2C u8g2(U8G2_R0, 9, 8, 1);

void setup(void)
{
  u8g2.setI2CAddress(0x6E);
  u8g2.begin();
}

void loop(void)
{
  u8g2.clearBuffer();                   // clear the internal memory
  u8g2.setFont(u8g2_font_ncenB08_tr);   // choose a suitable font
  u8g2.drawStr(10, 10, "Hello World!"); // write something to the internal memory
  u8g2.sendBuffer();                    // transfer internal memory to the display
  delay(1000);
}

**Comment by olikraus** [comment]
I have created a new beta with some updates: 2.34.19
Will this work better?
You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Arduino IDE:
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

PlatformIO:
`platformio.ini` (https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) should include 
```
lib_deps =
  u8g2=https://github.com/olikraus/U8g2_Arduino/archive/master.zip
```

**Comment by iggymayer** [comment]
The version number of the file downloaded by the link is 2.34.20.
The problem remains.

**Comment by olikraus** [comment]
Strange. Are you able to check the same with SPI interface instead?

**Comment by iggymayer** [comment]
Only use I2C

**Comment by olikraus** [comment]
I am not sure how to continue from here. I have exactly implemented the information from your data sheet and the last commit fixed some values which might have been wrong.

**Comment by iggymayer** [comment]
Thank you for your help!
Let's close this issue for now, and I'll figure it out when I have time.

**Comment by olikraus** [comment]
Sure, no problem. Closing for now.

**Comment by iggymayer** [comment]
#2785 
Sorry for the long wait.

**Comment by olikraus** [comment]
hmm... The PR is huge and difficult to check.
