### ISSUE TITLE
git version tags

### ISSUE THREAD

**Issue by tcurdt** [olikraus/u8g2#214]
The log suggests there are versions (2.4.17) for the lib - but the repo has no releases nor tags.
Did you maybe forgot a `git push --all`?

**Comment by olikraus** [comment]
The releases are maintained in a different repo:
https://github.com/olikraus/U8g2_Arduino/releases

Any lib which should appear in the Arduino IDE has to have a specific structure. However this structure differes from the u8g2 project. Thats why there are two github projects: One which is used for development and another project for Arduino Lib Releases.

**Comment by tcurdt** [comment]
It still would be nice to have the release tags on the dev repo.

**Comment by olikraus** [comment]
True. I try to them in the future.

**Comment by RechieKho** [comment]
True, it still would be nice to have the release tags on the dev repo.

**Comment by RechieKho** [comment]
Woah, so cool that I got such quick response!

Unfortunately, I only get the [tag from 3 years ago](https://github.com/olikraus/u8g2/releases/tag/2.29.11). It is not mandatory, but it would still be nice to have a tag so it is easier to include this as a CMake project via FetchContent (at least for me). Did you push the tags (via `git push --tags`) though?

**Comment by olikraus** [comment]
Hmm... good point.
Maybe I should do something like: git config --global push.followTags true
in the repo

**Comment by olikraus** [comment]
Once you turn `git config --global push.followTags true` setting on, your standard git push becomes smarter. It will automatically include tags, but with two important safety rules:

 * It only pushes Annotated Tags: It will ignore lightweight tags (tags created without the -a, -s, or -m flags).
 * It only pushes Relevant Tags: It will only push tags that belong to the history of the specific branch you are pushing. It won't push random tags sitting on other branches.

... this probably is still not good enough... 
I feel i still should do 
`git push --tags`

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/commit/37baa160be1867d17505e4760c0cd3a9d0ba682e

**Comment by olikraus** [comment]
this should work better now...
