### ISSUE TITLE
ST7567 122x32 LCD

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#2152]
### Discussed in https://github.com/olikraus/u8g2/discussions/2140

<div type='discussions-op-text'>

<sup>Originally posted by **Ultramxn** March 23, 2023</sup>
Hello,
I have a ST7657 12232 LCD cannot display anything with 12232 constructor in u8g2 but display well with OS12864 constructor except skipping six pixels on the left of the screen, that is, missing first character in the test. May I ask can we override screen width of a constructor by passing parameter?

</div>

**Comment by olikraus** [comment]
Summary:
Based on the U8G2_ST7567_OS12864_F_4W_SW_SPI there should be a new constructor for a 122x32 display with x offset 10.

@ultramxn is there any link to sales location or a datasheet for the display?

**Comment by Ultramxn** [comment]
@olikraus It was bought from ali before covid so I'm sorry I haven't got data sheet and the link's no longer exist.

**Comment by olikraus** [comment]
There is already a 122x32 constructor available in u8g2 (issue #1759). Will this work for you? How will the output look like with this existing `U8G2_ST7567_122X32_xxx` constructor? 
You might need to adjust contrast with `u8g2.setContrast`.

**Comment by Ultramxn** [comment]
> There is already a 122x32 constructor available in u8g2 (issue #1759). Will this work for you? How will the output look like with this existing `U8G2_ST7567_122X32_xxx` constructor? You might need to adjust contrast with `u8g2.setContrast`.

By changing contrast as you said, I got something displayed but freezed at graphics test example when the same example running well with OS12864  constructor except there were six pixels missing on the left. The following was taken when running graphics test with u8g2 122X32 constructor:
![20230623_211332](https://github.com/olikraus/u8g2/assets/128638756/e3a9d778-9f2b-47bb-afd9-d14d476d3d6f)

**Comment by olikraus** [comment]
Please execute FlipMode.ino example (See example menu in Arduino IDE or [here](https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/FlipMode/FlipMode.ino)). The flip mode test example will cycle through eight modes. In all modes there must be a solid frame next to the border of the display.

So maybe can you send a picture of that border frame?

**Comment by Ultramxn** [comment]
> Please execute FlipMode.ino example (See example menu in Arduino IDE or [here](https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/FlipMode/FlipMode.ino)). The flip mode test example will cycle through eight modes. In all modes there must be a solid frame next to the border of the display.
> 
> So maybe can you send a picture of that border frame?

There was no display using 12232 constructor :
![20230708_022039](https://github.com/olikraus/u8g2/assets/128638756/77ad51ad-5605-4933-bf2a-6898d1da7e8d)
and these are some photos taken when using OS12864 constructor :
![20230708_021941](https://github.com/olikraus/u8g2/assets/128638756/002fea68-71ee-48ea-89d7-ecedbe93c065)
![20230708_022206](https://github.com/olikraus/u8g2/assets/128638756/74ee4e4c-237e-4b21-b1ef-8f71ccd8ba45)
![20230708_022110](https://github.com/olikraus/u8g2/assets/128638756/d727fd4a-e491-4d3e-bc0d-951ce5b47797)

**Comment by olikraus** [comment]
ok, so you have used the OS12864 constructor for the ST7567 to generate the above pictures with a custom set contrast value. What had been your costom value?

**Comment by Ultramxn** [comment]
Yes, I've used OS12864 constructor but its default value to generate the above pictures.

**Comment by olikraus** [comment]
Excause, probably I missed the email replies on this topic.
Actually I don't know how to proceed here.  Initially you mentioned, that the `U8G2_ST7567_122X32` constructor work. Later it didn't work any more. 

Is there any datasheet for this display? Where did you buy this display?
