### ISSUE TITLE
Installing outside of Arduino IDE

### ISSUE THREAD

**Issue by ninjadude752** [olikraus/u8g2#2165]
Is it possible to install the library outside of the arduino IDE? I'd like to install it in Atmel Studio 7 if that is possible.

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/wiki/u8g2as7

https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform

**Comment by ninjadude752** [comment]
Thank you!
