### ISSUE TITLE
Ks0108 and pcf8574

### ISSUE THREAD

**Issue by sonic2wb** [olikraus/u8g2#217]
Thank You for such a great library. A while back i stumbled apon useing this display with u8g2 and 2 i2c port expanders. well the posts and files are gone! all thats left is a youtube video showing it working. I was hoping maybe someone had a copy of the schematic what what info needs to be changed in the library to make it work, I know theres native support in paraell mode but i was going to get this working on an esp8266.
https://www.youtube.com/watch?v=rqFrl2glvq8

Google has the cashed post but the links to the files are dead. 

http://webcache.googleusercontent.com/search?q=cache:eJ8YhDTNGGAJ:forum.wemos.cc/topic/945/driving-a-ks0108-glcd-display/6+&cd=1&hl=en&ct=clnk&gl=us

**Comment by olikraus** [comment]
The discussion for this project actually happend in the Arduino forum:
https://forum.arduino.cc/index.php?topic=409966.60

Some parts of the code are located there (not sure whether this is complete). You could also try to contact Arduino forum member PaulRB.
