### ISSUE TITLE
EA DOGS102N display contrast

### ISSUE THREAD

**Issue by linxcow** [olikraus/u8g2#2181]
I have noticed the contrast is a bit off ( light gray background ) for the DOGS102N graphic display.

Is this something i can change myself in the code?

**Comment by olikraus** [comment]
You could try different values with the https://github.com/olikraus/u8g2/wiki/u8g2reference#setcontrast command.

**Comment by linxcow** [comment]
Thank you , will try it.

**Comment by linxcow** [comment]
Worked great , closing.
