### ISSUE TITLE
Suggestion: font_tiny5

### ISSUE THREAD

**Issue by Gissio** [olikraus/u8g2#2185]
I have just published font_tiny5, a variable-size 5-pixel font for low-resolution LCD displays:

https://github.com/Gissio/font_tiny5

Perhaps you consider it worthwhile for the u8g2 fonts repository. Though it is quite similar to other fonts, there are tiny details that make it (IMHO) more legible than alternatives. It also features Unicode block 1.

BTW, thanks for u8g2! I used it in a custom firmware for a Geiger counter: https://github.com/Gissio/fs2011pro.

**Comment by olikraus** [comment]
Very nice font and cool project.

Thanks for contributing your font to u8g2 :-)

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/wiki/fntgrpu8g
