### ISSUE TITLE
Add support for LC7981 with 160x160

### ISSUE THREAD

**Issue by Ancalagon94** [olikraus/u8g2#222]
Hi,
I would like to use a Winstar WG 160x160 display with a LC7981 interface. However, I can't seem to find any library that supports this, the closest being for 160x80 display. If there isn't a simple solution I have overlooked, would it be possible to add support for this resolution?

**Comment by olikraus** [comment]
Can be done if you you takeover testing. But I do not have much internet access at the moment. Maybe next week.

**Comment by olikraus** [comment]
I have a test version here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip

Please install this zip file via the "add zip lib" feature of the Arduino IDE. 
Can you sent me some test results of the new driver?

**Comment by stevie72** [comment]
Hello olikraus!
I´m using a PCD8544 (Nokia5110). Is there a clearscreen funtion in you Library u8g2 for arduino?
Thanks, Stefan

**Comment by olikraus** [comment]
Clear screen: yes, see the reference.
