### ISSUE TITLE
Add support for CH1115

### ISSUE THREAD

**Issue by norgey** [olikraus/u8g2#2227]
Please add support for CH1115
https://www.orientdisplay.com/wp-content/uploads/2021/02/CH1115_Datasheet.pdf

**Comment by olikraus** [comment]
Did you try any of the SSD1306 display driver?

**Comment by norgey** [comment]
That was a good hint... Now it works with some init-modifications. THX!

**Comment by alexbussiere** [comment]
@norgey What were the init modifications that you needed to do ? I am looking to use a CH1115 based display as well

**Comment by norgey** [comment]
Finally IT worked without modifications. In used ssd1306 drüber.
