### ISSUE TITLE
Clear particular pixels and not entire display 

### ISSUE THREAD

**Issue by himanshushah05** [olikraus/u8g2#2246]
How can we clear just particular pixles on the screen and not the entire display using clearDisplay() ?

**Comment by v1993** [comment]
Wouldn't this be just `setDrawColor(0)` followed by `drawBox` with appropriate values? Don't forget to call `setDrawColor()` afterwards to restore normal drawing mode for other operations.

**Comment by himanshushah05** [comment]
> Wouldn't this be just `setDrawColor(0)` followed by `drawBox` with appropriate values? Don't forget to call `setDrawColor()` afterwards to restore normal drawing mode for other operations.
> 
> Speaking of which - `clearDisplay()` docs note that it is usually not needed as `sendBuffer`/`nextPage` already clear the buffer. So you shouldn't rely on image persisting between frames, it would seem.

Oh yeah, worked perfectly fine
Thank you
