### ISSUE TITLE
Which driver chip to select for M5stack Coreink  module ?

### ISSUE THREAD

**Issue by linxcow** [olikraus/u8g2#2247]
@olikraus 

What config should i use for using library with my coreink module?
the current api from M5stack has only 2 size fonts for this module.

**Comment by olikraus** [comment]
Hmm I have no idea

**Comment by linxcow** [comment]
This is what i could about the Eink display used , dont know if this helps?

https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/core/CoreInk-K048-GDEW0154M09%20V2.0%20Specification.pdf

**Comment by olikraus** [comment]
Thanks for the link, however this eInk is not supported by u8g2 (as far as I understood the datasheet).

**Comment by linxcow** [comment]
Thank you for taking a look , i will try to find other solution
