### ISSUE TITLE
2 Pixel horrizontal offset?

### ISSUE THREAD

**Issue by maik-dmxc** [olikraus/u8g2#225]
I have a problem with the u8g2 and a SSD1306_128X64 display.
on the left side, 2 pixels are lost?
on the rigth side, a strange 2 pixel wide vertikal line appears

the sketch is the full_buffer fps.ino

selected hardware is
`U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);
`

same thing with spi display.
same behavior with all other sample sketches.
![20170325_205652](https://cloud.githubusercontent.com/assets/8010861/24325694/a3f319ac-119e-11e7-9cce-641561e55651.jpg)
![20170325_205702](https://cloud.githubusercontent.com/assets/8010861/24325698/a84ba636-119e-11e7-8f73-c032b914dc12.jpg)

**Comment by combs** [comment]
Try the SH1106 initializer instead of SSD1306... I think the SH1106 is very similar but has 132x64 pixels in its internal memory instead of 128x64.

**Comment by maik-dmxc** [comment]
solved!!!

Hi comps,

with 
`U8G2_SH1106_128X64_NONAME_1_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE, /* clock=*/ SCL, /* data=*/ SDA);`
it works for me.

regards Maik
