### ISSUE TITLE
[HELP] Custom fonts

### ISSUE THREAD

**Issue by Dario-Ciceri** [olikraus/u8g2#2259]
hi, how can I create a custom font from something like this https://www.fontrepo.com/font/21332/seven-segment?

I can't understand how fony works and how to convert bdf (parameters, command line etc)
For example: i would like to have a font with 0123456789+-. size 15x31 what should I do?

Thanks

**Comment by olikraus** [comment]
Did you check the FAQ?

https://github.com/olikraus/u8g2/blob/605f6c5c8e369cd52b87dba61dd47479c9a87c61/doc/faq.txt#L255-L294

Let me know if you have still question.

**Comment by olikraus** [comment]
Some 7-segment fonts are listed here: https://github.com/olikraus/u8g2/wiki/fntgrpu8g

**Comment by Dario-Ciceri** [comment]
> Did you check the FAQ?
> 
> https://github.com/olikraus/u8g2/blob/605f6c5c8e369cd52b87dba61dd47479c9a87c61/doc/faq.txt#L255-L294
> 
> Let me know if you have still question.

Yes, also read some old issues! It was me not understanding how to use Fony.... now it perfectly works!
Great library!
Thanks.
