### ISSUE TITLE
ks0108 constructor

### ISSUE THREAD

**Issue by sonic2wb** [olikraus/u8g2#226]
U8G2_KS0108_128X64_1(rotation, d0, d1, d2, d3, d4, d5, d6, d7, enable, dc, cs0, cs1, cs2 [, reset])

can you tell me what dc stands for. my board has cs1 and cs2 im assuming i use cs0 and cs1 and leave cs2 as none. also what pin does R/W need to be on. ur just tie it low? and the D/I pin. what or where is that defined??

i cant get the pcf i2c board i made to work so i thought i would try this first. but still no luck.
i did get OpenGLCD to work but my project is all coded with u8g2 and would love to get this display working.

**Comment by sonic2wb** [comment]
Please delete or close I got it to work!! thank u so much for your time and effort!!

**Comment by olikraus** [comment]
D/I = dc
