### ISSUE TITLE
U8G2 and timer interrupts

### ISSUE THREAD

**Issue by robmaxtech** [olikraus/u8g2#2267]
I'm using U8G2 on an AVR128DB48 with an 128x32 OLED; works excellent! But one question is open for me: I'm using a timer interrupt for audio playback which works fine and without interfering any UI functionality; but updating the display blocks the timer interrupt obviously. Does the U8G2 lib disables interrupts or something similar? I couldn't find anything in the code, but I'd like to understand why the timer interrupt routine is affected. Thanks a lot!

**Comment by robmaxtech** [comment]
Ok, thanks; good to know! So I know I don't have to suspect U8G2 any more ;-)  It's such a great library!

**Comment by olikraus** [comment]
Of course U8g2 will use SPI or Wire interface as implemented by the Arduino Environment. Those low level communication procedures may use interrupts.
