### ISSUE TITLE
Suggestions to FAQ

### ISSUE THREAD

**Issue by madneon** [olikraus/u8g2#230]
As a novice I got confused with using display unit, so maybe some additional info could be added to FAQ?

1. Why is there VCC and GND connectors on display unit, why it doesn't need to be connected (display still working without those connected) and is it better to utilise it?

2. Why is "reset" connection/constructor parameter optional, and how does it work when connected/utilised by lib?

**Comment by olikraus** [comment]
First question I do not understand. Vcc and gnd are always  required.

**Comment by olikraus** [comment]
no further answer... closing...
