### ISSUE TITLE
In  u8g2_font_logisoso62_tn , the graphics for displaying "3" is not aligned with the other numbers

### ISSUE THREAD

**Issue by grossmag01** [olikraus/u8g2#2313]
I am using a  253x63 matrix VFD to display  time of day in the largest possible numbers.  With the font u8g2_font_logisoso62_tn and i.e. 
u8g2.setCursor(0,0);  all following characters should be on the same vertical position. The character "3" is always displayed 
1 pixel lower than all the others . I didn't  see this in any other font. It is of course not a big problem, but the work around by placing every single character separately and positioning it up 1 pixel, if it is a "3" ,  is quite cumbersome.  Can this be corrected in a more elegant way ?

**Comment by olikraus** [comment]
Nothing much what i can do here... already discussed multiple times:

https://github.com/olikraus/u8g2/issues/1722

https://github.com/olikraus/u8g2/issues/1484
