### ISSUE TITLE
Pixel Loss

### ISSUE THREAD

**Issue by Alejandro13C** [olikraus/u8g2#2348]
Hi all,

I see how i lost a lot of pixel.
Some picture:
![image](https://github.com/olikraus/u8g2/assets/14128511/33ccc8c9-c6c5-4e9c-8c16-7c2f084b08ff)
![image](https://github.com/olikraus/u8g2/assets/14128511/a6222ad8-39ba-4233-ab18-bea080f0008e)
![image](https://github.com/olikraus/u8g2/assets/14128511/a2e47874-d291-4551-9902-fab2de410881)

`u8g2.firstPage();
  SerialLogger();
  do {

    if(Vbat < 12.0){    //If the battery is less than 12.0, show battery voltage.
      //Converts from float to const char
      dtostrf(Vbat, 4, 2, Battery_char); 
      u8g2.drawStr(35 , 60, Battery_char);
      u8g2.drawStr(85 , 60 , "V");
      u8g2.drawXBMP(48, 2, 40, 40, BatteryLogo);

    } else {

      // Else show Oil pressure value.
      dtostrf(Oil_pressure, 4, 2, OP_char);
      u8g2.drawStr(75 , 60 , "Bar");
      u8g2.drawXBMP(48, 10, 32, 32, OilLogo);

    }
  } while ( u8g2.nextPage() );
  delay(1000);
`

Thanks in Advance!

**Comment by olikraus** [comment]
Never change the content within the "while" first/next page loop.
To solve this, move the while loop into the if/else body.

**Comment by Alejandro13C** [comment]
Hi,

Okey, thanks i will create one while for each case.
Thanks!

**Comment by Alejandro13C** [comment]
Not an issue.
Use proper structure.
