### ISSUE TITLE
DrawXBM issues

### ISSUE THREAD

**Issue by Tulsa2008** [olikraus/u8g2#237]
04/01/17

For the most part , I have been able to get everything I have tried in your library to work but DrawBMX is giving me a bit of trouble.  I am using an ADA Product 250 ST 7565 display with the full buffer option.  The processor is an Arduino Mega.  The display(s) I have two work fine.

When I tried to use the DrawBMX function, I was able to draw lines by setting up an array with alternating rows of OxFFs and Ox00s. I got what I expected.  Multiple rows of lines across the screen.

When I tried to display my bit maps generated from crude BMP files using the "Image2cpp" conversion program, I get a display that kind of looks like my BMP but not quite.  The image kind of looks like it might be mirrored.  The image by the way is 122X56 on a 128X64 display.  

What are you using (or can suggest) to convert  BMP files to XBM files that will work.  I have to believe that I am missing something basic.   

If it would help, I could send you a picture of the display.  I have used Image2cpp with ADA's library and it works although their "DrawBitMap" function for the ST7565 has significant problems.

Any light you can shed will be greatly appreciated.   
Ken

**Comment by olikraus** [comment]
GIMP generates the correct image format.

**Comment by Tulsa2008** [comment]
Thanks for your input.  I'll look that one up.

Ken 
  ----- Original Message -----

**Comment by tongbajiel** [comment]
Hello Olikraus ...
Can you build this library for me, to be use with PCF8814 nokia 1100 screen. 
I was confused to modify itself many times.
Sorry, my English is bad. I come from Indonesia
Thank you in advance.

**Comment by Tulsa2008** [comment]
Thanks for the hint.  Gimp is a bit more tool than I need but , Hey, it's always nice to have a nice tool to work with.

Thanks again
Ken

**Comment by olikraus** [comment]
:)

**Comment by fire1** [comment]
Please add this information into WiKI method's docs (like a note ) Thanks!

**Comment by olikraus** [comment]
@fire1 GIMP isnow mentioned.
