### ISSUE TITLE
Added Support for Active High

### ISSUE THREAD

**Issue by FriedCircuits** [olikraus/u8g2#238]
I added a new parameter on begin for setting active high for inverted buttons. I will do a pull request and hopefully I followed the library structure correctly.

Of course documentation would have to updated to account for option. I had to put in in the middle after menu_prev_pin.

This could be expanded to have a button type per button instead of overall.

Hope this helps.

**Comment by FriedCircuits** [comment]
I haven't quite figured out how the u8x8_read_pin_state function works. Maybe someone can help make the change there to take into account the button type?

**Comment by olikraus** [comment]
ok, I will have a look at this...

**Comment by olikraus** [comment]
I decided not to implement this any more.u8g2 is the wrong place. The interface functions are just a little add on. u8g2 concentrates on displays.
