### ISSUE TITLE
ST7920 Hardware SPI support?

### ISSUE THREAD

**Issue by PascalKoe** [olikraus/u8g2#24]
Hey,
I've wondered whether if there is any plan to support HW SPI withe the ST9700 Controller (128x64)?
Would be great to have more than 1 FPS :)

**Comment by olikraus** [comment]
Good point. Maybe i just missed this.

**Comment by olikraus** [comment]
ok, it is not yet implemented because some functions/interfaces are missing.
https://github.com/olikraus/u8g2/blob/master/tools/codebuild/codebuild.c

**Comment by olikraus** [comment]
done
