### ISSUE TITLE
ZJY-M150 not working with I2C

### ISSUE THREAD

**Issue by NoahT07** [olikraus/u8g2#2407]
As discussed in Issue #1960, ZJY M-150 displays were added. However, my Display doesn't work with I2C. There seems to be something wrong with the constructor, because I get an error. I just uncommented the line, as instructed.

> error: 'U8G2_SSD1327_ZJY_128X128_1_HW_I2C' does not name a type;

**Comment by olikraus** [comment]
Good point, I guess I missed this. I have updated the repo.
Do you require a regular beta release?

**Comment by NoahT07** [comment]
I made it work myself so I don't need a release, but thank you.

olikraus ***@***.***> schrieb am So., 31. März 2024, 22:36:
