### ISSUE TITLE
How to draw ellipsis with drawUTF8

### ISSUE THREAD

**Issue by JanB97** [olikraus/u8g2#2412]
I am using the u8g2_font_profont22_tf font.
The font has the … (ellipsis) glyph, but I am unable to use it:

![image](https://github.com/olikraus/u8g2/assets/7881168/32f1303e-d184-48e5-af73-7dc67f5e6e83)

I tried adding "0xE2 0x80 0xA6" to the String and I have also tried just pasting the encoded "…", but it just doesn't get displayed.

What sequence do I need to include with this font?

**Comment by olikraus** [comment]
Did you enable UTF8? What is the actual code?

**Comment by JanB97** [comment]
Yes, this is my setup, I have one of those OLEDs that is 2 screens in one:
![image](https://github.com/olikraus/u8g2/assets/7881168/42be1437-721b-4c18-a974-e6e3b2a6a4bf)

The function I call is this:
`drawUTF8(22, 97, text.c_str());`

That is declared like this: 
```
void drawUTF8(u8g2_uint_t x, u8g2_uint_t y, const char *s){
  u8g2_current->drawUTF8(x-offset,y,s);
}
```
In my String i tried using: "\u2026", (0xE2,0x80,0xA6) and "…".
With "\u2026" and "…", it just is blank and with the byte codes it prints them as numbers.

These are the attempts:
![image](https://github.com/olikraus/u8g2/assets/7881168/f425eb90-0d59-4c46-9e4d-ce3351c00716)

text is a String and cstr is a char array with 60 elements.

**Comment by olikraus** [comment]
But "..." is at position "\x85"

**Comment by JanB97** [comment]
You are right, its working with "\x85", thank you so much :)
I searched everywhere but all I could find was the unicode.
I think also finally understood the font overview.
