### ISSUE TITLE
"°" displayed incorrectly

### ISSUE THREAD

**Issue by Vincent0690** [olikraus/u8g2#2413]
![image](https://github.com/olikraus/u8g2/assets/86123039/8e4511df-8aa4-4226-b302-5bb87f7b8c96)

Hello, when using this font the degree character is always preceded by a "Â".

```
u8x8.setFont(u8x8_font_8x13B_1x2_f);
u8x8.print("°");
```

I am using a SSD1306.

**Comment by olikraus** [comment]
Probably you need to enable UTF8 mode: https://github.com/olikraus/u8g2/wiki/u8g2reference#enableutf8print

**Comment by Vincent0690** [comment]
Oops yes sorry, thanks!
