### ISSUE TITLE
Issue with different "User Pages"

### ISSUE THREAD

**Issue by FelixMue** [olikraus/u8g2#242]
Hi Oli,

i'm not so sure if this is the right way, but i didn't find any other chance to get in touch with you. i'm curious how to get different "user pages" working but couldn't really find something promising. the thing i try to do is a user interface which displays various sensor data such as acceleration, speed, etc.. because this is a lot of data the text is pretty small and hard to read in detail (if not directly in front of the display). my solution to this would be an "overview" page and 2-3 pages with bigger, detailed information which can be scrolled through via button press. how can i get this with u8g2 and/or M2tklib?

maybe you can drop an email adress here to discuss this via PM?

cheers

Felix

**Comment by olikraus** [comment]
Probably this is more a programming​ question, than a U8g2 question.
But first of all you should decide what exactly you want: scrolling or pages.

**Comment by FelixMue** [comment]
should be pages.

i found this on yt https://www.youtube.com/watch?v=wtU02eBNJfQ 
i want to do the same he does at about 4:50.

**Comment by olikraus** [comment]
Six displays on six different uC with six different outputs? I think that person just wrote six different ino files for that. Maybe you should ask the author of the video.

**Comment by FelixMue** [comment]
i want to do this with only one oled. i don't know how to code this "page switch" on button press. more a programming question, i know.

thanks for your help

**Comment by olikraus** [comment]
closing...
