### ISSUE TITLE
Can I use u8g2 with SSD1357 mono mode?

### ISSUE THREAD

**Issue by stayfooll** [olikraus/u8g2#2432]
Can I use u8g2 with SSD1357 mono mode?

I have a project using an SSD1357 WINSTAR 128x64 OLED Model No: WEP012864UWPP3D00000.

The datasheet mentions mono mode.

Is it possible for me to use u8g2 with the SSD1357 mono mode?

If yes, how can I modify the existing code to support SSD1357 mono mode?

Should I start with the function u8x8_cad_SendData?

Thanks.

![image](https://github.com/olikraus/u8g2/assets/12412394/f9e59438-16ea-41f6-b971-ef35d456525c)

SSD1357 WINSTAR 128x64 OLED datasheet:
[https://drive.google.com/file/d/1YEhlR5Wt07mSpj_zeLDudUAPKW4Alpdt/view?usp=drive_link](url)

**Comment by olikraus** [comment]
it is not supported...

**Comment by stayfooll** [comment]
Got it. Thank you!

**Comment by stayfooll** [comment]
Close the issue.
