### ISSUE TITLE
U8x8Log Print Function

### ISSUE THREAD

**Issue by CWGwaltney** [olikraus/u8g2#2454]
can you please update the code to provide a way to have serial print automaticly echo to u8x8log screen without having to use a different command... Thanks!

**Comment by olikraus** [comment]
Not sure how I can do this without changing the Arduino framework.

**Comment by CWGwaltney** [comment]
It sure would be helpful for debugging

**Comment by olikraus** [comment]
Maybe I was not clear enough: I don't know how to do this.

**Comment by CWGwaltney** [comment]
i understand... i dont know how to do it either... i may not be clear that i apreciate your software

**Comment by olikraus** [comment]
Somehow this sounds like this: https://github.com/olikraus/u8g2/issues/2339
