### ISSUE TITLE
Please add hebrew font

### ISSUE THREAD

**Issue by bmeisels** [olikraus/u8g2#246]
Could you please add a Hebrew font?
the Hebrew Unicode range  includes U+0590 to U+05FF and U+FB1D to U+FB4F.

**Comment by olikraus** [comment]
Ok, will do this with the unifont bdf file

**Comment by olikraus** [comment]
added hebrew to cu12, unicode, 6x13 and 6x13B

**Comment by bmeisels** [comment]
Thanks!
