### ISSUE TITLE
ST5767_LW12832* Compile error

### ISSUE THREAD

**Issue by kittenarmy** [olikraus/u8g2#2463]
As I was working through [list](https://github.com/olikraus/u8g2/wiki/u8g2setupcpp
) of constructors for https://github.com/olikraus/u8g2/issues/2462 I get this error compiling for GraphicsTest.ino:

```
U8G2_ST7567_LW12832_1_SW_I2C' does not name a type; did you mean 'U8G2_ST7567_122X32_1_SW_I2C'?
```

Also with (I didn't test the others):
```
// U8G2_ST7567_LW12832_1_SW_I2C u8g2(U8G2_R0, A5, A4, 19); 
// U8G2_ST7567_LW12832_2_SW_I2C u8g2(U8G2_R0, A5, A4, 19); 
// U8G2_ST7567_LW12832_1_HW_I2C u8g2(U8G2_R0, A5, A4, 19); 
```

**Comment by olikraus** [comment]
For me the following constructor works without problems:

``` C++
U8G2_ST7567_LW12832_1_SW_I2C u8g2(U8G2_R0, /* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ 5);
```
