### ISSUE TITLE
Bdfconv won't run on Win 11 machine

### ISSUE THREAD

**Issue by No1sonuk** [olikraus/u8g2#2466]
As title:
I can't run bdfconv.exe on my Win 11 64-bit computer.
Error message says it's not compatible with 64-bit.

**Comment by olikraus** [comment]
oh, ok, I will try to verify this on my own win system.

**Comment by olikraus** [comment]
I can confirm, that it work fine on my win environment

**Comment by No1sonuk** [comment]
![image](https://github.com/user-attachments/assets/d9247d7b-a221-4563-8dd6-1fbee268e152)
Still doesn't work on mine...

**Comment by No1sonuk** [comment]
![image](https://github.com/user-attachments/assets/11a001ca-a611-4978-81a2-e4e35882e23d)
Still doesn't work on mine.

**Comment by olikraus** [comment]
I am not a windows expert, so it's difficult to tell what is the problem here. 
I have create the binary with mingw environment, so maybe as a workaround, just install msys2 and mingw and compile the code by yourself

**Comment by olikraus** [comment]
closing...
