### ISSUE TITLE
U8G2 Arduino T6963 Text Support

### ISSUE THREAD

**Issue by DinoxGaming** [olikraus/u8g2#2467]
Hello, I am working on a project where I need to use the built-in text mode of the t6963 controller to quickly send text data to the 240x64 LCD Display. However, there is no u8x8 support for the t6963 controller (yet). According to the datasheet, the text only mode should be possible. Is there any way this mode could be built into the u8g2 library? I would like to use the text only function. Thank you very much!

**Comment by olikraus** [comment]
Just to clarify: u8x8 will still use graphics mode. U8x8 is more like a simplified low level graphics mode, which is offered for some (but unfortunately) not all displays, which share the same low level memory architecture.

The text mode of the T6963 is not supported, however it shouldn't be a big issue just to use the text mode of the T6963 with plain SPI commands.
