### ISSUE TITLE
How can I change the I2C address?

### ISSUE THREAD

**Issue by velliLi** [olikraus/u8g2#2476]
I'm trying to use ssd1306 and a BMP280 sensor now but if I want to use them together, it doen't work. 
I tried to use the founction: 
u8g2.setI2CAddress(0x76); 
bmp.begin(0x77,0x58);

and I got this:
rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download

I wonder why it's 'waiting for download'
Anyone can help me? Please.

**Comment by olikraus** [comment]
Maybe you need to slow down u8g2 by using the setBusClock command.

See note 2 in the manual: https://github.com/olikraus/u8g2/wiki/u8g2reference#setbusclock
