### ISSUE TITLE
Library much slower on ESP32 than ESP8266. Display uses the I2C interface

### ISSUE THREAD

**Issue by DidierCrane** [olikraus/u8g2#2482]
Using the default settings, driving a 128x32 OLED, along with the Arduino.h and Wire.h libraries. 
I have not traced if the difference was in the u8g2lib.h, Wire.h or the Arduino.h libraries, just looking for pointers in case somebody has already found the cause.
`
    #include <Arduino.h>  
    #include <U8g2lib.h> // version 2.34.22 installed  
    #include <Wire.h>  
    #define SCL 4 
    #define SDA 5 
    setup(){
      U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2( U8G2_R0,SCL,SDA, U8X8_PIN_NONE );
      u8g2.setI2CAddress( 0x78  );
      u8g2.begin();
      u8g2.setFont( u8g2_font_7x14B_tf );
      u8g2.clearBuffer();
      u8g2.drawStr( 0, 14, "ESP32-WROOM" );
      u8g2.drawStr( 10, 28, "Test OLED 128x64" );
      u8g2.drawStr( 10, 44, "I2C Addr 0x78"  );
      u8g2.drawStr( 10, 60, "D5=SDA D4=SCL" );
      u8g2.sendBuffer();
    }
`

**Comment by olikraus** [comment]
Maybe you need to use HW_I2C
