### ISSUE TITLE
SH1106_128X64_NONAME horizontal and vertical offset with rotation 2

### ISSUE THREAD

**Issue by D3add3d** [olikraus/u8g2#249]
Using U8G2_SH1106_128X64_NONAME_1_4W_SW_SPI u8g2(U8G2_R0, 13, 11, 10, 8, 7); for initialization works fine when rendering, [0,0] is at the top left of the display, however when using R2 the [0,0] is offset.

**R0**
![img_20170421_191811](https://cloud.githubusercontent.com/assets/1764903/25288907/c4ae9318-26c7-11e7-83bb-6d95f5c0d2c6.jpg)

**R2**
![img_20170421_191845](https://cloud.githubusercontent.com/assets/1764903/25288936/e213bb86-26c7-11e7-9f06-d1d60a676d4f.jpg)

**Comment by olikraus** [comment]
Maybe this is a ssd1306 display

**Comment by D3add3d** [comment]
Haven't tried treating it as SSD1306 because I've used some other libraries for SSD1306 and they did not work correctly, libraries for SH1106 did however... I will give it a try, one moment.

**Comment by D3add3d** [comment]
Works like a charm, thank you! My apologies, I should have realized my mistake earlier.

**Comment by olikraus** [comment]
No problem
