### ISSUE TITLE
ST7920 Hardware SPI not working correctly

### ISSUE THREAD

**Issue by PascalKoe** [olikraus/u8g2#25]
Hi,
I've just tested the HW SPI with a ST7920 128X64 LCD.
At the start most of the picture is displayed partly correctly but then it starts the get messed up.
Tested own code and example-code
Examples: http://imgur.com/a/Jvxel
Tested on Arduino Uno
Pins: 
RS -> 10
R/W -> 11
E -> 13
(RST -> 8)

Constructor: U8G2_ST7920_128X64_F_HW_SPI lcd(U8G2_R0, 10, U8X8_PIN_NONE);
and U8G2_ST7920_128X64_F_HW_SPI lcd(U8G2_R0, 10, 8);

**Comment by olikraus** [comment]
thanks. i have seen similar effects. I will work on this. Problem seems to be, that the SPI speed is to high for the controller.

**Comment by olikraus** [comment]
fixed... (hopefully)

**Comment by PascalKoe** [comment]
Thank you very much! Works flawlessly with a FPS increase of 63% compared to U8Glib :D
