### ISSUE TITLE
Unifont japanese glyph problem

### ISSUE THREAD

**Issue by alsoduck** [olikraus/u8g2#2502]
There is two unifont variants: unifont and unifont_jp.
Unifont uses chinese character of simplified chinese variant. but it is used only in china. 
Japanese uses different variant, but same unicode. 
unifont-jp replaced chinese character with japanese variant. 
so unifont_jp should be used for japanese unifont.
![image](https://github.com/user-attachments/assets/8113c655-32d4-4089-baab-1e1869d22f72)
image to help you understand

**Comment by olikraus** [comment]
![grafik](https://github.com/user-attachments/assets/8d730930-c26d-45da-a47a-c3d84643f392)
