### ISSUE TITLE
SSD1312 Support For 0.63 Inch LCD

### ISSUE THREAD

**Issue by Amir1387aht2** [olikraus/u8g2#2509]
Hello there!
I have been purchased this lcd : https://www.buydisplay.com/i2c-0-63-inch-ultra-thin-oled-display-screen-120x28-ssd1312-14pins
It says it uses SSD1312 but i can't get it work with u8g2 or any other library,
The Documentaion Have a Sample Code for It, But Its for an Unknown Mcu
Can you support this lcd in u8g2? Thanks!

**Comment by olikraus** [comment]
Did you close this issue because of https://github.com/olikraus/u8g2/issues/2483 ?
If so, can you confirm, that https://github.com/olikraus/u8g2/issues/2483 works?

**Comment by Amir1387aht2** [comment]
> Did you close this issue because of https://github.com/olikraus/u8g2/issues/2483 ?
> If so, can you confirm, that https://github.com/olikraus/u8g2/issues/2483 works?

Actually I think it's work but it have bugs,  but can you contact me on telegram? I say bug on there, cause it has some problems

Telegram : @Do3p3iri

**Comment by olikraus** [comment]
Display related question can be dropped here. Other questions I can not answer...

**Comment by Amir1387aht2** [comment]
> Display related question can be dropped here. Other questions I can not answer...

So I will be brief, the display brightness is too low, I don't know it's software issue or hardware issue

**Comment by olikraus** [comment]
The first thing would be to assign 255 as a contrast value: https://github.com/olikraus/u8g2/wiki/u8g2reference#setcontrast

If this is still not good enough, then you need to play with the internal register values of the display:
https://github.com/olikraus/u8g2/blob/061c72762b8dc1a6685f0ccca567258103909e6a/csrc/u8x8_d_ssd1312.c#L163-L165

For this, use the sendF command (https://github.com/olikraus/u8g2/wiki/u8g2reference#sendf)

for example:
```
u8g2.sendF("ca", 0xdb, 0x30); 
```
to change the vcomh value (see the datasheet of the controller for details)
hmm in fact looking at the 0xdb command, then the current value of 0x40 doesn't make sense, because this value isn't allowed: 
![grafik](https://github.com/user-attachments/assets/4c17327e-dc27-4525-b9a0-2232ef6577b9)

So valid values are 0x00, 0x10, 0x20 and 0x30

**Comment by Amir1387aht2** [comment]
> The first thing would be to assign 255 as a contrast value: https://github.com/olikraus/u8g2/wiki/u8g2reference#setcontrast
> 
> If this is still not good enough, then you need to play with the internal register values of the display:
> 
> https://github.com/olikraus/u8g2/blob/061c72762b8dc1a6685f0ccca567258103909e6a/csrc/u8x8_d_ssd1312.c#L163-L165
> 
> For this, use the sendF command (https://github.com/olikraus/u8g2/wiki/u8g2reference#sendf)
> 
> for example:
> 
> ```
> u8g2.sendF("ca", 0xdb, 0x30); 
> ```
> 
> to change the vcomh value (see the datasheet of the controller for details) hmm in fact looking at the 0xdb command, then the current value of 0x40 doesn't make sense, because this value isn't allowed
> (Image)
> So valid values are 0x00, 0x10, 0x20 and 0x30

I tried your codes but its didn't work, but, Please don't make fun of me, but i just connected vcc, vss, scl, sda to my board and there's no resistors and these stuff! and you know the lcd is not for development and so there's no additional component for it, so may it cause for this reason? I searched a lot to how to add component for it to work but i found nothing :(

**Comment by Amir1387aht2** [comment]
> > The first thing would be to assign 255 as a contrast value: https://github.com/olikraus/u8g2/wiki/u8g2reference#setcontrast
> > If this is still not good enough, then you need to play with the internal register values of the display:
> > https://github.com/olikraus/u8g2/blob/061c72762b8dc1a6685f0ccca567258103909e6a/csrc/u8x8_d_ssd1312.c#L163-L165
> > 
> > For this, use the sendF command (https://github.com/olikraus/u8g2/wiki/u8g2reference#sendf)
> > for example:
> > ```
> > u8g2.sendF("ca", 0xdb, 0x30); 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to change the vcomh value (see the datasheet of the controller for details) hmm in fact looking at the 0xdb command, then the current value of 0x40 doesn't make sense, because this value isn't allowed
> > (Image)
> > So valid values are 0x00, 0x10, 0x20 and 0x30
> 
> I tried your codes but its didn't work, but, Please don't make fun of me, but i just connected vcc, vss, scl, sda to my board and not other pins and also there's no resistors and regulators for lcd cause it not a development lcd ! so may it cause for this reason? I searched a lot to how to connect pins for it to work but i found nothing :(

**Comment by olikraus** [comment]
Which constructor did you use? You connection should work with the SW_I2C constructor.

**Comment by Amir1387aht2** [comment]
Are you sure only that 4 pins are enough? For example vcomh pin are not connected anywhere

And I use this constructor : U8G2_SSD1312_120X28_1_SW_I2C

**Comment by olikraus** [comment]
> Are you sure only that 4 pins are enough?

I can only speak for U8g2. In other words, yes, from a U8g2 perspective you need SDL (DSA) and SCL pins to connect.
Obviously you have to do anything else what is requested in the datasheet. Each display is different and if you buy a display, it comes with all required instructions what you need to do. 
In your case, there is a huge list of todo's, so you can just follow that list (capter 4 of the data sheet).
Additionally remember to fullfill the electrical side conditions in chapter 4.2 and 4.3: Do not connect 5V boards like Arduino Uno directly to that display.

**Comment by Amir1387aht2** [comment]
Okay but please just tell me what is internal charge pump and should i use it or not?

**Comment by olikraus** [comment]
Nice question. LCDs and OLEDs require 8 to 15 volt. In section 4 of your display you can read the following values:
![grafik](https://github.com/user-attachments/assets/ff25f622-5bdd-46c3-846b-76f4bafa62a4)

In oldern times, it was the duty of the user to provide this voltage.
Nowadays the controller comes with a helper circuit, which allows to generate that high voltages from 3.3V with little effort. So you can basically say:
The SSD1312 has two options for the required high voltage:
 - Feed the circuit with the required high voltage from an external source
 - Use the internal charge pump to produce the high voltages from the 3.3v 

You can see this in the block diagram of the SSD1312: 
![grafik](https://github.com/user-attachments/assets/f3e990bb-b9f9-47a8-9452-1ba5405d9094)

There is a charge pump which is somehow unconnected to the rest of the display. Indeed it is just an optional helping circuit to generate the required high voltage. 

The good thing is, you just need two capacitors to generate the high voltage with the help of that circuit. I would say, that in 99% percent of all displays that charge pump is used to generate the high voltage. In u8g2 that charge pump will be automatically activated, assuming that most users will use this.

So yes: The charge pump is a classical way to produce higher voltage from a lower voltage source and yes you should use it.

You can use usually use 2x ceramic caps with values between 1uF or 2.2uF. You can also use electrolyt caps with the same value. The later type has a + and a - connection which has to be connected to P and N inputs accordingly.
Ceramic caps are little bit better and don't have the issue with the + - connection, but could be more expensive. For example here are 10 pieces for 1 dollar or so: https://de.aliexpress.com/item/1005001493545069.html

You might need some more caps here and there, but this is described in the datasheet.

**Comment by Amir1387aht2** [comment]
Thanks dude, I think I need some researches, and after these storied, you could say u8g2 lib is working correctly for this display, thanks
