### ISSUE TITLE
ST7920 128x64 Stm32 HAL Hardware Spi displays just first 8 pixels correct

### ISSUE THREAD

**Issue by LukasAusserhuber** [olikraus/u8g2#2542]
Hi, i am using a stm32 cubemx generated project to control a ST7920 128x64 display via SPI. The controller is stm32 bluepill board where the SPI1 is used.
The Spi is configured also via cubemx. So the transmission is done via the hardware spi peripheral.

In a first test i used a arduino nano and the u8g2 example project to display the "Hello World!" text. This worked perfectly.
Afterwards i ported the library to the stm32 as mentioned in the ref manual. To have the same input i just rebuilt the arduino example within the stm32 project.

Suprisingly the first 8 horizontal pixel-lines are displayed correctly the rest looks like random as mentioned in other issues.
See following picture:
![IMG_20241127_225738360](https://github.com/user-attachments/assets/c0928b8a-6e0b-422d-b0de-d8a002902032)

Does anybody know this issue? 
If not maybe i do something wrong at the lcd callbacks? Can anybody have a short look at the LcdCtrl file?
If needed i have logic analyser traces from the arduino spi startup and from the stm32 spi startup.

Attached also the LcdCtrl.c where the callbacks are implemented and also the task which initializes and controlls the LCD.
[LcdCtrl.c.txt](https://github.com/user-attachments/files/17950665/LcdCtrl.c.txt)

Thank you!
Regards, Lukas

**Comment by olikraus** [comment]
You should use the full page constructor: u8g2_Setup_st7920_s_128x64_f
