### ISSUE TITLE
U8X8_PIN_NONE was not declared in this scope

### ISSUE THREAD

**Issue by Mekol** [olikraus/u8g2#257]
I have this issue with Eclipse(with avr plugin). I ve linked arduino libraries but i still have an errors.
My program is empty, i just cant build u8x8lib.cpp

**Comment by olikraus** [comment]
maybe you missed to define the ARDUINO constant.

**Comment by Mekol** [comment]
which one? where it is?

**Comment by olikraus** [comment]
It is passed with the -D option to the compiler within the Arduino Environment and checked in line 173 of u8x8.h

**Comment by Mekol** [comment]
ok, i see. do you know how can i enable this in eclipse(or any other ide)?
