### ISSUE TITLE
SAMD21 support?

### ISSUE THREAD

**Issue by anhtuanmanga** [olikraus/u8g2#261]
I bought the samd21 broad
http://robotdyn.com/catalog/boards/samd21_m0_mini/
Do your lib work on this broad
Sorry for bad english, this is not may native language

**Comment by olikraus** [comment]
If this board works with the Arduino IDE, then probably yes.
U8g2 just uses Arduino function and should be compatible with all Arduino Boards.

**Comment by anhtuanmanga** [comment]
I succes to upload code to broad but not thing show on oled.
Did you test with arduino zero before?

**Comment by olikraus** [comment]
I did tests with the Feather M0 Board.
In most cases this is a wiring problem.

**Comment by anhtuanmanga** [comment]
Check every thing but still not work.
May be problem is my broad.
Thanks for your help

**Comment by olikraus** [comment]
Feel free to send more information for cross check: pic of setup, code, ...

**Comment by anhtuanmanga** [comment]
here is my code

#include <Arduino.h>
#include <U8g2lib.h>

#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif


U8G2_SSD1306_64X48_ER_1_SW_I2C u8g2(U8G2_R0, 7, 8);
void setup(void) {

  u8g2.begin();  
}

void loop(void) {
  u8g2.firstPage();
  do {
    u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.drawStr(0,24,"Hello World!");
  } while ( u8g2.nextPage() );
}
here is my setup
![img_6827](https://cloud.githubusercontent.com/assets/14345732/25782799/89a3d3e4-337b-11e7-91bf-fca261f6cee8.JPG)

**Comment by olikraus** [comment]
I might be wrong but it looks like d9 is connected and not d8

**Comment by anhtuanmanga** [comment]
no it is d8

**Comment by olikraus** [comment]
Then, I also don't know. All looks correct.

**Comment by anhtuanmanga** [comment]
me too, may be because of my broad
thanks for your support

**Comment by olikraus** [comment]
not sure how to support further... closing this...

**Comment by anhtuanmanga** [comment]
i  change to platformio ide and everything work.
don't know why.

**Comment by olikraus** [comment]
Somethimes there are breadboard issues...
