### ISSUE TITLE
U8G2_T6963_240X64_F_8080 works on Arduino Mega but not Arduino Due

### ISSUE THREAD

**Issue by jasoneppink** [olikraus/u8g2#270]
I have working code with constructor U8G2_T6963_240X64_F_8080 that can write to a display from an Arduino Mega, but the same code and constructor run from an Arduino Due does not write to the display. Any idea what the problem may be?

**Comment by olikraus** [comment]
Pin output levels of the Due are 3.3v. But the display expects 5v.

**Comment by jasoneppink** [comment]
Well damn. Thanks dude.

**Comment by olikraus** [comment]
Maybe use a more modern display, like this:
http://www.mouser.com/Search/Refine.aspx?Keyword=dogm240

It expects 3.3v (so it will work with Due, but not with Mega) and has a SPI interface (less wires required).
