### ISSUE TITLE
ST7565_LM6059 starts from the center line

### ISSUE THREAD

**Issue by lavboy** [olikraus/u8g2#279]
Hi there!
Could you please check why all the examples for 
U8G2_ST7565_LM6059_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 7, /* data=*/ 6, /* cs=*/ 2, /* dc=*/ 4, /* reset=*/ 3);
starts not from the top left corner but from the center line of the screen?
![img_20170528_222255](https://cloud.githubusercontent.com/assets/23376766/26531583/0ab84bea-43fd-11e7-8c3f-e06b946bdf4b.jpg)

**Comment by olikraus** [comment]
did you try any of the other ST7565 constructors? For example the dogm128 constructor?
What are results with the other constructors?

**Comment by olikraus** [comment]
no further response, closing...
