### ISSUE TITLE
add extended fonts, -m '32-701' ("e" range)

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#284]
this will also include glyphs hex 170/171 (see #105)

**Comment by olikraus** [comment]
update wiki for "e" range (32-701)

**Comment by olikraus** [comment]
The fonts are included in the .1 prerelease:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip

**Comment by tuccerHU** [comment]
Can you give me a hint how can i get the font what i need??? I am not an expert in this..... :D

**Comment by olikraus** [comment]
1. look out for the font name (ends in "te"). Fonts can be found 
here: https://github.com/olikraus/u8g2/wiki/fntgrpadobex11
and here: https://github.com/olikraus/u8g2/wiki/fntgrpx11

2. install the developer snapshot of u8g2: download 
https://github.com/olikraus/U8g2_Arduino/archive/master.zip
then inside Arduino IDE, do add library zip file installation.

3. Have fun with the new fonts. Use u8g2.drawUTF8() !!!
