### ISSUE TITLE
reduce data size

### ISSUE THREAD

**Issue by schmurfy** [olikraus/u8g2#286]
is there a way to reduce this library size by dropping fonts I don't use ?

**Comment by olikraus** [comment]
This happens automatically for gcc with enable linker garbage collector (which is default for the Arduino IDE).

**Comment by schmurfy** [comment]
I missed that but it means my problem might not be there, I am running my code on an atmega328 and when including this library my data usage (SRAM I think ?) jumps 1476 byes up which brings me above 100% and my program does not even start, any idea what might take that much ?

If you compile the GraphicTest example you already have 71% memory used :(

**Comment by olikraus** [comment]
Suggestions differ depending on the location of the data (RAM or FLASH).

Flash: 
Use only a few fonts or better only one font. Try to use the "tr" fonts if possible. "tr" (transparent + reduced) will contain lesser glyphs, but will also occupy lesser flash.

RAM:
Use the _1_ page buffer display constructor. This will minimze the RAM consumption.

**Comment by schmurfy** [comment]
Thanks a lot, much better !
My problem was with the RAM usage and using only 1 buffer does the trick, I now realize it was documented but this library does a lot of things and I did not know where to look, I really like it though :)

**Comment by olikraus** [comment]
:)

**Comment by maopiccoto** [comment]
This tread helped me a lot, thanks!
