### ISSUE TITLE
PROGMEM and drawXBM

### ISSUE THREAD

**Issue by getget1980** [olikraus/u8g2#289]
Hello, first of all, nice work with u8g2 :)

I'm having a problem with a Arduino nano v3 (ATMega328), u8g2 2.16.0 and LCD ST920.

When using RAM to store XBM it works ok. When using PROGMEM (nano has few RAM :( ), picture gets corrupted :(

Any idea ?

**Comment by olikraus** [comment]
Did you use  drawXBMP()?

https://github.com/olikraus/u8g2/wiki/u8g2reference#drawxbm

**Comment by getget1980** [comment]
Nope, it works now, thanks :)

**Comment by olikraus** [comment]
:)
