### ISSUE TITLE
96x16 OLED support

### ISSUE THREAD

**Issue by whatnick** [olikraus/u8g2#295]
I have a 96x16 oled mounted on an Adafruit feather. Hello World runs with scaling issues, OLED is set as U8G2_SSD1306_128X32_UNIVISION_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE). Support for this appreciated. Here is what I [see](https://goo.gl/photos/qt5vdqTyzrb9JPnQA)

**Comment by olikraus** [comment]
Can you share the code, which generates the content on your OLED?
The Adafruit Feather OLED comes with a 128x32 OLED. Did you mount or own 96x16 OLED on it?

**Comment by whatnick** [comment]
Yes I managed to burn the 128x32 with a freak accident, wrongly ordered a 96x16 and mounted that. It works fine. With some glitches. The output is produced by the u8g2 "hello_world" sample.

```
void setup(void) {
  u8g2.begin();
}

void loop(void) {
  u8g2.clearBuffer();					// clear the internal memory
  u8g2.setFont(u8g2_font_ncenB14_tr);	// choose a suitable font
  u8g2.drawStr(0,20,"Hello World!");	// write something to the internal memory
  u8g2.sendBuffer();					// transfer internal memory to the display
  delay(1000);  
}
```

**Comment by olikraus** [comment]
Understand. ok, then please locate u8x8_d_ssd1306_128x32.c on your drive (might be somewhere in Arduino/libraries/u8g2/...
for reference:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_ssd1306_128x32.c

Then goto line 50 and change
U8X8_CA(0x0d3, 0x000), /* display offset */
to
U8X8_CA(0x0d3, 0x010), /* display offset */

Will this work?

Oliver

**Comment by whatnick** [comment]
Should I copy this and make a custom class with this offset hardcoded ?

**Comment by olikraus** [comment]
I will create a new class, but before that i would like to know what init sequence is required. So if you could modify the 132x32 constructor from above, so that the hello world appears correctly, then i will start to implement this.

Do you have a datasheet for your 96x16 display module?

**Comment by whatnick** [comment]
This is the module I have -
http://www.buydisplay.com/default/graphic-i2c-0-69-inch-96x16-oled-display-mp3-module-white-on-black
. Datasheet is on a link on the page.

**Comment by whatnick** [comment]
I have tested the new release with the OLED and ESP32. Works great. Thanks
a lot for supporting this one. Hope others find it useful as well.

**Comment by olikraus** [comment]
great, thanks for the feedback
