### ISSUE TITLE
64x48 support for U8x8

### ISSUE THREAD

**Issue by judge2005** [olikraus/u8g2#303]
Hi,

I want to use the U8x8 library with a 64x48 OLED shield for the Wemos Pro Mini. It looks like you already have this for the U8g2 library. Could you add it for the U8x8 library (or can I add it myself)?

Thanks - Paul

**Comment by olikraus** [comment]
It should be there already:

https://github.com/olikraus/u8g2/wiki/u8x8setupcpp#ssd1306-64x48_er

The example files only contain a small number of constructors.

Oliver

**Comment by judge2005** [comment]
Don't know how I missed that. Thanks!

**Comment by olikraus** [comment]
no problem
