### ISSUE TITLE
Rising edge of clock

### ISSUE THREAD

**Issue by basilfx** [olikraus/u8g2#31]
The LS013B7DH03 requires SPI clock mode 'second rising', whereas other displays use 'first falling'. 

I presume the field `sck_takeover_edge` in `u8x8_display_info_t` can be used for this, but is there a standardized mapping of values to clock modes?

I can create a PR to fix this, e.g. taking the modes as defined by https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus#Mode_numbers?

(Yes, the LS013B7DH03 driver has the wrong clock mode in the display info structure, but I did not notice this until I refactored my platform driver, because I hard coded the mode.)

**Comment by olikraus** [comment]
sure, pull request is fine.

**Comment by basilfx** [comment]
I opened #32 to fix the issue with the LS013B7DH03 driver.

For the SPI modes: well, not all are supported right now, but I don't have any ways of testing all changes. Therefore I think the current fix is sufficient and it should be changed when it is actually needed.

I'll close this one.

**Comment by basilfx** [comment]
OK, I am reconsidering this, as I confused some terms:

What I now assume:
`sck_takeover_edge` -> clock sampling phase (CPHA)

What I need (LS013B7DH03 uses inverted clock):
`sck_polarity` -> clock polarity (CPOL)

It would waste memory by adding another variable, so I propose to change it to `sck_mode` and map to the values of https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus#Mode_numbers

I'll create another PR :-)
