### ISSUE TITLE
ST7565 init inaccurate comment

### ISSUE THREAD

**Issue by nickvanderstel** [olikraus/u8g2#311]
ST7565 command 0x027 sets the V5 voltage regulator internal resistor ratio - it does not configure the regulator, booster and follower as the comment suggests.

**Comment by olikraus** [comment]
yes, true... thanks for this.
However, i will reject the pull and change it manually, because it is called v0 in newer datasheets.

**Comment by nickvanderstel** [comment]
Looks good - verified that it is now called V0 in both the ST7565R and ST7565P datasheets.

**Comment by olikraus** [comment]
ok, so we can close this?

**Comment by nickvanderstel** [comment]
Sure
