### ISSUE TITLE
ubuntu installation

### ISSUE THREAD

**Issue by naomi87** [olikraus/u8g2#313]
`test.ino:6:18: fatal error: u8x8.h: File o directory non esistente
compilation terminated.`

I cant figure out how to install this librarie on ubuntu, looks like the IDE cant recognize the subfolder structure. I'm struggling to find an answer in the forums.
thanks

**Comment by olikraus** [comment]
It nicely works for my own ubuntu.
Did you follow this procedure?
https://github.com/olikraus/u8g2/wiki/u8g2install

**Comment by naomi87** [comment]
I dont have the manage libraries option in my Arduino IDE on lubuntu :(
I put the extracted zip file in the libraries folder... I can see the librarie in the menu and I can open the example files.

**Comment by olikraus** [comment]
Well, then, the question is, how can i support here? 
I have tested the two options in the official Arduino IDE (library manager and add library zip file menu). Both options work without problems. BTW manual extraction works, 
My suggestion is to use the official 1.8.x release or Arduino IDE together with the library manager.

**Comment by JamesGKent** [comment]
just a guess, but i seem to remember you saying something about this repo being for the development, and you have another arduino repo that puts the files into the correct folder structure to be recognized by the IDE, is it possible that the wrong repo/download is being used here? is it worth trying this [zip](https://github.com/olikraus/U8g2_Arduino/archive/2.15.2.zip) which is release 2.15.2 (latest) from your arduino repo, and extracting the contents into the arduino libraries folder?

**Comment by olikraus** [comment]
Possible... the correct download location is mentioned here:
https://github.com/olikraus/U8g2_Arduino
The lastest version of the zip is here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip
