### ISSUE TITLE
setup, loop vs. main and while(1)

### ISSUE THREAD

**Issue by Fox82** [olikraus/u8g2#315]
Dear u8g2 supporters,

Why is this code for me working,

`
#include <Arduino.h>
#include <SPI.h>
#include <U8g2lib.h>

U8G2_SH1106_128X64_NONAME_1_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE, /* clock=*/ SCL, /* data=*/ SDA);

void setup(void) {
	u8g2.begin();
}

void loop(void) {
		u8g2.firstPage();
	do {
		u8g2.setFont(u8g2_font_ncenB14_tr);
		u8g2.drawStr(0,20,"Hello World!");
	} while ( u8g2.nextPage() );
	delay(1000);
}

`

and this one is not working! Display is blank. This is a big issue for me because with the switch from u8g to u8g2lib Display is not woring any more for my project.

`
#include <Arduino.h>
#include <SPI.h>
#include <U8g2lib.h>

U8G2_SH1106_128X64_NONAME_1_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE, /* clock=*/ SCL, /* data=*/ SDA);

int main (void) {
	u8g2.begin();

while(1){
		u8g2.firstPage();
	do {
		u8g2.setFont(u8g2_font_ncenB14_tr);
		u8g2.drawStr(0,20,"Hello World1");
	} while ( u8g2.nextPage() );
	delay(1000);	
}
}
`

**Comment by olikraus** [comment]
Hmmm.. without loop it will not work, but this is an Arduino point, not  a U8g2 issue.

**Comment by Fox82** [comment]
I replaced the structure to setup and loop. now it works. But just strange, because u8g was woring with that and made no problems.

**Comment by olikraus** [comment]
setup/loop are mandatory for any Arduino program. Maybe it had been just luck, that u8glib did work without setup/loop.

**Comment by Fox82** [comment]
Something is wrong. I cannot place any display request on an other place than in the loop.

For example this leads also to an frozen OLED.

`ISR(INT1_vect) { 

	u8g2.firstPage();
	do {
		u8g2.setFont(u8g2_font_ncenB14_tr);
		u8g2.drawStr(0,20,"INT1 on");
	} while ( u8g2.nextPage() );

} // ISR INT1 END`

**Comment by olikraus** [comment]
Display output takes some time. If isr is faster than the output to the display, then your program will not work. Again this is not an U8g2 problem. Maybe you should better ask in Arduino for such questions.

**Comment by huseyinbb** [comment]
I want to ask a question about display fonts light. I want to use the U8g2 library in my Arduino flashing text. Adafruit has a backlight code but I couldn't find a code like a backlight for the U8g2 library. Can you help me?

**Comment by olikraus** [comment]
If the backlight is controllable, then you can use normal Arduino commands.

**Comment by huseyinbb** [comment]
We want use flashing text in the display with using U8g2 but we havent do
this yet.
Do you have any code like "backlight adafruit " this ?

13 Mar 2022 Paz 22:27 tarihinde olikraus ***@***.***> şunu
yazdı:

**Comment by huseyinbb** [comment]
We want use flashing text in the display with using U8g2 but we havent do
this yet.
Do you have any code or function  like "backlight adafruit " this ?

13 Mar 2022 Paz 22:32 tarihinde hüseyin büyükbayram <
***@***.***> şunu yazdı:

**Comment by olikraus** [comment]
You need to provide more information. I have no idea what "backlight adafruit" is. Please remember: This is u8g2 library. It has nothing todo with Adafruit.

**Comment by olikraus** [comment]
I don't see a video
