### ISSUE TITLE
Double click and long click support by GetMenuEvent and u8g2_UserInterfaceSelectionList

### ISSUE THREAD

**Issue by 4refr0nt** [olikraus/u8g2#317]
For systems with one button only this features may be usefull.
Single click - `u8sl_Next`
Double click - select menu item
Long click - menu exit

**Comment by olikraus** [comment]
Well... I never inteded these functions to be a full featured user interface.
It is more like an example of what could be done. So I actually do not plan to extend these functions in any way.
