### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by laterrps** [olikraus/u8g2#320]
I would like to wirite in an oled ssd1306 something like
Variable=77
and below a graph in real time something  like PPG signal but i cant do it because i dont know how to update this signal without clearing all the screen. i would like to do something like in this video at 1:07 i mean how they graph the signal

**Comment by olikraus** [comment]
The first/next page loop automatically clears the screen. The fullbuffer constructor includes also a screen clear function.

**Comment by laterrps** [comment]
does your library have something like u8g2.clear(0,5) and this function clear these determined area from the screen? I do this question because sometimes we dont wanna to clear whole screen instead of this just clear determined area

**Comment by olikraus** [comment]
You can use the box command.
