### ISSUE TITLE
test esp32 with u8g2

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#330]
from #329 

> https://github.com/espressif/arduino-esp32
Check out:
https://www.youtube.com/channel/UCu7_D0o48KbfhpEohoP7YSQ/videos

**Comment by olikraus** [comment]
still no boardfile for Arduino IDE

**Comment by bobybobybob** [comment]
Call me "Mr. Tester" ;-D

Have a look at Video  https://youtu.be/Nd6Ffxltc04

1. ESP32 and E-Ink 1.54       Bugs
2. Pro Mini and E-Ink 1.54   OK
3. ESP32 and OLED 128x64 OK

**Comment by olikraus** [comment]
Because of the missing boardfile, there is still no simple way to add support for ESP32 to Arduino IDE.
I will close this issue and reopen, once a boardfile is available.

**Comment by bobybobybob** [comment]
But it works

**Comment by olikraus** [comment]
Actually I tried everything to make it work, but failed. Maybe Linux is not supported. Anyhow, I will wait until a board package is available.

**Comment by bobybobybob** [comment]
My Videos with ESP32 show it work with some device
I use IDE Windows
