### ISSUE TITLE
ERC240120 UC1608 240x120

### ISSUE THREAD

**Issue by floris-b** [olikraus/u8g2#333]
Hello,

I want to use the ERC240120 from buydisplay.com and got it working with SW and HW SPI on a Teensy 3.2 with: U8G2_UC1608_240X128_F_4W_HW_SPI u8g2(U8G2_R0, 9, 8, 6);

A small problem I have is that the top 8 rows are not shown, it is a 240x120 pixel display
I tried changing the pixel_height but then the top 8 rows are still not visible and I lose the bottom 8 rows.
How can I solve this?

**Comment by olikraus** [comment]
I have created a new device for this.
Please download u8g2 from here:

https://github.com/olikraus/U8g2_Arduino/archive/master.zip

Please use the "add lib zip file" menu of the Arduino IDE for the installation.

Then use:
U8G2_UC1608_ERC240120_F_4W_HW_SPI u8g2(U8G2_R0, 9, 8, 6);

Note for 2.17 release: U8G2_UC1608_ERC240120 not yet added to ino constructor list

**Comment by floris-b** [comment]
The update does not work. Maybe my explanation was not clear.
When I run: u8g2.drawFrame(0,0,240,120 )

U8G2_UC1608_240X128: bottom horizontal line is correct at the bottom of the display, top horizontal line does not show

U8G2_UC1608_ERC240120: bottom horizontal line is 8 pixels obove the botom of the display,  top horizontal line does not show ( after a while there is a shift from the top and is shown at the bottom 8 rows )

**Comment by olikraus** [comment]
can you attach a picture?

**Comment by olikraus** [comment]
Thanks.
I have created u8g2 2.17.2. It is available under the above link.
Will it work now?
Please also test u8x8/FlipMode example. Will there be a text in the upper left corner for both modes?

Thanks for testing!

**Comment by floris-b** [comment]
At first it works but after some time there is an error, I am running the page buffer FPS example

![20170814_215219](https://user-images.githubusercontent.com/31005120/29289110-8e606b50-813b-11e7-935a-84bdbd836fab.jpg)
![20170814_215221](https://user-images.githubusercontent.com/31005120/29289111-8e61331e-813b-11e7-8608-26b7946b89d2.jpg)
![20170814_214528](https://user-images.githubusercontent.com/31005120/29289113-8e68d362-813b-11e7-9a1b-7f6750bfb2fc.jpg)
![20170814_214033](https://user-images.githubusercontent.com/31005120/29289112-8e632f16-813b-11e7-90c4-6f28d3f7bf07.jpg)

**Comment by floris-b** [comment]
Also the default contrast should be set to 80

**Comment by olikraus** [comment]
ok, i have fixed the flipmode 1 and updated the contrast.
Will it work now?
The unexpected change after some time might be caused by glitches in your test environment.

**Comment by floris-b** [comment]
The first time it flips upside down there are some random pixels and they stay there untill it flips the second time upside down
I also tried u8g2 flipmode example and that works perfect

![20170814_233012](https://user-images.githubusercontent.com/31005120/29292843-03a42282-8149-11e7-8bf6-abc72e0b3236.jpg)

**Comment by olikraus** [comment]
Hmmm... Ok... Maybe some other issue, but I think your 240x120 display is now done :)
Thanks for testing.

**Comment by floris-b** [comment]
Thanks for the quick response and the great library
