### ISSUE TITLE
Port to ARM

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#34]
create an example project, which demonstrates ARM usage

**Comment by basilfx** [comment]
Just for the reference, your library is already included in RIOT-OS, which also works on ARM :-)

https://github.com/RIOT-OS/RIOT/tree/master/pkg/u8g2

**Comment by olikraus** [comment]
Amazing...  I guess i have to check this with my STM discovery board.
Thanks for the information.

**Comment by basilfx** [comment]
I even have some screenshots of the demo application: https://github.com/RIOT-OS/RIOT/pull/5549

I use the EFM32, which is an ARM Cortex M3 CPU.

**Comment by olikraus** [comment]
wow, i am really impressed by the pictures.

Oliver

**Comment by olikraus** [comment]
no issue required...
