### ISSUE TITLE
SH1106_128X64 IIC

### ISSUE THREAD

**Issue by gochisar** [olikraus/u8g2#348]
U8GLIB_SH1106_128X64 u8g(U8G_I2C_OPT_NONE);

This U8GLIB version is works fine. But U8G2 libs of SH1106 is needs vertical line correction. first vertical line is draving on the last vertical line.

**Comment by olikraus** [comment]
At least my own SH1106 works without problems. Can you send picture and code?

**Comment by olikraus** [comment]
no feedback... closing...
