### ISSUE TITLE
Supporting Grayscale controller SSD1322

### ISSUE THREAD

**Issue by e-music** [olikraus/u8g2#355]
Hi again,

As you know, the SSD1322 integrates 16 gray-scale levels. I was wondering if that can be utilized somehow with the U8G2 library. 

Thanks in advance!

**Comment by olikraus** [comment]
During development of u8g2, it was a design decision not to support gray-level display any more.
One thing I learnd during u8glib, was, that adding gray level support makes the lib more complicated and slower. I think there should be a complete new lib for this purpose.

**Comment by e-music** [comment]
Do you have plans to work on it in the near future?

**Comment by olikraus** [comment]
Idea is there but no plan to start in the near future.
