### ISSUE TITLE
getStrWidth using variables

### ISSUE THREAD

**Issue by LEADEROS** [olikraus/u8g2#358]
Hello I how to using with getStrWidth
int w = u8g2.getStrWidth(a);

**Comment by olikraus** [comment]
Yes, if a is of type "char *"

https://github.com/olikraus/u8g2/wiki/u8g2reference#getstrwidth

**Comment by LEADEROS** [comment]
please write examples? My Engilish not good :/

**Comment by LEADEROS** [comment]
why only char my variables is String and int :(

**Comment by olikraus** [comment]
```
int w = u8g2.getStrWidth("abc");
```
or
```
char *s = "abc";
int w = u8g2.getStrWidth(s);
```

**Comment by JamesGKent** [comment]
@LEADEROS you can call .c_str() on your string objects to get a char array:
String data = String("mystring");
int w = u8g2.getStrWidth(data.c_str())

see here: [https://www.arduino.cc/en/Reference/CStr](https://www.arduino.cc/en/Reference/CStr)
