### ISSUE TITLE
Alternative OLED 64x32 Device

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#361]
Change 2f back to 1f for the 64x32 device
U8X8_CA(0x0a8, 0x1f), /* multiplex ratio: changed from 0x1f to 0x2f */

create new device for this, update examples.

see #254

**Comment by k1hop** [comment]
If anyone is curious to see this display operating with this change, here's a video I did of some preliminary experimentation.  Sorry, the camera is a bit out of focus. Using U8G2 library.
https://youtu.be/ecOLQpK0U3s

Russ - K1HOP

**Comment by k1hop** [comment]
hi... thanks for creating the new constructor(s) to support this change.
I had a chance to test it out this morning.  Before downloading and installing your new zip file to Arduino, I first removed the change I had done to the C file and confirmed that the old problem persisted.  Here's a photo of the 64x32 screen with the old C file and constructor showing the problem.  As you can see, the image appears shifted up by a couple of rows (half a screen) and the lower half is full of random RAM junk which never gets cleared or addressed with new data.

![0118bb9761d2e2debe7fda13ac49c5cd03af466f7e](https://user-images.githubusercontent.com/14240591/30776233-f7c4af26-a070-11e7-8a6c-303aa1b249a3.jpg)

**Comment by k1hop** [comment]
I then downloaded and installed your new version of the library with the new constructor(s).  I changed my Arduino code to use the new constructor:  U8G2_SSD1306_64X32_1F_F_HW_I2C u8x8(U8G2_R0, 19, 18);
This worked just fine, as attested by the following screen images.

![018c651437d8b4b2047b2292aec195789b2d4d04f6](https://user-images.githubusercontent.com/14240591/30776396-a4301776-a073-11e7-9f5c-37d7fd3d341f.jpg)
![0193ea77f5b6bc3ba6ae962adcf5c27b88d8a56134](https://user-images.githubusercontent.com/14240591/30776397-a430457a-a073-11e7-8019-2c2e5c1fa54f.jpg)

**Comment by k1hop** [comment]
If you care to view a portion of the full demo using both the old and new constructors, you can see short videos at my YouTube channel: https://www.youtube.com/channel/UCkJYUHvNJll_MdXTmdzZ2gg

**Comment by olikraus** [comment]
Nice Videos and Pictures. So all is done and fixed, right? We can close this issue?

Thanks a lot for your contribution!

**Comment by k1hop** [comment]
Looks great to me!  Would be nice/comforting if other users of same display chimed in.  But I'm A-OK now! :)

**Comment by olikraus** [comment]
there will be an official release soon :-)
