### ISSUE TITLE
Wire.h included when using SW_I2C

### ISSUE THREAD

**Issue by DirkHeinke** [olikraus/u8g2#369]
Hello,

I'm not sure but is this the normal behavior?

I do `#include <U8g2lib.h>`. In that header `#include <U8x8lib.h>` is included and there `U8X8_HAVE_HW_I2C` is defined, so that later on the `Wire.h` file is loaded?

Later in my code I use `U8G2_SSD1306_128X64_NONAME_F_SW_I2C`.

How can I use u8g2 without including Wire.h?

**Comment by olikraus** [comment]
Due to a bug in the Arduino environment, the Wire code is still included although you just use SW I2C. As a workaround, undefine U8X8_HAVE_HW_I2C and do not include Wire.h anywhere. See also

https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L169

**Comment by olikraus** [comment]
closing...
