### ISSUE TITLE
Test dogxl240, full buffer mode does not work

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#370]
... for next release because of modifications #339

**Comment by olikraus** [comment]
- FPS seems to be partly corrupted, other examples do not work at all
- Changing the optimization flags, does not change this (tested in Arduino IDE)
- Tested with DOGXL240 and Arduino Due. Other displays affected?

**Comment by olikraus** [comment]
/tmp/arduino_build_608416/sketch/HelloWorld.ino.cpp.o: In function `U8G2::setPageCurrTileRow(unsigned char)':
/home/kraus/Arduino/libraries/U8g2/src/U8g2lib.h:163: undefined reference to `u8g2_SetPageCurrTileRow'

**Comment by olikraus** [comment]
beta release 2.18.12 should fix this bug.

**Comment by arnoldvillasanta** [comment]
The fix works with UC1611 LCD (240x160) for all the full_buffer samples:
Great support and timely fix as always.

![20170930_210516](https://user-images.githubusercontent.com/31164013/31046021-e5d2a364-a623-11e7-9260-212f0bc35593.jpg)

**Comment by olikraus** [comment]
Thanks a lot. I wonder that noone complained about this before. The full buffer problem must exist since several versions. 

I also just released 2.18.13. It will be available for the Arduino IDE soon.

**Comment by arnoldvillasanta** [comment]
Maybe most users have limited MCU RAM that they opted for the page_buffer.  You're such a good project owner to keep up with all these changes (sometimes with too demanding users).

**Comment by olikraus** [comment]
:)
