### ISSUE TITLE
support 256x128 LCD

### ISSUE THREAD

**Issue by aradarbel10** [olikraus/u8g2#374]
for example: 256x128 LCD HYUNDAI HG25604-B from All Electronics

**Comment by olikraus** [comment]
Reference: https://forum.arduino.cc/index.php?topic=503084

Let me know whether you want to use u8g2 for this display. I can just offer to implement support for this dimension (and remember, this is a open source project and I do this for free in my spare time), but I need you for testing.

**Comment by olikraus** [comment]
Any update on this topic?

**Comment by aradarbel10** [comment]
Not yet, probably tommorw Ill go to few shops and buy everything I need. In
israel all the stores are close on saturday.

**Comment by olikraus** [comment]
Great, I just was about to clean up this issue list. I will wait for your input and keep this open.

**Comment by aradarbel10** [comment]
Hello again,
as you said, I got a power supply of -20v.
just using a normal DC power supply (MCH-303A)...
but in chapter 7 there is a potentiometer, should I ignore that?
anyways,  I tried to connect it to  -21v and its working! all of the screen is turned on! Now the hard part... 
which is the code. I uploaded the u8g2 hello world sample with the right constructor and it sends a weird error:

"vrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt X of 10: not in sync: resp=0x00"

And while trying to upload (unsuccessfully...) the display is kinda blinking...
also, finally its sending a message says that it can't upload the sketch to the board.
I am on the Arduino uno board and COM3 so this is not the problem. is it a problem with the hardware?

Arad.

**Comment by olikraus** [comment]
Well, the potentiometer is there for contrast adjustment. So usually it is required, but for testing, a fixed source might be ok.

> avrdude: stk500_getsync() attempt X of 10: not in sync: resp=0x00"

This is not u8g2 specific. You should be able to program the Arduino. Maybe you have selected the wrong port.

**Comment by olikraus** [comment]
no feedback... can this be closed?

**Comment by aradarbel10** [comment]
Im sorry, but still no... as I mentiond before, I had a problem with my arduino, it will take more time till I recive it from ebay... I dont even know when I will recive it and cant do anything about it.

**Comment by olikraus** [comment]
ok, no problem

**Comment by olikraus** [comment]
can i close this issue? You can reopen or open a new issue, if required...
