### ISSUE TITLE
how kerning works for arabic ?

### ISSUE THREAD

**Issue by smarty551** [olikraus/u8g2#375]
i found a kerning table for this Arabic font here so how can i use it ?
http://www.adambaker.org/kerning_font.php
thank you

**Comment by olikraus** [comment]
I once started to implement kerning, but finally failed. Kerning tables get too big and will not fit into RAM/ROM of small embedded controllers. So finally, I removed kerning procedures. However some might still be there.

There is a small workaround, described in one of the issues.

**Comment by olikraus** [comment]
some details are here: #42

**Comment by smarty551** [comment]
ok i will try to get around kerning in arabic and pass it to you

**Comment by smarty551** [comment]
but the main problem that it has to be font specific even that i was thinking about a loop with all the conditions of kerning (the same one you were talking about in the #42 )

**Comment by olikraus** [comment]
Yes, the current solution is very specific. But anything else will generate very huge tables. The will not fit into the uC ROM.

**Comment by smarty551** [comment]
sorry but have you tried to work it with the same idea of bdfconv that the user will have to put the text in file then generate array that will be fed into drawstr

**Comment by olikraus** [comment]
no
during my own experiments, i just generated the kerning between all glyphs of the font (however, number of glyphs can be selected/restricted). The problem still is, that the table gets too big.
I finally stopped working on this.

**Comment by olikraus** [comment]
I know this is not a good answer, but I do not see how this can be implemented on small uC systems.
