### ISSUE TITLE
ESP8266 HW i2c

### ISSUE THREAD

**Issue by Testato** [olikraus/u8g2#38]
In your  boardlist https://github.com/olikraus/u8g2/wiki/boardlist
there is support for SW and HW i2c on Esp8266.

But the esp do not have hw i2c. It is writed in the datasheet, and if you check the arduino port for esp there is a bitbanging i2c

**Comment by olikraus** [comment]
Thanks for the hunt. I should be more precise here

**Comment by olikraus** [comment]
updated board list

**Comment by Testato** [comment]
This boardlist ?
https://github.com/olikraus/u8g2/wiki/boardlist

It seems incorrect again to me

**Comment by olikraus** [comment]
HW I2C just means that Wire.h is used.

**Comment by Testato** [comment]
But you sre leaved OK in the table to hw and to sw i2c.
A people that look your yable think that esp have an hw i2c, that is not true.

Other problem is that wire.h is used also on sw i2c, like on esp arduino core, because the author modified it.

I think that the simplest way is remove wire.h mention, and simply put an N.A. in the ESP hw i2c

**Comment by olikraus** [comment]
ok, done.
