### ISSUE TITLE
German Umlauts: getStrWidth() returns differnt values for characters with same width

### ISSUE THREAD

**Issue by luebbe** [olikraus/u8g2#386]
Hi folks,
I stumbled across this with one font. Haven't tried with other fonts, so I can't tell whether it's a problem with this specific font.
I'm using u8g2_font_helvR18_tf to draw centered text. When the text contained umlauts, it wasn't centered anymore.
* getStrWidth('AOU') returns 51 Pixel
* getStrWidth('ÄÖÜ') returns 67 Pixel

Only tested with this one font
Does getStrWidth() count hidden UTF-8 bytes as well?

Cheers & thanks

**Comment by olikraus** [comment]
Which values will you get with getUTF8Width?
 *   getUTF8Width('AOU') 
 *   getUTF8Width('ÄÖÜ') 

Applying unicode string to getStrWidth will probably lead to unexpected results.

**Comment by luebbe** [comment]
It obviously  does :)
getUTFWidth did the trick. I'm usin drawUTF already. Should have thought of this ...

Thanks for your help and sorry for the fuzz

**Comment by olikraus** [comment]
:)
