### ISSUE TITLE
Arabic font

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#39]
Dear Oliver
Thanks for your rapid reply

I think for Persian language I need these Unicode 9.0 Ranges of the Arabic Font :
1) Arabic 0600-06FF
2) Arabic Presentation Forms-A FB50-FBB1
3) Arabic Presentation Forms-B FE70-FEFF

Greetings from Iran
Farzad

**Comment by farzad321554** [comment]
You're great Oliver
I'm waiting for Ver2.1
And I promise the first code on my lovely SSD1306 OLED will be:

u8g2.print("اولیور به ایران خوش آمدی");     //Means "Welcome to Iran Oliver"     ;)    ;)

**Comment by olikraus** [comment]
I have created several arabic fonts:
https://raw.githubusercontent.com/wiki/olikraus/u8g2/fntpic/u8g2_font_cu12_t_arabic.png
https://raw.githubusercontent.com/wiki/olikraus/u8g2/fntpic/u8g2_font_10x20_t_arabic.png
https://raw.githubusercontent.com/wiki/olikraus/u8g2/fntpic/u8g2_font_unifont_t_arabic.png

**Comment by olikraus** [comment]
looks ok, but i am not sure because of the writing direction. 

![arabic](https://cloud.githubusercontent.com/assets/1084992/17513083/3a01a490-5e2b-11e6-86b1-7b80a3af3629.png)

**Comment by farzad321554** [comment]
Yes, the direction is right to left.
Is'nt there any hope for kerning?

**Comment by olikraus** [comment]
U8g2 fonts are derived from the BDF file format. To my knowledge, this BDF file format does not contain any kerning information. So u8g2 font calculation tool chain can not get and handle this information.

The only option what i could imagine, is that we add the kerning information as an extra table manually. Would this be an option?

**Comment by olikraus** [comment]
Currently i am thinking on the introduction of a kerning table, which has to be added manually.
Something like this:
{ 
code1, code2, kerning,
code1, code2, kerning,
code1, code2, kerning,
...
}
Probably you have to experiment a little bit and derive the kerning table manually.

What do you think?

**Comment by olikraus** [comment]
afm files contain proper kerning, some fonts are mentioned here.
The kerning table could be derived from the atm files:
http://www.nsl.com/k/pdf/afm/
