### ISSUE TITLE
will it work with waveshare 4.2inch_e-Paper_Module? with lua

### ISSUE THREAD

**Issue by shimondoodkin** [olikraus/u8g2#394]
https://www.waveshare.com/wiki/4.2inch_e-Paper_Module
seems there is no matching display driver
how to make it work?
can somebody develop this, to help me?

**Comment by shimondoodkin** [comment]
found this, esp32 brahttps://nodemcu.readthedocs.io/en/dev-esp32/en/modules/u8g2/
supports u8g2.

**Comment by olikraus** [comment]
indeed this 4.2" module is not supported. Adding support is thinkable, but almost impossible without having the device in my lab.

**Comment by shimondoodkin** [comment]
there is similar display  implemented already
maybe  it is possible to look in the code of the example code.zip and do the small modifications required.

**Comment by shimondoodkin** [comment]
https://github.com/olikraus/u8g2/issues/318 similar implemenations

**Comment by shimondoodkin** [comment]
i had compared the code of 2.9 and 4.2 , the files are different, but with similar structure

**Comment by olikraus** [comment]
The structure will be the same, even for u8g2. The most biggest question is: What init code is required for the display. Or let me start with a more simple question: What is the name of the build-in graphics controller for that display. Will we get the datasheet for this controller?

**Comment by MrJazzmax** [comment]
Hi Oliver,, datasheet for this display is here: https://www.waveshare.com/wiki/File:4.2inch-e-paper-specification.pdf
I got the same problem as shimon,, I woud like to use this display with your graphic library.
Im not sure if this help you .. (probably you have seen this datasheed already).
PS: I can sent you my own Waveshare 4.2 inch display (any problem)

**Comment by olikraus** [comment]
The problem is, I simple don't have time at the moment to work on such a complicated device. Have a look at the issue regarding the implementation of the 2.9" display. It requires so much investigation, which i can not do at the moment.

**Comment by shimondoodkin** [comment]
I'm sorry. My project canceled.

**Comment by olikraus** [comment]
Reference to 2.9" epaper discussion: #318

**Comment by MrJazzmax** [comment]
I understand,, but maybe one day, when you get a time and taste to get back to this display ..
Controller: IL0398 : http://www.good-display.com/download_detail/downloadsId=537.html

thanks for your fast respond !

**Comment by olikraus** [comment]
I reopen this... let's see... 
From where do you know that this is the correct controller?
At least it seems to fit.

**Comment by MrJazzmax** [comment]
because I found another library for this display,, exactly this device (waveshare 4.2) and there was description .. Also I compared my display  with good display, it seems to be the same manufacturer at first glance. very similar like in case of waveshare 2.9 (IL3820).

**Comment by MrJazzmax** [comment]
I forgot to write the name of device,, Its GxGDEW042T2

**Comment by bobybobybob** [comment]
Waveshare has Arduino Libary too. Maybe it is OK for 4.2" Paperdisplay. https://github.com/soonuse/epd-library-arduino

**Comment by ZinggJM** [comment]
It works with GxEPD: https://github.com/ZinggJM/GxEPD
And there is new GxEPD2_AVR and GxEPD2_32 "under construction" with interface similar to U8G2.

**Comment by olikraus** [comment]
This issue started long back. Until now I did not found any time to implement support for another e-paper display. Also the question is, is it really worth to do so, as there are other great libs, supported by @ZinggJM  .

At the moment I do not think, that I will be able to provide support for the 4.2" e-paper requested here.

**Comment by baoyingcheng** [comment]
the driver chip is il0398 and I can offer you the datasheet and demo driver app in stm32
[4.2inch_epaper_stm32.zip](https://github.com/olikraus/u8g2/files/1750136/4.2inch_epaper_stm32.zip)

**Comment by shimondoodkin** [comment]
What was wanted is to use semi-large epaper display with node mcu with elua. Which is not possible with any lib availible. u8g2 is integrated into node mcu.

**Comment by ZinggJM** [comment]
I don't know elua. But if it can be extended with C++ classes, it should not be too difficult to adapt and add the class GxEPD2_32_BW. You would need to change the few places using the Arduino SPIClass, and setMode() and digitalWrite() IO calls.

**Comment by olikraus** [comment]
I decided to concentrate on oleds and lcds. There are other good libs for e-paper displays (see above)
