### ISSUE TITLE
SPI half duplex

### ISSUE THREAD

**Issue by sonic2wb** [olikraus/u8g2#400]
I have a quick question, I tried to daisy chain a LCD with the st7920 chipset and a NRF24 radio, They did not play well together. It was suggested that maybe u8g2 was setting half duplex on the spi bus, if so how can i enable full duplex and would it mess up u8g2?

**Comment by olikraus** [comment]
Not sure what you mean by half duplex/full duplex...
From my perspective there are two preconditions for usage of multiple SPI clients:
1. There must be a separate chip select line for each client
2. On the host/uC side all communication must happen through Arduino standard SPI library. Especially the SPI.beginTransaction (https://www.arduino.cc/en/Reference/SPIbeginTransaction) function must be used. 

If you use a very old library for NRF24 maybe the second point is not implemented. Same is true if you wrote your own access function: You need to correctly use the SPI funcitons from the Arduino Lib as described here: https://www.arduino.cc/en/Reference/SPI
