### ISSUE TITLE
sytax highlighting

### ISSUE THREAD

**Issue by m9365428** [olikraus/u8g2#402]
Love the library but noticed a lack of a Keywords.txt
This makes keeping track of functions in the code a bit tedious.
Any chance of getting one added to the library. (If i get time I can work on it but I don't know how to look at the source so it wont be comprehensive.)

**Comment by olikraus** [comment]
Yes, I know, it is missing for a long time. In fact I do not know and where to start. Any contribution would be great.

**Comment by m9365428** [comment]
Ok just added a test keywords.txt with a good bit of info in the note.
Honestly its no where near complete but it works.
Load it up and checkout the code examples to see effect.

**Comment by olikraus** [comment]
where can i find your file?

**Comment by m9365428** [comment]
Sorry new to github thought my file would be visible.
Established new Pull request

**Comment by olikraus** [comment]
Thanks for the pull request.

Added your comment here also for reference:
=======

Test run for keywords.txt
quick test using commands listed in https://github.com/olikraus/u8g2/wiki/u8g2reference
included one font in literals for testing.

Thought: If font codes where rewriten as u8g2.font.ncenB08.tr then fewer entries would be needed and it might simplify backend code.

method:

    add new line for keyword in proper section
    after keyword intert literal TAB not spaces. I edited in note pad and copied over.
    after TAB insert word type (KEYWORD 1, KEYWORD 2, KEYWORD3, LITERAL 1, LITERAL2)

more documentation on keyword.txt
https://gist.github.com/gschandler/8704468 (template)
https://www.arduino.cc/en/Hacking/LibraryTutorial (near the bottom)
https://spencer.bliven.us/index.php/2012/01/18/arduino-ide-keywords/ (what are the types)

**Comment by olikraus** [comment]
todo: release script must copy keywords.txt to destination lib.

**Comment by m9365428** [comment]
Ok awesome. Glad I could help.
Like I said it's not a completed file as it doesn't include all commands and arguments but it does establish the framework to build everything on.

**Comment by olikraus** [comment]
keywords.txt is now included in the current beta release 2.20.2

**Comment by olikraus** [comment]
works as expected... Thanks!
