### ISSUE TITLE
Request- add ST7735

### ISSUE THREAD

**Issue by folkos** [olikraus/u8g2#415]
Please add a display ST7735.

**Comment by olikraus** [comment]
ST7735 is a RGB controller. U8g2 however is a monochrome lib, so st7735 can not be supported.

**Comment by folkos** [comment]
Got it. Thank you.

**Comment by olikraus** [comment]
👍

**Comment by maxholgasson** [comment]
Could the ST7735 be used in only one color? Or is it a general issue?

**Comment by olikraus** [comment]
There is no 1-bit mode for the ST7735. This means u8g2 would transfer 24 bit to show a one bit information. In other words using ST7735 would be 24 times slower than a true monochome display. Why would you want this? Better get a true monochrome display or use a RGB library for the ST7735.

**Comment by maxholgasson** [comment]
Ah ok, 
>Why would you want this?  
because this is the best lib I found so far
