### ISSUE TITLE
how to write in Russian???

### ISSUE THREAD

**Issue by timurufa86** [olikraus/u8g2#419]
Good afternoon!
I cannot understand how to write on cyrillic... I use the u8g2_font_cu12_t_cyrillic font. This command I set the u8g2.setFont(u8g2_font_cu12_t_cyrillic) font; can somewhere else what that needs to be added?
Tell me please!

**Comment by olikraus** [comment]
There are some additional requirements:
- Your Editor must support UTF-8 (I think this is true for the Arduino IDE)
- You must use drawUTF8 (https://github.com/olikraus/u8g2/wiki/u8g2reference#drawutf8) or enable UTF8 for the print command (https://github.com/olikraus/u8g2/wiki/u8g2reference#enableutf8print).

**Comment by timurufa86** [comment]
hi!!!
  I tried an example where hi the world on Chinese - in it the Chinese eroglifa are not displayed too

**Comment by timurufa86** [comment]
you can give me a code working for example with a text "Привет мир"

**Comment by olikraus** [comment]
void setup(void) {
  u8g2.begin();
  u8g2.enableUTF8Print();		// enable UTF8 support for the Arduino print() function
}

void loop(void) {
  u8g2.setFont(u8g2_font_cu12_t_cyrillic);  // use chinese2 for all the glyphs of "你好世界"
  u8g2.firstPage();
  do {
    u8g2.setCursor(0, 40);
    u8g2.print("Привет мир");
  } while ( u8g2.nextPage() );
}

**Comment by kewin2013** [comment]
Everything done as written here, but Cyrillic is not displayed. What can be?
```
#include <Arduino.h>
#include <U8g2lib.h>

U8G2_SSD1306_128X64_NONAME_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ A4, /* data=*/ A3, /* cs=*/ A0, /* dc=*/ A1, /* reset=*/ A2); 

void setup(void) {
  u8g2.begin();
  u8g2.enableUTF8Print();    // enable UTF8 support for the Arduino print() function
}

void loop(void) {
  u8g2.setFont(u8g2_font_cu12_t_cyrillic);  
  u8g2.firstPage();
  do {
    u8g2.setCursor(0, 40);
    u8g2.print("Привет мир");
  } while ( u8g2.nextPage() );
}
```

**Comment by olikraus** [comment]
does the HelloWorld example work?
I mean, does the display work correctly?

**Comment by timurufa86** [comment]
Hello! An example from the box does not work, but if you play with the
fonts, you can find a working ...

2 марта 2018 г. 3:12 AM пользователь "olikraus" <notifications@github.com>
написал:

**Comment by kewin2013** [comment]
Код заработал, теперь отображается кириллица

**Comment by Dmitrykrz** [comment]
> Код заработал, теперь отображается кириллица

Что надо было поменять чтобы заработал?


> does the HelloWorld example work?
> I mean, does the display work correctly?
Screen works fine. I can see english text on the screen but only ??? for russian text. I have tried all cyrrilic fonts and examples from this thread.

**Comment by olikraus** [comment]
Do you use the Arduino IDE?

**Comment by Dmitrykrz** [comment]
> Do you use the Arduino IDE?

Microsoft Visual Studio with vMicro

**Comment by olikraus** [comment]
Great. UTF8 editor support is required for this feature.
