### ISSUE TITLE
Question about freedoomr font

### ISSUE THREAD

**Issue by aslobodyanuk** [olikraus/u8g2#425]
Hi, is there a ttf variant of freedoomr25n font? I have searched everywhere and could not find it. I need ttf font because i want to scale it down a bit.

**Comment by olikraus** [comment]
It is a bitmap font only. It was contributed long time back. I even do not have contact information any more:

https://github.com/olikraus/u8g2/issues/13

The font sources are here:

https://github.com/olikraus/u8g2/blob/master/tools/font/bdf/freedoomr10r.bdf
https://github.com/olikraus/u8g2/blob/master/tools/font/bdf/freedoomr25n.bdf

I assume .bdf can be imported into fontforge (or similar tools), but I assume rescaling is difficult.
