### ISSUE TITLE
Request for supporting for waveshare 7.5in b/w epaper

### ISSUE THREAD

**Issue by evan-opener** [olikraus/u8g2#427]
Hi, I saw the demo for a lot of display devices and it was impressive. I want to know if you can support the waveshare 7.5inch b/w epaper. The datasheet is blow: 
https://www.waveshare.com/w/upload/b/b6/7.5inch-e-paper-specification.pdf
It also has a raspberryPi hat version with the connector.
https://www.ebay.com/itm/7-5inch-E-Ink-display-HAT-for-Raspberry-Pi-three-color-640x384-resolution-SPI-/253175592970

Current I just use the library from ZinggJM/GxEPD and there is no Chinese font support.
BTW, my Arduino device is ESP8266 wemos D1 mini and I also have one wemos D1 mini pro.
Thanks in advance.

**Comment by evan-opener** [comment]
I know it is a little bit rackless to ask for the support.
If I want to use the construct function, where I can modify the  parameter to change the resolution and pin definition?

**Comment by olikraus** [comment]
It is complicated and probably requires a lot of investigation.

See for example here: #318

**Comment by evan-opener** [comment]
@olikraus 
Thanks. I will study them first.
