### ISSUE TITLE
UC1610 contrast control is incorrect

### ISSUE THREAD

**Issue by MattMatic** [olikraus/u8g2#428]
The range of contrast for the DOGXL160 is 0-255, not 0-63 as stated in the file.
u8x8_d_uc1610.c.
Just removed the  >>2

**Comment by olikraus** [comment]
oh... indeed

https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_uc1610.c#L242

Thanks for this. Nice finding.

**Comment by vaibhav2678** [comment]
I  am using OLED 128x64 using U8glib Code 
I have used Constructor SH1106 and is successfully Tested 
I want to code for Clock can U suggest me where I want to start ??

**Comment by olikraus** [comment]
@vaibhav2678 
I think this is not related to this topic. Consider to open a new issue.

**Comment by MattMatic** [comment]
Noticed this has not yet been corrected. The ">> 2" needs removing ;)

**Comment by olikraus** [comment]
Oh

**Comment by olikraus** [comment]
should be ok now

**Comment by olikraus** [comment]
thanks for the hint!
