### ISSUE TITLE
I'm not able to draw a bitmap from an array of bitmaps

### ISSUE THREAD

**Issue by uncle-buzz** [olikraus/u8g2#430]
Hi !
I want to use same function to display some menu and submenu with bitmap, so I try to deal with array of bitmaps and give pointer to my function.
The result is not what I expected, some snow random bitmap...

My bitmaps are store in flash with PROGMEM, and I am able to draw them by calling directly the bitmap's pointer in U8g2.drawXBMP

here is how I defined them : 
```
#define first_bitmap_width 36
#define first_bitmap_height 8
static const unsigned char first_bitmap_bits[] U8X8_PROGMEM = { ... };

#define second_bitmap_width 36
#define second_bitmap_height 8
static const unsigned char second_bitmap_bits[] U8X8_PROGMEM = { ... };

#define third_bitmap_width 36
#define third_bitmap_height 8
static const unsigned char third_bitmap_bits[] U8X8_PROGMEM = { ... };
```

```
#define NB_MENU_IMG 6 // number of bitmaps in this menu
const unsigned char* menuIMG[NB_MENU_IMG] =
{
	first_bitmap_bits,
	second_bitmap_bits,
	third_bitmap_bits,
        (...)
}
```

```
#define MENU_IMG_DISPLAYED 3 // 3 bitmaps on screen

void displayImgMenu(
const unsigned char** arrayIMG, // pointer to array of bitmaps
 byte sizeOfArrayIMG, // size of array
 byte selected) // index of selected bitmap (center)
{
	(...) // some stuff to set drawing position, color... etc

	byte index;

	for (byte i = 0; i < MENU_IMG_DISPLAYED; i++)
	{
		(...) // setting position

		index = selected - 1 + i; // selected = center

		if (index + sizeOfArrayIMG < index) // < 0
			index += sizeOfArrayIMG ;
		else if (index - sizeOfArrayIMG < index) // > sizeOfArrayIMG 
			index -= sizeOfArrayIMG ;

		screen.drawXBMP(x, y, w, h, arrayIMG[index]);
	}
	
	screen.sendBuffer();
}
```

I tried
`screen.drawXBMP(x, y, w, h, *(arrayIMG + index));`

I tried directly without passing a pointer to my array of bitmap
`screen.drawXBMP(x, y, w, h, menuIMG[index]);`

I have always same results : snow instead of my bitmap.

only direct call to bitmap is working :
`screen.drawXBMP(x, y, w, h, first_bitmap_bits);`

How should I declare my array of bitmap ?

Thank you for help

**Comment by uncle-buzz** [comment]
well, the faulty part was my "index"...
my conditions in if statement expected some overflow on byte, but instead of that, byte - byte seems to be interpreted as an int with negative value...

**Comment by olikraus** [comment]
:+1:
