### ISSUE TITLE
About cyrillic letters in u8g2_font_crox1hb_tf font

### ISSUE THREAD

**Issue by fire1** [olikraus/u8g2#433]
I'm seen there are cyrillic letters in u8g2_font_crox1hb_tf font but cannot draw them from drawExtUTF8 method. I'm seeing there is support of  cyrillic ... or not ?

 Only when using as example u8g2_font_10x20_t_cyrillic everything is O.K.

**Comment by olikraus** [comment]
Yes, the bdf source file for u8g2_font_crox1hb_tf has a different encoding. UTF8 does not make sense with these fonts. I just added them due to some requests. You could use them with UTF8 disabled.
