### ISSUE TITLE
ESP12E/F to SPI_HW SH1106

### ISSUE THREAD

**Issue by 999chris** [olikraus/u8g2#435]
Hi All,

I'm really concerned I'm doing something dumb here.

I have my SH1106 1.3" screen using 4W HW SPI connected to an ESP8266 module:

14 - CLK
13 - MOSI
15 - CS
12 - DC
16 - Reset

My constructor:
U8G2_SH1106_128X64_NONAME_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ 15, /* dc=*/ 12, /* reset=*/ 16);

And some code running further down which I can see in the Serial Monitor is firing. The code and constructor works fine when hooked up to a normal Arduino, but I am not getting anything off my ESP8266. Is there something I'm doing wrong? connections seem fine and I'm supplying 3.3v to the screen.

**Comment by 999chris** [comment]
Okay I have this working under Software SPI, why is it not working with Hardware SPI? I've included the SPI.h library.

**Comment by olikraus** [comment]
Maybe the ESP8266 HW SPI is available on other pins only. 
This is not an u8g2 issue, but probably more a question to your board, where the HW pins are located.

**Comment by 999chris** [comment]
Maybe, the CLK and MOSI pins match up, but I'm using the pin that is assigned for MISO for another purpose (CS). Could this be causing the issue?

**Comment by olikraus** [comment]
could be...

**Comment by olikraus** [comment]
not sure how to support here... closing...
