### ISSUE TITLE
Right part of the screen have some random pixel

### ISSUE THREAD

**Issue by Eternyt** [olikraus/u8g2#436]
![img_20171126_225057](https://user-images.githubusercontent.com/16137719/33244701-769fbbe8-d2fc-11e7-867d-d6baf220c52d.jpg)
No matter what I do, initDisplay() or begin(), this little bar remain whatever I do after.
Aliexpress ssd1306 128*64 using hardware I2C bus. Used the following setup:
U8X8_SSD1306_128X64_NONAME_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);

**Comment by olikraus** [comment]
this is a sh1106 controller

**Comment by Eternyt** [comment]
Thanks, fixed.
Just for curiosity, how do you spot that my screen is a sh1106 and not a ssd1306?

**Comment by olikraus** [comment]
> Just for curiosity, how do you spot that my screen is a sh1106 and not a ssd1306?

because of your title: " Right part of the screen have some random pixel"
:)
