### ISSUE TITLE
Incorrect pixel placement - esp8266

### ISSUE THREAD

**Issue by nottledim** [olikraus/u8g2#44]
I'm using an esp8266 (esp-01) with a 128x64 oled display SSD1306 with i2c interface.

I'm using u8g2 version 2.1.5 (downloaded yesterday) with Arduino 1.6.6 and the Generic ESP8266 v2 board library.

Running your example page_buffer/HelloWorld for example shows the text "HelloWorld!" followed by half of the letter "H" from the beginning.  What I've noticed is that the first few pixel columns, 8 I think,  of text placed at the start of a line is duplicated at the end of the line. This happens irrespective of the length of the text or size of the font.

![img_20160811_151456](https://cloud.githubusercontent.com/assets/1743415/17591630/e1675f2a-5fd6-11e6-95d8-bbb32d92d779.jpg)

I've tried various variations including frame buffer, which makes no difference, and different drivers which changes the symptoms but is still wrong.

I use this constructor in your example program:
#define gpio_SDA 0
#define gpio_SCL 2
U8G2_SSD1306_128X64_NONAME_1_SW_I2C u8g2(U8G2_R0, /* clock=*/ gpio_SCL, /* data=*/ gpio_SDA, /* reset=*/ U8X8_PIN_NONE);   // All Boards without Reset of the Display

Is there anything I can do to cure this problem?

Thanks

**Comment by olikraus** [comment]
What is the display resolution? Is it 128x64 or is it 132x64? Are you ablet to count the horizontal resolution?
You could also try a different chipset. You display might contain the SH1106 controller instead of the SSD1306.

Note: Information from the seller is sometimes not correct...

**Comment by nottledim** [comment]
it's 128x64.  I've tried SH1106 controller - with HelloWorld it looks the same i.e. same error.  

I can place text exactly where I want it except that the last few pixels of the line are corrupted.  So I don't think it's a dimension error.  Anyway it all works fine with u8glib with arduino processor.

I've got 2 similar displays and they both show same error.

It's weird isn't it :-)

**Comment by olikraus** [comment]
strange...

**Comment by Mark-Wills** [comment]
Just to let you know, I'm having the exact same problem with the exact same display board. U8glib and u8x8 in g2lib don't seem to be a problem. It's just a problem with U8G2.

```c++
#include <Arduino.h>
#include <SPI.h>
#include <U8g2lib.h>

U8G2_SSD1306_128X64_NONAME_1_SW_I2C u8g2(U8G2_R0, 19,18);

void setup(void) {
  u8g2.begin();
}

void loop(void) {
  u8g2.firstPage();
  do {
    //u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.setFont(u8g2_font_7x14B_tf);
    u8g2.drawStr(0,10,"Hello!");
  } while ( u8g2.nextPage() );
  delay(1000);
}
```
The above will re-produce the problem. I'm using an Arduino UNO. I tried both hardware and software I2C constructors; same result.

![20160812_190119](https://cloud.githubusercontent.com/assets/20996490/17632663/7c047afa-60c1-11e6-90cf-5c0f4ec56ab0.jpg)

**Comment by olikraus** [comment]
Can you draw some lines like this:

```
void loop(void) {
  u8g2.firstPage();
  do {
    //u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.setFont(u8g2_font_7x14B_tf);
    u8g2.drawStr(0,10,"Hello!");
    u8g2.drawLine(0,0,63,63);
    u8g2.drawLine(63,63,63+63,63-63);
    u8g2.drawPixel(126,20);
    u8g2.drawPixel(127,21);
  } while ( u8g2.nextPage() );
  delay(1000);
}
```

Can you send me the result?

**Comment by Mark-Wills** [comment]
Sure. Give me a minute... on it now...

**Comment by olikraus** [comment]
wow, thats quick :-)

**Comment by olikraus** [comment]
I personally think that this is not a SSD1306 controller... but let us see...

**Comment by Mark-Wills** [comment]
Here you go:

![20160812_192846](https://cloud.githubusercontent.com/assets/20996490/17633026/4df3c592-60c3-11e6-884a-21bef5b8ee6c.jpg)

**Comment by olikraus** [comment]
hmmm, this is strange...
did you include the drawPixel() commands?
they are not visible, right?

**Comment by Mark-Wills** [comment]
Hang on... I'm posting another pic (takes a while to bluetooth it from my phone and re-size it ;-) )

**Comment by olikraus** [comment]
yes, a better close up of the upper right part would be interesting

**Comment by Mark-Wills** [comment]
Here you go... 
![20160812_193250](https://cloud.githubusercontent.com/assets/20996490/17633162/d631d0e8-60c3-11e6-8470-2ec2190f11c4.jpg)

**Comment by Mark-Wills** [comment]
So, the above pic is with the `u8g2.drawStr(0,10,"Hello!");` commented out.

**Comment by olikraus** [comment]
yes, ... so... no pixel... right?

**Comment by olikraus** [comment]
ok, this "is" strange
let me see whether I can verify this

**Comment by Mark-Wills** [comment]
I'm just trying another test....

**Comment by Mark-Wills** [comment]
Okay, this shows the problem beautifully...
```c++
int x;

void loop(void) {
  u8g2.firstPage();
  do {
    //u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.setFont(u8g2_font_7x14B_tf);
    u8g2.drawPixel(x,20);
    u8g2.setCursor(10,10);
    u8g2.print(x);
  } while ( u8g2.nextPage() );
  delay(100);
  if(x++>128) x=0;
}
```
I'll see if I can upload a video... Might take a while...

**Comment by olikraus** [comment]
ok, i can reproduce the problem
![sam_5083](https://cloud.githubusercontent.com/assets/1084992/17633660/b7150f12-60ce-11e6-9998-66415c13c024.JPG)

**Comment by Mark-Wills** [comment]
Yeah, you got it. Here's a video:
[https://youtu.be/5wb4CEAcEBo](https://youtu.be/5wb4CEAcEBo)
It's unlisted.

**Comment by Mark-Wills** [comment]
So columns 0 to 7 are being copied into columns 120 to 127.

**Comment by olikraus** [comment]
yes exactly. Nice video

**Comment by nottledim** [comment]
On 08/12/16 20:00, olikraus wrote:
> yes exactly. Nice video
>
>
With that video do you see a rogue pixel at start 5 and 6 I think, placed incorrectly below the main line.

**Comment by Mark-Wills** [comment]
No, I'm not seeing that. Might just be a compression artefact on the video. I'm just seeing the pixel from 0 to 7 being copied to 120 to 127. I guess a modulo error ;-)

**Comment by olikraus** [comment]
... a programming error.... introduce with the last release...
It is now fixed:
https://github.com/olikraus/u8g2/commit/bb19b64e2d87a217e1e2aa41d38b746825e13cff#diff-e486df1652b0f6e504a83b07d15e02bc

**Comment by olikraus** [comment]
The fixed version is here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Download this zip and manually install this lib via IDE library manager (i think it is calld "add library as zip" or something like this)

Thank you so much for pointing out the bug. 
@nottledim: please excause the delay on this.

**Comment by Mark-Wills** [comment]
Wow! How's that for service ;-)

How do I get the latest files? I'm new to this Github thing...

**Comment by olikraus** [comment]
Just click on 
https://github.com/olikraus/U8g2_Arduino/archive/master.zip

**Comment by Mark-Wills** [comment]
Ah, I see you just posted. Thanks **SO** much for your work on this!

**Comment by olikraus** [comment]
Thank you for pointing out this bug!

**Comment by olikraus** [comment]
Maybe you can just confirm that this fix works for you.

**Comment by Mark-Wills** [comment]
Okay, confirmed working using the little "walking pixel" code above. Thanks again.

**Comment by olikraus** [comment]
Great. Then i will close this issue.

**Comment by nottledim** [comment]
On 08/12/16 20:16, olikraus wrote:
> The fixed version is here: 
> https://github.com/olikraus/U8g2_Arduino/archive/master.zip Download this
> zip and manually install this lib via IDE library manager (i think it is
> calld "add library as zip" or something like this)
> 
> Thank you so much for pointing out the bug. @nottledim
> <https://github.com/nottledim>: please excause the delay on this.
> 

I did the easy bit; thank you for fixing it (not to mention writing the
library in the first place).

**Comment by nottledim** [comment]
On 08/12/16 20:19, olikraus wrote:
> Maybe you can just confirm that this fix works for you.
> 

Yes, that works.  I just tried my app again and it works as expected.

Many thanks

**Comment by olikraus** [comment]
Excellent. Thanks for the feedback.
