### ISSUE TITLE
odd behavior with xor (color 2) over text

### ISSUE THREAD

**Issue by soundscu** [olikraus/u8g2#443]
Hi,

I'm using the u8g2 port to pic33 that rbresca helped with a few weeks ago (https://github.com/olikraus/u8g2/issues/376).

First, I write a simple 5-line text menu to the screen, white letters on black background.
Then I draw a color 2 (xor) box around the menu option I want to highlight.

If my declaration of u8g2 (this line: u8g2_t u8g;) is in the main loop as a local variable, all works perfectly.

But if I move that declaration out of main to be a global variable, then the xor draws as blocks in the outline of the characters, rather than complete readable letters.  There are no compile errors.  Either way,  looking in the watch window, I can see that the u8g2 structure is in the exact same memory location and is the same size.

What I think must be a valuable hint:
If I compile with the global declaration, and program the pic, the code them runs immediately with blocks in inverse.
If I cycle the power for a clean restart, it remains displaying blocks.
![with global u8g2 structure](https://user-images.githubusercontent.com/32483291/33518634-0a808cee-d766-11e7-86b2-8cd344b11c6a.jpg)

But if I then compile for the local declaration, and program the pic, the code runs immediately AND STILL SHOWS BLOCKS.
After I cycle the power for a clean restart, I then have correct display of inverse characters.
![with local u8g2 structure](https://user-images.githubusercontent.com/32483291/33518633-0a6b8baa-d766-11e7-9cdf-89aad7d6f3d7.jpg)

Of course, I need u8g2 to be global so that I can have libraries of menu writing functions in separate files, not in the Main loop.

Attached is my project, you'll see some notes in newmainXC16.c.  Also attached are a couple of photos.
[U8G2_PIC33.X.zip](https://github.com/olikraus/u8g2/files/1524056/U8G2_PIC33.X.zip)

Many thanks for any help you can offer to solve this!
Thanks,
Jim

**Comment by olikraus** [comment]
Did you set https://github.com/olikraus/u8g2/wiki/u8g2reference#setfontmode to transparent?

**Comment by soundscu** [comment]
That fixed it.  Many thanks!

In hopes of understanding this more deeply, why did declaring u8g2 locally seem to override the need to set fontmode to transparent?  Put another way, why is is necessary to setfontmode transparent only if I have declared u8g2 globally?

Thanks again.

**Comment by olikraus** [comment]
hmm... yes indeed. it is not correctly set during init phase.
