### ISSUE TITLE
Very long lines of text may still wrap

### ISSUE THREAD

**Issue by MattMatic** [olikraus/u8g2#446]
In testing the ProFont issues, I found that ProFont29 was producing an odd output. Looks like the line is so long that it's wrapping back and overwriting (I am drawing a white box around the text, then drawing the text with XOR mode).

The snapshot is the 160x104 display, with ProFont 10,11,15,17, and 22. The "EF" letters have been rendered over the "29". The "defABCD" are correctly hidden and not-rendered.

Trying to drill down and find where the issue is...
![lcd 2017-12-04 110434](https://user-images.githubusercontent.com/12079512/33549697-4ff9ad22-d8e3-11e7-92b6-a33bae161334.png)

**Comment by AnHardt** [comment]
The string for "22" is longer than 256 pixels.
Coordinates are 8 bit.
Values between 160 and 256 are clipped correctly.
Above 256 they appear as low numbers again -  8 bit overflow.

https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L159 ?

**Comment by MattMatic** [comment]
Aha! Perfect. Thank you 👍
