### ISSUE TITLE
Problem : U8G2_ST7920_128X64_2_SW_SPI u8g2

### ISSUE THREAD

**Issue by nachon99** [olikraus/u8g2#448]
thank you
https://youtu.be/BLShTEyVdh8
![24818923_1785513458156885_720666605_o](https://user-images.githubusercontent.com/33146781/33642510-e325d726-da6c-11e7-874a-ba44f055ee6a.jpg)

**Comment by olikraus** [comment]
bad connection? too long wires?

**Comment by olikraus** [comment]
no feedback, closing...
