### ISSUE TITLE
DrawUTF8 not working

### ISSUE THREAD

**Issue by Flole998** [olikraus/u8g2#449]
Hi,

I'm using this code to display a text containing an Umlaut. However, the umlaut is just skipped when displaying, so it is missing in the text.

```
u8g2.begin();
u8g2.clearBuffer();					// clear the internal memory
u8g2.setFont(u8g2_font_profont12_mr);	// choose a suitable font
u8g2.drawUTF8(15, 40, "Selbsttest läuft");	// write something to the internal memory
u8g2.sendBuffer();
```

Is this issue related to the font? The font from the example (u8x8_font_amstrad_cpc_extended_f) is creating an empty screen so I am not sure if all fonts have umlauts available. I am using U8G2_ST7920_128X64_F_8080 on a mega1284.

**Comment by olikraus** [comment]
You should always crosscheck the font pictures:
https://github.com/olikraus/u8g2/wiki/fntgrpprofont

These font pictures list all available gylphs. for u8g2_font_profont12_mr, there are no umlaut glyphs ("r" = reduced font size). You probably want to use u8g2_font_profont12_mf ("f" = full font size).


This is the "r" font from your code:
![https://github.com/olikraus/u8g2/wiki/fntpic/u8g2_font_profont12_mr.png](https://github.com/olikraus/u8g2/wiki/fntpic/u8g2_font_profont12_mr.png)

And I think, this is what you need:
![https://github.com/olikraus/u8g2/wiki/fntpic/u8g2_font_profont12_mf.png](https://github.com/olikraus/u8g2/wiki/fntpic/u8g2_font_profont12_mf.png)

**Comment by Flole998** [comment]
Thanks
