### ISSUE TITLE
add icon font

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#451]
https://github.com/stark/siji  --> siji.bdf

http://www.1001fonts.com/pixel-dingbats-7-font.html
Author style 7 has a lot of nice fonts: http://style-7.1001fonts.com/ 
http://www.styleseven.com/

**Comment by MattMatic** [comment]
Thanks for the link.
Conversion:
`bdfconv -f 1 -b 0 -m "57344-57974" -n Font_Icons -o icons.c siji.bdf`
(All the glyphs are in the upper Unicode U+E000 to U+E276)

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/wiki/fntgrpsiji
