### ISSUE TITLE
Strange drawFilledEllipse

### ISSUE THREAD

**Issue by v1993** [olikraus/u8g2#453]
Base code to reproduce:

    #include <U8g2lib.h>
    U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ 22, /* data=*/ 23);
    void setup() {
      // put your setup code here, to run once:
      u8g2.begin();
    }

    void loop() {
      // put your main code here, to run repeatedly:
      u8g2.clearBuffer();
      u8g2.drawFilledEllipse(30, 35, 22, 27, U8G2_DRAW_UPPER_LEFT | U8G2_DRAW_LOWER_LEFT);
      u8g2.sendBuffer();
      delay(2000);
      u8g2.clearBuffer();
      u8g2.drawFilledEllipse(30, 35, 23, 27, U8G2_DRAW_UPPER_LEFT | U8G2_DRAW_LOWER_LEFT);
      u8g2.sendBuffer();
      delay(2000);
    }

Video: http://vallua.ru/wp-content/uploads/2017/12/VID_20171210_223112.mp4

First code works OK, second produce bug.

**Comment by olikraus** [comment]
It is not a bug. Instead there is a integer overflow. You need to activate 16 bit mode (see FAQ).
