### ISSUE TITLE
userInterfaceSelectionList is a blocking procedure

### ISSUE THREAD

**Issue by Jacotheron** [olikraus/u8g2#459]
I am building a device which uses a few extra sensors and needs a small interface. The sensors include an RTC, Lux sensor and Temperature sensor, and other things connected to the processor is Bluetooth and a bunch of mosfets to turn different things on and off.

The idea is very simple, have both a Bluetooth Interface and a GUI to turn the mosfet outputs on and off.

For this I have first implemented the Bluetooth Interface, and it is working fine. I have now received the display and upon trying to use it (with the Selection List example code, plan is to work from the working example to create the required interface), I found that everything breaks:
Temperature sensor is unable to report the temperature with my specified interval, also the Lux sensor and RTC can't report their values. The Ble interface simply does nothing (since it does not communicate with the processor).

I have now opened the U8G2 library files to try to find the cause, and here is what I found:
File _u8x8_selection_list.c_, line number _154_:
`for(;;)`
 - this creates and endless loop until a Menu event happened (either a Select or Home). This causes all of my other code to not run in the required intervals.

How can I create a user interface (the select menu style with a separate home screen), without running blocking code (if the code takes a few millis to complete, it is fine)? Both Ble and GUI should be able to run in parallel.

I have written all my code to be non-blocking, and rather loop over to continue on a next loop than delay execution (everything uses the "Blink without delay" style timings). 

I am using an Adafruit Feather M0 Bluefruit, so I have interrupts on all exposed pins (I believe an interrupt system will be better). Are there any other U8g2 compatible libraries you can suggest?

**Comment by olikraus** [comment]
U8g2 is a graphics library. The user interface procedures are just for demonstration. They are especially not able to replace a proper menu system.
Usually a menu system builds on top of a graphics library. So you need both, a graphics lib (like u8g2) and a menu library.
