### ISSUE TITLE
Missing spaces after bdfconv 

### ISSUE THREAD

**Issue by fire1** [olikraus/u8g2#462]
This is not a bug in U8G2 library but... 
Somehow i destroy spaces in my custom font (no spaces between words)
i was using this command:
`bdfconv.exe -f 1 -m "32-1104,~403-899"  -n u8g_font_opel_ic_13 -o u8g_font_opel_ic_13.c OpelSansBold-13.bdf -v`

Any idea how to fix it  ?
Thanks!

**Comment by olikraus** [comment]
I am not sure about the ~ operator.
Maybe try "32-403,899-1104".

**Comment by fire1** [comment]
Ok in  "FontForge" space characters was marked as red, with opening and closing (without touching anything) edit option ... it FIXES this issue.
Thanks for time!

**Comment by olikraus** [comment]
:)

**Comment by fire1** [comment]
P.S. Your command excludes more characters ... so ... it is better than my! (don't know way)

**Comment by olikraus** [comment]
you mean "32-403,900-1104"? I think it is better to express what you want, than what you don't want ;-)
