### ISSUE TITLE
Hardware SPI unstable

### ISSUE THREAD

**Issue by mrSynaps** [olikraus/u8g2#463]
Hi,
I am using a Megatronics board with the ST7920 interface.  The software interface works just fine but the hardware interface is not stable. Is this a known issue? What can I do to prevent this. I really would like to use the hardware interface.

U8G2_ST7920_128X64_1_HW_SPI u8g2(U8G2_R0, 52); // not stable
U8G2_ST7920_128X64_1_SW_SPI u8g2(U8G2_R0, 52, 51, 56); // works fine

**Comment by olikraus** [comment]
ST7920 is very sensitive. How long are your wires? Did you solder the wiring?

**Comment by olikraus** [comment]
no response, closing...

**Comment by mrSynaps** [comment]
Uh yes we checked al that and that made it a little better. 
Can you give advice on another display which van be used in combination with hardware SPI, we really would like to free up the clock cycles
Switching to another display is at this stage no problem for us

**Comment by olikraus** [comment]
ST7565 based Displays are much more reliable.
