### ISSUE TITLE
advice on display with good SPI hardware support

### ISSUE THREAD

**Issue by mrSynaps** [olikraus/u8g2#470]
Hi,

This is not really an issue but a request for some advice or pointers in the right direction. In a previous issue you mentioned that the ST7920 SPI hardware connection is very sensitive, we really would like to free up the clock cycles and use the SPI Hardware support on the ATMega2560.
Can you give some advice on which displays are working fine with the SPI on chip

**Comment by olikraus** [comment]
Better use ST7565 based Displays.
Also Controller starting with UCxxxx are fine.

**Comment by mrSynaps** [comment]
thnxs :)
