### ISSUE TITLE
Element positioning

### ISSUE THREAD

**Issue by takeaweb** [olikraus/u8g2#477]
Hi, i need to center a text to some coordinates
for String there is getWidth, but if i print a variable?
ho can i get the width? There is an option to center an element (a string) to another element (a circle) ?
Thanks

**Comment by olikraus** [comment]
You have to convert the value of the variable to a string (e.g. with sprintf). Then calculate the width of the string and center the string.

**Comment by olikraus** [comment]
no further feedback...
