### ISSUE TITLE
Feature Request: SSD1673

### ISSUE THREAD

**Issue by PeterKietzmann** [olikraus/u8g2#480]
Are there any plans to port the SSD1673 display controller?

**Comment by olikraus** [comment]
Not at the moment. 

Reason is this: Adding a new LCD controller is not so complicated and can be done in a small amount of time even without having access to the device itself. E-paper devices are much more complicated and I will certainly fail with the implementation without having physical access to a E-paper device. The other problem is the ammount of time, required for the implementation.

Have a look here to get an idea on the discussions: https://github.com/olikraus/u8g2/issues/318

**Comment by PeterKietzmann** [comment]
Thanks for your fast response and to pointer.
