### ISSUE TITLE
Feature Request: Custom Menu Event Triggers

### ISSUE THREAD

**Issue by SimGas** [olikraus/u8g2#485]
Hi,

I haven't found a way of triggering menu events other than with single pins defined in the begin procedure.
So I assume, there is currently no other way achieving that. 

Specifically, I want to use a I2C port extender PCF8574 for triggering menu events like up, down, right, left, set and so on.

An idea would be to introduce another function setMenuEvent() which can be called in a interrupt service routine and executed next time the loop is executed.

Is there an easy way to creat such a function?

Thanks,
Simon

**Comment by olikraus** [comment]
I added the menu procedure as an example and not as a full feature menu system. Actually u8g2 is just a graphics library and I think it should be just this.

As an alternative, you could take the source and replace the event procedure with your custom code:
https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_message.c#L173
