### ISSUE TITLE
Issue using "drawStr"

### ISSUE THREAD

**Issue by wEPac** [olikraus/u8g2#488]
First, thanks a lot for this marvellous and fast driver, and all the job you did.

I was playing with it and fonts, I dont know if that s a real issue but I noticed something weird. Drawing a text with "drawStr" at the pos (0, y), the text was too long for the screen width, and the first character of the line became covered by what I suppose to be the characters from the truncated part of the text.

Using "print" does not produce the same artefact, the truncated text is just ignored.

Best regards.

**Comment by olikraus** [comment]
Will the problem vanish in 16Bit mode? I assume this is a 8 bit overflow.

**Comment by wEPac** [comment]
hehe... yes! I only work in 8Bit mode at the moment, using g8u2 as it comes with an Arduino Nano.

**Comment by olikraus** [comment]
ok, closing...
