### ISSUE TITLE
[IL3820] Waveshare 2.9inch_e-Paper drawing issues

### ISSUE THREAD

**Issue by petrkr** [olikraus/u8g2#495]
Hi,
I testing 2.9" e-Paper based on IL3820 and figured out some drawing issues. I tested library on OLED and it works fine, so I think there will be something regarding to e-paper one, I checked code, but I did not saw anything "at first good".

Problematic functions:
DrawFrame
DrawRBox
DrawDisc

Here are screenshost from GraphicsDemo sketch while using this constructor
`U8G2_IL3820_V2_296X128_F_4W_HW_SPI u8g2(U8G2_R0, /*cs=*/ D8, /* dc=*/ D2);`
_(I tested also without V2, and SW SPI). Also tested rotation R1 (much worst) and R2 (same, just 180 rotated)_

Tested platform:
MCU: ESP8266
SDK: 2.3.0
U8G2 lib: latest master (regarding to library version: 2.21.5)

Screens
![20180127_191455](https://user-images.githubusercontent.com/6428351/35475044-ed8fa012-0397-11e8-91cb-b48c17688da5.jpg)
![20180127_191647](https://user-images.githubusercontent.com/6428351/35475045-edaf7950-0397-11e8-8777-6d7486ffcd80.jpg)
![20180127_191659](https://user-images.githubusercontent.com/6428351/35475046-edca4af0-0397-11e8-9d7c-bc0f533549fe.jpg)
![20180127_191712](https://user-images.githubusercontent.com/6428351/35475047-ede5fac0-0397-11e8-8a56-0b76b9f293c8.jpg)
![20180127_191726](https://user-images.githubusercontent.com/6428351/35475048-ee0027ce-0397-11e8-8a08-6ad40767a471.jpg)

Regards
Petr

**Comment by petrkr** [comment]
Well...
my mistake, I missunderstood that note about `switching to 16-bit`. Also tried define that `U8G2_16BIT` in my sketch, but seems I need uncomment it in .h library, which I think is not so much good solution as I need to change library which I expect to be on all systems same (like if we are more developers). Can this be done some other way to control it from sketch code?

Petr

**Comment by olikraus** [comment]
I always wished that Arduino IDE would allow extra options. Almost all other IDEs known to me have this option to pass extra defines to the compiler. Well it is not there with the Arduino IDE, so then the .h file has to be modified. I could permanently define this macro, but then AVR code will be 5% larger.

**Comment by viveksoni95** [comment]
How to draw Bluetooth symbol on e-paper display ?

**Comment by olikraus** [comment]
see  #841
