### ISSUE TITLE
ra8835 128х128 not work?

### ISSUE THREAD

**Issue by githubrn** [olikraus/u8g2#496]
pls help, not work hello world.

`#include <Arduino.h>
#include <U8g2lib.h>
#include <SPI.h>
#include <Wire.h>

U8G2_RA8835_NHD_240X128_2_8080 u8g2(U8G2_R0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12); 

void setup(void) {
  u8g2.begin();
  
}

void loop(void) {
  u8g2.firstPage();
  do {
    u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.drawStr(0,24,"Hello World!");
  } while ( u8g2.nextPage() );
  delay(1000);
}`

![default](https://user-images.githubusercontent.com/35894816/35483422-ca4ae79a-0452-11e8-8892-7ad75db228ea.png)

wired:

+5V LCD pins: 3,4,18
gnd LCD pins:  2,19

[vl-ps-mgcs128128-07.pdf](https://github.com/olikraus/u8g2/files/1671174/vl-ps-mgcs128128-07.pdf)

**Comment by olikraus** [comment]
> +5V LCD pins: 3,4,18

According to the datasheet pins 4 and 18 need other voltage than 5V

**Comment by githubrn** [comment]
I am just learning.
please tell me the table for pin 4 and 18.

Cold cathode fluorescent lamps (CCFL) backlight. +12V through the inverter - it works. PCB inverter separately.

Thank you!

**Comment by olikraus** [comment]
> Cold cathode fluorescent lamps (CCFL) backlight. +12V through the inverter - it works.

Then the datasheet is wrong: Table 6 requests 235V.

According to datasheet pin 4 requires -17 V

**Comment by githubrn** [comment]
maybe option

![default](https://user-images.githubusercontent.com/35894816/35486144-e58ff0e0-047a-11e8-9d3f-4c5bb8604d60.png)
![default](https://user-images.githubusercontent.com/35894816/35486147-f3314050-047a-11e8-87e5-15cc7ed981fc.png)

it?
![default](https://user-images.githubusercontent.com/35894816/35486064-96aa994a-0479-11e8-9086-13cc61f98117.png)
why -17V?

**Comment by olikraus** [comment]
yes, should be +17V.

**Comment by githubrn** [comment]
Thank you.
ordered a voltage regulator.
I'll write a result later.

**Comment by olikraus** [comment]
feel free to reopen this issue for further discussion...
