### ISSUE TITLE
PCD8544 (nokia 5110) hardware spi with wemos d1 mini (esp8266)

### ISSUE THREAD

**Issue by muisje** [olikraus/u8g2#500]
Hey,

I'm trying out the GraphicsTest.ino but i'm having issues with getting hardware spi to work.

When i try software spi it works: 
U8G2_PCD8544_84X48_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ D5, /* data=*/ D7, /* cs=*/ D8, /* dc=*/ D6, /* reset=*/ D0); 

but this doesnt:
U8G2_PCD8544_84X48_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ D8, /* dc=*/ D6, /* reset=*/ D0); 		// Nokia 5110 Display

it will just flash a black screen. 

Am i doing something wrong here?

**Comment by olikraus** [comment]
HW SPI night have different out put lines

**Comment by olikraus** [comment]
no further response, closing...
