### ISSUE TITLE
add initialize option for redirecting display output

### ISSUE THREAD

**Issue by cyberman54** [olikraus/u8g2#504]
If programming for different type of boards with and without OLED display it would be great to have an option to call u8g2 / u8x8 with an constructor which does nothing. This is useful on boards without OLED display, driving them with the same code that also runs on board with OLED displays.

**Comment by cyberman54** [comment]
thanks!
should be implemented both for u8x8 and u8g2.

**Comment by olikraus** [comment]
u8x8_setup.c 
```
uint8_t u8x8_d_null_cb(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
```

u8g2_setup.c
```
void u8g2_Setup_null(u8g2_t *u8g2, const u8g2_cb_t *rotation, u8x8_msg_cb byte_cb, u8x8_msg_cb gpio_and_delay_cb)
```

**Comment by olikraus** [comment]
new devices:
```
U8X8_NULL u8x8;
U8G2_NULL u8g2(U8G2_R0);
```

some testing in the Arduino IDE required...

**Comment by cyberman54** [comment]
Could you release a new version with this feature to platformio lib?

**Comment by olikraus** [comment]
> Could you release a new version with this feature to platformio lib?

unfortunately no. I have no idea about platformio. But i will release u8g2 soon into the Arduino IDE.

**Comment by olikraus** [comment]
test ok...
