### ISSUE TITLE
cannot address 320x240 screen in U8G2_RA8835_320X240_1_8080 mode

### ISSUE THREAD

**Issue by phe78** [olikraus/u8g2#505]
Hello, I am using a RA8835 320xx240 screen with a 8080 interface (model reference https://www.buydisplay.com/default/5-7-inch-320x240-lcd-display-graphic-module-touch-panel-black-on-white ). It appears the adressable screen stays limited to a 240x240 window. Any attempt to adress X>240 is wrapped to zero. 
I am using an Arduino Nano and cannot use the Full buffer mode as the RAM amount is limited. 
Am I doing something wrong, or maybe there is a problem is the screen buffer management ?
thanks in advance for your feedbak
Philippe

**Comment by JamesGKent** [comment]
In the faq you'll find a bit about enabling 16 bit mode, you need to do that to address screens larger than 256 pixels

**Comment by phe78** [comment]
thanks for your quick response James. My display only supports 8-bit 8080 interfacing.

**Comment by olikraus** [comment]
You must enable U8g2 16 Bit. It has nothing to do with the interface. It just enables 16 bit arithmetics fo x and y coordinates.

**Comment by phe78** [comment]
thanks a lot. worked perfectly.
