### ISSUE TITLE
SSD1322 Support

### ISSUE THREAD

**Issue by Zborex** [olikraus/u8g2#527]
Hello would You like to implement support for ssd1322?
I'm looking for help in setting up an 2x ssd1322 oled 256x128 pix
I can provide You a support. I would like to use it in MBED

Regards

**Comment by Zborex** [comment]
edit:
Please close i found the solution in FAQ ;)

**Comment by olikraus** [comment]
What is your solution then? This display is probably not yet supported... But I think it could be done, based on one of the existing devices.

**Comment by Zborex** [comment]
I think i will use 2 256x64 while one rotated, i will let You know if it will work






On Wed, Feb 28, 2018 at 6:31 AM +0100, "olikraus" <notifications@github.com> wrote:












What is your solution then? This display is probably not yet supported... But I think it could be done, based on one of the existing devices.

**Comment by Zborex** [comment]
I worked today to try to solve it, but I have problems on setting up the display through the Clib, especially in making the uC specific code implementation for the Mbed software. I want to use lpc1768 with hardware SPI

**Comment by olikraus** [comment]
So you did follow the instructions form here? https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform
