### ISSUE TITLE
draw1x2string dose not appear to be implemented

### ISSUE THREAD

**Issue by derekchall** [olikraus/u8g2#537]
The draw1x2String method dose not appear to be implemented as in the documentation, draw2x2String works OK I have version 2.21.8 installed
Thanks

**Comment by olikraus** [comment]
oh...

will
```
u8x8_Draw1x2String(u8g2.getU8x8(), x, y, s);
```
work?

**Comment by olikraus** [comment]
Yes, I guess I missed that part.

**Comment by olikraus** [comment]
implemented
