### ISSUE TITLE
vertical line misaligned in SSD1322 on Arduino Due full-buffer mode.

### ISSUE THREAD

**Issue by tinyboxxx** [olikraus/u8g2#539]
thanks for your time.

![snipaste20180314_103813](https://user-images.githubusercontent.com/13427224/37380589-4c8b0372-2774-11e8-9c9d-83d6bc322cc8.jpg)
![snipaste20180314_103821](https://user-images.githubusercontent.com/13427224/37380602-5e157906-2774-11e8-9c34-34f36ff1b1c4.jpg)
![snipaste20180314_103833](https://user-images.githubusercontent.com/13427224/37380604-610cb1b0-2774-11e8-8b33-6093ac00357a.jpg)
![snipaste20180314_103841](https://user-images.githubusercontent.com/13427224/37380610-67cbd6fc-2774-11e8-9b4a-a954a14e0e57.jpg)

I use U8G2_SSD1322_NHD_256X64_F_4W_HW_SPI.

It seems is a problem with the width of the screen, it will move the left line to the end of the previous row.

FYI, if I run in page buffer mode, last few pixels will be lost. this is what I run fps, you can see right part is blank.
![snipaste20180314_110025](https://user-images.githubusercontent.com/13427224/37381218-efc5e398-2776-11e8-9a31-5d231f2f1d81.jpg)

**Comment by olikraus** [comment]
Did you activate 16 bit mode?

**Comment by tinyboxxx** [comment]
Thanks for your quick reply.
I didn't realize that a comment is an option, It works great now!
![image](https://user-images.githubusercontent.com/13427224/37415894-7bf3ea48-27e7-11e8-8823-7bc200442453.png)

Love your work! appreciated!

**Comment by olikraus** [comment]
Looks good!
