### ISSUE TITLE
bdf converersion, u8g2.

### ISSUE THREAD

**Issue by HuksBee** [olikraus/u8g2#54]
Hi Oliver,
I'm trying to use bdfconv.exe but I'm not getting success.
I do not really understand how to use it, I created my bdf file from
an existing source, and put in the bdf folder, hoping he would convert, and nothing happened.

**Comment by olikraus** [comment]
There is still no proper wiki page for bdfconv. 

As written in the PM, it should be like this:
./bdfconv -v -f 1 -m '32-255' myfont.bdf -o myfont.c -n myfont

This will generate the c file myfont.c (where you can copy the content into your ino file) with the name myfont. "-f 1" just creates u8g2 fonts. -m '32-255' specifies the unicode range which should be take from the bdf file.
