### ISSUE TITLE
Support for WiseChip 0.42 OLED SH1106

### ISSUE THREAD

**Issue by feistyz** [olikraus/u8g2#547]
Hi,

Would it be possible to add support for the [WiseChip 0.42 SH1106 display](http://www.wisechip.com.tw/en/product-549063/0-42-inch-OLED-Display.html)?

I can get it mostly working with the generic U8G2_SH1106_128X64_NONAME_F_4W_HW_SPI class except for having the coordinate system be in the right place. Hopefully, this would be a simple addition.

Thanks!

**Comment by olikraus** [comment]
You have a datasheet? Picture of HelloWorld Example?
Are you sure it is SH1106?

**Comment by feistyz** [comment]
Yes, it's the SH1106. Do you need the datasheet for the display or sh1106? The HelloWorld Example is off the screen and therefore doesn't show but the graphics test works. Here are some photos:

![imag1776](https://user-images.githubusercontent.com/10438760/37866938-90fdcfc6-2f4e-11e8-940b-d0c2c6973e3a.jpg)
![imag1778](https://user-images.githubusercontent.com/10438760/37866939-9112ea96-2f4e-11e8-8775-d4b5cf15c3d2.jpg)
![imag1779](https://user-images.githubusercontent.com/10438760/37866940-9129b2c6-2f4e-11e8-924e-0f6c6bebd09f.jpg)

**Comment by olikraus** [comment]
The datasheet of the display. It should explain the offset.

**Comment by feistyz** [comment]
Here you go
[WiseChip 0.42.pdf](https://github.com/olikraus/u8g2/files/1844656/WiseChip.0.42.pdf)

**Comment by olikraus** [comment]
ok, from page 2:
y: 12 to 51 (40)
x: 30 to 101 (72)

page 14: 
display offset 0x0d3 0x0c

**Comment by feistyz** [comment]
That seems right based on what I am visually seeing. 

I am not as familiar with the library internals but can I plug these values into the 128x64 code and see if it works or do you need to generate a new set of classes?

**Comment by olikraus** [comment]
I will generate a new class soon.

**Comment by feistyz** [comment]
Thanks much!

**Comment by olikraus** [comment]
new constructor will be: U8G2_SH1106_72X40_WISE_1_4W_HW_SPI

**Comment by feistyz** [comment]
That was fast. Thanks!

So the width is correct but the height is wrong. See hello world below. Only 8 rows are visible.
![imag1786](https://user-images.githubusercontent.com/10438760/37869914-a44b1d74-2f7e-11e8-9045-3cfd312fa964.jpg)

**Comment by olikraus** [comment]
Strange. Can you send the complete code for this example?
What about other examples? Can you test u8x8 example? Will it work?

**Comment by feistyz** [comment]
I take it back. My mistake. I was running full buffer examples instead of page examples. When I run the page examples Hello World. Here is what it and the Flip example look like:


![imag1798](https://user-images.githubusercontent.com/10438760/37872178-05bcd290-2fb7-11e8-8c51-9c236f17c74e.jpg)
![imag1799](https://user-images.githubusercontent.com/10438760/37872183-0a7c8bcc-2fb7-11e8-83f4-7abf6effe566.jpg)
![imag1800](https://user-images.githubusercontent.com/10438760/37872184-0a929368-2fb7-11e8-95a8-d05b5c499be9.jpg)
![imag1801](https://user-images.githubusercontent.com/10438760/37872185-0aa81de6-2fb7-11e8-85ff-15cd6c37e695.jpg)
![imag1802](https://user-images.githubusercontent.com/10438760/37872186-0abdb93a-2fb7-11e8-97d0-d40e2139e5e8.jpg)

**Comment by feistyz** [comment]
BTW, Is it possible to have it be a full buffer?

Here is a video of the flip app. Might be easier to see what it is doing. 
[VIDEO0452.zip](https://github.com/olikraus/u8g2/files/1845074/VIDEO0452.zip)

**Comment by olikraus** [comment]
> BTW, Is it possible to have it be a full buffer?

It should be there and working.

> Here is a video of the flip app. Might be easier to see what it is doing.

I will have a look, but I assume it is the y offset in flip mode 1 which is still not correct. 

I have created a new release for download: 2.22.7 
Please download from here: https://github.com/olikraus/U8g2_Arduino

If 2.22.7 is still incorrect, can you locate file u8x8_d_sh1106_72x40.c on your hard disk and modify the offset 24 to something else:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_sh1106_72x40.c#L102

What will be the correct value for your display?

**Comment by olikraus** [comment]
After seening your video, maybe the offset should 0 instead of 24... Hope you can modify the code to figure out the correct offset in flip mode 1.

**Comment by feistyz** [comment]
Sorry for the delay. 
2.22.7 with 24 didn't work. 
Zero for the offset didn't work either.

Trial and error yields either -12 or 52.

Here are the videos (names correspond to offsets):
[flip.zip](https://github.com/olikraus/u8g2/files/1846331/flip.zip)

**Comment by olikraus** [comment]
Thanks, looks good. I have create beta 2.22.8 with value 52.

**Comment by feistyz** [comment]
Thanks for adding the display!

**Comment by olikraus** [comment]
No problem
