### ISSUE TITLE
information missing from u8g2reference wiki page

### ISSUE THREAD

**Issue by mikekgr** [olikraus/u8g2#557]
Dear Sirs, Dear @olikraus 
I am trying to learn and then to use this very very good library ( thanks for your excellent work )  and studying the wiki, more precisely the url: 
https://github.com/olikraus/u8g2/wiki/u8g2reference
There, I can not find commands like getDisplayHeight   getMaxCharHeight etc that there are in the examples like Shennong.ino but not in the wiki
Please try to have documentation without missing items.

Thanks and Best Regards,
Mike Kranidis

**Comment by olikraus** [comment]
good point. Will add this.

**Comment by mikekgr** [comment]
thanks a lot Sir for your fast reaction to this documentation inconsistency problem. Keep the fine work!

**Comment by olikraus** [comment]
I leave this open, until i did the change to the wiki

**Comment by olikraus** [comment]
getDisplayHeight/Width is done...

**Comment by mikekgr** [comment]
Thanks a lot hard worker @olikraus  !

**Comment by olikraus** [comment]
:-)

Documented https://github.com/olikraus/u8g2/wiki/u8g2reference#getmaxcharheight

Also getMaxCharWidth is there, but the code will be delayed until release of 2.22.

**Comment by matthijskooijman** [comment]
@olikraus, seems the code for getMaxCharWidth is still not present, but it is documented. What's the plan here?

**Comment by olikraus** [comment]
It is implemented and released with version 2.22.
https://github.com/olikraus/u8g2/blob/master/cppsrc/U8g2lib.h#L302
Current version is 2.23, this function should be available since almost a half year.
Which u8g2 version do you use?

**Comment by matthijskooijman** [comment]
Hm, seems I was wrong then. I used the github search which showed no code results, so I was either wrong to trust github search, or perhaps I made a typo. So never mind, sorry for the noise :-)

**Comment by olikraus** [comment]
no problem
