### ISSUE TITLE
Cypress psoc4 SH1106 OLED Setup Problem...

### ISSUE THREAD

**Issue by skyldh89325** [olikraus/u8g2#559]
Hello !

The psoc4 tool works on sh1106 OLED using u8g2 lib.

However, if you compile, overflow causes the u8g2 setting itself.

To solve this problem, we changed the heap size and stack size on the system, and because we read the u8g2 wiki content and Qna contents, we could not solve this problem.

I'd appreciate it if you could tell me how to fix this.

**Comment by olikraus** [comment]
I do not know anything about psoc4. Anyone else?
