### ISSUE TITLE
Possible to implement vertical screen scrolling in u8g2 mode?

### ISSUE THREAD

**Issue by mikekgr** [olikraus/u8g2#560]
Dear Sirs,
this is not a problem but more a question for how can do this.
In one of my projects, using ESP32 and OLED 128X64, I want to implement vertical scrolling. More precisely I want to "simulate" the behavior of a LCD screen that initially when you write something ( printing ) you started at the top of screen ( home: 0,0 ) and all new writings goes down line by line, till you fill all the screen, then, a new line forces all upper lines to go one line up to give the required space for the new and for all forthcoming new lines.
What do you think, what is the best way to achieve it.
Please take into consideration that my OLED with the given mono-spaced font has 25 characters per line and 8 lines per screen.

Thanks and Best Regards,
Mike Kranidis

**Comment by olikraus** [comment]
This is more a programming question. Usual approach is to store all lines on the screen in a buffer. Then you can redraw all lines at any time. If a new line is added, you just move all lines up, discarding the first line and then do a redraw.

**Comment by mikekgr** [comment]
thanks a lot!

**Comment by mikekgr** [comment]
Dear @olikraus ,
please consider to implement vertical scrolling to your excellent library, Although there is another library for the SSD1306 that has implemented it, I certainly prefer yours, that's why I kindly asking you to consider it.
Thanks and Best Regards,
Mike Kranidis

**Comment by olikraus** [comment]
Is this what you want? 
https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_full_buffer/Shennong/Shennong.ino

**Comment by mikekgr** [comment]
Yes, this example is in the direction that I looking for. But need improvements like to have a unique method to print any string and not only string arrays, also to auto calculate the screen length, lines per screen etc based on the selected font and screen "real estate". Doing this at the end, we will have a fantastic way to implement what Serial.print does but to OLED display. Fantastic help for stand alone debugging etc etc.
Thanks for your time and help.

**Comment by olikraus** [comment]
ok, like Serial.print. But still, it is something, that builds on top of a graphics lib, not something which should be part of a graphics lib. So, I could create an example for u8x8 API.

**Comment by mikekgr** [comment]
That will be fine. Please keep me informed when you do to test and let you know.
Thanks a lot for your fast and fine support.

**Comment by olikraus** [comment]
I started to document this new feature: https://github.com/olikraus/u8g2/wiki/u8logreference

**Comment by olikraus** [comment]
Documentation done

**Comment by mikekgr** [comment]
Dear @olikraus  first of all I thank you for implemented this requested by me feature and the documentation. You are really a very devoted and hard worker full of programming capabilities engineer! 
Best Regards,
Mike Kranidis

**Comment by olikraus** [comment]
:-)

**Comment by mikekgr** [comment]
@olikraus may I ask you when this ( these ) improvement(s) will be integrated to your Arduino library U8g2_Arduino ? As I think, the correct way is to get U8g2_Arduino library for Arduino. Am I right? Thanks!

**Comment by olikraus** [comment]
You an download beta 2.22.16 from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip

Install the zip file via your Arduino IDE (add zip library).

**Comment by mikekgr** [comment]
@olikraus THANKS
