### ISSUE TITLE
cypress i2c sleep I'll ask you a question!

### ISSUE THREAD

**Issue by OfnyaHoo** [olikraus/u8g2#562]
I have a question. I am using cypress cy8c4248 mcu. Connecting i2c to one component as shown below. mems module and an OLED (U8G2) module, the i2c_sleep () / OLED_EN_Wrtie (0) call does not go into the SLEEP routine. There is no problem when using only MEMS module. However, OLED module does not shut down properly when only SLEEP logic is configured by configuring only OLED module.

![kakaotalk_20180406_113806899](https://user-images.githubusercontent.com/13115842/38402047-87138b5e-3994-11e8-9221-f813e6925c0a.jpg)

![20180406_121851](https://user-images.githubusercontent.com/13115842/38402076-b396c092-3994-11e8-9c7b-8ad9b1623f71.png)

Is there a function for I2C Deep Sleep?

Below is the OLED setting / writing source code. Thank you for your reference.

[source code]

u8g2_t u8g2;
u8x8_t u8x8;
uint8_t u8x8_byte_hw_i2c(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr);
uint8_t psoc_gpio_and_delay_cb(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr);

extern const uint8_t u8g2_font_t0_22b_tf[] U8G2_FONT_SECTION("u8g2_font_t0_22b_tf") ;
extern const uint8_t u8g2_font_9x15B_tn[] U8G2_FONT_SECTION("u8g2_font_9x15B_tn");
extern const uint8_t u8g2_font_7x13_tr[] U8G2_FONT_SECTION("u8g2_font_7x13_tr");
extern const uint8_t u8x8_font_5x8_f[] U8X8_FONT_SECTION("u8x8_font_5x8_f");

uint8_t tiles_01[] = {0x01,0x03,0x07,0xff,0xff,0x07,0x03,0x01};
uint8_t battery_tiles_02[] = {0xff,0x81,0xbd,0xbd,0x81,0xbd,0xbd,0x81};    

uint8_t data[11];

Print_OLED_t OLED_PRINT;

void OLED_INIT(void)
{   
    
    // u8g2 Init
    u8g2_Setup_sh1106_i2c_128x64_noname_1(&u8g2,U8G2_R0, u8x8_byte_hw_i2c,psoc_gpio_and_delay_cb);
    u8g2_InitDisplay(&u8g2);
    u8g2_SetPowerSave(&u8g2, 0);
    
    // u8x8 Init
    #if 0
    u8x8_Setup(&u8x8, u8x8_d_sh1106_128x64_noname,u8x8_cad_ssd13xx_i2c,u8x8_byte_hw_i2c,psoc_gpio_and_delay_cb);
    u8x8_InitDisplay(&u8x8);
    u8x8_SetPowerSave(&u8x8, 0);
    #endif 
 }   

void oled_u8x8_display(void)
{
    u8x8_DrawTile(&u8x8,0,0,1,tiles_01);
    u8x8_DrawTile(&u8x8,1,0,1,tiles_02);
    
    u8x8_SetFont(&u8x8, u8x8_font_5x8_f);
    u8x8_DrawString(&u8x8, 11, 0, "B");  //  BLE CONNECT
      
    u8x8_DrawTile(&u8x8,14,0,1,battery_tiles_01);
    u8x8_DrawTile(&u8x8,15,0,1,battery_tiles_02);
}

void OLED_U8G2_DISPLAY(void)
{
    u8g2_FirstPage(&u8g2);
    do
    {
        draw(&u8g2);
    } 
    while( u8g2_NextPage(&u8g2));
}

void draw(u8g2_t *u8g2) 
{

    switch(OLED_PRINT)
    {
        case ACTIVATED :
        
        u8g2_SetFontMode(u8g2,1);
        u8g2_SetFontDirection(u8g2,0);
        u8g2_SetFont(u8g2,u8g2_font_t0_22b_tf);
        
        u8g2_DrawStr(u8g2,12,35,"ACTIVATED");
        
        u8g2_DrawStr(u8g2,23,60,hh1_Buffer);
        u8g2_DrawStr(u8g2,33,60,hh2_Buffer);
        u8g2_DrawStr(u8g2,43,57,":");
        u8g2_DrawStr(u8g2,53,60,mm1_Buffer);
        u8g2_DrawStr(u8g2,63,60,mm2_Buffer);
        u8g2_DrawStr(u8g2,73,57,":");
        u8g2_DrawStr(u8g2,83,60,ss1_Buffer);
        u8g2_DrawStr(u8g2,93,60,ss2_Buffer);
       
        oled_u8x8_display();
        break;
    }
}

void OLED_ON(void)
{   
    u8g2_SetPowerSave(&u8g2, 0);
    //u8x8_SetPowerSave(&u8x8, 0);
}   

void OLED_OFF(void)
{   
    u8g2_SetPowerSave(&u8g2, 1);
    u8x8_SetPowerSave(&u8x8, 1);
}   

uint8_t u8x8_byte_hw_i2c(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
    #ifdef DEBUG_UART
    char buff[20];
    #endif
    uint8_t *data;
    
    switch(msg)
    {   
        
        case U8X8_MSG_BYTE_SEND:
            data = (uint8_t *)arg_ptr;
            while( arg_int > 0 )
            {
                #ifdef DEBUG_UART
                sprintf(buff,"%x\n",*data);
                UART_UartPutString(buff);
                #endif
                (void)I2C_I2CMasterWriteByte(*data); // No Error Checking..
  	            data++;
	            arg_int--;
            }
        break;
      
        case U8X8_MSG_BYTE_INIT: // Using the HW block you dont need to set 1/1
        break;
        case U8X8_MSG_BYTE_SET_DC:
        break;
        case U8X8_MSG_BYTE_START_TRANSFER:
            (void)I2C_I2CMasterSendStart(u8x8_GetI2CAddress(u8x8)>>1,I2C_I2C_WRITE_XFER_MODE); // no Error Checking
            //(void)I2C_I2CMasterSendStart(0x78,I2C_I2C_WRITE_XFER_MODE); // no Error Checking
         break;
        
        case U8X8_MSG_BYTE_END_TRANSFER:
            (void)I2C_I2CMasterSendStop(); // no error checking
        break;
    
        default:
            return 0;
         
    }
    
    return 1;
}

uint8_t psoc_gpio_and_delay_cb(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
    (void)u8x8;
    (void)arg_ptr;
    switch(msg)
    {
        case U8X8_MSG_GPIO_AND_DELAY_INIT: // for now who cares?
        break;
        case U8X8_MSG_DELAY_MILLI:
            CyDelay(arg_int);
        break;
        case U8X8_MSG_DELAY_10MICRO:
            CyDelayUs(10);
        break;
        case U8X8_MSG_DELAY_100NANO:
            CyDelayCycles((CYDEV_BCLK__SYSCLK__HZ/1000000) * 100 - 16); //PSoC system reference guide says ~16 extra cycles 
        break;
        /*    - My Display has only I2C... which I have implemented in HW
         * If you want to use a software interface or have these pins then you 
         * need to read and write them
        case U8X8_MSG_GPIO_SPI_CLOCK:
        case U8X8_MSG_GPIO_SPI_DATA:
        case U8X8_MSG_GPIO_CS:
        case U8X8_MSG_GPIO_DC:
        case U8X8_MSG_GPIO_RESET:
        case U8X8_MSG_GPIO_SPI_CLOCK:
        case U8X8_MSG_GPIO_SPI_DATA:		
        case U8X8_MSG_GPIO_D0:    
        case U8X8_MSG_GPIO_D1:			
        case U8X8_MSG_GPIO_D2:		
        case U8X8_MSG_GPIO_D3:		
        case U8X8_MSG_GPIO_D4:	
        case U8X8_MSG_GPIO_D5:	
        case U8X8_MSG_GPIO_D6:	
        case U8X8_MSG_GPIO_D7:
        case U8X8_MSG_GPIO_E: 	
        case U8X8_MSG_GPIO_I2C_CLOCK:
        case U8X8_MSG_GPIO_I2C_DATA:
        break;  */
    }
    return 1;
}

**Comment by olikraus** [comment]
hmm.. my knowledge on your system is probably too less to answer this question.
