### ISSUE TITLE
u8g2 not work with TinyGPS++

### ISSUE THREAD

**Issue by firatkaya7** [olikraus/u8g2#564]
Hello i trying see gps time on oled but not work. Always see 00:00. 
I think overlap baudrates.
My code:
#include <Arduino.h>
#include <U8g2lib.h>

#ifdef U8X8_HAVE_HW_SPI
#include <SPI.h>
#endif
#ifdef U8X8_HAVE_HW_I2C
#include <Wire.h>
#endif

#include <TinyGPS++.h>
#include <SoftwareSerial.h>
U8G2_SSD1306_128X64_NONAME_1_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);

TinyGPSPlus gpsacs;

// The serial connection to the GPS device
SoftwareSerial ss(4, 3);

void setup(void) {
  Serial.begin(9600);
  ss.begin(9600);
  u8g2.begin();
}

void loop(void) {
  Serial.println("hey");
  if(ss.available() > 0){
    if (gpsacs.encode(ss.read())){
      if (gpsacs.time.isValid()){
        Serial.println(gpsacs.time.hour());
      }
    }
  }
  
  u8g2.setFont(u8g2_font_ncenB14_tr);
  u8g2.firstPage();
  do {
    u8g2.setCursor(0, 20);
  if(ss.available() > 0){
    if (gpsacs.encode(ss.read())){
      if (gpsacs.time.isValid()){
        u8g2.print(gpsacs.time.hour());
      }
    }
  }
    
  } while ( u8g2.nextPage() );
  delay(1000);
}

**Comment by olikraus** [comment]
gpsacs.time.hour()  should be called outside the next page loop and assigned to a variable. Then print the content of that variable.

**Comment by olikraus** [comment]
no further response, closing...
