### ISSUE TITLE
Caracter "°" problem

### ISSUE THREAD

**Issue by matushromada** [olikraus/u8g2#565]
Hello, thanks for the excellent library. I've got strange behavior. When using the method u8g2.print with character "°" used for Clesia marking, I got character "A" on the display. With the older library U8GLIB I got "°A" on the display. Maybe I'm missing something, but didn't find anything about it in the docs. Thanks!

**Comment by olikraus** [comment]
Did you activate Utf8 mode for print?

**Comment by olikraus** [comment]
no further response... closing...

**Comment by olikraus** [comment]
Sure: https://github.com/olikraus/u8g2/wiki/u8g2reference#enableutf8print

**Comment by matushromada** [comment]
Now I see, the GitHub search wasn't going as good as expected. Was something similar present in u8glib as I'm using it because of HW compatibility issues? Or how should I print this character using u8glib. Thanks in advance for any hint.

**Comment by olikraus** [comment]
The u8glib fonts are restricted to 256 chars. So need to look at the font overview, figure out a glyph, which looks most similar to "°" and derive the hex code for it. Then use print("\xf8")... assuming that hex f8 is the position of the ° in the u8glib font.

One of the key features of u8g2 had been the introduction of UTF8 to simplify this task.

**Comment by olikraus** [comment]
Example: If you take this page:
https://github.com/olikraus/u8glib/wiki/fontgroupadobex11

look at u8g_font_courB10, then °  is at hex b0. So just use u8g.print("\xb0");
