### ISSUE TITLE
Only soft-i2c on d-duino (NodeMCU based)

### ISSUE THREAD

**Issue by TomTheDragon** [olikraus/u8g2#572]
Hi,

i played around a little and finally got the 128x64 SSD1306 oled display to run on my d-duino. But only in software mode, which is super slow. I know that it could do better since i tested an other library before.

**Comment by olikraus** [comment]
u8g2 includes a hardware SPI device, but I do not know much about NodeMCU. Maybe ask in some NodeMCU forum how to use hardware SPI.

**Comment by TomTheDragon** [comment]
I was talking about i2c, not spi and i know that it can do "much" faster then it did on my tests.

**Comment by olikraus** [comment]
oh, ok, but same is true for I2C. You have to connect to the I2C pins, which i do not know on your target system.

**Comment by TomTheDragon** [comment]
The screen is directly on the board, so its always connected to D1 and D2
http://dong-sen.com/wp-content/uploads/2016/02/D-duino.png

I was using "ESP8266 OLED SSD1306" before, it worked really well and fast. But it cant do things like polygons, so wanted to give u8g2 a try.

**Comment by olikraus** [comment]
Did you try HW SPI with HW Pin Remapping?

```
U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, U8X8_PIN_NONE , D2, D1);
```
or maybe
```
U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, U8X8_PIN_NONE , 4, 5);
```

**Comment by olikraus** [comment]
closing this for now...

**Comment by vijju27** [comment]
I made a pong game using u8g2 library on nodemcu using hardware i2c. My OLED display has sh1106 though.
It works like a charm for me.
Refresh rate is awesome.

**Comment by olikraus** [comment]
Sounds good, thanks for the feedback. Even I think HW I2C should work without problem.
