### ISSUE TITLE
SSD1322_256_64 DrawFrame & DrawFrame  issue 

### ISSUE THREAD

**Issue by alxumukus** [olikraus/u8g2#574]
it seems u8g2_DrawHVLine(u8g2, x, y, len, 1);  does not work .
u8g2.drawFrame(0,0,200,60);
look's like 
![2018-04-13 19 30 08](https://user-images.githubusercontent.com/38358742/38746782-37bea968-3f51-11e8-8784-9681a9e37d75.jpg)

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L159

**Comment by alxumukus** [comment]
sorry :(
my mistake with configuration after library update :(

**Comment by olikraus** [comment]
no problem ;-)
