### ISSUE TITLE
Support for LX-12864P1(LX-12864N8) LCD with ST7565R driver

### ISSUE THREAD

**Issue by IMAN4K** [olikraus/u8g2#576]
Hi @olikraus 
I'm thinking to add support for these kind of light-weight LCDs with `ST7565R` driver:

![-glcd-64128- - - -st7565r](https://user-images.githubusercontent.com/16017595/38776692-4362af98-40b0-11e8-8c7f-442563f949b2.jpg)
These are available shots for pinout and connection:

![tb211wuatamykjjszfgxxb ffxa_ 3300052663](https://user-images.githubusercontent.com/16017595/38776733-0efec178-40b1-11e8-8485-a3f8f16559e7.jpg)
![tb2g3ryifxxxxx9xpxxxxxxxxxx_ 675598918](https://user-images.githubusercontent.com/16017595/38776722-d2d41edc-40b0-11e8-9987-edd7339c1f35.jpg)
![photo_2018-04-15_12-38-15](https://user-images.githubusercontent.com/16017595/38776723-d5563168-40b0-11e8-9e88-e0e8b4d3a440.jpg)

Assuming `D6` as `clock`, `D7` as `data` and `CS` as `chip select` i choose this constructor:
` U8G2_ST7565_64128N_F_3W_SW_SPI(const u8g2_cb_t *rotation, uint8_t clock, uint8_t data, uint8_t cs, uint8_t reset = U8X8_PIN_NONE)`
but no drawing result!

Regards.
IMAN.

**Comment by olikraus** [comment]
You must
 * connect A0 (which is named "dc" in u8g2) to a GPIO line
 * connect reset line to a GPIO output
 * use a 4-wire SPI constructor

**Comment by IMAN4K** [comment]
Don't know what's wrong with this !?

![photo_2018-04-15_15-22-12](https://user-images.githubusercontent.com/16017595/38777661-cf619c6a-40c0-11e8-8d83-86361afc9ca4.jpg)

I'v tried all `ST7565_*_F_4W_SW_SPI` constructors and the shot is from `U8G2_ST7565_64128N_F_4W_SW_SPI`

**Comment by olikraus** [comment]
This already looks quite good. There is nothing wrong with your display, Just the internal memory architecture is different.

So you have tested the other constructors, like this person:
https://github.com/olikraus/u8g2/issues/440

Did you also test the `U8G2_ST7565_LM6059_F_4W_SW_SPI`? If not, can you send me a picture of the result with this display?

**Comment by IMAN4K** [comment]
`U8G2_ST7565_LM6059_F_4W_SW_SPI` AND `U8G2_NT7534_TG12864R_F_4W_SW_SPI` both seems working but maybe we've back light problem!

![photo_2018-04-15_18-15-32](https://user-images.githubusercontent.com/16017595/38779110-050aad80-40d9-11e8-80e9-dd7b40eff6ed.jpg)

**Comment by IMAN4K** [comment]
The results with different constructors.
`U8G2_ST7565_LM6059_F_4W_SW_SPI`:

![photo_2018-04-15_18-40-15](https://user-images.githubusercontent.com/16017595/38779365-75fc9b18-40dc-11e8-98d1-67f7d8480bce.jpg)

`U8G2_NT7534_TG12864R_F_4W_SW_SPI`:

![photo_2018-04-15_18-42-52](https://user-images.githubusercontent.com/16017595/38779389-d5296828-40dc-11e8-8233-9ed4992aaf04.jpg)

`U8G2_ST7565_64128N_F_4W_SW_SPI`:

![photo_2018-04-15_18-44-33](https://user-images.githubusercontent.com/16017595/38779396-0e6e57ba-40dd-11e8-884f-45e9099140fa.jpg)

`U8G2_ST7565_ZOLEN_128X64_F_4W_SW_SPI`:

![photo_2018-04-15_18-52-35](https://user-images.githubusercontent.com/16017595/38779473-2e4ad616-40de-11e8-9808-11ace161045e.jpg)

`U8G2_ST7565_ERC12864_F_4W_SW_SPI`:

![photo_2018-04-15_18-58-29](https://user-images.githubusercontent.com/16017595/38779533-022b7bde-40df-11e8-9557-ed3429abc2c1.jpg)

`U8G2_ST7565_EA_DOGM128_F_4W_SW_SPI`:

![photo_2018-04-15_19-07-08](https://user-images.githubusercontent.com/16017595/38779626-3679dd76-40e0-11e8-8eb0-e936382709f2.jpg)

`U8G2_ST7565_NHD_C12864_F_4W_SW_SPI` same as `U8G2_ST7565_ZOLEN_128X64_F_4W_SW_SPI`

Do you have any idea why changing constructors also change pixels to black like the first picture ?

**Comment by olikraus** [comment]
> Do you have any idea why changing constructors also change pixels to black like the first picture ?

This is simple: The contrast needs to be adjusted.
See, it is like this: Your GLCD has two main components: The ST7565 controller and the Liquid Crystal itself. These two things can be connected in a different way, which results in a different memory architecture. Moreover the Liquid Crystal itself has different characteristics. Some need 8V to operate others need 10V others only 6V. And also the timing requirements are different. All in all there are hundreds of different types of ST7565 displays, and we have to figure out what exactly is needed for your liquid crystal. 

My suggestion is to go forward with the `U8G2_ST7565_LM6059_F_4W_SW_SPI`, which looks most promising (because the memory architecture seems to be correct). Now use u8g2.setContrast() to choose a different contrast value. Current default is the value 24, so I would start to try lower values and see whether this improves the picture. Try  `u8g2.setContrast(20)` or `u8g2.setContrast(16)`. Finally you have to test several values, until you find the best one.

**Comment by olikraus** [comment]
For the `U8G2_ST7565_LM6059_F_4W_SW_SPI`:
How will u8g2.setContrast(80) look like?

**Comment by IMAN4K** [comment]
Using `U8G2_ST7565_LM6059_F_4W_SW_SPI` at contrast `80`:

![photo_2018-04-16_00-54-33](https://user-images.githubusercontent.com/16017595/38782956-dc791dd8-4110-11e8-9b2e-f62c1709f23f.jpg)

**Comment by olikraus** [comment]
ok, what about smaller values? like 60 or 40?
Will it change? Will it be better?

**Comment by IMAN4K** [comment]
For value 45:

![photo_2018-04-16_09-58-59](https://user-images.githubusercontent.com/16017595/38791420-d23baa9c-415c-11e8-955b-98262249944c.jpg)

and 15:

![photo_2018-04-16_09-59-54](https://user-images.githubusercontent.com/16017595/38791431-ee691380-415c-11e8-9cf3-e04167527571.jpg)

There is no improvement of changing contrast at all!
Unfortunately i couldn't find any datasheet for the  `LX-12864P1` or `LX-12864N8` module, only for `ST7565R` :(

**Comment by olikraus** [comment]
very strange. There should be some improvement.

ok, let us try a different approach: Please locate file u8x8_d_st7565.c on your hard disk

Then goto line 646:

https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_st7565.c#L646

You should see the following:
```
  U8X8_CA(0x0f8, 0x000),		/* set booster ratio to 4x (ST7567 feature) */
  U8X8_C(0x027),		                /* set V0 voltage resistor ratio to max  */
U8X8_CA(0x081, 0x018), /* set contrast, contrast value, EA default: 0x016 */
```
Change this to 
```
  U8X8_CA(0x0f8, 0x000),		/* set booster ratio to 4x (ST7567 feature) */
  U8X8_C(0x027),		                /* set V0 voltage resistor ratio to max  */
U8X8_CA(0x081, 0x01e), /* set contrast, contrast value, EA default: 0x016 */
```

**Comment by IMAN4K** [comment]
Yeah it's working.
I updated lib to `v.2.20.13` and changed `u8x8_d_st7565.c(644)`
Half box drawing with contrast `5`:

![c5](https://user-images.githubusercontent.com/16017595/38797263-2e04fafc-4173-11e8-8a35-583fbf594700.jpg)

and contrast `24`:

![c24](https://user-images.githubusercontent.com/16017595/38797272-316c0f32-4173-11e8-95e7-326a23ad22c1.jpg)

But logo drawing doesn't have good quality as box (?):

![photo_2018-04-16_12-40-56](https://user-images.githubusercontent.com/16017595/38797366-79a74e6a-4173-11e8-9386-a704884977df.jpg)

**Comment by olikraus** [comment]
ok, looks good. I will change the repository and create a new constructor for you.
Regarding the quality: Try to use lower contrast with the logo (like in your first pic of your last post).

Another reason for the low quality might be your capacitors. All the 2U2 caps need to be high quality ceramic caps. Do not use electrolytic capacitors. Same is true for the 100N caps.

**Comment by IMAN4K** [comment]
Thanks for helping on this issue.
The quality is perfect with those cap you said.
Can i add this `LX-12864P1` to Gallery or should be tested on your desk ?

King Regards.
IMAN.

**Comment by olikraus** [comment]
Looks great. Good job. I can add the above picture to the gallery.
Can you send me your modifications to the c code? Or is it only the "a2" value?
What contrast value did you use?

**Comment by IMAN4K** [comment]
It was just `0x0a3` -> `0x0a2`.
Last picture is with contrast level `2`

**Comment by olikraus** [comment]
I have created beta 2.22.15
It contains the constructor U8G2_ST7565_LX12864_F_4W_SW_SPI for your display (see the examples).

Download: https://github.com/olikraus/U8g2_Arduino

**Comment by olikraus** [comment]
:-)
