### ISSUE TITLE
draw1x2string dose not appear to be implemented in u8x8

### ISSUE THREAD

**Issue by yanalp73** [olikraus/u8g2#585]
Hello.The draw1x2String method in u8x8 dose not appear to be implemented as in the documentation, draw2x2String works OK.
I have version 2.21.8 installed
Thanks

**Comment by olikraus** [comment]
See #537 
This is fixed in 2.22

You can download a prerelease for 2.22 from here: https://github.com/olikraus/U8glib_Arduino
