### ISSUE TITLE
int8_t u8g_GetFontBBXOffX(u8g2_t *u8g2)

### ISSUE THREAD

**Issue by jasoroony** [olikraus/u8g2#59]
In u8g2_font.c - this function should be called:

int8_t u8g2_GetFontBBXOffX(u8g2_t *u8g2)

**Comment by olikraus** [comment]
can you be more precised?
What is the problem?
What will be solved?
How should it be solved?

**Comment by jasoroony** [comment]
It's not linkable with U8GLib, a duplicate reference error is given when you have both libraries included.

I'm implementing a dual boot system, each system uses the alternate library.
