### ISSUE TITLE
A question, why not separate Interface and Lcd Driver? 

### ISSUE THREAD

**Issue by ghosoft** [olikraus/u8g2#600]

**Comment by olikraus** [comment]
What exactly do you mean?

**Comment by ghosoft** [comment]
some what like: 
//cpp code:
U8g2 u(ST7920/*LCD Driver*/, P8080/*interface*/);

**Comment by olikraus** [comment]
Ah, ok: not all combinations are valid.

**Comment by olikraus** [comment]
but by the way: This is already implemented like this... 
Anyhow... no feedback since 8 days, so I close this...

**Comment by ghosoft** [comment]
I work in a LCD/LCM factory, and my job is making LCD/LCM tester, 
so I will face a lot LCD Resolution X LCD combinations, 
and a lot of the combinations are not in your LIB, so what can i do? 
by the way, how can i make a new LCD driver?

**Comment by olikraus** [comment]
> and a lot of the combinations are not in your LIB

Obvdiously. This is open source, freely available software. There is no budget to support all kind of displays. 

> so what can i do?

You can add the missing combinations by yourself. If the display is available for the public, then I could be convinced to add the missing combination, but as I said: There is no budget to do this. I have to do this in my spare time. 

Sometimes, I receive donation for the implementation of a new LCD, which helps to add missing combinations.

> by the way, how can i make a new LCD driver?

Here is a brief description:
https://github.com/olikraus/u8g2/wiki/internal#new-displays
