### ISSUE TITLE
u8log print "\n" does not scroll

### ISSUE THREAD

**Issue by makbas** [olikraus/u8g2#606]
Hi,
Even after setting u8x8log.setRedrawMode(0); the print("\n") command does not make it scroll.
In a loop It writes from top row down to bottom, and starts writing on the most bottom line over and over with new values. The above lines stops the same.

Any help?

Thanks

**Comment by olikraus** [comment]
Can you provide the code?

**Comment by makbas** [comment]
`#include <Arduino.h>
#include <U8x8lib.h>

// U8x8 constructor for OLED display
U8X8_SSD1306_128X64_NONAME_SW_I2C OLED(22, 21);

// Create a U8x8log object
U8X8LOG DEBUG; 

// Define the dimension of the U8x8log window
#define U8LOG_WIDTH 16
#define U8LOG_HEIGHT 8

// Allocate static memory for the U8x8log window
uint8_t u8log_buffer[U8LOG_WIDTH*U8LOG_HEIGHT];

/* u8x8.begin() is required and will sent the setup/init sequence to the display */
void setup(void)
{
    OLED.begin();
    OLED.setFont(u8x8_font_pressstart2p_f);

    // Start U8x8log, connect to U8x8, set the dimension and assign the static memory
    DEBUG.begin(OLED, U8LOG_WIDTH, U8LOG_HEIGHT, u8log_buffer);
  
    // Set the U8x8log redraw mode
    DEBUG.setRedrawMode(0);    // 0: Update screen with newline, 1: Update screen for every char  
    
}

void loop(void)
{

    DEBUG.print(millis());
    DEBUG.print("\n");

    delay(100);
    
}`

**Comment by olikraus** [comment]
ok, I see the problem. 
It works fine in DEBUG.setRedrawMode(1); but does not work with DEBUG.setRedrawMode(0);

**Comment by makbas** [comment]
Thanks for your prompt reply, have a nice one...

**Comment by olikraus** [comment]
I leave it open, until the bug is fixed... I just created a test file for now.

**Comment by olikraus** [comment]
I think I have fixed the problem. Please download beta 2.23.2 from here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip

Add the library via the "add zip library" menu of your Arduino IDE.

**Comment by makbas** [comment]
Lighting fast solution!

Works great, thank you.

**Comment by olikraus** [comment]
:-)
