### ISSUE TITLE
section `.bss' is not within region `data'

### ISSUE THREAD

**Issue by fornellas** [olikraus/u8g2#618]
I'm trying to port my project
https://github.com/fornellas/3d_printed_keyboard/tree/ef09a30e044ccf0f2a88266721ca88b7c8c5b746
to u8g2. It worked great with u8g, but with u8g2 I'm failing into this failure when compiling:

```
 [LNK]     : Linking object files into "Keyboard.elf"
avr-gcc obj/Keyboard.o obj/Counter.o obj/Descriptors.o obj/Display.o obj/KeyboardReport.o obj/Keymap.o obj/LayerState.o obj/ScanKeys.o obj/Sequence.o obj/Timer.o obj/HIDParser.o obj/Device_AVR8.o obj/EndpointStream_AVR8.o obj/Endpoint_AVR8.o obj/Host_AVR8.o obj/PipeStream_AVR8.o obj/Pipe_AVR8.o obj/USBController_AVR8.o obj/USBInterrupt_AVR8.o obj/ConfigDescriptors.o obj/DeviceStandardReq.o obj/Events.o obj/HostStandardReq.o obj/USBTask.o obj/AudioClassDevice.o obj/CDCClassDevice.o obj/HIDClassDevice.o obj/MassStorageClassDevice.o obj/MIDIClassDevice.o obj/PrinterClassDevice.o obj/RNDISClassDevice.o obj/AndroidAccessoryClassHost.o obj/AudioClassHost.o obj/CDCClassHost.o obj/HIDClassHost.o obj/MassStorageClassHost.o obj/MIDIClassHost.o obj/PrinterClassHost.o obj/RNDISClassHost.o obj/StillImageClassHost.o obj/u8g2_d_setup.o obj/u8g2_font.o obj/u8g2_hvline.o obj/u8g2_d_memory.o obj/u8g2_setup.o obj/u8x8_byte.o obj/u8x8_cad.o obj/u8x8_d_ssd1306_128x64_noname.o obj/u8x8_display.o obj/u8x8_gpio.o obj/u8x8_setup.o obj/u8g2_ll_hvline.o obj/TWI_AVR8.o -o Keyboard.elf -lm -Wl,-Map=Keyboard.map,--cref -Wl,--gc-sections -Wl,--relax -mmcu=at90usb1286 
/usr/lib/gcc/avr/4.9.2/../../../avr/bin/ld: address 0x819b17 of Keyboard.elf section `.bss' is not within region `data'
/usr/lib/gcc/avr/4.9.2/../../../avr/bin/ld: address 0x819b17 of Keyboard.elf section `.bss' is not within region `data'
collect2: error: ld returned 1 exit status
lufa/LUFA/Build/DMBS/DMBS/gcc.mk:238: recipe for target 'Keyboard.elf' failed
make: *** [Keyboard.elf] Error 1
```

The issue comes from u8g2/csrc/u8g2_d_memory.c having tons of static arrays declared, that for whatever reason, are not discarded when linking happens. I can make things compile, if I comment out all functions that are not necessary.

I found this reference 
https://github.com/olikraus/u8glib/blob/master/csrc/u8g.h#L997
to nocommon attribute from u8g, and it is used to declare buffers all over. I tried using that, but no luck (I'm no Avr expert though...).

I'm not sure if this is something that can be solved by some avr-gcc argument, or if there's the need for some specific support from u8g2.

Thanks in advance.

**Comment by fornellas** [comment]
Humm... apparently compiling with -fdata-sections allows --gc-sections to purge unused data as well, apparently taking care of this issue.

**Comment by olikraus** [comment]
:+1:
