### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by pppeixoto** [olikraus/u8g2#624]
I have a arduino system with 2 OLEds, initialization below:
U8G2_SSD1326_ER_256X32_1_4W_SW_SPI OLED_RIGHT(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 7, /* dc=*/ 6, /* reset=*/ 5);         // experimental driver for ER-OLED018-1 10 9 8
U8G2_SSD1326_ER_256X32_1_4W_SW_SPI OLED_LEFT(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);         // experimental driver for ER-OLED018-1 10 9 8
When I write in the first OLED  the second presents a "noise" in the lower right corner, in the form of a square. The reverse does not happen. What could be causing the problem?
https://ibb.co/fZCugT
after writing in OLED 1 disappears

**Comment by pppeixoto** [comment]
I've checked that when I put the D/C pin of OLEd on which I'm not writing LOW, the problem no longer happens. However I think it is a driver problem.

**Comment by olikraus** [comment]
hmm... I think there are also some hints in the FAQ.

**Comment by olikraus** [comment]
closing...
