### ISSUE TITLE
LC7981 display does not work

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#625]
E-Mail:

Hi,

I have been trying to get a PG24064A-P2 with LC7981 driver to work with your library without luck. I know the contrast control is working correctly but I can get nothing to display.

As your library does not have support for 240x64 I chose 240x128 - is it ok to do this?

The wiring is correct but I do not understand the pin assignments. This is the example in the HelloWorld script and after DB0 to DB7 there are five control lines referenced for the display

U8G2_LC7981_240X128_1_6800 u8g2(8, 9, 10, 11, 4, 5, 6, 7, 18, 14, 15, 17, 16); // 8Bit Com: D0..D7: 8,9,10,11,4,5,6,7 en=18, cs=14 ,di=15,rw=17, reset = 16

However in U8g2lib.h there is only four control lines referenced. I don't understand how the library works but should I be concerned about this difference?

class U8G2_LC7981_240X128_1_6800 : public U8G2 {
  public: U8G2_LC7981_240X128_1_6800(const u8g2_cb_t *rotation, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7, uint8_t enable, uint8_t cs, uint8_t dc, uint8_t reset = U8X8_PIN_NONE) : U8G2() {
    u8g2_Setup_lc7981_240x128_1(&u8g2, rotation, u8x8_byte_8bit_6800mode, u8x8_gpio_and_delay_arduino);
    u8x8_SetPin_8Bit_6800(getU8x8(), d0, d1, d2, d3, d4, d5, d6, d7, enable, cs, dc, reset);
  }
};

**Comment by vk3alb** [comment]
I am now a github member

**Comment by olikraus** [comment]
hmm.., ok, this is what you reported:
```
U8G2_LC7981_240X128_1_6800 u8g2(8, 9, 10, 11, 4, 5, 6, 7, 18, 14, 15, 17, 16); // 8Bit Com: D0..D7: 8,9,10,11,4,5,6,7 en=18, cs=14 ,di=15,rw=17, reset = 16
```
This is the u8g2 HelloWorld.ino example:
```
U8G2_LC7981_240X128_1_6800 u8g2(U8G2_R0, 8, 9, 10, 11, 4, 5, 6, 7, /*enable=*/ 18, /*cs=*/ 14, /*dc=*/ 15, /*reset=*/ 16); // Connect RW with GND
```

So I think the example is correct.

**Comment by vk3alb** [comment]
No idea it was there when I opened the sketch. It has been some time since I looked at it perhaps a result of some experimenting on my part. I will change the wiring to suit the line you showed me then test again.

**Comment by vk3alb** [comment]
OK success, that line works. Sorry for the mix up with the code.
Do I need to care that I am using 240x128 for a display that is 240x64?
Thank you for your help.

**Comment by olikraus** [comment]
> Do I need to care that I am using 240x128 for a display that is 240x64?

Display results are correct? Well, a 240x64 device would be twice as fast as the 240x128 driver...
I can add the 240x64 version, but you need to take over the testing.

**Comment by vk3alb** [comment]
Yes display result is correct.
I will test the current configuration and if necessary I can open a change request. For now I can address the whole screen just fine.

Thanks again

**Comment by olikraus** [comment]
I expect better performance. But just let me know/repopen this issue.
