### ISSUE TITLE
MAX7219 with a single module (8x8)

### ISSUE THREAD

**Issue by mz2212** [olikraus/u8g2#628]
The library is great, but I only have a single MAX7219 module at the moment, can support for the 8x8 resolution be added?

**Comment by olikraus** [comment]
The existing 32x8 doesn't work?

**Comment by mz2212** [comment]
It does, but 0 on the x axis starts on the what would be the 4th module. Meaning that for a single module, you need to start at 24 to get the first column of pixels. It's not super important, but it would be handy to start at 0 to get at those pixels.

I suppose it would be possible to use a different rotation in the initializer, but that would also cause the (0, 0) point to be in an unexpected place.

**Comment by olikraus** [comment]
Ok, I will add this

**Comment by olikraus** [comment]
Done, constructor is:
U8G2_MAX7219_8X8_F_4W_SW_SPI

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by olikraus** [comment]
any feedback?

**Comment by mz2212** [comment]
Sorry for forgetting to get back to you for so long on this one.
It works for the cases I use it in (text display), I haven't tested it with the graphics portion of the library.

**Comment by olikraus** [comment]
No problem. Thanks for the feedback.
