### ISSUE TITLE
Capture cursor position after print method

### ISSUE THREAD

**Issue by fire1** [olikraus/u8g2#629]
How can i capture cursor position after "print" method is called (in my case using getStrWidth() is useless  )
I want to draw a frame as example and continue to print characters on same row ... 

Even return of  last "setCursor"  "X"  will help

**Comment by olikraus** [comment]
The current cursor position is available in the public member variables `tx` and `ty`.

**Comment by fire1** [comment]
Тhanks!

**Comment by gtmans** [comment]
> The current cursor position is available in the public member variables `tx` and `ty`.

Thanx a lot. This works great: u8g2Fonts.tx I use it to print smaller spaces like this u8g2Fonts.setCursor(y,u8g2Fonts.tx+(fontw/2));

**Comment by klen25** [comment]
> The current cursor position is available in the public member variables `tx` and `ty`.

hi,
why I always get 0 ? I use drawStr(). Is that problem?

**Comment by klen25** [comment]
Thanks a lot man
what if I want to know current font type that I'm using?

**Comment by olikraus** [comment]
Font detection might be possible, but instead I suggest a global flag or number to remember the font.

**Comment by juanlatzke** [comment]
> Yes, use the print command. tx and ty are only updated with print command.

Hi, what if I'm ussing the u8g2log.print function? I can't find the variables tx and ty of the cursor position. And of corse when i call Serial.print(u8g2.tx); Serial.println(u8g2.ty); Allways returns zero. 
Does the u8g2log object has public member variables tx and ty too? And how I get them?
Thanks!
