### ISSUE TITLE
Arduino Mega + ST7920 + HW SP

### ISSUE THREAD

**Issue by neoblack2** [olikraus/u8g2#630]
Hello, tell me how can I attach these details?
Arduino Mega + ST7920 + HW SP

I am used
U8G2_ST7920_128X64_F_HW_SPI u8g2(U8G2_R0,53,8);
or
U8G2_ST7920_128X64_F_SW_SPI u8g2(U8G2_R0, /* clock=/ 52, / data=/ 51, / CS=/ 53, / reset=*/ 49);
and it does not work ((

**Comment by olikraus** [comment]
Looks correct, check your wiring, power supply and ensure that you use level shifters if required.

**Comment by olikraus** [comment]
no further comments, closing...
