### ISSUE TITLE
Big 7-Segments style font

### ISSUE THREAD

**Issue by Busa357** [olikraus/u8g2#634]
Hi,

I wanted a big font for my clock project. An 7-Segments like style.
Since it does not exist, I created one by myself. The size is 26x42.
To minimise the weight, the font have  only 12 glyphs. (0,1,2,3,4,5,6,7,8,9, : ,space) 
Note that the two dots and the space glyph have exactly the same width.
So you could easily make the two dots blinking by alternating these two characters.
I hope that this font could be usefull to someone. 
Oli, you can of course add it to the library if you find it interesting.

[7Segments_26x42.zip](https://github.com/olikraus/u8g2/files/2092975/7Segments_26x42.zip)

![photo 12-06-18 08 59 18](https://user-images.githubusercontent.com/39987807/41276026-2622ff5a-6e23-11e8-9c38-f5790441be9d.jpg)

**Comment by olikraus** [comment]
Nice. Thanks for the contribution.

**Comment by olikraus** [comment]
added, font rebuild required.

**Comment by olikraus** [comment]
font added, docu updated

**Comment by bisra2** [comment]
Je teste cette belle font sur un afficheur tft 320x240 mais le segment 'd' du digit '1' s'allume!
