### ISSUE TITLE
Adafruit Feather nRF52 Bluefruit LE - nRF52832

### ISSUE THREAD

**Issue by ELIVB** [olikraus/u8g2#638]
Hello

I bought the board from adafruit:  ARM Cortex M4F Nordic nRF52832 Bluetooth:
https://www.adafruit.com/product/3406
Does your library u8g2 support the board?

Thanks
eli

**Comment by olikraus** [comment]
I do not own this board... So I can't say...

**Comment by neu-rah** [comment]
Used it on adafruit feather nRF52, working nice

**Comment by ELIVB** [comment]
Hi
neu-rah, you have the adafruit nRF52832 board?
Have you been able to connect oled? my screen is SH1106_128X64 from china.

eli

**Comment by ELIVB** [comment]
Hi

All good screen works
eli
