### ISSUE TITLE
Support for LC7981_240X64

### ISSUE THREAD

**Issue by vk3alb** [olikraus/u8g2#642]
I have a PG 24064 display that uses a LC7981. It works OK with U8G2_LC7981_240X128_1_6800 but I understand it could be faster if the library was made for this size. Is it possible to add support for 240x64 pixels please?

**Comment by olikraus** [comment]
New constructor: 
`U8G2_LC7981_240X64_1_6800`
`U8G2_LC7981_240X64_2_6800`
`U8G2_LC7981_240X64_F_6800`

**Comment by olikraus** [comment]
I have created beta 2.23.11

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by vk3alb** [comment]
Thanks,

The first two libraries work and they are faster. I cannot try U8G2_LC7981_240X64_F_6800 because it creates too many variables for my UNO. I suspect it would work ok in a MEGA. Thanks for the quick turn around.

Lou

**Comment by olikraus** [comment]
Thanks for the feedback. There's no need to test F variant.

**Comment by vk3alb** [comment]
OK great. Case closed.
