### ISSUE TITLE
Change C-prototype of setPageCurrTileRow() to u8g2_SetBufferCurrTileRow in the wiki

### ISSUE THREAD

**Issue by ribasco** [olikraus/u8g2#647]
Perhaps this needs to be updated in the wiki

I did not find any references to **setPageCurrTileRow()** in the C-implementation (exists only in C++) as per the [wiki](https://github.com/olikraus/u8g2/wiki/u8g2reference#setpagecurrtilerow). However in the code, I see that this points to **u8g2_SetBufferCurrTileRow** instead.

**Comment by olikraus** [comment]
hmm... yes indeed this is confusing.

actually setPageCurrTileRow is obsolete and it should be setBufferCurrTileRow.
In the C++ you see both functions defined:
https://github.com/olikraus/u8g2/blob/master/cppsrc/U8g2lib.h#L162
and
https://github.com/olikraus/u8g2/blob/master/cppsrc/U8g2lib.h#L164

But yes, I need to update the wiki.

Todo: Rename setPageCurrTileRow to setBufferCurrTileRow and getPageCurrTileRow to getBufferCurrTileRow

**Comment by ribasco** [comment]
Thanks for the clarification

**Comment by olikraus** [comment]
done
