### ISSUE TITLE
No HW_SPI option in C?

### ISSUE THREAD

**Issue by kingofsnake** [olikraus/u8g2#648]
I want to convert my u8glib project to u8g2, to see if it solves certain issues, but I can't see hw_spi setup functions in C, which were present in u8glib. Am I understanding this correctly? Is there a reason behind this?

**Comment by olikraus** [comment]
What exactly do you mean by hw_spi setup?

U8g2 more clearly separates hardware dependent files. AVR specific code is removed. Only the C++ part contains calls to Arduino HAL.

Other hardware specific topics are discussed here:
https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform

**Comment by kingofsnake** [comment]
By hw_spi I meant that in u8glib I was using u8g_dev_sh1106_128x64_hw_spi as a device in InitSPI setup, but I didn't see an equivalent in u8g2.

But I guess I'm starting to understand, so there's no AVR-specific HW SPI code in u8g2 any more? I'll have a look at the examples on the page you linked, thanks.

**Comment by olikraus** [comment]
Ah, AVR... no I removed this. But the u8g2 porting guide (link above) has some links for this.
