### ISSUE TITLE
max7912 big fonts and table

### ISSUE THREAD

**Issue by wchpikus** [olikraus/u8g2#652]
hello
is it possible to add driver for max7912, but connected to highest display?
e.g. 24x32 normal is 8x32.
I thing about send one part of fonts to display 1 and second part do x further from display one.
if all display will be connected like this (16 displays long and 4 height), next part will be start upper 128 pixel)
1st counted from down matrix left to right, 2'th matrix upper first, 3'th upper 2'th ect..
------3'th----->
|
<----------------
                       |
------2'th----->
|
<----------------
                       |
-----1st------->

In driver add parameter long and high.

**Comment by olikraus** [comment]
You could simply use three different u8g2 objects. Connect the led matrix to three different IO lines and use SW SPI.

**Comment by wchpikus** [comment]
I have some question..
Function nextpage=clear lcd?
Clearbuffer+sendbuffer also?

**Comment by olikraus** [comment]
U8g2 does not use dynamic memory, so RAM es never allocated or freed.
first/next page is more portable and will work with 1, 2 and F constructors.
clearbuffer/sendbuffer will work only with F constructors, see also the manual for more details.

**Comment by wchpikus** [comment]
Hi
Next question..
Is it possible to scroll text using u82g.print?
I have to use this print becouse i have one string with variable text inside and i can not using u2gt.sendstr..error with compiling.
String test =""; and when i use u2gt.sendStr(0,0 test); i have error...so i using print

**Comment by olikraus** [comment]
Using print is fine. Just change the x position by one and rebuild the complete picture with print.
