### ISSUE TITLE
Support the s028hn118a display  and the ERC240160 display

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#661]
Add support the s028hn118a display in the Smart Response XE and the ERC240160 display

see #660

**Comment by olikraus** [comment]
I think this is done...

**Comment by pepermn** [comment]
Hola tengo un glcd ra8835
Habilite 16bits
Funciona bien pero
Solo muestra x 240  y 240
Y tendria q set x329 y 240
Q estoy haciendo mal
Gracias saludos de argentina

**Comment by pepermn** [comment]
Perdon 
Tendria que set 320 x   240 y
Error en x    solo muestra 240 pixel
