### ISSUE TITLE
16m1/31m1/64m1

### ISSUE THREAD

**Issue by geraldjust** [olikraus/u8g2#662]
https://github.com/olikraus/u8g2/blob/d7a20ce5f89c1729721b917025599c57ca105c55/cppsrc/U8x8lib.h#L87

Hi! just found a small issue were atmega16m1 was repeated 3 times rather than the three variants!

Both for the m1 and the c1

**Comment by olikraus** [comment]
Ah, yes.,

**Comment by olikraus** [comment]
done, thanks for the input.
