### ISSUE TITLE
link to download the latest Arduino u8g2 library

### ISSUE THREAD

**Issue by mikekgr** [olikraus/u8g2#666]
Dear Sirs,
can you provide me the link to download the latest Arduino u8g2 library? Can be this link permanent to point always to the latest "snapshot" of the u8g2 Arduino library?

Many thanks and Best Regards,
Mike Kranidis

**Comment by v1993** [comment]
Is https://github.com/olikraus/u8g2/archive/master.zip ok for you?

**Comment by mikekgr** [comment]
Dear @v1993  yes this is what I am looking for. Thanks!

**Comment by olikraus** [comment]
Actually, the Arduino library is available here for download:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip

**Comment by mikekgr** [comment]
... Small detail but now I realized that this issue is #666  ...   to whom may concern !

**Comment by olikraus** [comment]
hehe... ok, i am more interessted in number theorie... the sum of the first (6+6)*(6+6) digits of Pi is 666.
