### ISSUE TITLE
Unicode Font to BDF

### ISSUE THREAD

**Issue by ernstjan18** [olikraus/u8g2#667]
Hello Olikraus,
I try since days to create a bdf from a unicode font. 

I'm using the cyrillic font: u8g2_font_6x12_t_cyrillic and u8g2_font_4x6_t_cyrillic with the example text "русский" it looks Ok. But I like to have it a little bit bigger. Like Bold Characters in a latin font.

I search at this board for information.
I try to generate it wiht fony. But this program only have the characters from 1-255. 
In your example fonts I have see that you have export the characters 32-128 / 1024-1264. 

How must I generate this font so that i can use it.  Can you give me some assistance. 

many thanks for this great project.

I found it out:    ->bdfconv.exe -v -f 1 -m "32-127,1024-1299" ...

**Comment by olikraus** [comment]
> I found it out: ->bdfconv.exe -v -f 1 -m "32-127,1024-1299" ...

yes
