### ISSUE TITLE
How draw variable value on LCD using C#?

### ISSUE THREAD

**Issue by serg825w** [olikraus/u8g2#672]
Hi. I use avr and AtmelStudio7. I read reference manual (u8g2), but don't found C prototype for draw variable values like "print" for Arduino?

**Comment by olikraus** [comment]
print is an Arduino function. It is only available in the Arduino environment.

**Comment by olikraus** [comment]
There are two itoa function included in u8g2:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8.h#L920

The first argument is the number, the second is the number of digits you want to output, so:
`u8x8_u8toa(7, 2)` will return `"07"`.
