### ISSUE TITLE
Sharp Memory LS027B7DH01 Support

### ISSUE THREAD

**Issue by vin7102** [olikraus/u8g2#675]
Hi,

I have a Sharp Memory LS027B7DH01 and would really love to use u8g2 for this 2.7" display.  Has anyone been able to use the u8g2 for this?  

Thank you,
Vince

**Comment by olikraus** [comment]
any datasheet available?

**Comment by vin7102** [comment]
Hi Oliver,

Sure, here it is...
[LS027B7DH01_Rev_Jun_2010.pdf](https://github.com/olikraus/u8g2/files/2270272/LS027B7DH01_Rev_Jun_2010.pdf)

**Comment by vin7102** [comment]
Hey Oliver,

I see you have support for a similar Sharp LS013B7DH03 128X128 display and I was looking through the library to see if I can modify it to work with this new 400 x 240 size and have made many attempts but no luck with it.  I am mainly in need of the HW version as like you pointed out a few months ago, using a bit banging spi along with my current hardware spi encoder doesnt work together.

Is it possible to modify your current 128x128 version to work with this display or is it far too complicated for a rookie like myself to work with?

Thanks again,
Vince

**Comment by olikraus** [comment]
From what I see, the LS013B7DH03 and the LS027B7DH01 do not differ much, right?
I assume it should not be a big problem to add support for your display.

What happens if your just use the existing LS013B7DH03 u8g2 device?

**Comment by olikraus** [comment]
Actually I can not even say, whether the LS013 works. At least I do not own this device.

**Comment by vin7102** [comment]
I don’t own an LS013 either so I couldn’t say either.  I did try your LS013 setup with the 027 and I just got a black screen with all pixels on.  I just figured it needs some modifications to the U8g2 and I didn’t want to damage the display.
However I was able to get the 027 to work with the adafruit library but I prefer to use U8g2 due to the hardware spi option as well as all of the custom fonts I created for U8g2.
Since you think the 013 may possibly work, I’ll give it another try tonight and let you know the results.
In the meantime, I’m going to try to order an 027 to test as well.
Would you like me to send you one of each display with a breakout board for you to keep for testing and evaluating?  I can at least do that.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by olikraus** [comment]
I have created a new beta release 2.23.16.

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by olikraus** [comment]
1.: You could use U8G2_R1
2.: Doesn't make sense. For a negative display it's just like this.

**Comment by olikraus** [comment]
Ok, back at my pc. Can you send and picture of the output of the HelloWorld.ino? .. based on the beta release from above?

**Comment by vin7102** [comment]
Sure,  
Attached are a couple screenshots of the black background using u8g2 HelloWorld posted above.  Also posted is the same display using the Adafruit GFX library and SW spi. The background configures white by default.

You can also see on the  HelloWorld u8g2 sketch that the orientation of characters is correct but the screen will only allow 240px horizontally (as you can see the #7 is cut off on the right.  Its like the 240 x 400 is swapped).  If I use R1 then I'll have to rotate all of my characters to use the display in this landscape orientation.

Thanks for your time bud!
![20180821_220941939_ios](https://user-images.githubusercontent.com/16926921/44432559-87ea4e80-a570-11e8-89d0-1ddc77b806fe.jpg)
![20180821_221037265_ios](https://user-images.githubusercontent.com/16926921/44432560-87ea4e80-a570-11e8-89f8-cc7a1a1bcd9b.jpg)
![img_5491](https://user-images.githubusercontent.com/16926921/44432596-b6682980-a570-11e8-96d7-41e20a194881.JPG)

**Comment by olikraus** [comment]
Did you enable 16 bit mode? 
https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L159
I think I forgot to mention this.

**Comment by olikraus** [comment]
any comments/feedback?

**Comment by vin7102** [comment]
Sorry Oliver, I’ve been very ill the last few days.  Going to try 16bit mode tomorrow and I’ll post the results.

Thank you!

On Aug 24, 2018, at 6:10 AM, olikraus <notifications@github.com<mailto:notifications@github.com>> wrote:


any comments/feedback?

**Comment by olikraus** [comment]
No Problem. Moved the issue to the next milestone. 
Take your time...

**Comment by vin7102** [comment]
Oliver,
My apologies, Back to work here!

16bit works perfectly and the layout spans the entire display...

The only last issue is trying to get the background color of the entire screen to white.
```

void loop(void) {
  u8g2.setFontMode(0); 
  u8g2.setDrawColor(1);
  u8g2.setFont(u8g2_font_logisoso58_tf); 
  u8g2.drawStr(0,100,"1234567890"); 
  u8g2.sendBuffer();  
}

```
See the attachments:
Setting DrawColor to 1 will give the Black background with White font color. (Pic #1)
Setting DrawColor to 0 will give the White background boxes around each character with Black font color. (Pic#2)

![20180825_131924396_ios](https://user-images.githubusercontent.com/16926921/44618762-2f55d280-a84a-11e8-9671-fd2270ee15a3.jpg)
![20180825_132144506_ios](https://user-images.githubusercontent.com/16926921/44618763-2f55d280-a84a-11e8-97c3-d736a96854e1.jpg)

**Comment by olikraus** [comment]
> Setting DrawColor to 1 will give the Black background with White font color. (Pic #1)
Setting DrawColor to 0 will give the White background boxes around each character with Black font color. (Pic#2)

It does not make sense for monochrome displays to associate 1 with white and 0 with black. The same display can be produced in a positive or negative variant and U8g2 will not know whether you have a positive or negative display. 

For u8g2 the simple truth is: DrawColor 1 means a set pixel in the memory of the controller. Whether this appears white or black (or any other color) depends on the display variant.

Using the background color will draw the glyph background box. Indeed this does not make sense for an "t" font (last to last letter is a "t" in your example). Using the background color only makes sense for "m" and "h" fonts. This is discussed in the reference manual.

**Comment by vin7102** [comment]
Thanks for the insight,  I will have to make due with the black background with white text.

I appreciate your help, We can close this issue.

Regards,
Vince

**Comment by olikraus** [comment]
:)

**Comment by kw81634dr** [comment]
For those who struggled, according to [issue#941](https://github.com/olikraus/u8g2/issues/941).
there's a simple workaround by adding the following 3 lines to make this Sharp monochrome memory LCD display text with a white-looking background.

`u8g2.setDrawColor(1);`
 `u8g2.drawBox(0,0,400,240);`
`u8g2.setDrawColor(0); //in order to make content visable` 

for instance, modifying the sample code 'GraphicsTest.ino' from u8g2lib, a part of the  code will be like:

> void u8g2_prepare(void) {
>   u8g2.setFont(u8g2_font_6x10_tf);
>   u8g2.setFontRefHeightExtendedText();
>   u8g2.setDrawColor(1); //set drawing color to 1 for drawing canvas for Sharp Mono Memory LCD.
>   u8g2.drawBox(0,0,400,240); //added for drawing white-looking canvas.
>   u8g2.setFontPosTop();
>   u8g2.setFontDirection(0);
>   u8g2.setDrawColor(0); //change from 1 to 0 to make content visable.
> }

so the actual LCD now looks like this (black pattern drawn on a white-looking background):
![IMG_1796](https://user-images.githubusercontent.com/26266974/145374518-a8890da0-1b5a-479f-b6fe-eebbe2ec145e.jpg)

we could apply the same idea to display text, see the following modified part of 'Chinese.ino' sample code:

>    do {
>     u8g2.setDrawColor(1); //added for set pixel color to generate white canvas for Sharp LCD.
>     u8g2.drawBox(0, 0, 400, 240); //added for drawing white canvas for Sharp LCD.
>     u8g2.setDrawColor(0); //change from 1 to 0 to make content visable.
>     u8g2.setCursor(10, 20);
>     u8g2.print("Hello World!");
>     u8g2.setCursor(10, 40);
>     u8g2.print("你好世界");		// Chinese "Hello World"
>     u8g2.setCursor(10, 70);
> } while ( u8g2.nextPage() );

![IMG_1803](https://user-images.githubusercontent.com/26266974/145375700-993ba0db-507e-4a91-9405-80e9f6bca0b1.jpg)
