### ISSUE TITLE
support for SSD1327 128x128 1.5" I2C

### ISSUE THREAD

**Issue by ghmac** [olikraus/u8g2#684]
Hi olikraus,

I just purchased the I2C version of the SSD1327 128x128 1.5" 16-bit grey level OLED by MakerHawk-US.
I'm pretty sure this is same one here: http://www.raspberrypiwiki.com/index.php/1.5_inch_OLED_Shield.
Would you please consider updating your constructor list for these?

Thanks

**Comment by olikraus** [comment]
You closed this. So this is not required any more?

**Comment by ghmac** [comment]
on second thought I have installed latest library for UNO and do not see it listed in the constructors

**Comment by olikraus** [comment]
In the .h file?

**Comment by ghmac** [comment]
OK seems this constructor works with most the test sketches:
U8G2_SSD1327_MIDAS_128X128_2_HW_I2C u8g2(U8G2_R0, (/* reset=*/ U8X8_PIN_NONE, (/* clock=*/ SCL, /* data=*/ SDA)));  // page buffer, size = 256 bytes
Full Buffer nothing works. Runs out of memory.
I hope I wrote it well enough that it's correct?
Thanks

**Comment by olikraus** [comment]
Out of memory?
Usually the linker garbage collector should be activated to ensure that all is unused blocks are removed.

**Comment by olikraus** [comment]
Which uC do you use? 128x128 will require 2KBytes: This will be too much for any ATMega3xx based system like Uno, Mini, Nano or similar.

**Comment by ghmac** [comment]
Ahh OK that's why then. I was using a Nano and then UNO. 
Both gave out of memory warnings.
Least it works under Page.
Thanks for all your work and help!

**Comment by olikraus** [comment]
:)
