### ISSUE TITLE
LCD 128X64 ST7920 - Bad highliting text with setdrawcolor

### ISSUE THREAD

**Issue by dromega75** [olikraus/u8g2#685]
Hi, i have my arduino mini pro with a LCD 128x64 (ST7920), set the u8g2_font_profont11_tr font and the setdrawcolor to 0.
The display show a bad highlight text. 
Here the code

LCD.firstPage();
  do {
  LCD.setFontMode(0);
  LCD.setDrawColor(1);
  LCD.drawStr(0,24,"THERMOHYGROMETER");
  LCD.setDrawColor(0);
  LCD.drawStr(0,34,"THERMOHYGROMETER");
  LCD.drawStr(0,44,"Thermohygrometer");

  } while ( LCD.nextPage() );

![img_20180820_124032](https://user-images.githubusercontent.com/42538901/44337373-c56cb000-a47a-11e8-980f-ecb08a02979f.jpg)

**Comment by olikraus** [comment]
Use a font with m or h as last to last letter

**Comment by olikraus** [comment]
no feedback.. closing
