### ISSUE TITLE
SSD1306 u8x8.setContrast(0-255) aint working

### ISSUE THREAD

**Issue by sysshad** [olikraus/u8g2#686]
Trying the 
U8X8_SSD1306_128X64_NONAME_HW_I2C
and with Arduino Mini Pro and everything works fine except the setContrast command that does nothing.
Anyone have a solution for this ? :)

Thanks in advance

**Comment by olikraus** [comment]
The change should be there, but is minimal. Try the vcom0 constructor instead.

**Comment by SeongJongKwak** [comment]
When I tested it, it didn't work.

Is there a way?
