### ISSUE TITLE
STM32 Memory usage

### ISSUE THREAD

**Issue by meldano** [olikraus/u8g2#688]
Hi,

I implemented the lib to a STM32F103 and it works fine.
But the Memory usage is huge. 
The u8g2 use 32KB from the 64KB Flash.

Options for
compiler: -ffunction-sections -fdata-sections
linker: -Wl,--gc-sections

According to a Code Analysis, the Problem is in 
`u8g2_SetFont(u8g2, u8g2_font_inr38_mf); `

This Font increase the Flash round About 14KB

What can I do to reduce the Memory usage ?
Which (big) Fonts are economical?

Thanks
Daniel

**Comment by olikraus** [comment]
You could use the `mr` variant, if only ASCII chars are required.

**Comment by meldano** [comment]
O.k. I will try it.
One idea for my Project:
I need a big font, but only numbers. What could I do to modify a existing font declaration?

I found the font const Arrays in u8g2_fonts.c


Thanks
