### ISSUE TITLE
Persian font not showing

### ISSUE THREAD

**Issue by jamalkaksouri** [olikraus/u8g2#696]
I use the u8g2lib in my arduino project and using below code
`u8g2.setFont(u8g2_font_unifont_t_arabic);
  u8g2.drawStr( 0, 15, "سلام دنیا");`
but is show me ????

I try to use 

`u8g2.setFont(u8g2_font_samim_fd_12_t_all);
u8g2.drawStr( 0, 15, "سلام دنیا");`

but again print ????

How to use persian font like samim in arduino using the u8g2lib?

**Comment by olikraus** [comment]
drawStr: You need to use drawUTF8.

print: You need to activate UTF8 first.

Please see the reference manual for both problems.

**Comment by jamalkaksouri** [comment]
i usaed drawUTF8.
how to active UTF8?

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/wiki/u8g2reference#enableutf8print
