### ISSUE TITLE
SSD1327 with I2C- U8G2 is blocking other pins 

### ISSUE THREAD

**Issue by Andrzej1000** [olikraus/u8g2#701]
Hello.
I have a problem with incompatibility U8G2 for SSD1327 with the "Meteino mega" platform:
[https://lowpowerlab.github.io/MoteinoCore/Moteino1.2.zip](url)
Moteino mega using pins: 2,4,5,6,7 for RF module.
In arduino I compile an oled in I2C and an error is shown:
"Arduino\libraries\U8g2\src\U8x8lib.cpp:1424:6: internal compiler error: Segmentation fault
 void u8x8_SetPin_8Bit_6800(u8x8_t *u8x8, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7, uint8_t enable, uint8_t cs, uint8_t dc, uint8_t reset)"
After all, for SSD1327 I use only pins for I2C (in Moteino mega: D16,D17), so the library should not block other pins.

It seems to me that the library should not block pins for other platforms if I use only I2C.
Please help me to make the U8G2 library allow this compilation?

**Comment by olikraus** [comment]
> internal compiler error: Segmentation fault

There is nothing what I can do. Maybe try a different compiler.
