### ISSUE TITLE
SED 1520 C

### ISSUE THREAD

**Issue by pavo141** [olikraus/u8g2#706]
The Library worked well on my Arduino. I still have some issues to import the project in Atmel Studio. I followed the guide to include the Library in Atmel Studio but the main function is for a SPI controller. So the display has only a 8 Bit Bus and two enable pins which makes the situation more difficult.

I think my main issue is the main.c class. I changed the setup function 
tou8g2_Setup_sed1520_122x32_1(&u8g2, U8G2_R0, u8x8_sed1520, u8x8_avr_gpio_and_delay);

Now my problem is the _gpis_and_delay_ Function, and the defines for the Pins. I need to define the Pins for my **AT90CAN128** and have the right _gpis_and_delay_ Function.

I'm pretty new to C but I couldn't figure out to solve my problem.

**Comment by olikraus** [comment]
For the 8 bit bus, you need react on all 8 data pin messages: One data pin message for each bit of a byte: https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#template-for-the-gpio-and-delay-callback

The messages are `U8X8_MSG_GPIO_D0` to `U8X8_MSG_GPIO_D7`.

Additionally you need to handle `U8X8_MSG_GPIO_E` (which has to go to E1 pin of the display) and `U8X8_MSG_GPIO_CS` which has to go to E2 pin of the display.

Once this works and you need further speedup, you could reimplement the byte transfer function. 
Currently this looks like this:
```
uint8_t u8x8_byte_sed1520(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
  uint8_t i, b;
  uint8_t *data;
  static uint8_t enable_pin; 
  switch(msg)
  {
    case U8X8_MSG_BYTE_SEND:
      data = (uint8_t *)arg_ptr;
      while( arg_int > 0 )
      {
	b = *data;
	data++;
	arg_int--;
	for( i = U8X8_MSG_GPIO_D0; i <= U8X8_MSG_GPIO_D7; i++ )
	{
	  u8x8_gpio_call(u8x8, i, b&1);
	  b >>= 1;
	}    
	
	u8x8_gpio_Delay(u8x8, U8X8_MSG_DELAY_NANO, u8x8->display_info->data_setup_time_ns);
	u8x8_gpio_call(u8x8, enable_pin, 1);
	u8x8_gpio_Delay(u8x8, U8X8_MSG_DELAY_NANO, 200);		/* KS0108 requires 450 ns, use 200 here */
	u8x8_gpio_Delay(u8x8, U8X8_MSG_DELAY_NANO, u8x8->display_info->write_pulse_width_ns);  /* expect 250 here */
	u8x8_gpio_call(u8x8, enable_pin, 0);
      }
      break;
      
    case U8X8_MSG_BYTE_INIT:
      /* disable chipselect */
      u8x8_gpio_SetCS(u8x8, u8x8->display_info->chip_disable_level);    
      /* ensure that the enable signals are low */
      u8x8_gpio_call(u8x8, U8X8_MSG_GPIO_E, 0);
      u8x8_gpio_call(u8x8, U8X8_MSG_GPIO_CS, 0);
      enable_pin = U8X8_MSG_GPIO_E;
      break;
    case U8X8_MSG_BYTE_SET_DC:
      u8x8_gpio_SetDC(u8x8, arg_int);
      break;
    case U8X8_MSG_BYTE_START_TRANSFER:
      /* cs lines are not supported for the SED1520/SBN1661 */
      /* instead, this will select the E1 or E2 line */ 
      enable_pin = U8X8_MSG_GPIO_E;
      if ( arg_int != 0 )
	enable_pin = U8X8_MSG_GPIO_CS;
      break;
    case U8X8_MSG_BYTE_END_TRANSFER:
      break;
    default:
      return 0;
  }
  return 1;
}

```

Especially you could replace the code for `U8X8_MSG_BYTE_SEND` if you have a more clever connection between uC and display. For example the loop could be replaced by a single write to a port.

**Comment by pavo141** [comment]
Tried but i can't define them without getting Errors that the Ports are redefined and priviously used in the `u8x8_gpio_and_delay_template`

This is my main Right now
`#include <avr/io.h>
#include <u8g2.h>
#include <util/delay.h>
 


 #define DISPLAY_DATA_DIR DDRA
 #define DISPLAY_DATA_PORT PORTA
 #define U8X8_MSG_GPIO_D0 PA0
 #define U8X8_MSG_GPIO_D1 PA1
 #define U8X8_MSG_GPIO_D2 PA2
 #define U8X8_MSG_GPIO_D3 PA3
 #define U8X8_MSG_GPIO_D4 PA4
 #define U8X8_MSG_GPIO_D5 PA5
 #define U8X8_MSG_GPIO_D6 PA6
 #define U8X8_MSG_GPIO_D7 PA7
 
 #define U8X8_MSG_GPIO_E PC1 //E1
 #define U8X8_MSG_GPIO_CS PC2 //E2
 #define U8X8_MSG_GPIO_RESET PC7
 #define U8X8_MSG_GPIO_DC PC0 //A0
 
 

 #define DISPLAY_DC_DIR DDRB
 #define DISPLAY_DC_PORT PORTB
 #define DISPLAY_DC_PIN 1 
 
 #define DISPLAY_RESET_DIR DDRC
 #define DISPLAY_RESET_PORT PORTC
 #define DISPLAY_RESET_PIN 7
                        

//#define P_CPU_NS (16000000UL / F_CPU)
#define F_CPU 16000000UL 
 
u8g2_t u8g2;
 
uint8_t u8x8_avr_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
        
        uint8_t cycles;
 
        switch(msg)
        {
                case U8X8_MSG_DELAY_NANO:     // delay arg_int * 1 nano second
                // At 20Mhz, each cycle is 50ns, the call itself is slower.
                break;
                case U8X8_MSG_DELAY_100NANO:    // delay arg_int * 100 nano seconds
                // Approximate best case values...
                #define CALL_CYCLES 26UL
                #define CALC_CYCLES 4UL
                #define RETURN_CYCLES 4UL
                #define CYCLES_PER_LOOP 4UL
 
                cycles = (100UL * arg_int) / (F_CPU * CYCLES_PER_LOOP);
 
                if(cycles > CALL_CYCLES + RETURN_CYCLES + CALC_CYCLES)
                break;
 
                __asm__ __volatile__ (
                "1: sbiw %0,1" "\n\t" // 2 cycles
                "brne 1b" : "=w" (cycles) : "0" (cycles) // 2 cycles
                );
                break;
                case U8X8_MSG_DELAY_10MICRO:    // delay arg_int * 10 micro seconds
                for(int i=0 ; i < arg_int ; i++)
                _delay_us(10);
                break;
                case U8X8_MSG_DELAY_MILLI:      // delay arg_int * 1 milli second
                for(int i=0 ; i < arg_int ; i++)
                _delay_ms(1);
                break;
                default:
                return 0;
        }
        return 1;
}
 
 
uint8_t u8x8_gpio_and_delay_template(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
        switch(msg)
        {
                case U8X8_MSG_GPIO_AND_DELAY_INIT:      // called once during init phase of u8g2/u8x8
                break;                                                  // can be used to setup pins
                case U8X8_MSG_DELAY_NANO:                       // delay arg_int * 1 nano second
                break;
                case U8X8_MSG_DELAY_100NANO:            // delay arg_int * 100 nano seconds
                break;
                case U8X8_MSG_DELAY_10MICRO:            // delay arg_int * 10 micro seconds
                break;
                case U8X8_MSG_DELAY_MILLI:                      // delay arg_int * 1 milli second
                break;
                case U8X8_MSG_DELAY_I2C:                                // arg_int is the I2C speed in 100KHz, e.g. 4 = 400 KHz
                break;                                                  // arg_int=1: delay by 5us, arg_int = 4: delay by 1.25us
                case U8X8_MSG_GPIO_D0:                          // D0 or SPI clock pin: Output level in arg_int
                //case U8X8_MSG_GPIO_SPI_CLOCK:
                break;
                case U8X8_MSG_GPIO_D1:                          // D1 or SPI data pin: Output level in arg_int
                //case U8X8_MSG_GPIO_SPI_DATA:
                break;
                case U8X8_MSG_GPIO_D2:                          // D2 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D3:                          // D3 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D4:                          // D4 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D5:                          // D5 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D6:                          // D6 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D7:                          // D7 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_E:                           // E/WR pin: Output level in arg_int //e1
                break;
                case U8X8_MSG_GPIO_CS:                          // CS (chip select) pin: Output level in arg_int //e2
                break;
                case U8X8_MSG_GPIO_DC:                          // DC (data/cmd, A0, register select) pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_RESET:                       // Reset pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_CS1:                         // CS1 (chip select) pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_CS2:                         // CS2 (chip select) pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_I2C_CLOCK:           // arg_int=0: Output low at I2C clock pin
                break;                                                  // arg_int=1: Input dir with pullup high for I2C clock pin
                case U8X8_MSG_GPIO_I2C_DATA:                    // arg_int=0: Output low at I2C data pin
                break;                                                  // arg_int=1: Input dir with pullup high for I2C data pin
                case U8X8_MSG_GPIO_MENU_SELECT:
                u8x8_SetGPIOResult(u8x8, /* get menu select pin state */ 0);
                break;
                case U8X8_MSG_GPIO_MENU_NEXT:
                u8x8_SetGPIOResult(u8x8, /* get menu next pin state */ 0);
                break;
                case U8X8_MSG_GPIO_MENU_PREV:
                u8x8_SetGPIOResult(u8x8, /* get menu prev pin state */ 0);
                break;
                case U8X8_MSG_GPIO_MENU_HOME:
                u8x8_SetGPIOResult(u8x8, /* get menu home pin state */ 0);
                break;
                default:
                u8x8_SetGPIOResult(u8x8, 1);                    // default return value
                break;
        }
        return 1;
}
 
 
int main(void)
{
        /*
                Select a setup procedure for your display from here: https://github.com/olikraus/u8g2/wiki/u8g2setupc
                1. Arg: Address of an empty u8g2 structure
                2. Arg: Usually U8G2_R0, others are listed here: https://github.com/olikraus/u8g2/wiki/u8g2reference#carduino-example
                3. Arg: Protocol procedure (u8g2-byte), list is here: https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#communication-callback-eg-u8x8_byte_hw_i2c
                4. Arg: Defined in this code itself (see above)
        */
        u8g2_Setup_sed1520_122x32_1(&u8g2, U8G2_R0, u8x8_byte_sed1520, u8x8_gpio_and_delay_template);
        u8g2_InitDisplay(&u8g2);
        u8g2_SetPowerSave(&u8g2, 0);
        
        /* full buffer example, setup procedure ends in _f */
    u8g2_ClearBuffer(&u8g2);
        u8g2_SetFont(&u8g2, u8g2_font_ncenB14_tr);
        u8g2_DrawStr(&u8g2, 1, 2, "test");
        u8g2_SendBuffer(&u8g2);
                
        while(1){
        }
}`

**Comment by olikraus** [comment]
You must not redefine the U8X8 messages, instead you must handle them.
See here for an example: 
https://github.com/olikraus/u8g2/blob/master/sys/avr/atmega328/main.c#L137

So it should look like this in your case (taking the D3 as an example):
```
case U8X8_MSG_GPIO_D3:
	if(arg_int)
		PORTA |= (1<<3);
	else
		PORTA &= ~(1<<3);
```

Of course, this has to be repeated for all the other pins. As you can see, no `#define` required.

**Comment by pavo141** [comment]
Thanks! 
Nothing happens on my Display
this is my Code now:

`
#include <avr/io.h>
#include <u8g2.h>
#include <util/delay.h>
 
#define DISPLAY_CLK_DIR DDRB
#define DISPLAY_CLK_PORT PORTB
#define DISPLAY_CLK_PIN 5


#define DISPLAY_DATA_DIR DDRB
#define DISPLAY_DATA_PORT PORTB
#define DISPLAY_DATA_PIN 3


#define DISPLAY_CS_DIR DDRB
#define DISPLAY_CS_PORT PORTB
#define DISPLAY_CS_PIN 2



#define DISPLAY_DC_DIR DDRB
#define DISPLAY_DC_PORT PORTB
#define DISPLAY_DC_PIN 1



#define DISPLAY_RESET_DIR DDRB
#define DISPLAY_RESET_PORT PORTB
#define DISPLAY_RESET_PIN 0



//#define P_CPU_NS (16000000UL / F_CPU)
#define F_CPU 16000000UL 
 
u8g2_t u8g2;
 
uint8_t u8x8_avr_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
        
        uint8_t cycles;
 
        switch(msg)
        {
                case U8X8_MSG_DELAY_NANO:     // delay arg_int * 1 nano second
                // At 20Mhz, each cycle is 50ns, the call itself is slower.
                break;
                case U8X8_MSG_DELAY_100NANO:    // delay arg_int * 100 nano seconds
                // Approximate best case values...
                #define CALL_CYCLES 26UL
                #define CALC_CYCLES 4UL
                #define RETURN_CYCLES 4UL
                #define CYCLES_PER_LOOP 4UL
 
                cycles = (100UL * arg_int) / (F_CPU * CYCLES_PER_LOOP);
 
                if(cycles > CALL_CYCLES + RETURN_CYCLES + CALC_CYCLES)
                break;
 
                __asm__ __volatile__ (
                "1: sbiw %0,1" "\n\t" // 2 cycles
                "brne 1b" : "=w" (cycles) : "0" (cycles) // 2 cycles
                );
                break;
                case U8X8_MSG_DELAY_10MICRO:    // delay arg_int * 10 micro seconds
                for(int i=0 ; i < arg_int ; i++)
                _delay_us(10);
                break;
                case U8X8_MSG_DELAY_MILLI:      // delay arg_int * 1 milli second
                for(int i=0 ; i < arg_int ; i++)
                _delay_ms(1);
                break;
                default:
                return 0;
        }
        return 1;
}
 
 
uint8_t u8x8_gpio_and_delay_template(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
        switch(msg)
        {
                case U8X8_MSG_GPIO_AND_DELAY_INIT:      // called once during init phase of u8g2/u8x8
                break;                                                  // can be used to setup pins
                case U8X8_MSG_DELAY_NANO:                       // delay arg_int * 1 nano second
                break;
                case U8X8_MSG_DELAY_100NANO:            // delay arg_int * 100 nano seconds
                break;
                case U8X8_MSG_DELAY_10MICRO:            // delay arg_int * 10 micro seconds
                break;
                case U8X8_MSG_DELAY_MILLI:                      // delay arg_int * 1 milli second
                break;
                case U8X8_MSG_DELAY_I2C:                                // arg_int is the I2C speed in 100KHz, e.g. 4 = 400 KHz
                break;                                                  // arg_int=1: delay by 5us, arg_int = 4: delay by 1.25us
                case U8X8_MSG_GPIO_D0:
				if(arg_int)
					PORTA |= (1<<0);
				else
					PORTA &= ~(1<<0);                          // D0 or SPI clock pin: Output level in arg_int
                //case U8X8_MSG_GPIO_SPI_CLOCK:
                break;
                case U8X8_MSG_GPIO_D1: 
					if(arg_int)
						PORTA |= (1<<1);
					else
						PORTA &= ~(1<<1);                          // D1 or SPI data pin: Output level in arg_int
                //case U8X8_MSG_GPIO_SPI_DATA:
                break;
                case U8X8_MSG_GPIO_D2:
					if(arg_int)
						PORTA |= (1<<2);
					else
						PORTA &= ~(1<<2);                          // D2 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D3:
					if(arg_int)
						PORTA |= (1<<3);
					else
						PORTA &= ~(1<<3);                          // D3 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D4:
					if(arg_int)
						PORTA |= (1<<4);
					else
						PORTA &= ~(1<<4);                          // D4 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D5:  
					if(arg_int)
						PORTA |= (1<<5);
					else
					PORTA &= ~(1<<5);                        // D5 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D6: 
					if(arg_int)
						PORTA |= (1<<6);
					else
						PORTA &= ~(1<<6);                         // D6 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_D7:   
					if(arg_int)
						PORTA |= (1<<7);
					else
						PORTA &= ~(1<<7);                       // D7 pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_E:  
					if(arg_int)
						PORTC |= (1<<1);
					else
						PORTC &= ~(1<<1);                         // E/WR pin: Output level in arg_int //e1
                break;
                case U8X8_MSG_GPIO_CS: 
					if(arg_int)
						PORTC |= (1<<2);
					else
						PORTC &= ~(1<<2);                         // CS (chip select) pin: Output level in arg_int //e2
				                         // CS (chip select) pin: Output level in arg_int //e2
                break;
                case U8X8_MSG_GPIO_DC: 
					if(arg_int)
						PORTC |= (1<<0);
					else
						PORTC &= ~(1<<0);                         // DC (data/cmd, A0, register select) pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_RESET: 
					if(arg_int)
						PORTC |= (1<<7);
					else
						PORTC &= ~(1<<7);                      // Reset pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_CS1:                         // CS1 (chip select) pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_CS2:                         // CS2 (chip select) pin: Output level in arg_int
                break;
                case U8X8_MSG_GPIO_I2C_CLOCK:           // arg_int=0: Output low at I2C clock pin
                break;                                                  // arg_int=1: Input dir with pullup high for I2C clock pin
                case U8X8_MSG_GPIO_I2C_DATA:                    // arg_int=0: Output low at I2C data pin
                break;                                                  // arg_int=1: Input dir with pullup high for I2C data pin
                case U8X8_MSG_GPIO_MENU_SELECT:
                u8x8_SetGPIOResult(u8x8, /* get menu select pin state */ 0);
                break;
                case U8X8_MSG_GPIO_MENU_NEXT:
                u8x8_SetGPIOResult(u8x8, /* get menu next pin state */ 0);
                break;
                case U8X8_MSG_GPIO_MENU_PREV:
                u8x8_SetGPIOResult(u8x8, /* get menu prev pin state */ 0);
                break;
                case U8X8_MSG_GPIO_MENU_HOME:
                u8x8_SetGPIOResult(u8x8, /* get menu home pin state */ 0);
                break;
                default:
                u8x8_SetGPIOResult(u8x8, 1);                    // default return value
                break;
        }
        return 1;
}
 
 
int main(void)
{
        /*
                Select a setup procedure for your display from here: https://github.com/olikraus/u8g2/wiki/u8g2setupc
                1. Arg: Address of an empty u8g2 structure
                2. Arg: Usually U8G2_R0, others are listed here: https://github.com/olikraus/u8g2/wiki/u8g2reference#carduino-example
                3. Arg: Protocol procedure (u8g2-byte), list is here: https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#communication-callback-eg-u8x8_byte_hw_i2c
                4. Arg: Defined in this code itself (see above)
        */
        u8g2_Setup_sed1520_122x32_1(&u8g2, U8G2_R0, u8x8_byte_sed1520, u8x8_gpio_and_delay_template);
        u8g2_InitDisplay(&u8g2);
        u8g2_SetPowerSave(&u8g2, 0);
        
        /* full buffer example, setup procedure ends in _f */
    u8g2_ClearBuffer(&u8g2);
        u8g2_SetFont(&u8g2, u8g2_font_ncenB14_tr);
        u8g2_DrawStr(&u8g2, 1, 2, "test");
        u8g2_SendBuffer(&u8g2);
                
        while(1){
        }
}
`

**Comment by pavo141** [comment]
Sorry for Closing the issue

**Comment by olikraus** [comment]
you need to call u8x8_avr_delay from somewhere.

Actually, you have missed this if clause:
https://github.com/olikraus/u8g2/blob/master/sys/avr/atmega328/main.c#L157

**Comment by pavo141** [comment]
I used the Template for this Function, 
i added the If clauses and Nothing changes


default:
	if (u8x8_avr_delay(u8x8, msg, arg_int, arg_ptr))	// check for any delay msgs
		return 1;
	u8x8_SetGPIOResult(u8x8, 1);      // default return value
	break;


Should i Change my Setup Function in an u8x8 Setup Function?

**Comment by olikraus** [comment]
> Should i Change my Setup Function in an u8x8 Setup Function?

not required. this does not matter

> u8g2_DrawStr(&u8g2, 1, 2, "test");

Better use `u8g2_DrawStr(&u8g2, 1, 20, "test");`
The reference point is the lower left edge of the "t", so it the reason why you do not see anything might be the fact, that your "test" output is actually above the screen.

**Comment by pavo141** [comment]
This wasn't the issue, 

i also tried the Hello world function which had worked on Arduino like this:

while(1){
	
	u8g2_FirstPage(&u8g2);
	do 
	{
		u8g2_SetFont(&u8g2, u8g2_font_ncenB14_tr);
		u8g2_DrawStr(&u8g2, 0,20,"test");
		
	} while (u8g2_NextPage(&u8g2));
	
		
	}

It doesn't worked. I changed a few times the second and third Argument in `u8g2_DrawStr()` but it doesn't helped.

**Comment by olikraus** [comment]
The next step will be to check your wiring. I would say 90% of all problems are wiring issues and power supply problems. If you have a scope, check the digital lines, whether you see activity there.

**Comment by olikraus** [comment]
feel free to reopen, if required...
