### ISSUE TITLE
Details in font installation

### ISSUE THREAD

**Issue by fabianlam** [olikraus/u8g2#708]
Hello friend. I have an issue in the installation of the customised font. I have downloaded the font set in TTF format and converted into the BDF file. But I’m puzzled in using of the BDFCONV. I know this awesome program converting software can turn the BDF into the C file. But May I know where should I place the output file into my Arduino Lib? If the BDF file had been turned into C, shall I keep this BDF file in my system? I’m not familiar with the operation in details and looking for your helping hand!

**Comment by olikraus** [comment]
The bdf file is not required any more. The generated c code can be copied and pasted into your project or .ino file
