### ISSUE TITLE
Can I port this library to rt-thread official packages?

### ISSUE THREAD

**Issue by wuhanstudio** [olikraus/u8g2#711]
RT-Thread is a growing real time operating system in China.
https://github.com/RT-Thread/rt-thread

U8g2 is my favorite library for display, so I'm really eager to introduce it to more people in China.
Can I port it to rt-thread and add it to official packages as a peripheral package? Now, I'm working on it in this repo.
https://github.com/wuhanstudio/rt-u8g2

Yet it is still a personal package, since I think it may be improper for me to send a PR to rt-thread official packages repo without your consent. Of course I'll add your licence and credit if required.

![tim 20180927211200](https://user-images.githubusercontent.com/15157070/46148148-020da180-c29a-11e8-97bb-2abb6dc707a1.png)

I failed to find your email address, so I'm trying to illustrate my idea in this issue. Sorry for any inconvenience.

**Comment by olikraus** [comment]
> U8g2 is my favorite library for display, so I'm really eager to introduce it to more people in China.

Sure, why not. The u8g2 license should allow the same without problem. 

> I failed to find your email address, so I'm trying to illustrate my idea in this issue. Sorry for any inconvenience.

This issue tracker is always ok. But it should be no problem to get my e-mail. Is is there in all c-codes and in the ChangeLog file.  But, as i said. I actually prefer this issue tracker.

I also try to respond as fast as possible to any new ticket.

**Comment by wuhanstudio** [comment]
Thanks for your reply, sorry for not noticing different font licences. I'll take a thorough look to fix this soon, and I'll list some minor changes I've made in U8g2 source code here.

**Comment by wuhanstudio** [comment]
After taking a look at different font licences, I have changed the LICENCE in my repo [here](https://github.com/wuhanstudio/rt-u8g2/blob/master/LICENSE). First, I duplicated your LICENCE, then I added some info about rt-thread package maintainer at the bottom, everything else remains. Will this be OK?

**Comment by olikraus** [comment]
Looks good, thanks.

**Comment by wuhanstudio** [comment]
And Thanks for your help :)
