### ISSUE TITLE
Return (userInterfaceMessage(var1, 1, var2))  and Return (userInterfaceSelectionList("text", 1, var)) not displaying.  

### ISSUE THREAD

**Issue by 3s10** [olikraus/u8g2#714]
I am pretty new to programming in general. When I try the code below, it won't display anything. I've tried to running your Hello World example against the same hardware and it works great.  It seems like the u8g2.userInterfaceSelectoinList() and u8g2.userInterfaceMessage() aren't working when they are called using the return ().  If I have missed something particularly easy, I apologize. 

int get_menu_choice() { 
//Logic for menu choices
	int selection = 0;
  if (Action_J) {
	// 5 periods indictes Action_J is active
	// TODO: animate periods, scroll txt, etc. to show Action_J is active
	// include STOP choice
     selection = u8g2.userInterfaceSelectionList(menu_title1, 1, 	menu_txt_str1);

    } else {
        // do not include stop
        selection = u8g2.userInterfaceSelectionList(menu_title2, 1, menu_txt_str2);
    }
    
    return (selection);

}

// Give the user some feedback and allow to confirm/cancel the action
int display_menu_action(int menu_selection) {

  int ret_val = 0;
  
  ret_val = u8g2.userInterfaceMessage("Start Action_J", menu_txt[menu_selection -1]," ", " Ok \n Cancel ");
  return (ret_val);

}

**Comment by olikraus** [comment]
Do the examples work, which include the userInterface functions?

https://github.com/olikraus/U8g2_Arduino/blob/master/examples/page_buffer/SelectionList/SelectionList.ino

**Comment by 3s10** [comment]
The examples work great. When I try and add u8g2.userInterfaceMessage() and u8g2.userInterfaceSelectionList() to variables and return the value of the variable to make the display work, is when I have the issue.

**Comment by olikraus** [comment]
Maybe you can create a minimal but complete example which shows the problem. Then post this example here.

**Comment by 3s10** [comment]
I just modified the code from the SelectionList example. 

const char *string_list = 
  "Altocumulus\n"
  "Altostratus";

uint8_t current_selection = 1;

uint8_t UserInterfaceMessage_Var1 = 'u8g2.userInterfaceMessage("Nothing selected.", "", "", " ok ");
uint8_t UserInterfaceMessage_Var2 = 'u8g2.userInterfaceMessage("Selection:", u8x8_GetStringLineStart(current_selection-1, string_list ), "", " \n cancel ");

void loop(void) {
  current_selection = u8g2.userInterfaceSelectionList(
    "Cloud Types",
    current_selection, 
    string_list);

  if ( current_selection == 0 ) {
    return (UserInterfaceMessage_Var1);
  } else {
    return (UserInterfaceMessage_Var2);
  }
}

**Comment by olikraus** [comment]
added code tages....
ok, i do not know what you want to do, but (A) "loop" is a void function and can not return values and (B) I do not think that you can call a function outside a function body.
I would say that this is a C++ problem but not a u8g2 problem.

**Comment by olikraus** [comment]
> I am trying to set the u8g2.userInterfaceMEssage() and u8g2.userInterfaceSelectionList() functions into variables

Yes, but the function call is outside a function body.

> and using the return() command to call the variable/u8g2 function

Yes, but the loop function is void so the return is useless.

And finally: Your code is still incomplete, so I can not test your code: I can just guess...
