### ISSUE TITLE
userInterfaceInputValue

### ISSUE THREAD

**Issue by MohdShanawaz** [olikraus/u8g2#719]
I am using u8g2.userInterfaceInputValue but I am able to set values from 0-255 i.e. 8 bits. I want to set 16 bit and 32 bit values and can I set specific predefined values? such as 50, 100, 150, 200....

Also, how to input text?

**Comment by olikraus** [comment]
These functions are not really part of this library. It is more like an example of what is possible.
Or, in other words, u8g2 is a graphics library, but not a user interface toolkit library.

You could just take the existing source, copy everything to your own project and update the code accordingly:

https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_input_value.c

**Comment by MohdShanawaz** [comment]
Thanks for your reply.
Which parameter should I change in u8g2_input_value.c to set 16 bit values.

**Comment by olikraus** [comment]
hmmm... I would exect some basic c programming knowledge from your side here.
Obviously you need to change the type of arguments "value", "lo" and "hi" from uint8_t to unit16_t
Consequently you have to change the type of "local_value" here: https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_input_value.c#L53
Then, u8toa to u16toa (you are in luck, that this function exists)
https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_input_value.c#L109

Please excause this direct comment from my side, but if this is already bejond your skills, then please think twice before implementing a "text input" feature.

**Comment by MohdShanawaz** [comment]
I made the following alterations:-

uint8_t u8g2_UserInterfaceInputValue(u8g2_t *u8g2, const char *title, const char *pre, uint16_t *value, uint16_t lo, uint16_t hi, uint8_t digits, const char *post)

uint16_t local_value = *value;
      
xx += u8g2_DrawUTF8(u8g2, xx, yy, u8x8_u16toa(local_value, digits));

==============================
Error:-

C:\Program Files (x86)\Arduino\libraries\U8g2_Arduino-master\src\clib\u8g2_input_value.c:44:9: error: conflicting types for 'u8g2_UserInterfaceInputValue'

 uint8_t u8g2_UserInterfaceInputValue(u8g2_t *u8g2, const char *title, const char *pre, uint16_t *value, uint16_t lo, uint16_t hi, uint8_t digits, const char *post)

In file included from C:\Program Files (x86)\Arduino\libraries\U8g2_Arduino-master\src\clib\u8g2_input_value.c:36:0:

C:\Program Files (x86)\Arduino\libraries\U8g2_Arduino-master\src\clib\u8g2.h:1176:9: note: previous declaration of 'u8g2_UserInterfaceInputValue' was here

 uint8_t u8g2_UserInterfaceInputValue(u8g2_t *u8g2, const char *title, const char *pre, uint8_t *value, uint8_t lo, uint8_t hi, uint8_t digits, const char *post);
===========================================


What am I missing?

**Comment by olikraus** [comment]
> What am I missing?

The error message is VERY precise. You must fix the function prototype in .h file.

**Comment by MohdShanawaz** [comment]
Thank you olikraus for your support.

**Comment by olikraus** [comment]
looks like a programming error but not a library issue.
