### ISSUE TITLE
SetFontMode is_transparent default is 0, but documentation says 1

### ISSUE THREAD

**Issue by matthijskooijman** [olikraus/u8g2#723]
[Docs for setFontMode](https://github.com/olikraus/u8g2/wiki/u8g2reference#setfontmode) says:

> Default mode is 1 (background color of the characters is not changed).

However, in the library code I cannot find any place that actually sets the mode on initialization, so I suspect it is just initialized to zero. This is also what I see when testing (latest master 2.24.0). I can provide a minimal example if that helps.

**Comment by olikraus** [comment]
I think you are right, but I need to check this.

**Comment by olikraus** [comment]
documentation updated, thanks!

**Comment by matthijskooijman** [comment]
Thanks :-D
