### ISSUE TITLE
ESP32 SPI 3 Wire SSD1306 Nois/Snow

### ISSUE THREAD

**Issue by arnold-b** [olikraus/u8g2#737]
Hello, 

I´m trying to use your lib, but all what i get is snow. i tried every type of setup. 
What could i try ?

Thanks Arnold
	u8g2_esp32_hal_t u8g2_esp32_hal = U8G2_ESP32_HAL_DEFAULT;
	u8g2_esp32_hal.clk   = PIN_CLK;
	u8g2_esp32_hal.mosi  = PIN_MOSI;
	u8g2_esp32_hal.cs    = PIN_CS;
	//u8g2_esp32_hal.dc    = PIN_DC;
	u8g2_esp32_hal.reset = PIN_RESET;
	u8g2_esp32_hal_init(u8g2_esp32_hal);

	u8g2_t u8g2;  // a structure which will contain all the data for one display
	u8g2_Setup_ssd1306_128x64_noname_f(
		&u8g2,
		U8G2_R0,
		u8g2_esp32_spi_byte_cb,
		u8g2_esp32_gpio_and_delay_cb);   // init u8g2 structure

	u8g2_InitDisplay(&u8g2);

**Comment by olikraus** [comment]
The DC pin is required.

**Comment by arnold-b** [comment]
Hi, 

 

i also tried this config. 

       u8g2_esp32_hal_t u8g2_esp32_hal = U8G2_ESP32_HAL_DEFAULT;

       u8g2_esp32_hal.clk   = PIN_CLK;

       u8g2_esp32_hal.mosi  = PIN_MOSI;

       u8g2_esp32_hal.cs    = PIN_CS;

       u8g2_esp32_hal.dc    = PIN_DC;

       u8g2_esp32_hal.reset = PIN_RESET;

       u8g2_esp32_hal_init(u8g2_esp32_hal);

 

 

same problem

 

Von: olikraus <notifications@github.com> 
Gesendet: Samstag, 3. November 2018 09:04
An: olikraus/u8g2 <u8g2@noreply.github.com>
Cc: arnold-b <arnold.braun@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [olikraus/u8g2] ESP32 SPI 3 Wire SSD1306 Nois/Snow (#737)

 

The DC pin is required.

**Comment by arnold-b** [comment]
Sent using the free GMX iPad App

Am 03.11.18 um 09:04 schrieb olikraus

**Comment by olikraus** [comment]
Maybe there is a connection problem on the DC pin.

**Comment by olikraus** [comment]
no further feedback...
