### ISSUE TITLE
oled and conversion bmp program

### ISSUE THREAD

**Issue by wchpikus** [olikraus/u8g2#740]
Hi.
One question,what program you using to convert bmp?
I have problem to display graph 256x64 on
U8G2_SSD1322_NHD_256X64_F_4W_HW_SPI Oled display.

Nothing on the screen.
I tryed lcdassistant and microlcd java program. Strange is, i only replace jlx display to ssd and forgot how to make this pictures...
I tryed gimp and export, not work.
Problem with 256x64?
When i try old 192x64 picture used on old Progmem, works ok.
Little help);)

**Comment by olikraus** [comment]
I always use gimp and export as XBM

**Comment by wchpikus** [comment]
Did you rotate the picture or in normal position convert in gimp?

**Comment by olikraus** [comment]
Does this matter? But no I didn't rotate the bitmap.

**Comment by wchpikus** [comment]
Hmm..strange why do not work for me.
Could you tell me, this manual is ok for export file?

https://sandhansblog.wordpress.com/2017/04/16/interfacing-displaying-a-custom-graphic-on-an-0-96-i2c-oled/

**Comment by olikraus** [comment]
> Could you tell me, this manual is ok for export file?
https://sandhansblog.wordpress.com/2017/04/16/interfacing-displaying-a-custom-graphic-on-an-0-96-i2c-oled/

Yes, this tutorial should exactly explain all the steps.

**Comment by wchpikus** [comment]
Hmm..ok I will today.
So no rotate,convert to b&w..i see;)
I do not use 1 bits pallete..
;)

**Comment by wchpikus** [comment]
Ok not work correctly..
![20181105_090534](https://user-images.githubusercontent.com/3776183/47985547-3b77cf00-e0da-11e8-85ce-75d1cb7f5632.jpg)
![20181105_090335](https://user-images.githubusercontent.com/3776183/47985555-4599cd80-e0da-11e8-9d02-e242d3828635.jpg)

**Comment by olikraus** [comment]
> max resolution is 248x64...fake oled??
250x64 and more do not work...

See here: https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#16-bit-mode

You may need to enable 16 bit mode for u8g2 (see FAQ: https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L159)

**Comment by wchpikus** [comment]
hmm, oki i try:)

**Comment by wchpikus** [comment]
ok, it is it:)
great thanks:)
So , only gimp and all works:)
