### ISSUE TITLE
Why using binary constants instead of HEX?

### ISSUE THREAD

**Issue by NailAgliev** [olikraus/u8g2#754]
https://github.com/olikraus/u8g2/blob/d7a20ce5f89c1729721b917025599c57ca105c55/csrc/u8x8_d_st7586s_erc240160.c#L195-L203

Hi all. My IDE(Keil) not support that definition of binary constant. Why just not to use HEX?

**Comment by olikraus** [comment]
True. Code was contributed. But yes, needs to be fixed.

**Comment by olikraus** [comment]
Thanks
