### ISSUE TITLE
typedef name has already been declared (with same type)

### ISSUE THREAD

**Issue by vredzhepov** [olikraus/u8g2#766]
There're two definitions of `typedef struct u8log_struct u8log_t;` in u8x8.h file line 412 (previously defined at the line 392). During compilation I've got an error `typedef name has already been declared (with same type)`. The development environment is IAR Embedded Workbench.

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8.h#L388
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8.h#L412

Nice finding. Thanks

**Comment by olikraus** [comment]
done
