### ISSUE TITLE
battery_font

### ISSUE THREAD

**Issue by vvadimv** [olikraus/u8g2#770]
Hello, I tried to use the font u8g2_font_battery19_tn, but the Arduino ide shows an error ('u8g2_font_battery19_tn' is not declared in this scope)

**Comment by olikraus** [comment]
Yes, issue #747 is not yet released, but it is part of the latest beta....

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).
