### ISSUE TITLE
ANAG VISION Display with Toshiba 6963 240x128 LCD

### ISSUE THREAD

**Issue by UltiCa** [olikraus/u8g2#773]
Hi, I have connected my Display to my Arduino MEGA. I have downloaded your lib 2.24.3 to my Arduino IDE Version 1.8.5
![bildschirmfoto 2018-12-28 um 12 04 26](https://user-images.githubusercontent.com/37214146/50514545-25193e80-0a9f-11e9-90d6-aa22a58e71c1.png)
this is from:
http://www.produktinfo.conrad.com/datenblaetter/175000-199999/181686-da-01-en-GRAFIK_MODUL_STN_BLAU_WEISS_240X128.pdf
I am using the hello world example:
there I have activated:
U8G2_T6963_240X128_F_8080 u8g2(U8G2_R0, 8, 9, 10, 11, 4, 5, 6, 7, /*enable=*/ 17, /*cs=*/ 14, /*dc=*/ 15, /*reset=*/ 16); // Connect RD with +5V, FS0 and FS1 with GND

The connections to my display:

Display -> Arduino MEGA
  1  VSS -> GND
  2  Vdd -> +5V
  3  VO  -> to the contrast Poti 10k (working fine to PIN17 Vee
  4  C/D -> PIN 15 (is this correct?dc? Command/data ReadWrite)
  5  RD  ->  +5V
  6  WR -> not connected
  7  DB0 -> 8
  8  DB1 -> 9
  9  DB2 -> 10
10  DB3 -> 11
11  DB4 -> 4
12  DB5 -> 5
13  DB6 -> 6
14  DB7 -> 7
15  CE   -> 17
16  RST -> 16
17  Vee -> Contrast from Poti
18  MD2 not connected
19  FS   -> GND
20  NC  -> not connected

when I run the program, I can observe the reset (short time a OnePixelLine) then nothing.
I am waiting for a HelloWord from the example-code

With the connections I am not 100% sure. Can anybody look over?
THX for help Carsten

**Comment by olikraus** [comment]
**Vee/V0 connetion**

It should be like this:
https://electronics.stackexchange.com/questions/279855/vee-negative-voltage-output-lcd
![https://i.stack.imgur.com/dp7O4.png](https://i.stack.imgur.com/dp7O4.png)


**U8g2 Constructor**
This ist the constructor
```
U8G2_T6963_240X128_F_8080 u8g2(U8G2_R0, 8, 9, 10, 11, 4, 5, 6, 7, /*enable=*/ 17, /*cs=*/ 14, /*dc=*/ 15, /*reset=*/ 16); // Connect RD with +5V, FS0 and FS1 with GND
```
Of course you can use different pin numbers, but let's assume the above mentioned pin numbers:
enable signal: This is the write enable signal and must be connected to WR
cs: This is the chip select signal and must be connected to CE (chip enable)
dc: Yes, this is the data/command signal and must be connected to C/D

So, i assume the correct table will be:
Display -> Arduino MEGA
1 VSS -> GND
2 Vdd -> +5V
3 VO -> to the contrast Poti 10k (working fine to PIN17 Vee
4 C/D -> PIN 15 (is this correct?dc? Command/data ReadWrite)
5 RD -> +5V
6 WR -> **17**
7 DB0 -> 8
8 DB1 -> 9
9 DB2 -> 10
10 DB3 -> 11
11 DB4 -> 4
12 DB5 -> 5
13 DB6 -> 6
14 DB7 -> 7
15 CE -> **14**
16 RST -> 16
17 Vee -> Contrast from Poti
18 MD2 not connected
19 FS -> GND
20 NC -> not connected

**Comment by UltiCa** [comment]
!!! HELLO WORLD !!!
it is working.
Great, thank you very much for your help. AND you are doing a great job with your TIME and your knowledge. Now I will dive into the universe of displays :o) THX - Carsten

**Comment by olikraus** [comment]
Bestens, viel Erfolg!
