### ISSUE TITLE
Display shows garbage when it's updated from separate tasks Esp32

### ISSUE THREAD

**Issue by EvertDekker** [olikraus/u8g2#775]
First thanks for the great lib.
I'm using a esp32-Wroom with i2c 0.96" oled display and Arduino ide 1.8.8 or 1.9.0 beta
Everything worked great until I update the esp32 Arduino core from ?.? to 1.0.0 version.

In the 1.0.0 the display works still great if it's updated from the main loop, however if it's updated from a separate tasks it will show unwanted characters of garbage depending on what you want to display.

This very simple sample below will show the problem. Instead of showing an **A** if will always show **.A**
It's not clear to me where the additional dot is coming from.
I tried updating the wire.cpp/h and esp32-hal-i2c.c/h as suggested in the Arduino core repository by people that had i2c problems but without success.

At the moment I'm trying to find with a jtag debugger and Sloeber Ide where's it's going wrong but it's hard to find.

Any tips/trick/ideas what could be the problem or where to look?

```
#include <U8x8lib.h>

U8X8_SH1106_128X64_NONAME_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);

TaskHandle_t ScreenUpdateHandle;

void setup(void)
{
  Serial.begin(115200);
  u8x8.begin();
  u8x8.setBusClock(500000);
  u8x8.setPowerSave(0);
  u8x8.setFont(u8x8_font_chroma48medium8_r);
  xTaskCreate(screenupdate,  "Screenupdate",  10500,  NULL,   5, &ScreenUpdateHandle);
}

void loop(void)
{
  vTaskDelay( 2000 / portTICK_PERIOD_MS);
}

void screenupdate( void * pvParameters ) {
  int loopcounter = 0;
  while (1) {
    u8x8.drawString(1, 1, "A");
    vTaskDelay( 2000 / portTICK_PERIOD_MS);
  }
  vTaskDelete( NULL );
}

```

**Comment by olikraus** [comment]
Of course u8x8 will make heavy use of the I2C bus and this access may not always be atomic.
Maybe you should put the u8x8 command into a critical section:

```
void screenupdate( void * pvParameters ) {
  int loopcounter = 0;
  while (1) {
    taskENTER_CRITICAL();
    u8x8.drawString(1, 1, "A");
    taskEXIT_CRITICAL();
    vTaskDelay( 2000 / portTICK_PERIOD_MS);
  }
  vTaskDelete( NULL );
}
```

ok, not sure, whether I used the right commands here....

**Comment by EvertDekker** [comment]
I understand that u8x8 uses the i2c bus heavy, however in this simple sample the display is the only user of the i2c bus, but with an rtos that the esp32 has you never know who is interfering with the bus.

One important detail I was forget to mention is that you expect that with **u8x8.drawString(1, 1, "A");** the **.A** is always drawn at position 1,1 however the x position is every loop increased with 2. So the display shows .A.A.A.A.A.A.A etc.

I tried your suggestion with **taskENTER_CRITICAL(&myMutex);**, the A is now displayed without the dot, however the x position is still increased every loop. And if use **u8x8.drawString(1, 1, "Hello world");** then only the **d** of world is shown at position 1,1

**Comment by olikraus** [comment]
hmmm... can you locate U8g2lib.h on your hard disk. then place the keyword "volatile" at the beginning of line 60:
https://github.com/olikraus/u8g2/blob/master/cppsrc/U8g2lib.h#L60

```
    volatile u8g2_uint_t tx, ty;
```

will this improve the situation?

**Comment by EvertDekker** [comment]
Changing line 60 doesn't help in U8g2lib.h
As mentioned above I'm using U8x8lib.h, changed here line 157 to `volatile uint8_t tx, ty;` , but this won't help also.

Did some more testing and noticed that if u8x8.begin is in the displayupdate task it works fine again.
However you can't use the display then anymore from outside the task and that's not the idea.
```
#include <U8x8lib.h>

U8X8_SH1106_128X64_NONAME_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);

TaskHandle_t ScreenUpdateHandle;


void setup(void)
{
  Serial.begin(115200);
  xTaskCreate(screenupdate,  "Screenupdate",  50500,  NULL,   5, &ScreenUpdateHandle);
}

void loop(void)
{
  vTaskDelay( 20000 / portTICK_PERIOD_MS);
}

void screenupdate( void * pvParameters ) {
  u8x8.begin();
  u8x8.setFont(u8x8_font_chroma48medium8_r);
  while (1) {
    u8x8.drawString(0, 0, "Hello world!");
    vTaskDelay( 2000 / portTICK_PERIOD_MS);
  }
  vTaskDelete( NULL );
} 
```

**Comment by v1993** [comment]
Hi. You have to use things called "mutexes" to do it right way, I think. Read about them in FreeRTOS or if you use C++, using `std::mutex`, `std::lock_guard` and so on would be awesome and OOP-way.

However, software time-based implementation of protocols (I²C, SPI, etc.) may require accurate timings and not allow changing tasks in middle of function. For this case, critical section mechanism should work.

Also, volatile keyword isn't required in 99% cases and will not do magick itself.

Good luck!

**Comment by EvertDekker** [comment]
They changed something is the Esp-idf and now you have to run the task on the same core as Arduino is running.
What I understand is core 0 now dedicated to the wifi and arduino is running on core 1.

Running the screenupdate sub pinned to core 1 solved the problem.

Thanks again for you lib and time.

```
#include <U8x8lib.h>

#if CONFIG_FREERTOS_UNICORE
#define ARDUINO_RUNNING_CORE 0
#else
#define ARDUINO_RUNNING_CORE 1
#endif

U8X8_SH1106_128X64_NONAME_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);

TaskHandle_t ScreenUpdateHandle;


void setup(void)
{
  Serial.begin(115200);
  u8x8.begin();
  u8x8.setFont(u8x8_font_chroma48medium8_r);
  xTaskCreatePinnedToCore(screenupdate,  "Screenupdate", 4000, NULL,  5, &ScreenUpdateHandle, ARDUINO_RUNNING_CORE); 
}

void loop(void)
{
  vTaskDelay( 20000 / portTICK_PERIOD_MS);
}

void screenupdate( void * pvParameters ) {
  while (1) {
    u8x8.drawString(0, 0, "Hello world!");
    vTaskDelay( 2000 / portTICK_PERIOD_MS);
  }
  vTaskDelete( NULL );
}

```

**Comment by blazoncek** [comment]
@EvertDekker thank you for sharing this.
