### ISSUE TITLE
Error T6963 128X64 mode

### ISSUE THREAD

**Issue by Bloker9** [olikraus/u8g2#777]
Hello! I use the WG12864D display on the T6963 controller with a resolution of 128 * 64. When using the initialization string "U8G2_T6963_160X80_F_8080" everything works fine, but it consumes extra memory. Therefore, I tried to select the correct resolution with the line "U8G2_T6963_128X64_F_8080" but then nothing is displayed on the screen. Arduino IDE 1.8.8; U8g2 v2.24.3

**Comment by olikraus** [comment]
I have created an alternative setup with the new `U8G2_T6963_128X64_ALT_F_8080` constructor.
Hope this will work. Use beta release 2.25.3 for this new constructor.

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by Bloker9** [comment]
completely deleted the contents of the folder at the address on the screen and copied it from your archive, rebuilt the skeche with a new line (which you specified) but it did not work :(
![default](https://user-images.githubusercontent.com/39840867/50741000-82805e80-1208-11e9-8b18-2b45b9a1dda8.jpg)

**Comment by olikraus** [comment]
which error?
maybe repeat the steps from above: delete the u8g2 folder from above and reinstall u8g2 via Arduino IDE

**Comment by olikraus** [comment]
well, ok, but what can I do to solve your initial problem.
I have created a new constructor, which has the init sequence from the 160x80 constructor but the memory management from the 128x64 variant.  But it doesn't work. I actually do not know what to do now....

**Comment by olikraus** [comment]
any feedback? Can I close this topic?

**Comment by Bloker9** [comment]
if nothing else can be done then probably close.

**Comment by olikraus** [comment]
Where did you order the WG12864D display?

**Comment by Bloker9** [comment]
I bought it second-hand, but you could buy a new one, for example, here https://www.winstar.com.tw/ru/products/graphic-lcd-display-module/12864-lcd.html

**Comment by olikraus** [comment]
thanks.... still a little bit expensive.

**Comment by olikraus** [comment]
well... i close this for now. Maybe I come across such a display once...
