### ISSUE TITLE
Provide csrc/u8g2_fonts and fntsrc/*.c

### ISSUE THREAD

**Issue by basilfx** [olikraus/u8g2#78]
For compilers that are less capable of sorting out which files to include, provide both the fonts combined and separated. 

For instance, the XC8 compiler has troubles with so many fonts.

Relates to #70

**Comment by olikraus** [comment]
The fonts are only one of several problems. Also if i would store each font in a single file, there are other things which will break XC8. I already tried hard to port u8glib to XC8, but finally i gave up. In fact i do not want to waste time on XC8. gcc is much better and for free.

**Comment by olikraus** [comment]
the font build process will be updated, so that the single font files are stored in
u8g2/tools/font/build/single_font_files

**Comment by olikraus** [comment]
font files are now available here:

https://github.com/olikraus/u8g2/tree/master/tools/font/build/single_font_files

Hope this is good enough.

**Comment by basilfx** [comment]
Yes, thank you very much. This works much better!
