### ISSUE TITLE
bdfconv with large font sizes

### ISSUE THREAD

**Issue by matphillips** [olikraus/u8g2#780]
From the comment here https://github.com/olikraus/u8g2/issues/676#issuecomment-436631856

There seems to be a 255 byte limit for the conversion. Is this a restriction of the resulting file format, or of the converter?
I'd like to convert some glyphs to a large size, currently the biggest I can get is 44px at 72dpi.

Is there any way to get it to convert to a much larger size?

**Comment by olikraus** [comment]
This is a restriction of the format. In some cases only some extra glyphs like @ or % violate this restriction. In this case you could just remove these chars if you don't require them.

**Comment by matphillips** [comment]
ah, ok. Thanks for the answer anyway.
