### ISSUE TITLE
SSD1327 128x128 form waveshare no lines

### ISSUE THREAD

**Issue by Andrzej1000** [olikraus/u8g2#793]
Hello.
SSD1327 128x128 form waveshare.
Arduino DUE does not display the top and bottom some lines.

"
#include <U8g2lib.h>
#include <Wire.h>
U8G2_SSD1327_EA_W128128_1_SW_I2C u8g2(U8G2_R0, /* clock=*/ A1, /* data=*/ A0, /* reset=*/ U8X8_PIN_NONE);
"

u8g2.drawBox(0, 0, 128, 1);  it's can be seen on the OLED but over the line you can see **unused** points/lines on OLED
u8g2.drawBox(0, 95, 128, 1);  it's can be seen on the OLED
 u8g2.drawBox(0, 96, 128, 1);  it's can **not** be seen on OLED

It looks like it did not light and non't use the first same lines and  the last same lines  did not light.
Please, help me display all 128 lines?
What to check ...

**Comment by olikraus** [comment]
what about the other constructor?
`U8G2_SSD1327_MIDAS_128X128_1_SW_I2C`

**Comment by Andrzej1000** [comment]
Thank you very much!
It works like that:
U8G2_SSD1327_MIDAS_128X128_1_SW_I2C u8g2(U8G2_R0, /* clock=*/ A1, /* data=*/ A0, /* reset=*/ U8X8_PIN_NONE);
and
U8G2_SSD1327_MIDAS_128X128_1_2ND_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);

Thank you - you can close the topic
;)

**Comment by olikraus** [comment]
:)
