### ISSUE TITLE
Add page buffer offsets (Add support for LS013B7DH03)

### ISSUE THREAD

**Issue by basilfx** [olikraus/u8g2#8]
For the Sharp LS013B7DH03 128x128 display you write individual lines of 128x1 pixels at minimum. The format is 1 address byte (Y coordinate), 16 bytes of pixel data, and a trailing byte (don't care). It's also possible to send multiple lines at once (e.g. one full page).

It looks something like this:

```
00 | 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 | 17
=========================================================
YY | XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX | TR
..
..
..
YY | XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX | TR
```

I was looking for a way to add these extra two bytes to the page buffer, so I can use DMA to transfer more data without CPU intervention. This will increase memory consumption because the extra bytes are just dead space, but lower energy consumption.

In U8glib I tried something like this:

* Catch `U8G_DEV_MSG_SET_PIXEL`, increase the X coordinate by 8 (so it moves to next byte)
* In `U8G_DEV_MSG_PAGE_NEXT`, set the 1st byte of each line in the page buffer to the correct address, and the 18th byte to the trailing byte (clearPage clears it all). Then use DMA to transfer full page buffer to the LCD. 

Unfortunately, this doesn't work, because increasing the X coordinate will result in problems at the borders (drawPixel checks bounds). 

So I was looking for a way to do this with U8g2, but as far as I can tell, it's not possible. Therefore, would it be possible to add an option to add offsets when writing to the page buffer?

**Comment by olikraus** [comment]
hope i will find some more time to answer this later. You have to catch U8X8_MSG_DISPLAY_DRAW_TILE
You will receive 8x128 pixel at once.

**Comment by olikraus** [comment]
I think it will be best to make it work first, then later add DMA access. Moreover DMA should be done in the low level com function only (gpio_and_delay_cb member of the u8x8 struct).

**Comment by olikraus** [comment]
I have added support for your display.
List of Arduino constructors:
https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#ls913b7dh03-128x128

of course not tested... please let me know the results. All in all timing of the display is very slow. Values do not fit into u8x8 data structures... so lets hope the best. maybe I need to increase the size of some variables. especially cs setup time is very huge.

**Comment by basilfx** [comment]
Thanks! I'll continue with the code and test it.

I don't want to be nitpicky, but you've made a typo in the driver's name :-)

**Comment by olikraus** [comment]
ups, thanks for the hint --> typo fixed

**Comment by olikraus** [comment]
can this be closed?

**Comment by basilfx** [comment]
The feature (buffer offset) is still desired, but you can close it if you are not going to implement this :-)

**Comment by olikraus** [comment]
Thanks for the pull request. I have merged your code. So even without the "buffer offset" it will work, right? It is not like that that i do not want to implement this "buffer offset" feature, it is more like this that i am not able to test this and that it will have some impact on the overall architecture. In fact i can not estimate the effort if we implement this correctly (memory calculation is done automatically by an external tool)

**Comment by basilfx** [comment]
The code I contributed works without the buffer offsets :-)

**Comment by olikraus** [comment]
Great, then, i would just leave it like this.
