### ISSUE TITLE
Text in QRCode display on 4.2inch EPD display on arduino

### ISSUE THREAD

**Issue by SekharBadike** [olikraus/u8g2#800]

**Comment by SekharBadike** [comment]
Hi am trying to display the text in QRcode format on 4.2inch EPD display on arduino Due,i did't got any reference based on QRcode on EPD display ,Please anybody has the reference regarding the QRCode on EPD display help to get it,
Thanking you

**Comment by olikraus** [comment]
even I have no idea about this, so closing...
