### ISSUE TITLE
support for Epson LCD S1D1

### ISSUE THREAD

**Issue by mahpour** [olikraus/u8g2#802]
How can I create a constructor for the Seiko Epson LCD controller documented here: [SEIKO EPSON S1D1 DATASHEET](https://datasheet.lcsc.com/szlcsc/Seiko-Epson-S1D13305F00A1_C7614.pdf) 

I feel like most of the settings are similar...

Any advises would be appreciated.

**Comment by olikraus** [comment]
This is a 640 × 256 pixel LCD?

> I feel like most of the settings are similar...

similar to what?

I do not know whether i have implement a display like this. It is also not clear whether this is a graphics LCD.
