### ISSUE TITLE
u8x8 print function with fonts wider that 8 pixels overlaps characters

### ISSUE THREAD

**Issue by manutremo** [olikraus/u8g2#804]
When using u8x8, and a font with a width higher than 8 pixel, like e.g. u8x8_font_inr21_2x4_n, the characters overlap. This does not happen if I use drawString. I'm using the following constructor:

U8X8_SH1106_128X64_NONAME_HW_I2C

My own guess is that since the u8x8.print function uses the Arduino print function, maybe it's not taking into account the additional spacing.

**Comment by olikraus** [comment]
yes, a bug, should be fixed.

**Comment by olikraus** [comment]
Thanks for the hint!
