### ISSUE TITLE
Linear memory layout supported for ePaper?

### ISSUE THREAD

**Issue by spachner** [olikraus/u8g2#806]
Hi Oli,

I am starting with your great u8g2 lib and wonder if it supports also linear layout? I would like to use an ePaper which does not have this vertical pixel layout (tile). Of course I could remap the pixel within the U8X8_MSG_DISPLAY_DRAW_TILE callback, but I just wanted to know if there is another option I do not known yet.

regards

spachner

**Comment by spachner** [comment]
In case somebody has the same issue. here are code snippets which let my ePaper display work with u8g2:
`
#define DISP_WIDTH      400
#define DISP_HEIGHT     300

#define TILE_WIDTH  (( DISP_WIDTH)       / 8) // 400 / 8 = 50
#define TILE_HEIGHT (((DISP_HEIGHT)+8-1) / 8) // 300 / 8 = 37.5, round up to 38 last tile which is truncated

#define PAGES 1
#define BUF_BYTES (TILE_WIDTH) * 8 * (PAGES) // 50 * 8 * 1 = 400 bytes

static uint8_t *u8g2_allocate_buffer(uint8_t *page_cnt)
{
    static uint8_t tile_buf[BUF_BYTES];
    *page_cnt = PAGES; // stored as u8g2->tile_buf_height
    return tile_buf;
}

static uint8_t u8x8_epaper_400x300_bwr_er(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
    return u8x8_epaper_400x300_bwr_generic(u8x8, msg, arg_int, arg_ptr);
}

void u8g2_setup_epaper_400x300_bwr(u8g2_t *u8g2, const u8g2_cb_t *rotation, u8x8_msg_cb byte_cb,
                                   u8x8_msg_cb gpio_and_delay_cb)
{
    uint8_t tile_buf_height;
    uint8_t *buf;
    u8g2_SetupDisplay(u8g2, u8x8_epaper_400x300_bwr_er, u8x8_cad_011, byte_cb, gpio_and_delay_cb);
    buf = u8g2_allocate_buffer(&tile_buf_height);
    u8g2_SetupBuffer(u8g2, buf, tile_buf_height, u8g2_ll_hvline_vertical_top_lsb, rotation);
}

static const u8x8_display_info_t u8x8_epaper_400x300_bwr_display_info = {
    ...
    /* tile_width   = */ TILE_WIDTH,
    /* tile_hight   = */ TILE_HEIGHT,
    ...
    /* pixel_width  = */ DISP_WIDTH,
    /* pixel_height = */ DISP_HEIGHT,
};

static uint8_t* convert_tile_buf_to_epaper(uint8_t* p_tiled_buf)
{
    static uint8_t conv_buf[BUF_BYTES];

    memset(conv_buf, 0, sizeof(conv_buf));
    static_assert(BUF_BYTES % 8 == 0, "convert_tile_buf_to_epaper does not work");

    for (uint32_t i = 0; i < (BUF_BYTES)/8; i += 1) {
        for (uint32_t j = 0; j < 8; j++) {
            uint32_t ridx = i*8;
            assert(ridx+7 < BUF_BYTES); // max resulting index below
            uint8_t b =
                (((p_tiled_buf[ridx+0] >> j) & 0x01) << 7)|
                (((p_tiled_buf[ridx+1] >> j) & 0x01) << 6)|
                (((p_tiled_buf[ridx+2] >> j) & 0x01) << 5)|
                (((p_tiled_buf[ridx+3] >> j) & 0x01) << 4)|
                (((p_tiled_buf[ridx+4] >> j) & 0x01) << 3)|
                (((p_tiled_buf[ridx+5] >> j) & 0x01) << 2)|
                (((p_tiled_buf[ridx+6] >> j) & 0x01) << 1)|
                (((p_tiled_buf[ridx+7] >> j) & 0x01) << 0);

            uint32_t widx = i + j*(TILE_WIDTH);
            conv_buf[widx] = b;
            assert(widx < sizeof(conv_buf));
        }
    }
    return conv_buf;
}
`
convert_tile_buf_to_epaper() is called for callback U8X8_MSG_DISPLAY_DRAW_TILE inside u8x8_epaper_400x300_bwr_generic() and the converted data is written to the ePaper display instead of the tile buffer

spachner

**Comment by olikraus** [comment]
There is also "u8g2_ll_hvline_horizontal_right_lsb", but this will not support the u8x8 (only u8g2)

**Comment by spachner** [comment]
Hi Oli,

thanks for your answer. u8g2_ll_hvline_horizontal_right_lsb works perfectly. So my conversion function was at least some kind of exercise ;-)

regards

spachner

**Comment by olikraus** [comment]
:)
