### ISSUE TITLE
Need to add a TTF font to U8G2

### ISSUE THREAD

**Issue by dominicklee** [olikraus/u8g2#807]
Hi Oliver,

I have a weather icons font that I want to integrate in the U8G2. Could you please convert the attached "Climacons.ttf" file so that it can be used in U8G2 and show me how to install it?

[Climacons.zip](https://github.com/olikraus/u8g2/files/2838655/Climacons.zip)

Can you also show me how to convert such TTF fonts for U8G2 in Windows? Thanks!

**Comment by olikraus** [comment]
it needs to be converted to bdf first. For this I need to know the desired pt size. 64pt and 128pt look good, but the icons will be large.

**Comment by dominicklee** [comment]
Can you make a 28pt font (for 5 rows of icons on a 128x128 screen) and a 36pt font (for 2 rows of icons)?

**Comment by dominicklee** [comment]
For example, like this:

![image](https://user-images.githubusercontent.com/7194952/52398071-c1166c80-2a85-11e9-9172-858489934004.png)

**Comment by olikraus** [comment]
I need to use the pt argument for the conversion tools. I do not know what pt=64 means and what the resulting height will be, but maybe the font author should know the minimal pt size for scan line conversion.

**Comment by olikraus** [comment]
with pt=64 the result looks like this:
![climacons64](https://user-images.githubusercontent.com/1084992/52518712-4b5dfc80-2c4f-11e9-8556-135099c2a641.png)

So the hight will be around 30 pixel. The quality will be very poor with any value blow 64.

**Comment by olikraus** [comment]
same picture with pt=32. You can see that the thermometer is broken:
![climacons32](https://user-images.githubusercontent.com/1084992/52518755-01294b00-2c50-11e9-8e8a-ff08d1f89345.png)

**Comment by olikraus** [comment]
hmm... I think the icons are from here: http://adamwhitcroft.com

**Comment by olikraus** [comment]
@AdamWhitcroft what would be the prefered pt size at 72 dpi to convert the icons to bitmaps?
