### ISSUE TITLE
myfont2.bdf does not work

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#81]
bdfconv does not work with a bdf file.
see 
http://forum.arduino.cc/index.php?topic=91395.msg2982033;topicseen#msg2982033

ToDo:
More analysis required.
./bdfconv  -v -b 2 -f 1 myfont12.txt -o tmp.c -n tmp

**Comment by olikraus** [comment]
I have fixed the bitmap parsing. Not sure whether this will fix your problem. 
Please get the latest code from this repo and try again. also remove the -m option. It should work without "-m ..."

**Comment by shakeNbake08** [comment]
Hi Oli

That has fixed the problem, everything is working correctly now.

Thanks again for the help!

Michael

**Comment by olikraus** [comment]
great, thanks for the feedback.
