### ISSUE TITLE
Are the KS0108 interface wrongly implemented as 6800 instead of 8080?

### ISSUE THREAD

**Issue by RndMnkIII** [olikraus/u8g2#819]
I've tried to initialiced the:
`U8G2_KS0108_ERM19264_F `
interface as:
` u8g2(U8G2_R0, 2,14,7,8,6,20,21,5,  11,9   , 12, 22, 23);`
but I'm unable to specify the RW pin (10) in the constructor and my screen shows random garbage.
the three CS pins are: 12,22,23, the DC is DI pin 9, and the enable pin is 11.
Can be wrongly implemented as a 6800 interface (without RW pin)?

tested with a Teensy 3.2 (Arduino 1.8.8, Teensyduino 1.45). 
For curiosity the screen works ok with u8glib using this constructor:
```
//u8g_Init8Bit(u8g, dev, d0, d1, d2, d3, d4, d5, d6, d7, en, cs1, cs2, cs3, di, rw, reset)
U8GLIB_KS0108_192 u8g(2,14,7,8,6,20,21,5,  11,   12,22,23, 9, 10);//Teensy 3.2
```
[u8g_dev_ks0108_192x64.c.zip](https://github.com/olikraus/u8g2/files/2861927/u8g_dev_ks0108_192x64.c.zip)

**Comment by olikraus** [comment]
Connect RW to ground

**Comment by olikraus** [comment]
Hmmm DC should be connected to RS, but I don't remember exactly

**Comment by olikraus** [comment]
Gallery page also has some hints on the KS0108: https://github.com/olikraus/u8g2/wiki/gallery

**Comment by RndMnkIII** [comment]
Works! Thank You!

**Comment by olikraus** [comment]
:-)
