### ISSUE TITLE
SSD1322 : newhaven display, only 248 pixels width even with 16 bit mode enabled

### ISSUE THREAD

**Issue by Sanzache** [olikraus/u8g2#820]
[Hello] Olikraus & the others, 
I'm using this display : (url = http://www.newhavendisplay.com/specs/NHD-3.12-25664UCW2.pdf)
with Arduino mkr1000 
and this constructor : U8G2_SSD1322_NHD_256X64_F_4W_HW_SPI

Before 16bit mode, the returned width was 240 and I had misalignment problems as seen in other issues. I looked in the issues and found the fix by  uncommenting the #define.
With 16 bit mode enabled, the returned widtht is 248, the misalignments problems are solved but I still cannot acces the last 8 pixels.
[](url)
What am I doing wrong?

Thanks for the help ! :)

**Comment by Sanzache** [comment]
Okay my bad, deleting the lib, then reinstalling the last update and uncommenting the  #define U8G2_16BIT **before** recompiling the project solved the issue !

**Comment by olikraus** [comment]
:-)

**Comment by Sanzache** [comment]
Thanks a lot for that wonderful lib Oli, it helped me a lot!!!
You can close this issue if you want.
Maybe it will help someone someday :)
