### ISSUE TITLE
Did micropython/python  support?

### ISSUE THREAD

**Issue by cx4** [olikraus/u8g2#829]
i use micropython and python want use u8g2.

**Comment by olikraus** [comment]
This projects hosts the u8g2 Arduino Library. 
It least, I did not do any port to micropython.

**Comment by cskurdal** [comment]
@olikraus what level of difficulty do you think it'd be to port this to MicroPython? MP can call C/C++, so might be just updating the classes/methods?

**Comment by olikraus** [comment]
I do not know MP and I also do not know the C/C++ interface, so it is difficult to tell.
At least I can try to answer questions regarding the U8g2 API, but I am not able to do any kind of MP integration.

**Comment by cskurdal** [comment]
I found and SSD1306 Python driver that works great with the Heltec Wifi Kit 8 https://raw.githubusercontent.com/micropython/micropython/master/drivers/display/ssd1306.py
