### ISSUE TITLE
Hello I w.ill contact you about current consumption

### ISSUE THREAD

**Issue by OfnyaHoo** [olikraus/u8g2#831]
Hello I w.ill contact you about current consumption
u8g2 It is in use as follows.

u8g2_Setup_sh1106_i2c_128x64_noname_1 (& u8g2, U8G2_R0, u8x8_byte_hw_i2c, psoc_gpio_and_delay_cb); u8g2_InitDisplay (& u8g2);
u8g2_ClearDisplay (& u8g2);
  u8g2_SetPowerSave (& u8g2, 0);

  u8g2_SetPowerSave (& u8g2, 0); OLED OFF state
  u8g2_SetPowerSave (& u8g2, 1); OLED ON state

There is a difference of 4 (ma).

I wonder if the OLED has shut down normally.

Please answer.

**Comment by olikraus** [comment]
What shell I answer?
