### ISSUE TITLE
Winstart WO12864D3-TFH#040

### ISSUE THREAD

**Issue by gorkembendin** [olikraus/u8g2#848]
Hey,
I want to use this library to run WO12864D3-TFH#040 display. According to researches, I decided to use U8X8_ST7565_ERC12864_4W_SW_SPI constructor but it doesn't work with my display. Could you help me about that please?

Specification of my display-> https://img.ozdisan.com/ETicaret_Dosya/355032_7224405.pdf

**Comment by olikraus** [comment]
Check your wiring and also check a different constructor (but with the same controller ST7565).

**Comment by olikraus** [comment]
no further feedback, closing...
