### ISSUE TITLE
[ESP32] Exception crash

### ISSUE THREAD

**Issue by DaveCalaway** [olikraus/u8g2#849]
Hi everyone,
i'm using an ESP32 ( Heltec Wifi LoRa 32 ) with a build in oled: https://goo.gl/TAypBL

When i load a simple sketch
```
#include <U8x8lib.h>

U8X8_SSD1306_128X64_NONAME_SW_I2C u8x8(/* clock=*/ 15, /* data=*/ 4, /* reset=*/ 16);

void setup() {
  Serial.begin(115200);
  u8x8.begin();
  delay(500);
}

void loop() {
  u8x8.drawString(0, 0, "Starting");
  delay(1000);
}
```
the board simply crash with this specific error:

![Screen Shot 2019-03-28 at 21 26 51](https://user-images.githubusercontent.com/10884164/55192923-f5fd9080-51a5-11e9-8863-575844b37e0e.png)

Someone can help me?

**Comment by olikraus** [comment]
You need to define the font.
