### ISSUE TITLE
u8g2, ESP8266 NodeMCU, and I2C OLED; missing features?

### ISSUE THREAD

**Issue by aliceand** [olikraus/u8g2#85]
Is it likely that not all functions (e.g. getStrWidth) are implemented for all displays?

I have a 4-pin I2C 128x64 OLED display  attached to an ESP8266 NodeMCU initialized with
U8G2_SSD1306_128X64_NONAME_1_SW_I2C u8g2(U8G2_R0, 5, 4); 

I've been able to print to the display and want to move on to make the code more sophisticated (e.g. text alignments, etc).  But, when I use 

w = u8g2.getStrWidth(infoText);  I get this error
 
error: no matching function for call to 'U8G2_SSD1306_128X64_NONAME_1_SW_I2C::getStrWidth(String&)'
           w = u8g2.getStrWidth(infoText);

I apologize for the simple question.  I found the u8g2 package after many false starts and really like what it provides.  But, as you can tell, I have a lot to learn yet.  Even if there are some features not implemented this is a really nice package that I will continue to use (and learn).

**Comment by olikraus** [comment]
U8g2 only supports char pointers, so you need to convert infoText to char * first.
