### ISSUE TITLE
Add a method to draw a given function

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [olikraus/u8g2#857]
Figured it could be useful to have a function that accepts a function pointer containing draw commands, then runs them in the draw loop for non-full buffer setups. So, something along the lines of

```cpp
void U8G2::draw(void (*drawFunction)(void)) {
    this.firstPage();
   do {
        drawFunction();
    } while ( this.nextPage() );
    return;
}
```

Any thoughts?

**Comment by MicroTransactionsMatterToo** [comment]
Assuming the use of C++, this would also allow the use of Lambda functions. It's not really necessary, but I think it'd be a nice touch

**Comment by olikraus** [comment]
Ok, but you have already provided such a function in your initial post. It could be easily added by any user.

**Comment by MicroTransactionsMatterToo** [comment]
I get your point, I just thought it might be nice to implement in the library. However, if you don't feel there's any reason to, I'll just close this issue :)

**Comment by olikraus** [comment]
yes, but thanks for the idea.
