### ISSUE TITLE
Loading U8g2 library into CLion

### ISSUE THREAD

**Issue by OscarVanL** [olikraus/u8g2#859]
Hi,

I use the CLion IDE instead of the normal Arduino IDE.
I'd love to be able to import U8g2 in CLion, however I can't work out how to import your library on it.

I've found the U8g2 folder in \Documents\Arduino\libraries\U8g2, but can't figure out how to include this in my CMake file.

Any suggestions on how I would achieve this?

Thanks

**Comment by olikraus** [comment]
I do not know CLion.
