### ISSUE TITLE
Change Display size or increase boundaries

### ISSUE THREAD

**Issue by josepetridelima** [olikraus/u8g2#864]
Hi! I am working in a menu with a sliding animation, and each menu item uses all screen size, when I slide the menu to next option an animation happens and a little bit of early option appears for a second in the new option. 
This occurs because the screen has an outside buffer, and the image on the screen still happens after the screen boundaries. But this space is not infinite, and after this end, it starts to appear on the opposite side. 
I would like to stop it. It like a tile effect. When something vanishes in one corner and appears on the opposite side. 
There is a way to avoid that? I tried setMaxClipWindow, setBufferCurrTileRow, updateDisplayArea and it didn't work for me =( 
I sent a video to youtube, so you can understand better my problem here. 

[https://youtu.be/KASK4QrD1As](url)

Thank you for your attention.

**Comment by olikraus** [comment]
I personally assume, that there is a software bug in your code, but if not: You could try to activate 16 bit mode (see FAQ) for u8g2. Maybe this works.

**Comment by josepetridelima** [comment]
Thank you very much! It's working!!! 
I am improving my code, but I didn't find a way to solve that problem, but with this 16 bit active the problem disappear! 
A think the space outside the screen where the image is formed take bigger with 16 bit active, so the image has space to slide and don't appears again in the opposite side =)

[https://youtu.be/ma4_BcujcBA](url)

**Comment by olikraus** [comment]
:)
