### ISSUE TITLE
setCursor error

### ISSUE THREAD

**Issue by edkeefe** [olikraus/u8g2#866]
Hello,

I developed a program using the U8G2 library on an Arduino Uno with an SSD1306 display. It worked perfectly.

I ported the code to an STM32F407VGT6. Everything works as expected except one command. 

In the Arduino code the line is (works):

u8g2.setCursor(20, 40);

On the STM32 I tried the following (doesn't work):

u8g2_setCursor(&u8g2, 20, 40);

I get the following error in Keil uVision:

Error: L6218E: Undefined symbol u8g2_SetCursor (referred from main.o).

I'm missing a file that contains this function. What is the name of the file that contains the missing code so I can included it?

Or is there something else I'm missing or doing wrong?

Thank you.

ED

**Comment by v1993** [comment]
Here's a clue:

Learn C. Learn what comiling and linkage is and what are differences between them, learn what does "symbol" mean. Also, please, note that putting your multiline code into ``` makes it formated nicely and single ` does so for one-line code.

`Undefined symbol` means that you include definition but don't link implementation into projec somehow. It most likely mean that you miss some `.c` file and/or forgot to reconfigure your build system somehow.

This also may be (not likely tho) a problem in u8g2 if they forgot to update some source list, but who knows.

**Comment by olikraus** [comment]
Note that the lower case uppercase spelling differs between u8x8 and u8g2. In this case "set" is different.

**Comment by WangShuoran** [comment]
> Note that the lower case uppercase spelling differs between u8x8 and u8g2. In this case "set" is different.

I search your code and https://github.com/olikraus/u8g2/wiki/u8g2reference information, I do not find this function, Please confirm!

**Comment by olikraus** [comment]
I think my comment was little bit wrong: The difference is between C and C++
The C++ part follows the Arduino naming convention, however for C i follow my own naming convention.
In the above mentioned link always both names (C and C++) are provided, like here: https://github.com/olikraus/u8g2/wiki/u8g2reference#setcontrast

**Comment by WangShuoran** [comment]
> I think my comment was little bit wrong: The difference is between C and C++ The C++ part follows the Arduino naming convention, however for C i follow my own naming convention. In the above mentioned link always both names (C and C++) are provided, like here: https://github.com/olikraus/u8g2/wiki/u8g2reference#setcontrast

Think you for your quickly reply. But my question is setCursor have not C function, does it have a replace?

![image](https://github.com/olikraus/u8g2/assets/43474491/8f18b493-2e67-46e0-a16b-8f80b033903f)

**Comment by olikraus** [comment]
> Thank you for your quickly reply. But my question is setCursor have not C function, does it have a replace?

No, because the setCursor function will set the draw position for the "print()" command which is actually from the Arduino IDE (u8g2 print() function is the same as the serial.print() function). So indeed there is another difference between C and C++: Additionally has the print() and setCursor() commands.

**Comment by WangShuoran** [comment]
Okay, can I understand that because there is an API directly in the C code to specify the display location, there is no need for setCursor and Print functions to display it?

**Comment by olikraus** [comment]
Exactly. The C drawStr function expects the position as part of its arguments.
Moreover the C functions are intended to work without Arduino Environment, as a consequence there is no print() (and not setCursor()) command, because the print() function is part of the Arduino IDE.
