### ISSUE TITLE
Hardware Scroll Vertically with Double Buffer or Similar?

### ISSUE THREAD

**Issue by xgarb** [olikraus/u8g2#878]
Playing with the new hardware scroll and I've found it's possible to do vertical as well as the horizontal and diagonal.

![bouncing 0000](https://user-images.githubusercontent.com/7646630/56516651-4ebd1080-653b-11e9-95a5-5c0b702c25c6.gif)

It's a bit of a hack because it seems to work by using the diagonal movement in unused pages to push the visible contents of the screen up or down.

I've using a 32px height screen and I would like to use this to move two windows of 32px  up and down into view. I tried experimenting with the 64px constructor but I don't know if I can do 64px in the buffer and move this up and down in the 32px space.

My loop  looks like this:
```
  u8g2.sendF("c", 0x02e);    // disable scroll
  u8g2.clearBuffer();
  u8g2.setFont(u8g2_font_logisoso32_tf);
  u8g2.drawStr(0, 32, "000000");
  u8g2.sendBuffer();
  u8g2.sendF("caaaaaac", 0x029, 0, 4, 0, 7, -1, 255, 0x2f);  // down
  delay(2300);
  u8g2.sendF("caaaaaac", 0x029, 0, 4, 0, 7, 1, 255, 0x2f);  // up
  delay(2300);
```

**Comment by Robiv8** [comment]
'class U8G2_SSD1305_128X32_NONAME_F_4W_HW_SPI' has no member named 'sendF'
or
'class U8G2_SSD1306_128X32_UNIVISION_F_HW_I2C' has no member named 'sendF'
hmm..?

**Comment by olikraus** [comment]
sendF is very new. I assume it is there only in the latest beta release.
Example is here: https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/HardwareScroll/HardwareScroll.ino

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by olikraus** [comment]
"SendF" command was introduced here: https://github.com/olikraus/u8g2/issues/822

**Comment by xgarb** [comment]
I just made a copy of the src directory from the Arduino folder from this repository, added it to the folder with the ino and included it like this:

```
//#include <U8g2lib.h>
#include "src/U8g2lib.h"
```

**Comment by xgarb** [comment]
Can I move two 'screens' up and down?

> I've using a 32px height screen and I would like to use this to move two windows of 32px up and down into view. I tried experimenting with the 64px constructor but I don't know if I can do 64px in the buffer and move this up and down in the 32px space.

**Comment by olikraus** [comment]
> Can I move two 'screens' up and down?

The commands are documented in the datasheet of the display.
