### ISSUE TITLE
Can add support for KS0108

### ISSUE THREAD

**Issue by RndMnkIII** [olikraus/u8g2#88]
Hello again Olikraus, can you add suport in u8g2 for the KS0108 controller?
Thanks!

**Comment by olikraus** [comment]
OpenGLCD is probably faster. You still want u8g2 support for this display?

**Comment by RndMnkIII** [comment]
Yes because I need:
- Proper screen clipping
- Big font characters
- Extensive UTF-8 support

With OpenGLCD I do not have support or I am not totally satisfied with the results obtained.

**Comment by RndMnkIII** [comment]
The speed or memory ussage is not an issue with the Teensy 3.2

**Comment by olikraus** [comment]
Introduce a new transfer start and end procedure with bit pattern for the CS signals as arguments.

Create a new byte transfer function which uses this new transfer start & end.

**Comment by olikraus** [comment]
Ks0108: looks like 6800 mode. R/W must be low. E latches with falling edge.

**Comment by olikraus** [comment]
cad001 or cad011 (no arts used)

**Comment by olikraus** [comment]
@RndMnkIII, you oncementioned a 192x64 controller, right? What are the cs0, cs1, cs2 settings for this display? Any datasheet?

**Comment by olikraus** [comment]
Todo: Optimization

**Comment by RndMnkIII** [comment]
http://www.buydisplay.com/default/4-inch-192x64-lcd-module-graphic-display-ks0107-ks0108-black-on-white
There are schematics, datasheet and source code example (note the chip selection is active to low).

**Comment by olikraus** [comment]
ERM19264
left: 011, middle: 101, right: 110, no chip select: 111

**Comment by RndMnkIII** [comment]
Yes, That's what I did  for implement it on u8glib.

**Comment by olikraus** [comment]
ok, i have added both devices to 2.8.2 from here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip
Maybe you can check the 192x64 GLCD and give me some feedback

Still not improved for speed on ATMega architectures...

**Comment by olikraus** [comment]
ok, i will close this... 
If you have any feedback on the 192x64 GLCD i would be glad to hear about that.
