### ISSUE TITLE
Missing pixels SSD1322_NHD_256X64

### ISSUE THREAD

**Issue by NUK2013** [olikraus/u8g2#885]
Hello,

How can I adapt the new version of the library u8g2 for a SSD1322 256x64 NHD Display Oled, the same that appears in the gallery list of your site ?
I have made a project with this library and now with the update , some pixels are missing , the size accepted is less . It is possible to get the old version ? 

please help 

thanks

**Comment by NUK2013** [comment]
SOLVED !!!! 
uncommenting the 16 bit line

**Comment by olikraus** [comment]
:+1:
