### ISSUE TITLE
Similar font to the X11 font type?

### ISSUE THREAD

**Issue by goodsireric** [olikraus/u8g2#886]
From my understanding, the u8g2_font_7x14_mf was generated from a fixed-pixel format.

Do you know of a scalable format font that is similar looking and could be used to generate mock screen for a user guide in Photoshop?

If not, feel free to close this question. 
Thanks for your great library! It's been working without any bugs for months for me!

**Comment by olikraus** [comment]
I think there is no scalable version of the 7x14 font. Some background is here: https://en.wikipedia.org/wiki/Fixed_(typeface)
