### ISSUE TITLE
u8g2 scrolling  Temperature Graph

### ISSUE THREAD

**Issue by mariusmym** [olikraus/u8g2#887]
Hi Oliver, hi guys !
So, i'm trying to make a temperature graph using this awesome library.
I want to mention from the start that i'm just an hobbyist when it comes to arduino / coding / programming stuff.
The code below works very well on the "else" part, until enters the "if" statement. I put a lot of "Serial.print" in order to try to debug the code, without success.
Can you guys give me a solution ?
The library for the BME280 sensor is here : https://github.com/Seeed-Studio/Grove_BME280

My code : 
https://pastebin.com/DwG3mgDN

(i tried to use the " insert code"  feature from git but for some reason it didn't work very well (only a part of the code was in that code box)

**Comment by olikraus** [comment]
In general you should use "sendBuffer()" only once. Anything else will only slowdown the graphics output (and you will complain about the low speed of u8g2).

But in general my suggestion is to restructure your code. Use two parts at least:
1. One part will fill and update the array
2. Output the array (and other information) to the display.

To simplify the code you could init the array with all "0" in setup().
Then always shift the array content to te left and add a new temperature value at the array end.
This will  avoid the if - else check in your code.

**Comment by mariusmym** [comment]
Thank you for your quick response!
The "else" part works well, and olso the "if" one until some point, after that I receive a "soft reset" message on the Serial monitor 
 (don't know why), and the code start to act weird. 
I will try to follow your advices and see what happens :)!
Thank you for your help!
