### ISSUE TITLE
u8g2lib extra methods

### ISSUE THREAD

**Issue by alanmi3833** [olikraus/u8g2#900]
I have added methods to the old u8glib to allow me to write directly to the display. On a LM6063 we had the problem that every once in a while the screen would flip and we had to reset it.
Looking at the code for the u8g2lib it is quite different from u8glib.

Would it be possible to add the following 3 methods or variants thereof.
`   u8g.chipSelect(1);   //1 select the display 0 deselect`
`    u8g.set_command(0);  //set dc pin to 0`
`    u8g.writeByte(0x40);  //write to display`

**Comment by olikraus** [comment]
You can use the sendF command: https://github.com/olikraus/u8g2/issues/896
