### ISSUE TITLE
Clear Display

### ISSUE THREAD

**Issue by eimogandolf** [olikraus/u8g2#911]
I want to clear the display to type new commands after the preview screen. 
Is there a direct command to clear the lcd?

**Comment by v1993** [comment]
[`u8g2.clear`](https://github.com/olikraus/u8g2/wiki/u8g2reference#clear)?

**Comment by olikraus** [comment]
Full buffer mode: u8g2.clear() will work, but u8g2.clearBuffer() might be sufficient
Page buffer mode: display is automatically cleared once you enter the loop again.

**Comment by eimogandolf** [comment]
will this work also in the old library u8g?

**Comment by olikraus** [comment]
U8g only supports page buffer mode. An empty page loop will clear the screen.

**Comment by eimogandolf** [comment]
I see. 
Thank you for your instant support :D

**Comment by olikraus** [comment]
:)
