### ISSUE TITLE
Improvement Request: multiple display buffer areas and memcpy to display memory

### ISSUE THREAD

**Issue by RndMnkIII** [olikraus/u8g2#93]
Hi, I've thinking that can be very useful to define procedures for graphic memory area  ucontroller to draw offscreen graphics and for  graphics animated fx and to copy this area to display controller memory.

**Comment by RndMnkIII** [comment]
Better explained: to have possibility to reserve memory for draw on it and transfer this memory to display controller memory without using an intermediate buffer

**Comment by olikraus** [comment]
This function already exists, but is not documented and not available on the Arduino level.

uint8_t u8x8_DrawTile(u8x8_t *u8x8, uint8_t x, uint8_t y, uint8_t cnt, uint8_t *tile_ptr);

This function has some drawbacks. Mostly it depends on the memory architecture of the target display. This means a bitmap transferred by this function will work on one display but will be garbled on others.

Well.. I guess this is what you want if you want to bypass u8g2 bitmap procedures, right?

**Comment by RndMnkIII** [comment]
I had thought that for example when you want to print text with u8g2, pass that method an extra field with a pointer to the area of ​​memory outside the screen and render it there using XOR,AND,... blending as an option. Another idea is render directly to the tilebuffer for create graphics fx: rotozoomer text, plasma animation, etc and memory copy to display controller memory.

**Comment by RndMnkIII** [comment]
The teensys 3.5 and 3.6 with fpu unit, 1xxMhz speed and 128kb RAM  are very capable of this.

**Comment by RndMnkIII** [comment]
The bitmaps can be preprocessed for the target display memory organization to speed up drawing

**Comment by RndMnkIII** [comment]
Many years ago I remember the existence of compiled bitmaps converted directly to machine code for speed up drawing on slow intel cpu 386. This is too xtreme and cpu architecture sensitive (needs small instructions size for to be faster than memcpy) but the idea is adjust the bitmap byte ordering to the screen memory organization to avoid checks on runtime

**Comment by olikraus** [comment]
Well, yes, I kept the memory architecture identical to the memory architecture of the target controller. There is only one graphics primitive which maps to the target memory architecture: a line drawing procedure for vertical and horizontal lines. All u8g2 price just call this one function.
Thinking about XOR, it would be simple to implement this, however it might slow down the project a lot if we add more functionality into this procedure.

**Comment by olikraus** [comment]
One more idea: I could provide a hook function,  which allows to pre fill the u8g2 buffer with some kind of background image. After that, the normal u8g2 can draw over it.

**Comment by RndMnkIII** [comment]
Can be create alternate method using C++ overload and use the method needed, the direct rendered or the offscreen rendered

**Comment by RndMnkIII** [comment]
Yes the hook function seems good idea and left the user do all the low level drawing stuff needed and blend it if needed with u8g2 primitives. For example a background plasma with foreground title text or scrolling text

**Comment by olikraus** [comment]
Okay, then let me do the following:
 * [ ] Provide and document the draw tile procedure
 * [ ] Implement a hook/callback function for the u8g2 buffer

**Comment by olikraus** [comment]
Will this help?

**Comment by RndMnkIII** [comment]
Thanks you! :-)

**Comment by olikraus** [comment]
Added documentation to u8x8 interface.

**Comment by RndMnkIII** [comment]
I'll try drawTile for testing memory organization and transfer performance witn teensies Auduino Mega and teensies 3.2 and 3.5

**Comment by olikraus** [comment]
```
void u8g2_SetBufferCurrTileRow(u8g2_t *u8g2, uint8_t row) U8G2_NOINLINE;

#define u8g2_GetBufferPtr(u8g2) ((u8g2)->u8g2->tile_buf_ptr)
#define u8g2_GetBufferTileHeight(u8g2)	((u8g2)->->tile_buf_height)
#define u8g2_GetBufferTileWidth(u8g2)	(u8g2_GetU8x8(u8g2)->display_info->tile_width)
/* the following variable is only valid after calling u8g2_FirstPage */
#define u8g2_GetBufferCurrTileRow(u8g2) ((u8g2)->tile_curr_row)
```

instead of the hok function, i guess i will better provide a suitable api

**Comment by RndMnkIII** [comment]
The text printing  after tile buffer manipulation preserves backgroung (masking glyph shape against background image)?

**Comment by olikraus** [comment]
I do not know exactly what you mean, but i plan to create an example which creates a custom background.

**Comment by olikraus** [comment]
code will look like this. Instead of the hook function, i just copy something to the buffer before doing the normal draw functions.
https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/DirectAccess/DirectAccess.ino

**Comment by olikraus** [comment]
documentation required

**Comment by olikraus** [comment]
testrelease is here:
https://github.com/olikraus/U8g2_Arduino/archive/master.zip
