### ISSUE TITLE
Unifont version

### ISSUE THREAD

**Issue by AlexFundorin** [olikraus/u8g2#931]
More of a question, rather than an issue.
I wonder, why Unifont v7 from 2014 is used, instead of the current v12 from about 20 days ago?
ftp://ftp.gnu.org/gnu/unifont/

**Comment by olikraus** [comment]
I would say, it is because I update fonts only on request. 

I looked at the change description on http://unifoundry.com/unifont/index.html
There are several updates which probably also affect the subset used in u8g2.

Shell I update unifont?

**Comment by AlexFundorin** [comment]
If you're asking me, I guess so. Many additions were made since v7.

**Comment by olikraus** [comment]
ok... let's do so.

**Comment by olikraus** [comment]
done
