### ISSUE TITLE
Detecting if I2C SSD1306 display is connected?

### ISSUE THREAD

**Issue by ivoras** [olikraus/u8g2#947]
Since the begin() method is documented to always return true, is there a way to detect if a SSD1306  display is actually connected (and responding, i.e. not broken) to the I2C bus?

**Comment by olikraus** [comment]
In case of I2C you can use the Arduino Wire lib to check whether the display answers on its I2C address.

Code will look like this: https://gist.github.com/tfeldmann/5411375

**Comment by ivoras** [comment]
Thanks!

**Comment by olikraus** [comment]
:)
