### ISSUE TITLE
 Undefined symbol u8g2_Setup_ssd1306_i2c_128x64_noname_1 (referred from main.o).

### ISSUE THREAD

**Issue by tpadcps999** [olikraus/u8g2#955]
Hi , I using Nuvoton M252 MCU and try porting u8g2 library using keil C(V6.12)
I 'm follow "Porting to new MCU platform" but have some trouble 
when i build the project get follow error

.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8g2_Setup_ssd1306_i2c_128x64_noname_1 (referred from main.o).

.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8g2_cb_r0 (referred from main.o).
.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8x8_InitDisplay (referred from main.o).
.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8x8_SetPowerSave (referred from main.o).
but I already add all files of the u8g2/csrc to my project and inclue Paths

 this is my main.c

/****************************************************************************//**
 * @file     main.c
 * @version  V0.10
 * @brief
 *           Demonstrate how to set I2C Master mode and Slave mode.
 *           And show how a master access a slave on a chip.
 *
 * @copyright (C) 2018 Nuvoton Technology Corp. All rights reserved.
 *****************************************************************************/
#include <stdio.h>
#include "u8g2.h"
#include "NuMicro.h"

 u8g2_t u8g2;
/*---------------------------------------------------------------------------------------------------------*/
/* Global variables                                                                                        */
/*---------------------------------------------------------------------------------------------------------*/

volatile uint8_t g_u8MstEndFlag = 0;

typedef void (*I2C_FUNC)(uint32_t u32Status);

volatile static I2C_FUNC s_pfnI2C0Handler = NULL;
volatile static I2C_FUNC s_pfnI2C1Handler = NULL;
// Screenbuffer

/*---------------------------------------------------------------------------------------------------------*/
/*  u8g2                                                                                                   */
/*---------------------------------------------------------------------------------------------------------*/
uint8_t u8x8_gpio_and_delay(U8X8_UNUSED u8x8_t *u8x8,U8X8_UNUSED uint8_t msg, U8X8_UNUSED uint8_t arg_int,U8X8_UNUSED void *arg_ptr)
{

			switch (msg)
			{

	
				case U8X8_MSG_GPIO_AND_DELAY_INIT:
				//HAL_Delay(1);
				TIMER_Delay(TIMER0, 1000); 
				break;
				case U8X8_MSG_DELAY_MILLI:
				//HAL_Delay(arg_int);
				TIMER_Delay(TIMER0, 1000*arg_int);
				break;
				case U8X8_MSG_DELAY_I2C:
				// delayUs(arg_int);
				break;
				case U8X8_MSG_GPIO_I2C_CLOCK:   
				// arg_int=0: Output low at I2C clock pin  
				// arg_int=1: Input dir with pullup high for I2C clock pin
				//HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, arg_int);
				if(arg_int==0)
				{	PB5=0;}
				else if(arg_int==1)
				{ PB5=1;}
				break;              
				case U8X8_MSG_GPIO_I2C_DATA:      
				// arg_int=0: Output low at I2C data pin  
				// arg_int=1: Input dir with pullup high for I2C data pin
				//HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, arg_int);				
				if(arg_int==0)
				{	PB4=0;}
				else if(arg_int==1)
				{ PB4=1;}
				break;              
				default:
				//u8x8_SetGPIOResult(u8x8, 1);      // default return value
				break;
			}
			return 1;
}
uint8_t u8x8_byte_hw_i2c(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)

{

		static uint8_t buffer[32];
		static uint8_t buf_idx;
		uint8_t *data;
		int addr;
	switch(msg)

		{
		case U8X8_MSG_BYTE_SEND:
			data = (uint8_t *)arg_ptr;
			while( arg_int >0)
				{
					buffer[buf_idx++] = *data;
					data++;
					arg_int--;
				}
			break;

			case U8X8_MSG_BYTE_INIT:
			break;

			case U8X8_MSG_BYTE_SET_DC:
			break;

			case U8X8_MSG_BYTE_START_TRANSFER:

			buf_idx=0;
			break;

			case U8X8_MSG_BYTE_END_TRANSFER:

			addr = u8x8_GetI2CAddress(u8x8);
			// addr = addr >>1;

		//	HAL_I2C_Master_Transmit(&hi2c1, (uint16_t)addr, buffer, (uint16_t)buf_idx, 10000);
			I2C_WriteMultiBytes(I2C0,(uint16_t)addr,buffer,(uint16_t)buf_idx);
		//	I2C_WriteByteOneReg(I2C0, (uint16_t)addr, buffer);
			while (g_u8MstEndFlag == 0);
			g_u8MstEndFlag = 0;
			break;

			default:

			return 0;
	}

return 1;

}
/*---------------------------------------------------------------------------------------------------------*/
/***********************************************************************************************************/
/*---------------------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------------------*/
/*  I2C0 IRQ Handler                                                                                       */
/*---------------------------------------------------------------------------------------------------------*/

void SYS_Init(void)
{
    /*---------------------------------------------------------------------------------------------------------*/
    /* Init System Clock                                                                                       */
    /*---------------------------------------------------------------------------------------------------------*/

    /* Enable Internal RC 48 MHz clock */
    CLK_EnableXtalRC(CLK_PWRCTL_HIRCEN_Msk);

    /* Waiting for Internal RC clock ready */
    CLK_WaitClockReady(CLK_STATUS_HIRCSTB_Msk);

    /* Switch HCLK clock source to Internal RC and HCLK source divide 1 */
    CLK_SetHCLK(CLK_CLKSEL0_HCLKSEL_HIRC, CLK_CLKDIV0_HCLK(1));

    /* Enable UART clock */
      CLK_EnableModuleClock(UART0_MODULE);

    /* Enable I2C0 clock */
    CLK_EnableModuleClock(I2C0_MODULE);
    CLK_EnableModuleClock(I2C1_MODULE);

	

    /* Select UART clock source from HIRC */
      CLK_SetModuleClock(UART0_MODULE, CLK_CLKSEL1_UART0SEL_HIRC, CLK_CLKDIV0_UART0(1));

			CLK_SetModuleClock(TMR0_MODULE, CLK_CLKSEL1_TMR0SEL_HIRC, 0);
    /* Update System Core Clock */
    /* User can use SystemCoreClockUpdate() to calculate SystemCoreClock and cyclesPerUs automatically. */
    
		
		
		//CLK_EnableSysTick(0xFFFFFF,CLK_CLKSEL0_STCLKSEL_HCLK);	
	  /* Set System Tick counter disabled */
    SysTick->CTRL = 0UL;
    /* Set System Tick clock source */
    SysTick->CTRL |= SysTick_CTRL_CLKSOURCE_Msk;
    /* Set System Tick reload value */
    SysTick->LOAD = 0x00FFFF;
    /* Clear System Tick current value and counter flag */
    SysTick->VAL = 0UL;
   /* Set System Tick interrupt enabled and counter enabled */
    SysTick->CTRL |=  SysTick_CTRL_ENABLE_Msk;

		SystemCoreClockUpdate();

    /*---------------------------------------------------------------------------------------------------------*/
    /* Init I/O Multi-function                                                                                 */
    /*---------------------------------------------------------------------------------------------------------*/
    Uart0DefaultMPF();

    /* Set I2C0 multi-function pins */
    SYS->GPB_MFPL = (SYS->GPB_MFPL & ~(SYS_GPB_MFPL_PB4MFP_Msk | SYS_GPB_MFPL_PB5MFP_Msk)) |
                    (SYS_GPB_MFPL_PB4MFP_I2C0_SDA | SYS_GPB_MFPL_PB5MFP_I2C0_SCL);

   
}

void I2C0_Init(void)
{
    /* Open I2C0 module and set bus clock */
    I2C_Open(I2C0, 100000);

    /* Get I2C0 Bus Clock */
    printf("I2C0 clock %d Hz\n", I2C_GetBusClockFreq(I2C0));

    /* Set I2C0 4 Slave Addresses */
    I2C_SetSlaveAddr(I2C0, 0, 0x15, 0);   /* Slave Address : 0x15 */

 
}

void I2C0_Close(void)
{
    /* Disable I2C0 interrupt and clear corresponding NVIC bit */
    I2C_DisableInt(I2C0);
    NVIC_DisableIRQ(I2C0_IRQn);

    /* Disable I2C0 and close I2C0 clock */
    I2C_Close(I2C0);
    CLK_DisableModuleClock(I2C0_MODULE);

}

void I2C1_Close(void)
{
    /* Disable I2C1 interrupt and clear corresponding NVIC bit */
    I2C_DisableInt(I2C1);
    NVIC_DisableIRQ(I2C1_IRQn);

    /* Disable I2C1 and close I2C1 clock */
    I2C_Close(I2C1);
    CLK_DisableModuleClock(I2C1_MODULE);
}

/*---------------------------------------------------------------------------------------------------------*/
/*  Main Function                                                                                          */
/*---------------------------------------------------------------------------------------------------------*/
int32_t main(void)
{
    uint32_t i;

    /* Unlock protected registers */
    SYS_UnlockReg();
    /* Init System, IP clock and multi-function I/O. */
    SYS_Init();
    /* Lock protected registers */
    SYS_LockReg();

    /* Configure UART0: 115200, 8-bit word, no parity bit, 1 stop bit. */
    UART_Open(UART0, 115200);

    /*
        This sample code sets I2C bus clock to 100kHz. Then, Master accesses Slave with Byte Write
        and Byte Read operations, and check if the read data is equal to the programmed data.
    */

    printf("+-------------------------------------------------------+\n");
    printf("| I2C Driver Sample Code for loopback test              |\n");
    printf("|                                                       |\n");
    printf("| I2C Master (I2C0) <---> I2C Slave(I2C1)               |\n");
    printf("+-------------------------------------------------------+\n");

    printf("\n");
    printf("Configure I2C0 as Master, and I2C1 as a slave.\n");
    printf("The I/O connection I2C0 to I2C1:\n");
    printf("I2C0_SDA, I2C0_SCL\n");
    printf("I2C1_SDA, I2C1_SCL\n\n");

    /* Init I2C0 */
    I2C0_Init();
    
		u8g2_Setup_ssd1306_i2c_128x64_noname_1(&u8g2, U8G2_R0, u8x8_byte_hw_i2c, u8x8_gpio_and_delay);  

		u8g2_InitDisplay(&u8g2); // send init sequence to the display, display is in sleep mode after this,
	  u8g2_SetPowerSave(&u8g2, 0); // wake up display
		int32_t k=0;
		while (1)
		{
			
		
		};

}
/*** (C) COPYRIGHT 2018 Nuvoton Technology Corp. ***/

**Comment by olikraus** [comment]
The procedure is defined here:
https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_d_setup.c#L244

**Comment by tpadcps999** [comment]
Hi olikraus : Thank you 
I try to add "u8g2_d_stup.c" to my keil project but got more error like this ><
.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8g2_m_11_6_1 (referred from u8g2_d_setup.o).
.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8g2_m_11_6_2 (referred from u8g2_d_setup.o).
.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8g2_m_11_6_f (referred from u8g2_d_setup.o).
.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8g2_m_12_12_1 (referred from u8g2_d_setup.o).
.\obj\I2C_Loopback.axf: Error: L6218E: Undefined symbol u8g2_m_12_12_2 (referred from u8g2_d_setup.o).

**Comment by olikraus** [comment]
... which are all available here: https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_d_memory.c

I am always happy to support here, but shouldn't it be clear to include all the files of the u8g2 project?

**Comment by olikraus** [comment]
For possible future discussions in this thread
https://community.arm.com/developer/tools-software/tools/f/keil-forum/31840/static-library-links-differently-with-gcc-ld-and-armlink
http://www.keil.com/support/man/docs/armlink/armlink_pge1362075556280.htm

**Comment by tpadcps999** [comment]
Olikraus, thank for immediate and proud support ,I'm include all .c first but ,flash was overflow
I will study linker problem first

**Comment by olikraus** [comment]
Yes, I expected that. You need to activate the garbage collector during link step. See my links above.

**Comment by tpadcps999** [comment]
Olikraus, thank for help ,  In keil "Options for Target" -> "c/c++" -> Click "One ELF Section per Function"
 that can remove unused .c file  .
And  my first project working now

![S__16449610](https://user-images.githubusercontent.com/18257369/61887057-6f7a7500-af33-11e9-8e07-e00e615cd52c.jpg)

**Comment by olikraus** [comment]
:)
