### ISSUE TITLE
unused const variable in csrc/u8x8_d_ld7032_60x32.c

### ISSUE THREAD

**Issue by ecc1** [olikraus/u8g2#964]
The u8x8_d_ld7032_60x32_init_seq_old defined on line 43 produces an unused-const-variable error, which causes the ESP-IDF build system to fail since it treats warnings as errors. The error could be supressed in the component.mk and CMakeLists.txt files, or the definition could be removed entirely from the C file.

**Comment by olikraus** [comment]
I am not the author of the two mentioned files. Maybe you can send me a pull request for these files.

**Comment by olikraus** [comment]
I have removed the old code via #ifdef 
This should solve your problem.
