### ISSUE TITLE
Porting to Atmel 1614 for SSD1306 using I2C

### ISSUE THREAD

**Issue by sognatore99** [olikraus/u8g2#970]
I have been trying to port this to work on a Atmel 1614 and SSD 1306.  It has taken considerable time to try to figure out the I2C using Atmel Studio.  I believe that I have it working correctly but I do not get anything on the display.  I have read your porting procedure (https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#hardware-i2c-communication).  Below is my routine I use, which is exactly like yours.  I have also attached a screen shot of the I2C data capture.  So I know data is going across but not sure if the timing is correct.  Btw nothing in the "u8x8_avr_gpio_and_delay" is being called except the first case statement "U8X8_MSG_GPIO_AND_DELAY_INIT".  Any help would be appreciated as I have spent the last several weeks trying to get this to work.  Thanks.

uint8_t u8x8_byte_arduino_hw_i2c(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{	
		
	  static uint8_t buffer[32];		/* u8g2/u8x8 will never send more than 32 bytes between START_TRANSFER and END_TRANSFER */
	  static uint8_t buf_idx;
	  uint8_t *data;
	  
	switch(msg)
	{
		case U8X8_MSG_BYTE_SEND:
		
			data = (uint8_t *)arg_ptr;
			while( arg_int > 0 )
			{
				buffer[buf_idx++] = *data;
				data++;
				arg_int--;
			}
			
		break;
		case U8X8_MSG_BYTE_INIT:
		
			address = u8x8_GetI2CAddress(u8x8);
		
		break;
		case U8X8_MSG_BYTE_SET_DC:
		break;
		case U8X8_MSG_BYTE_START_TRANSFER:
			buf_idx = 0;
	
		break;
		
		case U8X8_MSG_BYTE_END_TRANSFER:
				
			I2C_Write_Data(address, buffer, buf_idx);
		
		break;
		default:
		return 0;
	}
	return 1;
}

![I2C_Capture](https://user-images.githubusercontent.com/10901213/62826324-a08bb400-bb87-11e9-8316-13be9aa4308c.png)

**Comment by olikraus** [comment]
The callback looks ok. How does the setup/rest of your code look like?

**Comment by sognatore99** [comment]
I have  listed the main.c below.  I am developing in Atmel studio so it generates a lot of other files.  I also apologize in advance for the poor layout, I am not a c/c++ programmer and I was basically throwing everything I could think of to get the I2C to work :)


#include <atmel_start.h>
#include "clock_config.h"
#include <avr/io.h>
#include <utils/atomic.h>

#include <u8g2.h>	//https://github.com/olikraus/u8g2
					//Porting to a new micro controller  https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#hardware-i2c-communication

#include <util/delay.h>

#define P_CPU_NS (1000000000 / F_CPU)
#define SSD1306  0x78
#define I2C_WRITE   0

u8g2_t u8g2;
uint8_t u8x8_avr_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr);
uint8_t u8x8_avr_gpio_and_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr);
uint8_t u8x8_byte_arduino_hw_i2c(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr);


uint8_t address;
i2c_error_t error;

volatile uint8_t startTransferCounter = 0;


/** Structure passed into read_handler to describe the actions to be performed by the handler */
typedef struct {
	uint8_t *data;
	uint8_t  size;
} transfer_descriptor_t;

uint8_t u8x8_avr_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
	uint8_t cycles;

	switch(msg)
	{
		case U8X8_MSG_DELAY_NANO:     // delay arg_int * 1 nano
		// At 20Mhz, each cycle is 50ns, the call itself is slower.
		break;
		case U8X8_MSG_DELAY_100NANO:    // delay arg_int * 100 nano seconds
		
		
		// Approximate best case values...
		#define CALL_CYCLES 26UL
		#define CALC_CYCLES 4UL
		#define RETURN_CYCLES 4UL
		#define CYCLES_PER_LOOP 4UL

		cycles = (100UL * arg_int) / (P_CPU_NS * CYCLES_PER_LOOP);

		if(cycles > CALL_CYCLES + RETURN_CYCLES + CALC_CYCLES)
		break;

		__asm__ __volatile__ (
		"1: sbiw %0,1" "\n\t" // 2 cycles
		"brne 1b" : "=w" (cycles) : "0" (cycles) // 2 cycles
		);
		break;
		case U8X8_MSG_DELAY_10MICRO:    // delay arg_int * 10 micro seconds
		for(int i=0 ; i < arg_int ; i++)
		_delay_us(10);
		break;
		case U8X8_MSG_DELAY_MILLI:      // delay arg_int * 1 milli second
		for(int i=0 ; i < arg_int ; i++)
		_delay_ms(1);
		break;
		default:
		return 0;
	}
	return 1;
}

uint8_t u8x8_avr_gpio_and_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{
	switch(msg)
	{
		case U8X8_MSG_GPIO_AND_DELAY_INIT:	// called once during init phase of u8g2/u8x8
		
		break;							// can be used to setup pins
		case U8X8_MSG_DELAY_NANO:			// delay arg_int * 1 nano second
		
		break;
		case U8X8_MSG_DELAY_100NANO:		// delay arg_int * 100 nano seconds
		
		break;
		case U8X8_MSG_DELAY_10MICRO:		// delay arg_int * 10 micro seconds
		
		break;
		case U8X8_MSG_DELAY_MILLI:			// delay arg_int * 1 milli second
		
		break;
		case U8X8_MSG_DELAY_I2C:				// arg_int is the I2C speed in 100KHz, e.g. 4 = 400 KHz
		if ( arg_int < 2 )
		{
			_delay_us(5);
		}
		else
		{
			_delay_us(1);
		}
		break;							// arg_int=1: delay by 5us, arg_int = 4: delay by 1.25us
		case U8X8_MSG_GPIO_D0:				// D0 or SPI clock pin: Output level in arg_int
		//case U8X8_MSG_GPIO_SPI_CLOCK:
		
		break;
		case U8X8_MSG_GPIO_D1:				// D1 or SPI data pin: Output level in arg_int
		//case U8X8_MSG_GPIO_SPI_DATA:
		
		break;
		case U8X8_MSG_GPIO_D2:				// D2 pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_D3:				// D3 pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_D4:				// D4 pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_D5:				// D5 pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_D6:				// D6 pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_D7:				// D7 pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_E:				// E/WR pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_CS:				// CS (chip select) pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_DC:				// DC (data/cmd, A0, register select) pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_RESET:			// Reset pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_CS1:				// CS1 (chip select) pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_CS2:				// CS2 (chip select) pin: Output level in arg_int
		
		break;
		case U8X8_MSG_GPIO_I2C_CLOCK:		// arg_int=0: Output low at I2C clock pin
		
		//if(arg_int)
		//SCL_set_level(true);
		//else
		//SCL_set_level(false);
		//DISPLAY_CLK_PORT &= ~(1<<DISPLAY_CLK_PIN);
		break;							// arg_int=1: Input dir with pullup high for I2C clock pin
		case U8X8_MSG_GPIO_I2C_DATA:			// arg_int=0: Output low at I2C data pin
		
		//if(arg_int)
		//SDA_set_level(true);
		//else
		//SDA_set_level(false);
		break;							// arg_int=1: Input dir with pullup high for I2C data pin
		case U8X8_MSG_GPIO_MENU_SELECT:
		u8x8_SetGPIOResult(u8x8, /* get menu select pin state */ 0);
		break;
		case U8X8_MSG_GPIO_MENU_NEXT:
		u8x8_SetGPIOResult(u8x8, /* get menu next pin state */ 0);
		break;
		case U8X8_MSG_GPIO_MENU_PREV:
		u8x8_SetGPIOResult(u8x8, /* get menu prev pin state */ 0);
		break;
		case U8X8_MSG_GPIO_MENU_HOME:
		u8x8_SetGPIOResult(u8x8, /* get menu home pin state */ 0);
		break;
		default:
		if (u8x8_avr_delay(u8x8, msg, arg_int, arg_ptr))	// check for any delay msgs
		return 1;
		u8x8_SetGPIOResult(u8x8, 1);      // default return value
		break;
	}

	return 1;
}



i2c_operations_t I2C_0_adr_nack_handler(void *d)
{
	return i2c_continue; // Send REPEATED START before read
}

i2c_operations_t I2C_0_set_data_nack_callback_handler(void *d)
{
	return i2c_continue; // Send REPEATED START before read
}


i2c_operations_t I2C_0_set_data_complete_callback_handler(void *d)
{
	return i2c_continue; // Send REPEATED START before read
}

i2c_operations_t I2C_0_set_timeout_callback_handler(void *d)
{
	return i2c_continue; // Send REPEATED START before read
}


i2c_operations_t I2C_0_set_write_collision_callback_handler(void *d)
{
	return i2c_continue; // Send REPEATED START before read
}

void setBufferDataSize(void *d)
{
	transfer_descriptor_t *desc = (transfer_descriptor_t *)d;
	I2C_0_set_buffer((void *)desc->data, desc->size);
}


void I2C_Write_Data(uint8_t sla_address, uint8_t *data, uint8_t size)
{
	uint8_t               sla = sla_address >> 1; //Need to right shift it since the I2C_0_open function left shifts it to account for setting a zero in lsb for writing
	//uint8_t               a   = adr & 0xff;
	transfer_descriptor_t d   = {data, size};
	while (!I2C_0_open(sla))
	; // sit here until we get the bus..
	
	// This callback specifies what to do after the first write operation has completed
	// The parameters to the callback are bundled together in the aggregate data type d.
	I2C_0_set_data_complete_callback(i2c_cb_return_stop, &d);
	// We should not get an an address NACK here
	I2C_0_set_address_nack_callback(I2C_0_adr_nack_handler, NULL);
	
	I2C_0_set_buffer((void *)data, size);
	// Start a Write operation
	I2C_0_master_operation(false);
	while (I2C_BUSY == I2C_0_close())
	; // sit here until the entire chained operation has finished
}

uint8_t u8x8_byte_arduino_hw_i2c(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
{		
	  static uint8_t buffer[32];		/* u8g2/u8x8 will never send more than 32 bytes between START_TRANSFER and END_TRANSFER */
	  static uint8_t buf_idx;
	  uint8_t *data;
	  
	switch(msg)
	{
		case U8X8_MSG_BYTE_SEND:
		
			data = (uint8_t *)arg_ptr;
			while( arg_int > 0 )
			{
				buffer[buf_idx++] = *data;
				data++;
				arg_int--;
			}
			
		break;
		case U8X8_MSG_BYTE_INIT:
		
			address = u8x8_GetI2CAddress(u8x8);
		
		break;
		case U8X8_MSG_BYTE_SET_DC:
		break;
		case U8X8_MSG_BYTE_START_TRANSFER:
			buf_idx = 0;
	
		break;
		
		case U8X8_MSG_BYTE_END_TRANSFER:
				
			I2C_Write_Data(address, buffer, buf_idx);
		
		break;
		default:
		return 0;
	}
	return 1;
}


int main(void)
{
	/* Initializes MCU, drivers and middleware */
	atmel_start_init();
	
	ENABLE_INTERRUPTS();
	
	u8g2_Setup_ssd1306_i2c_128x64_noname_f(&u8g2, U8G2_R0, u8x8_byte_arduino_hw_i2c, u8x8_avr_gpio_and_delay);
	u8g2_SetI2CAddress(&u8g2, SSD1306);
	u8g2_InitDisplay(&u8g2);
	u8g2_SetPowerSave(&u8g2, 0);


	u8g2_ClearBuffer(&u8g2);
	u8g2_SetFont(&u8g2, u8g2_font_fur35_tn);
	u8g2_SetFontRefHeightText(&u8g2);
	u8g2_SetFontPosTop(&u8g2);
	u8g2_DrawStr(&u8g2, 0, 14, "AVR");
	u8g2_SendBuffer(&u8g2);

}

**Comment by olikraus** [comment]
From my perspective everything looks good. If you remove everything after ClearBuffer, do you see some snow on the screen?

Did you check wiring?

Which voltage do you use?

**Comment by sognatore99** [comment]
Using 5v and did check the wiring, and no snow on the screen just blank.  What I do is switch projects and run a oled lcd code from (https://github.com/PaulKlinger/tinypc) to make sure everything is working.  This project uses a different I2C (simple_i2c_fgras78.c) but I was not able to get that to work with your code either.  Your graphic library is more robust and that is why I am putting a lot of effort into it.  What is confusing is that I ran the same test on a Nano and captured the same signals.  If you look they look very similar.  Now I do not know about the timing maybe that is wrong?  I have tested the baud at 100khz, 400khz and 800 khz with 20Mhz clock and even prescaled it to 5Mhz.  Wow my mind is blown.
![Nano_vs_1614](https://user-images.githubusercontent.com/10901213/62838949-160f8700-bc51-11e9-8a0a-e1fb0f200bb5.png)

**Comment by sognatore99** [comment]
One thing I did notice is that it does not erase the screen if something is on it already but makes it brighter

**Comment by sognatore99** [comment]
Ok I had to take a step back and look to see what could be wrong.  One of the things I tested was to remove the PicKit4 programmer from the circuit.  So now I see snow on the screen.  When I comment out the remaining code thou it clears the screen but no text.  Any suggestion from this point?  Thanks for you help.

**Comment by sognatore99** [comment]
ok I got it all working.  I had to use the following which I found in another in another issue (https://github.com/olikraus/u8g2/issues/325).  Thanks for your help!  Note to any users of the Pickit4 when I switched to release it started to work, I guess debugging was the issue!

	u8g2_SetI2CAddress(&u8g2, SSD1306);
	u8g2_InitDisplay(&u8g2);
	u8g2_SetPowerSave(&u8g2, 0);

	u8g2_SetFont(&u8g2, u8g2_font_6x12_tf);
	u8g2_ClearBuffer(&u8g2);
	u8g2_DrawStr(&u8g2, 0,12, "STM32L031");
	u8g2_DrawStr(&u8g2, 20,24, "MHz");
	u8g2_SendBuffer(&u8g2);

**Comment by olikraus** [comment]
ah... ok...
