### ISSUE TITLE
Platform IO Library Issue 

### ISSUE THREAD

**Issue by pthompson8594** [olikraus/u8g2#974]
I installed u8g2 library from the platform io library installer and when using that version my display is shifted to right by about 20 pixels and seems to roll over ghosted. [Display = SSD1322_NHD_256X64_F_4W_HW_SPI] However if I overwrite the platform IO library manually with same version of u8g2 from this github everything works fine. Seems as if there might be an issue with library that platform IO downloads.

Platform IO Downloaded Library version = 2.26.14
 ![PlatformIO Downloaded Library](https://user-images.githubusercontent.com/3021723/63079215-0a46ed80-befb-11e9-8a04-f78506a38eb4.jpg)
Github Downloaded Library version=2.26.14
![Manually Downloaded Library](https://user-images.githubusercontent.com/3021723/63079216-0ca94780-befb-11e9-92af-1b1dc2a19d09.jpg)

**Comment by olikraus** [comment]
Not sure whether Platform IO people will read the issue here...
At least from my perspective (u8g2 author) i do not know how to support here.

**Comment by olikraus** [comment]
Maybe
https://community.platformio.org/c/libraries
would  be a better place to ask.

**Comment by pthompson8594** [comment]
Yeah, that makes sense. Though I would bring it to your attention anyway. Although I guess your version works so not really your problem. Thanks

**Comment by olikraus** [comment]
👍
