### ISSUE TITLE
drawing circle missing pixels

### ISSUE THREAD

**Issue by cydrollinger** [olikraus/u8g2#977]
I have been utilizing the U8g2.lib for a month or so and have recently experienced missing pixels when drawing circles, at the beginning and the end of the sections. My display is a 64x48 SSD1306. It seems to me I was not having this issue when I first started. Any thoughts would be greatly appreciated!

**Comment by olikraus** [comment]
Example Code and picture would be helpful.

**Comment by cydrollinger** [comment]
Sorry, I figured it out the function: u8g2_DrawCircle does not work with the color scheme 2. Likely there are duplicate pixels being drawn in the circle.

**Comment by olikraus** [comment]
Ah, yes, could be
