### ISSUE TITLE
How can I use (all of) korean ?

### ISSUE THREAD

**Issue by ddubbu** [olikraus/u8g2#978]
Hello!
I am impressed your effort.

I want to use your font with (all of) Korean

But I met this error in ARDUINO IDE

c:/users/hello/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: address 0x400013c0 of C:\Users\hello\AppData\Local\Temp\arduino_build_408025/Test-11-Expand.ino.elf section .bss' is not within region `dram0_0_seg'

c:/users/hello/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: address 0x400013c0 of C:\Users\hello\AppData\Local\Temp\arduino_build_408025/Test-11-Expand.ino.elf section .bss' is not within region dram0_0_seg'

collect2.exe: error: ld returned 1 exit status

exit status 1
보드 NodeMCU 1.0 (ESP-12E Module) 컴파일 에러`

I Guess that it accurs becasue memory (or flash size) is not enough to read this big font file
can you help me?

**Comment by olikraus** [comment]
> I Guess that it accurs becasue memory (or flash size) is not enough to read this big font file

Yes, looks like...

> can you help me?

I do not know how...
