### ISSUE TITLE
U8g2 Menu System

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8g2#979]
Check https://github.com/neu-rah/ArduinoMenu
Maybe add examples
U8x8 output???

**Comment by neu-rah** [comment]
there is an example for each, U8x8, U8G2, U8GLib and UCGLib

thank for your awesome library and for the time you dedicate to it and to the community

**Comment by olikraus** [comment]
Thanks for your work on ArduinoMenu. I am really impressed. Looking forward to do some tests.
I think it shares a lot of ideas with my old m2tk lib.

**Comment by olikraus** [comment]
![dogs102_menu](https://user-images.githubusercontent.com/1084992/63656412-94ad0e00-c793-11e9-8798-829c8257de56.jpg)

Nice, works out of the box, but I guess I need to learn more...

**Comment by neu-rah** [comment]
nice!
after my journey on menu UI i have some experience, learning with the errors also. I'm quite sure that AM code is not organised as yours, but we will see...

you can also reach me on https://gitter.im/ArduinoMenu/Lobby or by email, you're welcome.

**Comment by olikraus** [comment]
:)

**Comment by AlexFundorin** [comment]
Wow, guys. This can't be real. olikraus wasn't aware that ArduinoMenu existed, even though it's already in version 4 and AM5 is planned?
Wish you two collaborated and made AM5 with all those bells and whistles, like smooth animations, transitions, cursor shapes, items and titles aligning, different fonts per menu item and everything else.

**Comment by dremeier** [comment]
btw. there is also another nice solution for Menu withe the U8g2 and U8x8 lib, called [TcMenu](https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/u8g2-renderer-plugin/).

**Comment by olikraus** [comment]
Is TcMenu available as an Arduino Lib?

**Comment by AlexFundorin** [comment]
https://github.com/davetcc/tcMenuLib/
https://github.com/davetcc/tcMenu
https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/
