### ISSUE TITLE
u8x8.setI2CAddress(0x3c); does not seem to work with SH1106 I2C

### ISSUE THREAD

**Issue by snoozer** [olikraus/u8g2#982]
Hello,

I am using U8x8lib.h on my Arduino Nano and try to use 2 displays. the 1st I2C address 0x3c and the 2nd has 0x3d, I can see both displays with the I2C scanner. As soon as I include in void setup

```
  u8x8.setI2CAddress(0x3c);
  u8x8.begin();
  u8x8.setPowerSave(0);
```
The display will; no longer work.

I am using this at the beginning of the code:
`U8X8_SH1106_128X64_NONAME_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);`

Any suggestion how I can make the 2nd Display work ?
Thanks
Jan P.

**Comment by olikraus** [comment]
Multiply the address by 2 (see reference manual)
