### ISSUE TITLE
Alignment for text

### ISSUE THREAD

**Issue by idreamsi** [olikraus/u8g2#983]
Hi 😊
I need to align words with a function (for example: center align, left align and etc), but I didn't find any specific function for this. I tested many ways to align words (Especially **UTF-8** words). The main problem is how to find the width of a word for example in font size 16 or etc. [As we know, changing the font changes the number of pixels used.]
Is there a way to auto alignment words?

Thanks for this great library.

**Comment by olikraus** [comment]
There is getUTF8Width() function here: https://github.com/olikraus/u8g2/wiki/u8g2reference#getutf8width
It calculates the width of the provided string. If you pass the word itself, it will return the pixel width. Of course you need to set the font before calling this function.

Note: getUTF8Width() is not 100% correct, it might be wrong by 1 or 2 pixel.

**Comment by idreamsi** [comment]
Thanks @olikraus 
I had seen this function on the wiki and I did a lot of testing but **getUTF8Width()** does not work right. by changing the font and size (UTF-8 font), the numbers are not accurate. For example, I use the **128x64** display and the **getUTF8Width()** output is 127, however, the text occupies only part of the screen width and part of the display is blank !

For example for the right-alignment I use the following code but it misses a few letters and gets much more error with changing font and size.
```
#define LCDWidth                          u8g2.getDisplayWidth()
#define ALINE_RIGHT(t)                  LCDWidth - u8g2.getUTF8Width(t)
```

**Comment by idreamsi** [comment]
Problem solved with some changes.
Thank you for your attention. The following code can be used to alignment the UTF-8 letters (especially right-to-left languages like Arabic and Persian).
```
#define LCDWidth                        u8g2.getDisplayWidth()
#define ALINE_CENTER(t)                 ((LCDWidth - (u8g2.getUTF8Width(t))) / 2)
#define ALINE_RIGHT(t)                  (LCDWidth -  u8g2.getUTF8Width(t))
#define ALINE_LEFT                      0
```

**Comment by olikraus** [comment]
:)

**Comment by NikilRagav** [comment]
Petition to add this functionality directly to the library

**Comment by olikraus** [comment]
It should not take much effort to implement this by yourself.

**Comment by NikilRagav** [comment]
sure - I can make a PR for it

**Comment by ShivamJoker** [comment]
We could have an built api for align text centre then ?

**Comment by olikraus** [comment]
There will be also a new drawing function which will allow centered text. 
Code is here: 
https://github.com/olikraus/u8g2/blob/master/csrc/u8g2_button.c

Not yet released or documented...
