### ISSUE TITLE
new display support JHD25664-G06PSWD

### ISSUE THREAD

**Issue by MasterSPB** [olikraus/u8g2#984]
Hi, I have display with ST75256 driver, how I can add support for this display?
Display datasheet: https://drive.google.com/file/d/15oFl9szMTue7YI4wFTKPgT8d2UDJmE-D/view?usp=sharing

**Comment by olikraus** [comment]
Will the existing U8G2_ST75256_JLX25664 constructor work?
What are the results with the  U8G2_ST75256_JLX25664 constructor?

https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#st75256-jlx25664

**Comment by MasterSPB** [comment]
I was tested with U8G2_ST75256_JLX25664_1_4W_SW_SPI - work great!
My problem was with wiring...
![photo1](https://user-images.githubusercontent.com/5583890/64218754-a72df280-cecb-11e9-8444-beb8fa4da1ff.png)

**Comment by olikraus** [comment]
:)
