### ISSUE TITLE
Poor SW Spi performance on NANO EVERY (atmega4809)

### ISSUE THREAD

**Issue by systempal** [olikraus/u8g2#987]
Hi, when using SW SPI constructors on a Arduino NANO EVERY (atmega4809) i've noticed very poor performance (flickering an slow screen redraws) compared with the same layout on a Arduino NANO V3 (atmega328p)

**Comment by olikraus** [comment]
SW SPI is always a little bit slow. What is your exact constructor name? Can you use HW SPI?

**Comment by Simone73** [comment]
The problem here is not to use SW OR HW SPI but the fact that SW on 4809 is significantly slower than on a 328 when the contrary is expected.

**Comment by Simone73** [comment]
Btw that is my constructor:

`	#define CL					4
	#define DA					3
	#define CS					10
	#define DC					8
	#define RES					9

U8X8_ST7565_JLX12864_4W_SW_SPI display(CL, DA, CS, DC, RES);`

**Comment by olikraus** [comment]
Nevertheless HW SPI would be faster

**Comment by Simone73** [comment]
Obviously!

BTW, if you can fix SW SPI for 4809 i would appreciate it

**Comment by olikraus** [comment]
The code is here: https://github.com/olikraus/u8g2/blob/master/cppsrc/U8x8lib.cpp#L358

What exactly shell I do to optimize SW SPI?

**Comment by olikraus** [comment]
More specific, I could enable the SW SPI optimization for the Atmega4809 if I would know the __AVR_ARCH__ option and wehter this is compatible with the other AVR Architectures.

**Comment by Simone73** [comment]
ATmega 4809 ARCH is xmega3

xmega3 == 103

The following works for me!

`#elif __AVR_ARCH__ == 4 || __AVR_ARCH__ == 5 || __AVR_ARCH__ == 51 || __AVR_ARCH__ == 6 || __AVR_ARCH__ == 103`

**Comment by olikraus** [comment]
Ah, ok :)

**Comment by Simone73** [comment]
i think you can include ARCH 100 to 103 at least,

also there are some other fixes needed:

```
#if (__AVR_ARCH__ < 100)
typedef enum {
	LOW = 0,
	HIGH = 1,
	CHANGE = 2,
	FALLING = 3,
	RISING = 4,
} PinStatus; 
#endif

```

and

```
	  if ( u8x8_GetPinIndex(u8x8, msg) < U8X8_PIN_OUTPUT_CNT )
	  {
	    digitalWrite(i, (PinStatus)arg_int);
	  }
	  else

```

to be compatible with arduino 1.8.9 new megaAVR core

**Comment by Simone73** [comment]
do you think to update the library with those fixes ?

**Comment by olikraus** [comment]
Good question. I think I need to test 1.8.9.

**Comment by Simone73** [comment]
> Good question. I think I need to test 1.8.9.

The proble is the new megaAVR core, if you compile for 328 on 1.8.9 there are no problems but if you select NANO EVERY or arduino uno WiFi V2 (4809) you need those fixes

**Comment by olikraus** [comment]
Sounds strange....

**Comment by Simone73** [comment]
> Sounds strange....

Please verify what i say ;)

**Comment by olikraus** [comment]
Hmm.. looks like a more general problem: https://github.com/arduino/ArduinoCore-API/issues/25

**Comment by olikraus** [comment]
Correct check probably uses
```
#if (ARDUINO_API_VERSION >= 10000)
...
#endif
```

**Comment by Simone73** [comment]
> Hmm.. looks like a more general problem: [arduino/ArduinoCore-API#25](https://github.com/arduino/ArduinoCore-API/issues/25)

Yep

**Comment by Simone73** [comment]
```
#if (ARDUINO_API_VERSION >= 10000)
typedef enum {
	LOW = 0,
	HIGH = 1,
	CHANGE = 2,
	FALLING = 3,
	RISING = 4,
} PinStatus; 
#endif
```

do NOT work for me,

stick to :

```
#if (__AVR_ARCH__ < 100)
typedef enum {
	LOW = 0,
	HIGH = 1,
	CHANGE = 2,
	FALLING = 3,
	RISING = 4,
} PinStatus; 
#endif

```

**Comment by olikraus** [comment]
Oh, that was just a hint for myself. You should stay with your solution, but for u8g2 I need to find a more generic solution which will work with all kind of processors.

**Comment by Simone73** [comment]
> Oh, that was just a hint for myself. You should stay with your solution, but for u8g2 I need to find a more generic solution which will work with all kind of processors.

Sure. Hope to see a fix and a new stable release soon

**Comment by Simone73** [comment]
Well, after a bit of research i found that ARDUINO_ARCH_MEGAAVR exists so:

```
#if not defined (ARDUINO_ARCH_MEGAAVR)
typedef enum {
	LOW = 0,
	HIGH = 1,
	CHANGE = 2,
	FALLING = 3,
	RISING = 4,
} PinStatus; 
#endif
```

can work better ;)

**Comment by olikraus** [comment]
Maybe, but the pinstatus is not related to xmega.

**Comment by egilkv** [comment]
Are you using Serial at the same time? There is a bug that seriously degrades performance when using serial on these devices. Not sure if the fix is officially released yet.

**Comment by olikraus** [comment]
I did some tests today. For some reason, I do not have ArduinoCore-API installed. So checking for 103 (as mentioned above) is sufficient to improve SW SPI speed.

**Comment by olikraus** [comment]
I have downloaded arduino linux64 1.8.10. 
How can I reproduce the bug with ArduinoCore API?
