### ISSUE TITLE
How to drive this display, anyone can help?

### ISSUE THREAD

**Issue by ngmacha** [olikraus/u8g2#992]

**Comment by ngmacha** [comment]
Thank you very much, @olikraus , for the great library, I have quite a few project using it! Apologies in advance, however, if this is NOT the place to post this kind of questions - please kindly advise where, then!

This is the graphic LCD from the control panel of the salvaged HP Deskjet 3050 printer I'm trying to reuse.
Front:
![image](https://user-images.githubusercontent.com/883534/64596664-ffc62980-d3bc-11e9-9713-e256752e2c63.png)

and back:
![image](https://user-images.githubusercontent.com/883534/64596795-40be3e00-d3bd-11e9-8867-0cb8f6c65641.png)

I tried to search for CH376, no match... Seems there are 6 lines from the connector on the back coming to the LCD pins, maybe SPI (MOSI, MISO, SCLK, SS and power)? I've already found the power lines (7 is GND and 10 is Vcc, counting from the V key), but still hesitating to power it. The DS32 and DS33 seen on two sides of the LCD connector are backlights...

Anyone could advise how to findout the pinouts and how to use it with this great library? Any help is very much appreciated. Thanks a lot in advance!
Mac Ha

**Comment by olikraus** [comment]
I have no idea...

**Comment by olikraus** [comment]
no further comments... closing...
